In [1]:
import os
import pandas as pd
import numpy as np

# Project path
project_path = os.path.dirname(os.getcwd())

# Load processed behavioral dataset
behavior_path = os.path.join(
    project_path,
    "data",
    "processed",
    "behavior_features.csv"
)

behavior_df = pd.read_csv(behavior_path)

print("Behavioral dataset loaded successfully!")
print("Shape:", behavior_df.shape)
print("\nColumns:")
print(behavior_df.columns.tolist())

Behavioral dataset loaded successfully!
Shape: (14368, 20)

Columns:
['id', 'account_type', 'label', 'statuses_count', 'followers_count', 'friends_count', 'favourites_count', 'listed_count', 'created_at', 'updated', 'account_age_days', 'statuses_per_day', 'followers_friends_ratio', 'friends_followers_ratio', 'favorites_per_status', 'log_statuses_count', 'log_followers_count', 'log_friends_count', 'log_favourites_count', 'log_listed_count']

In [2]:
# Behavioral features used by the neural network

behavior_features = [
    "statuses_count",
    "followers_count",
    "friends_count",
    "favourites_count",
    "listed_count",
    "account_age_days",
    "statuses_per_day",
    "followers_friends_ratio",
    "friends_followers_ratio",
    "favorites_per_status",
    "log_statuses_count",
    "log_followers_count",
    "log_friends_count",
    "log_favourites_count",
    "log_listed_count"
]

X = behavior_df[behavior_features].copy()
y = behavior_df["label"].copy()

print("Number of behavioral features:", len(behavior_features))
print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nBehavioral features:")
print(behavior_features)

print("\nLabel distribution:")
print(y.value_counts())

Number of behavioral features: 15
X shape: (14368, 15)
y shape: (14368,)

Behavioral features:
['statuses_count', 'followers_count', 'friends_count', 'favourites_count', 'listed_count', 'account_age_days', 'statuses_per_day', 'followers_friends_ratio', 'friends_followers_ratio', 'favorites_per_status', 'log_statuses_count', 'log_followers_count', 'log_friends_count', 'log_favourites_count', 'log_listed_count']

Label distribution:
label
1    10894
0     3474
Name: count, dtype: int64

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

print("Training set:", X_train.shape)
print("Test set:", X_test.shape)

print("\nTraining distribution:")
print(y_train.value_counts())

print("\nTest distribution:")
print(y_test.value_counts())

Training set: (10057, 15)
Test set: (4311, 15)

Training distribution:
label
1    7625
0    2432
Name: count, dtype: int64

Test distribution:
label
1    3269
0    1042
Name: count, dtype: int64

In [4]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled training shape:", X_train_scaled.shape)
print("Scaled test shape:", X_test_scaled.shape)

print("\nFirst 5 scaled training rows:")
print(X_train_scaled[:5])

Scaled training shape: (10057, 15)
Scaled test shape: (4311, 15)

First 5 scaled training rows:
[[-0.29515333 -0.02996183 -0.20416001 -0.20048632 -0.0419566  -0.48152522
  -0.2672219  -0.03108261 -0.13214822 -0.13683032 -0.56910057 -1.01416658
  -0.98263434 -0.57344755 -0.65967813]
 [-0.295565   -0.02974188 -0.10478585 -0.20048632 -0.0419566  -0.99996345
  -0.2652982  -0.03228106  0.44644692 -0.13683032 -0.64976718 -0.62799287
   0.29791115 -0.57344755 -0.65967813]
 [ 0.38415916 -0.00608126 -0.12576484  0.07058427 -0.0227204   0.63551769
   0.19117445  0.01779694 -0.40883234 -0.03566158  1.52840203  1.20478516
   0.17267441  1.77539036  0.80762879]
 [-0.29574143 -0.02949051 -0.1276051  -0.20048632 -0.0419566  -1.28982681
  -0.2590098  -0.03158929 -0.01912948 -0.13683032 -0.69073561 -0.40266509
   0.16036081 -0.57344755 -0.65967813]
 [-0.29591786 -0.02980472 -0.14122304 -0.20048632 -0.0419566  -1.31140888
  -0.25908633 -0.03215772  0.29766755 -0.13683032 -0.73694749 -0.70841583
   0.06061215 -0.57344755 -0.65967813]]

In [5]:
%pip install tensorflow

Requirement already satisfied: tensorflow in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (7.36.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (84.0.0)
Requirement already satisfied: six>=1.12.0 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (2.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (1.83.1)
Requirement already satisfied: keras>=3.12.0 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (2.5.2)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: rich in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.20.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import sys

print("Python being used by this notebook:")
print(sys.executable)

print("\nPython version:")
print(sys.version)

Python being used by this notebook:
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Scripts\python.exe

Python version:
3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]

In [7]:
import sys
import tensorflow as tf

print("Python:", sys.version)
print("TensorFlow:", tf.__version__)

Python: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
TensorFlow: 2.21.0

In [8]:
import pandas as pd
import numpy as np
import sklearn
import tensorflow as tf

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Scikit-learn:", sklearn.__version__)
print("TensorFlow:", tf.__version__)

Pandas: 3.0.5
NumPy: 2.5.2
Scikit-learn: 1.9.0
TensorFlow: 2.21.0

In [9]:
import os
import pandas as pd
import numpy as np

project_path = os.path.dirname(os.getcwd())

behavior_path = os.path.join(
    project_path,
    "data",
    "processed",
    "behavior_features.csv"
)

behavior_df = pd.read_csv(behavior_path)

print("Behavioral dataset loaded successfully!")
print("Shape:", behavior_df.shape)

Behavioral dataset loaded successfully!
Shape: (14368, 20)

In [10]:
behavior_features = [
    "statuses_count",
    "followers_count",
    "friends_count",
    "favourites_count",
    "listed_count",
    "account_age_days",
    "statuses_per_day",
    "followers_friends_ratio",
    "friends_followers_ratio",
    "favorites_per_status",
    "log_statuses_count",
    "log_followers_count",
    "log_friends_count",
    "log_favourites_count",
    "log_listed_count"
]

X = behavior_df[behavior_features].copy()
y = behavior_df["label"].copy()

print("Number of behavioral features:", len(behavior_features))
print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nLabel distribution:")
print(y.value_counts())

Number of behavioral features: 15
X shape: (14368, 15)
y shape: (14368,)

Label distribution:
label
1    10894
0     3474
Name: count, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

print("Training set:", X_train.shape)
print("Test set:", X_test.shape)

print("\nTraining distribution:")
print(y_train.value_counts())

print("\nTest distribution:")
print(y_test.value_counts())

Training set: (10057, 15)
Test set: (4311, 15)

Training distribution:
label
1    7625
0    2432
Name: count, dtype: int64

Test distribution:
label
1    3269
0    1042
Name: count, dtype: int64

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit ONLY on training data
X_train_scaled = scaler.fit_transform(X_train)

# Apply the same scaling to test data
X_test_scaled = scaler.transform(X_test)

print("Scaled training shape:", X_train_scaled.shape)
print("Scaled test shape:", X_test_scaled.shape)

Scaled training shape: (10057, 15)
Scaled test shape: (4311, 15)

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

behavior_nn = Sequential([
    Dense(64, activation="relu", input_shape=(15,)),
    Dropout(0.3),

    Dense(32, activation="relu"),
    Dropout(0.2),

    Dense(1, activation="sigmoid")
])

behavior_nn.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

behavior_nn.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         1,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,137 (12.25 KB)

 Trainable params: 3,137 (12.25 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

history = behavior_nn.fit(
    X_train_scaled,
    y_train,
    validation_split=0.20,
    epochs=30,
    batch_size=32,
    callbacks=[early_stopping],
    verbose=1
)

print("\nTraining completed!")
print("Epochs actually completed:", len(history.history["loss"]))

Epoch 1/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7535 - loss: 0.6039 - val_accuracy: 0.7684 - val_loss: 0.5433
Epoch 2/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7556 - loss: 0.5593 - val_accuracy: 0.7684 - val_loss: 0.5418
Epoch 3/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7556 - loss: 0.5571 - val_accuracy: 0.7684 - val_loss: 0.5416
Epoch 4/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7556 - loss: 0.5580 - val_accuracy: 0.7684 - val_loss: 0.5428
Epoch 5/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7556 - loss: 0.5572 - val_accuracy: 0.7684 - val_loss: 0.5423
Epoch 6/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7556 - loss: 0.5580 - val_accuracy: 0.7684 - val_loss: 0.5413
Epoch 7/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7556 - loss: 0.5575 - val_accuracy: 0.7684 - val_loss: 0.5419
Epoch 8/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7556 - loss: 0.5576 - val_accuracy: 0.7684 - val_loss: 0.5416
Epoch 9/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7556 - loss: 0.5583 - val_accuracy: 0.7684 - val_loss: 0.5418
Epoch 10/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7556 - loss: 0.5576 - val_accuracy: 0.7684 - val_loss: 0.5423
Epoch 11/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7556 - loss: 0.5578 - val_accuracy: 0.7684 - val_loss: 0.5431

Training completed!
Epochs actually completed: 11

In [15]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Predict probabilities
y_test_prob = behavior_nn.predict(X_test_scaled)

# Convert probabilities to binary predictions
y_test_pred = (y_test_prob >= 0.5).astype(int).ravel()

# Calculate metrics
nn_accuracy = accuracy_score(y_test, y_test_pred)
nn_precision = precision_score(y_test, y_test_pred)
nn_recall = recall_score(y_test, y_test_pred)
nn_f1 = f1_score(y_test, y_test_pred)

print("Behavioral Neural Network Performance")
print("=" * 55)
print(f"Accuracy : {nn_accuracy:.4f}")
print(f"Precision: {nn_precision:.4f}")
print(f"Recall   : {nn_recall:.4f}")
print(f"F1-Score : {nn_f1:.4f}")

print("\nDetailed Classification Report:")
print(
    classification_report(
        y_test,
        y_test_pred,
        target_names=["Genuine", "Bot"]
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

135/135 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Behavioral Neural Network Performance
=======================================================
Accuracy : 0.7583
Precision: 0.7583
Recall   : 1.0000
F1-Score : 0.8625

Detailed Classification Report:
              precision    recall  f1-score   support

     Genuine       0.00      0.00      0.00      1042
         Bot       0.76      1.00      0.86      3269

    accuracy                           0.76      4311
   macro avg       0.38      0.50      0.43      4311
weighted avg       0.58      0.76      0.65      4311


Confusion Matrix:
[[   0 1042]
 [   0 3269]]

c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [16]:
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.unique(y_train)

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y_train
)

class_weight_dict = dict(zip(classes, class_weights))

print("Class weights:")
print(class_weight_dict)

Class weights:
{np.int64(0): np.float64(2.0676398026315788), np.int64(1): np.float64(0.6594754098360656)}

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# Create a fresh model
behavior_nn_weighted = Sequential([
    Dense(64, activation="relu", input_shape=(15,)),
    Dropout(0.3),

    Dense(32, activation="relu"),
    Dropout(0.2),

    Dense(1, activation="sigmoid")
])

behavior_nn_weighted.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Early stopping
early_stopping_weighted = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

# Train with class weights
history_weighted = behavior_nn_weighted.fit(
    X_train_scaled,
    y_train,
    validation_split=0.20,
    epochs=30,
    batch_size=32,
    class_weight=class_weight_dict,
    callbacks=[early_stopping_weighted],
    verbose=1
)

print("\nTraining completed!")
print(
    "Epochs actually completed:",
    len(history_weighted.history["loss"])
)

c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.5677 - loss: 0.6955 - val_accuracy: 0.2316 - val_loss: 0.6962
Epoch 2/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.2706 - loss: 0.6957 - val_accuracy: 0.2316 - val_loss: 0.6968
Epoch 3/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.2444 - loss: 0.6957 - val_accuracy: 0.2316 - val_loss: 0.6963
Epoch 4/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.2620 - loss: 0.6957 - val_accuracy: 0.2316 - val_loss: 0.6972
Epoch 5/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.2444 - loss: 0.6957 - val_accuracy: 0.2316 - val_loss: 0.6985
Epoch 6/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.2444 - loss: 0.6957 - val_accuracy: 0.2316 - val_loss: 0.6978

Training completed!
Epochs actually completed: 6

In [18]:
y_weighted_prob = behavior_nn_weighted.predict(X_test_scaled)
y_weighted_pred = (y_weighted_prob >= 0.5).astype(int).ravel()

print("Weighted Behavioral Neural Network")
print("=" * 55)
print(f"Accuracy : {accuracy_score(y_test, y_weighted_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_weighted_pred, zero_division=0):.4f}")
print(f"Recall   : {recall_score(y_test, y_weighted_pred, zero_division=0):.4f}")
print(f"F1-Score : {f1_score(y_test, y_weighted_pred, zero_division=0):.4f}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_weighted_pred))

135/135 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
Weighted Behavioral Neural Network
=======================================================
Accuracy : 0.2417
Precision: 0.0000
Recall   : 0.0000
F1-Score : 0.0000

Confusion Matrix:
[[1042    0]
 [3269    0]]

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam

improved_nn = Sequential([
    Dense(128, activation="relu", input_shape=(15,)),
    BatchNormalization(),
    Dropout(0.3),

    Dense(64, activation="relu"),
    BatchNormalization(),
    Dropout(0.25),

    Dense(32, activation="relu"),
    Dropout(0.15),

    Dense(1, activation="sigmoid")
])

improved_nn.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

improved_nn.summary()

c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 128)            │         2,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,185 (51.50 KB)

 Trainable params: 12,801 (50.00 KB)

 Non-trainable params: 384 (1.50 KB)

In [20]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping_improved = EarlyStopping(
    monitor="val_loss",
    patience=7,
    restore_best_weights=True
)

history_improved = improved_nn.fit(
    X_train_scaled,
    y_train,
    validation_split=0.20,
    epochs=50,
    batch_size=32,
    callbacks=[early_stopping_improved],
    verbose=1
)

print("\nTraining completed!")
print(
    "Epochs actually completed:",
    len(history_improved.history["loss"])
)

Epoch 1/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7526 - loss: 0.5790 - val_accuracy: 0.7684 - val_loss: 0.5492
Epoch 2/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7556 - loss: 0.5654 - val_accuracy: 0.7684 - val_loss: 0.5519
Epoch 3/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7556 - loss: 0.5622 - val_accuracy: 0.7684 - val_loss: 0.5435
Epoch 4/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7556 - loss: 0.5624 - val_accuracy: 0.7684 - val_loss: 0.5419
Epoch 5/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7556 - loss: 0.5602 - val_accuracy: 0.7684 - val_loss: 0.5468
Epoch 6/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7556 - loss: 0.5598 - val_accuracy: 0.7684 - val_loss: 0.5414
Epoch 7/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7556 - loss: 0.5606 - val_accuracy: 0.7684 - val_loss: 0.5414
Epoch 8/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7556 - loss: 0.5603 - val_accuracy: 0.7684 - val_loss: 0.5517
Epoch 9/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7556 - loss: 0.5610 - val_accuracy: 0.7684 - val_loss: 0.5444
Epoch 10/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7556 - loss: 0.5597 - val_accuracy: 0.7684 - val_loss: 0.5456
Epoch 11/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7556 - loss: 0.5608 - val_accuracy: 0.7684 - val_loss: 0.5491
Epoch 12/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7556 - loss: 0.5596 - val_accuracy: 0.7684 - val_loss: 0.5445
Epoch 13/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7556 - loss: 0.5589 - val_accuracy: 0.7684 - val_loss: 0.5494
Epoch 14/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7556 - loss: 0.5587 - val_accuracy: 0.7684 - val_loss: 0.5456

Training completed!
Epochs actually completed: 14

In [21]:
from sklearn.utils import resample
import pandas as pd
import numpy as np

# Combine scaled features with labels
train_balanced_df = pd.DataFrame(
    X_train_scaled,
    columns=behavior_features
)
train_balanced_df["label"] = y_train.to_numpy()

# Separate genuine and bot accounts
genuine_train = train_balanced_df[train_balanced_df["label"] == 0]
bot_train = train_balanced_df[train_balanced_df["label"] == 1]

# Randomly reduce bots to match the number of genuine accounts
bot_train_balanced = resample(
    bot_train,
    replace=False,
    n_samples=len(genuine_train),
    random_state=42
)

# Combine them
balanced_train_df = pd.concat(
    [genuine_train, bot_train_balanced],
    axis=0
).sample(frac=1, random_state=42).reset_index(drop=True)

# Separate X and y
X_balanced = balanced_train_df[behavior_features].values
y_balanced = balanced_train_df["label"].values

print("Original training distribution:")
print(y_train.value_counts())

print("\nBalanced training distribution:")
print(pd.Series(y_balanced).value_counts())

print("\nBalanced training shape:")
print(X_balanced.shape)

Original training distribution:
label
1    7625
0    2432
Name: count, dtype: int64

Balanced training distribution:
0    2432
1    2432
Name: count, dtype: int64

Balanced training shape:
(4864, 15)

In [22]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam

balanced_nn = Sequential([
    Dense(128, activation="relu", input_shape=(15,)),
    BatchNormalization(),
    Dropout(0.3),

    Dense(64, activation="relu"),
    BatchNormalization(),
    Dropout(0.25),

    Dense(32, activation="relu"),
    Dropout(0.15),

    Dense(1, activation="sigmoid")
])

balanced_nn.compile(
    optimizer=Adam(learning_rate=0.0005),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

balanced_nn.summary()

c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_10 (Dense)                │ (None, 128)            │         2,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_2           │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_3           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,185 (51.50 KB)

 Trainable params: 12,801 (50.00 KB)

 Non-trainable params: 384 (1.50 KB)

In [23]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping_balanced = EarlyStopping(
    monitor="val_loss",
    patience=7,
    restore_best_weights=True
)

history_balanced = balanced_nn.fit(
    X_balanced,
    y_balanced,
    validation_split=0.20,
    epochs=50,
    batch_size=32,
    callbacks=[early_stopping_balanced],
    verbose=1
)

print("\nTraining completed!")
print(
    "Epochs actually completed:",
    len(history_balanced.history["loss"])
)

Epoch 1/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.5012 - loss: 0.6978 - val_accuracy: 0.4687 - val_loss: 0.6949
Epoch 2/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4986 - loss: 0.6952 - val_accuracy: 0.4687 - val_loss: 0.6953
Epoch 3/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.5027 - loss: 0.6941 - val_accuracy: 0.4687 - val_loss: 0.6943
Epoch 4/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.4996 - loss: 0.6950 - val_accuracy: 0.4687 - val_loss: 0.6974
Epoch 5/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.4986 - loss: 0.6947 - val_accuracy: 0.4687 - val_loss: 0.6963
Epoch 6/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.4983 - loss: 0.6949 - val_accuracy: 0.5313 - val_loss: 0.6927
Epoch 7/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5137 - loss: 0.6938 - val_accuracy: 0.5313 - val_loss: 0.6920
Epoch 8/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5112 - loss: 0.6943 - val_accuracy: 0.5313 - val_loss: 0.6912
Epoch 9/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.4963 - loss: 0.6951 - val_accuracy: 0.4687 - val_loss: 0.6951
Epoch 10/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.4950 - loss: 0.6958 - val_accuracy: 0.4687 - val_loss: 0.6961
Epoch 11/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4955 - loss: 0.6953 - val_accuracy: 0.4687 - val_loss: 0.6941
Epoch 12/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.5035 - loss: 0.6946 - val_accuracy: 0.4687 - val_loss: 0.6954
Epoch 13/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5063 - loss: 0.6937 - val_accuracy: 0.4687 - val_loss: 0.6943
Epoch 14/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.5058 - loss: 0.6950 - val_accuracy: 0.4687 - val_loss: 0.6939
Epoch 15/50
122/122 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5024 - loss: 0.6949 - val_accuracy: 0.4687 - val_loss: 0.6947

Training completed!
Epochs actually completed: 15

In [24]:
print("Training feature statistics:")
print(pd.DataFrame(X_train_scaled, columns=behavior_features).describe().T[
    ["mean", "std", "min", "max"]
])

print("\nUnique predictions from balanced NN:")

balanced_probs = balanced_nn.predict(X_test_scaled, verbose=0).ravel()

print("Minimum probability:", balanced_probs.min())
print("Maximum probability:", balanced_probs.max())
print("Mean probability:", balanced_probs.mean())

Training feature statistics:
                                 mean       std       min        max
statuses_count           1.342380e-17  1.000050 -0.297153  23.200614
followers_count         -3.532578e-19  1.000050 -0.030088  93.970559
friends_count            2.048895e-17  1.000050 -0.217778  77.768854
favourites_count         9.361332e-18  1.000050 -0.200486  31.923890
listed_count             7.065156e-19  1.000050 -0.041957  93.630629
account_age_days         2.269388e-16  1.000054 -1.413364   3.004866
statuses_per_day         1.444502e-17  1.000054 -0.270104  34.942643
followers_friends_ratio  1.455434e-18  1.000051 -0.032875  79.462866
friends_followers_ratio -4.820210e-17  1.000051 -0.418979  19.116535
favorites_per_status    -1.892590e-17  1.000050 -0.136830  71.491804
log_statuses_count      -2.006504e-16  1.000050 -1.854362   2.808317
log_followers_count      1.554334e-17  1.000050 -1.724098   4.853357
log_friends_count        1.342380e-17  1.000050 -3.208710   4.296325
log_favourites_count    -2.508130e-17  1.000050 -0.573448   3.299828
log_listed_count        -9.820567e-17  1.000050 -0.659678   7.611611

Unique predictions from balanced NN:

Minimum probability: 0.5266261
Maximum probability: 0.5266261
Mean probability: 0.5266261

In [25]:
from sklearn.preprocessing import RobustScaler

robust_scaler = RobustScaler()

X_train_robust = robust_scaler.fit_transform(X_train)
X_test_robust = robust_scaler.transform(X_test)

print("Robust-scaled training shape:", X_train_robust.shape)
print("Robust-scaled test shape:", X_test_robust.shape)

print("\nRobust-scaled feature statistics:")
print(
    pd.DataFrame(
        X_train_robust,
        columns=behavior_features
    ).describe().T[["mean", "std", "min", "max"]]
)

Robust-scaled training shape: (10057, 15)
Robust-scaled test shape: (4311, 15)

Robust-scaled feature statistics:
                               mean         std       min           max
statuses_count             3.823582   13.030500 -0.048276    306.124138
followers_count            2.875112   98.230273 -0.080247   9233.169753
friends_count              0.683508    5.467081 -0.507042    425.830986
favourites_count         128.609835  641.521219  0.000000  20607.444444
listed_count               3.635213   86.646520  0.000000   8116.000000
account_age_days           0.389235    0.846079 -0.806518      2.931452
statuses_per_day           2.787013   10.598067 -0.075409    373.091686
followers_friends_ratio    1.958321   66.464655 -0.226604   5283.159802
friends_followers_ratio    0.613245    2.219291 -0.316544     43.036223
favorites_per_status      14.137180  103.324255  0.000000   7400.603319
log_statuses_count         0.257938    0.735066 -1.105073      2.322133
log_followers_count        0.158900    0.587921 -0.854683      3.012149
log_friends_count         -0.114647    0.645819 -2.186792      2.659864
log_favourites_count       0.779980    1.360226  0.000000      5.268269
log_listed_count           0.581079    0.880896  0.000000      7.285787

In [26]:
print("Feature ranges after RobustScaler:")

for feature in behavior_features:
    idx = behavior_features.index(feature)
    print(
        f"{feature:30s} "
        f"min={X_train_robust[:, idx].min():10.3f} "
        f"max={X_train_robust[:, idx].max():10.3f}"
    )

Feature ranges after RobustScaler:
statuses_count                 min=    -0.048 max=   306.124
followers_count                min=    -0.080 max=  9233.170
friends_count                  min=    -0.507 max=   425.831
favourites_count               min=     0.000 max= 20607.444
listed_count                   min=     0.000 max=  8116.000
account_age_days               min=       nan max=       nan
statuses_per_day               min=       nan max=       nan
followers_friends_ratio        min=       nan max=       nan
friends_followers_ratio        min=       nan max=       nan
favorites_per_status           min=       nan max=       nan
log_statuses_count             min=    -1.105 max=     2.322
log_followers_count            min=    -0.855 max=     3.012
log_friends_count              min=    -2.187 max=     2.660
log_favourites_count           min=     0.000 max=     5.268
log_listed_count               min=     0.000 max=     7.286

In [27]:
# Check NaN values in the original training and test data

print("NaN values in X_train:")
print(pd.DataFrame(X_train, columns=behavior_features).isna().sum())

print("\nNaN values in X_test:")
print(pd.DataFrame(X_test, columns=behavior_features).isna().sum())

NaN values in X_train:
statuses_count               0
followers_count              0
friends_count                0
favourites_count             0
listed_count                 0
account_age_days           711
statuses_per_day           711
followers_friends_ratio    293
friends_followers_ratio    328
favorites_per_status       108
log_statuses_count           0
log_followers_count          0
log_friends_count            0
log_favourites_count         0
log_listed_count             0
dtype: int64

NaN values in X_test:
statuses_count               0
followers_count              0
friends_count                0
favourites_count             0
listed_count                 0
account_age_days           289
statuses_per_day           289
followers_friends_ratio    139
friends_followers_ratio    142
favorites_per_status        33
log_statuses_count           0
log_followers_count          0
log_friends_count            0
log_favourites_count         0
log_listed_count             0
dtype: int64

In [28]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# Create imputer
imputer = SimpleImputer(strategy="median")

# Fit ONLY on training data
X_train_imputed = imputer.fit_transform(X_train)

# Apply same imputer to test data
X_test_imputed = imputer.transform(X_test)

# Scale after imputation
nn_scaler = StandardScaler()

X_train_nn = nn_scaler.fit_transform(X_train_imputed)
X_test_nn = nn_scaler.transform(X_test_imputed)

print("Training shape:", X_train_nn.shape)
print("Test shape:", X_test_nn.shape)

print("\nNaNs after imputation:")
print("Training:", np.isnan(X_train_nn).sum())
print("Test:", np.isnan(X_test_nn).sum())

Training shape: (10057, 15)
Test shape: (4311, 15)

NaNs after imputation:
Training: 0
Test: 0

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

clean_nn = Sequential([
    Dense(128, activation="relu", input_shape=(X_train_nn.shape[1],)),
    BatchNormalization(),
    Dropout(0.25),

    Dense(64, activation="relu"),
    BatchNormalization(),
    Dropout(0.20),

    Dense(32, activation="relu"),
    Dropout(0.10),

    Dense(1, activation="sigmoid")
])

clean_nn.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

clean_nn.summary()

c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_14 (Dense)                │ (None, 128)            │         2,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_4           │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_10 (Dropout)            │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_11 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_12 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,185 (51.50 KB)

 Trainable params: 12,801 (50.00 KB)

 Non-trainable params: 384 (1.50 KB)

In [30]:
early_stopping_clean = EarlyStopping(
    monitor="val_loss",
    patience=7,
    restore_best_weights=True
)

history_clean = clean_nn.fit(
    X_train_nn,
    y_train,
    validation_split=0.20,
    epochs=50,
    batch_size=32,
    callbacks=[early_stopping_clean],
    verbose=1
)

print("\nTraining completed!")
print(
    "Epochs actually completed:",
    len(history_clean.history["loss"])
)

Epoch 1/50

252/252 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.9507 - loss: 0.1387 - val_accuracy: 0.9856 - val_loss: 0.0792
Epoch 2/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9802 - loss: 0.0700 - val_accuracy: 0.9866 - val_loss: 0.0601
Epoch 3/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9823 - loss: 0.0606 - val_accuracy: 0.9866 - val_loss: 0.0566
Epoch 4/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9830 - loss: 0.0614 - val_accuracy: 0.9866 - val_loss: 0.0482
Epoch 5/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9832 - loss: 0.0601 - val_accuracy: 0.9866 - val_loss: 0.0546
Epoch 6/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9851 - loss: 0.0545 - val_accuracy: 0.9871 - val_loss: 0.0571
Epoch 7/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9841 - loss: 0.0552 - val_accuracy: 0.9871 - val_loss: 0.0590
Epoch 8/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9862 - loss: 0.0495 - val_accuracy: 0.9876 - val_loss: 0.0496
Epoch 9/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9838 - loss: 0.0517 - val_accuracy: 0.9871 - val_loss: 0.0556
Epoch 10/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9865 - loss: 0.0511 - val_accuracy: 0.9881 - val_loss: 0.0453
Epoch 11/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9867 - loss: 0.0476 - val_accuracy: 0.9881 - val_loss: 0.0514
Epoch 12/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9856 - loss: 0.0463 - val_accuracy: 0.9891 - val_loss: 0.0508
Epoch 13/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9872 - loss: 0.0473 - val_accuracy: 0.9891 - val_loss: 0.0446
Epoch 14/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9867 - loss: 0.0468 - val_accuracy: 0.9871 - val_loss: 0.0493
Epoch 15/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9862 - loss: 0.0463 - val_accuracy: 0.9891 - val_loss: 0.0414
Epoch 16/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9874 - loss: 0.0473 - val_accuracy: 0.9906 - val_loss: 0.0402
Epoch 17/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9872 - loss: 0.0438 - val_accuracy: 0.9886 - val_loss: 0.0483
Epoch 18/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9869 - loss: 0.0469 - val_accuracy: 0.9861 - val_loss: 0.0554
Epoch 19/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9867 - loss: 0.0446 - val_accuracy: 0.9891 - val_loss: 0.0513
Epoch 20/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9862 - loss: 0.0462 - val_accuracy: 0.9891 - val_loss: 0.0430
Epoch 21/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9878 - loss: 0.0443 - val_accuracy: 0.9886 - val_loss: 0.0416
Epoch 22/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9882 - loss: 0.0442 - val_accuracy: 0.9871 - val_loss: 0.0501
Epoch 23/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9868 - loss: 0.0451 - val_accuracy: 0.9866 - val_loss: 0.0544

Training completed!
Epochs actually completed: 23

In [31]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Predict probabilities
test_probs_clean = clean_nn.predict(
    X_test_nn,
    verbose=0
).ravel()

# Convert probabilities to class predictions
test_pred_clean = (test_probs_clean >= 0.5).astype(int)

print("Cleaned Behavioral Neural Network Performance")
print("=" * 55)

print(f"Accuracy : {accuracy_score(y_test, test_pred_clean):.4f}")
print(f"Precision: {precision_score(y_test, test_pred_clean):.4f}")
print(f"Recall   : {recall_score(y_test, test_pred_clean):.4f}")
print(f"F1-Score : {f1_score(y_test, test_pred_clean):.4f}")

print("\nDetailed Classification Report:")
print(
    classification_report(
        y_test,
        test_pred_clean,
        target_names=["Genuine", "Bot"]
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, test_pred_clean))

Cleaned Behavioral Neural Network Performance
=======================================================
Accuracy : 0.9865
Precision: 0.9929
Recall   : 0.9893
F1-Score : 0.9911

Detailed Classification Report:
              precision    recall  f1-score   support

     Genuine       0.97      0.98      0.97      1042
         Bot       0.99      0.99      0.99      3269

    accuracy                           0.99      4311
   macro avg       0.98      0.98      0.98      4311
weighted avg       0.99      0.99      0.99      4311


Confusion Matrix:
[[1019   23]
 [  35 3234]]

In [32]:
# Check available variables related to temporal evaluation

temporal_vars = [
    var for var in globals()
    if any(keyword in var.lower() for keyword in ["temporal", "time", "date", "train", "test"])
]

print("Potential temporal variables:")
for var in temporal_vars:
    print(var)

Potential temporal variables:
train_test_split
X_train
X_test
y_train
y_test
X_train_scaled
X_test_scaled
y_test_prob
y_test_pred
train_balanced_df
genuine_train
bot_train
bot_train_balanced
balanced_train_df
X_train_robust
X_test_robust
X_train_imputed
X_test_imputed
X_train_nn
X_test_nn
test_probs_clean
test_pred_clean

In [33]:
import pandas as pd

dataframes = []

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        dataframes.append((name, obj.shape))

print("DataFrames currently loaded:")

if dataframes:
    for name, shape in dataframes:
        print(f"{name}: {shape}")
else:
    print("No DataFrames currently loaded.")

DataFrames currently loaded:
behavior_df: (14368, 20)
X: (14368, 15)
X_train: (10057, 15)
X_test: (4311, 15)
train_balanced_df: (10057, 16)
genuine_train: (2432, 16)
bot_train: (7625, 16)
bot_train_balanced: (2432, 16)
balanced_train_df: (4864, 16)

In [34]:
# Find all variables that may belong to our temporal evaluation
keywords = ["temporal", "future", "time", "date", "cutoff"]

matches = []

for name in list(globals().keys()):
    if any(k in name.lower() for k in keywords):
        matches.append(name)

print("Potential temporal/time-related variables:")
for name in sorted(set(matches)):
    print(name)

Potential temporal/time-related variables:
temporal_vars

In [35]:
print("Behavior dataframe columns:")
print(behavior_df.columns.tolist())

Behavior dataframe columns:
['id', 'account_type', 'label', 'statuses_count', 'followers_count', 'friends_count', 'favourites_count', 'listed_count', 'created_at', 'updated', 'account_age_days', 'statuses_per_day', 'followers_friends_ratio', 'friends_followers_ratio', 'favorites_per_status', 'log_statuses_count', 'log_followers_count', 'log_friends_count', 'log_favourites_count', 'log_listed_count']

In [36]:
print("created_at sample:")
print(behavior_df["created_at"].head(10))

print("\nData type:")
print(behavior_df["created_at"].dtype)

print("\nDate range:")
print(behavior_df["created_at"].min())
print(behavior_df["created_at"].max())

created_at sample:
0    Tue Jun 11 11:20:35 +0000 2013
1    Tue May 13 10:37:57 +0000 2014
2    Wed May 04 23:30:37 +0000 2011
3    Fri Sep 17 14:02:10 +0000 2010
4    Fri Feb 06 04:10:49 +0000 2015
5    Mon Oct 28 16:08:18 +0000 2013
6    Tue Oct 08 15:59:30 +0000 2013
7    Tue Feb 22 04:37:34 +0000 2011
8    Thu Sep 05 20:52:02 +0000 2013
9    Mon Apr 08 08:37:42 +0000 2013
Name: created_at, dtype: str

Data type:
str

Date range:
1183552203000L
Wed Sep 30 23:34:09 +0000 2009

In [37]:
print("\nLabel distribution by year:")

temp = behavior_df.copy()
temp["created_date"] = pd.to_datetime(
    temp["created_at"],
    errors="coerce"
)

print(temp.groupby(temp["created_date"].dt.year)["label"].value_counts())

Label distribution by year:

C:\Users\namit\AppData\Local\Temp\ipykernel_1412\2335887537.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp["created_date"] = pd.to_datetime(

created_date  label
2007.0        0          35
              1           1
2008.0        0         107
              1          12
2009.0        1        1255
              0         558
2010.0        0         412
              1         404
2011.0        0         580
              1         535
2012.0        1        2369
              0         588
2013.0        1        1485
              0         554
2014.0        1        3705
              0         502
2015.0        0         138
              1         128
Name: count, dtype: int64

In [38]:
import pandas as pd
import numpy as np

temporal_df = behavior_df.copy()

temporal_df["created_date"] = pd.to_datetime(
    temporal_df["created_at"],
    errors="coerce"
)

# Check invalid dates
print("Invalid dates:", temporal_df["created_date"].isna().sum())

# Remove invalid dates
temporal_df = temporal_df.dropna(subset=["created_date"]).copy()

# Sort chronologically
temporal_df = temporal_df.sort_values("created_date").reset_index(drop=True)

print("Temporal dataset shape:", temporal_df.shape)
print("Earliest:", temporal_df["created_date"].min())
print("Latest:", temporal_df["created_date"].max())

C:\Users\namit\AppData\Local\Temp\ipykernel_1412\3170706949.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temporal_df["created_date"] = pd.to_datetime(

Invalid dates: 1000
Temporal dataset shape: (13368, 21)
Earliest: 2007-01-22 01:57:38+00:00
Latest: 2015-11-30 18:00:41+00:00

In [39]:
split_index = int(len(temporal_df) * 0.70)

temporal_train_df = temporal_df.iloc[:split_index].copy()
temporal_test_df = temporal_df.iloc[split_index:].copy()

print("Temporal training:", temporal_train_df.shape)
print("Temporal testing :", temporal_test_df.shape)

print("\nTraining date range:")
print(temporal_train_df["created_date"].min())
print(temporal_train_df["created_date"].max())

print("\nTesting date range:")
print(temporal_test_df["created_date"].min())
print(temporal_test_df["created_date"].max())

print("\nTraining labels:")
print(temporal_train_df["label"].value_counts())

print("\nTesting labels:")
print(temporal_test_df["label"].value_counts())

Temporal training: (9357, 21)
Temporal testing : (4011, 21)

Training date range:
2007-01-22 01:57:38+00:00
2014-02-19 17:01:32+00:00

Testing date range:
2014-02-19 17:03:01+00:00
2015-11-30 18:00:41+00:00

Training labels:
label
1    6447
0    2910
Name: count, dtype: int64

Testing labels:
label
1    3447
0     564
Name: count, dtype: int64

In [40]:
invalid_dates = behavior_df[
    pd.to_datetime(
        behavior_df["created_at"],
        errors="coerce"
    ).isna()
]

print("Invalid date rows:", len(invalid_dates))

print("\nInvalid created_at examples:")
print(invalid_dates["created_at"].head(20).to_list())

print("\nLabels of invalid-date accounts:")
print(invalid_dates["label"].value_counts())

print("\nAccount types:")
print(invalid_dates["account_type"].value_counts())

C:\Users\namit\AppData\Local\Temp\ipykernel_1412\2872252185.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(

Invalid date rows: 1000

Invalid created_at examples:
['1183552203000L', '1185440851000L', '1192725360000L', '1196614406000L', '1209536534000L', '1211155018000L', '1212017203000L', '1216718943000L', '1223578831000L', '1223956217000L', '1228777401000L', '1232222609000L', '1232785000000L', '1233042075000L', '1234046205000L', '1234289703000L', '1235321212000L', '1236064330000L', '1236287604000L', '1236806337000L']

Labels of invalid-date accounts:
label
1    1000
Name: count, dtype: int64

Account types:
account_type
traditional_spambots_1    1000
Name: count, dtype: int64

In [41]:
def parse_created_at(value):
    value = str(value).strip()

    # Handle Unix timestamp ending with L
    if value.endswith("L"):
        try:
            timestamp_ms = int(value[:-1])
            return pd.to_datetime(timestamp_ms, unit="ms", utc=True)
        except:
            return pd.NaT

    # Handle normal Twitter date format
    try:
        return pd.to_datetime(value, utc=True)
    except:
        return pd.NaT


temporal_df = behavior_df.copy()

temporal_df["created_date"] = temporal_df["created_at"].apply(
    parse_created_at
)

print("Invalid dates after fixing:", temporal_df["created_date"].isna().sum())

print("\nDate range:")
print(temporal_df["created_date"].min())
print(temporal_df["created_date"].max())

Invalid dates after fixing: 0

Date range:
2007-01-22 01:57:38+00:00
2015-11-30 18:00:41+00:00

In [42]:
# Sort all accounts chronologically
temporal_df = temporal_df.sort_values("created_date").reset_index(drop=True)

# 70% earliest accounts for training
# 30% latest accounts for testing
split_index = int(len(temporal_df) * 0.70)

temporal_train_df = temporal_df.iloc[:split_index].copy()
temporal_test_df = temporal_df.iloc[split_index:].copy()

print("Temporal training shape:", temporal_train_df.shape)
print("Temporal testing shape :", temporal_test_df.shape)

print("\nTraining date range:")
print(temporal_train_df["created_date"].min())
print("→", temporal_train_df["created_date"].max())

print("\nTesting date range:")
print(temporal_test_df["created_date"].min())
print("→", temporal_test_df["created_date"].max())

print("\nTraining label distribution:")
print(temporal_train_df["label"].value_counts())

print("\nTesting label distribution:")
print(temporal_test_df["label"].value_counts())

Temporal training shape: (10057, 21)
Temporal testing shape : (4311, 21)

Training date range:
2007-01-22 01:57:38+00:00
→ 2014-02-14 07:51:21+00:00

Testing date range:
2014-02-14 09:51:29+00:00
→ 2015-11-30 18:00:41+00:00

Training label distribution:
label
1    7154
0    2903
Name: count, dtype: int64

Testing label distribution:
label
1    3740
0     571
Name: count, dtype: int64

In [43]:
behavioral_features = [
    "statuses_count",
    "followers_count",
    "friends_count",
    "favourites_count",
    "listed_count",
    "account_age_days",
    "statuses_per_day",
    "followers_friends_ratio",
    "friends_followers_ratio",
    "favorites_per_status",
    "log_statuses_count",
    "log_followers_count",
    "log_friends_count",
    "log_favourites_count",
    "log_listed_count"
]

X_temporal_train = temporal_train_df[behavioral_features].copy()
y_temporal_train = temporal_train_df["label"].copy()

X_temporal_test = temporal_test_df[behavioral_features].copy()
y_temporal_test = temporal_test_df["label"].copy()

print("Temporal training features:", X_temporal_train.shape)
print("Temporal testing features :", X_temporal_test.shape)

print("\nNaNs before imputation:")
print("Training:", X_temporal_train.isna().sum().sum())
print("Testing :", X_temporal_test.isna().sum().sum())

Temporal training features: (10057, 15)
Temporal testing features : (4311, 15)

NaNs before imputation:
Training: 2964
Testing : 79

In [44]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

temporal_imputer = SimpleImputer(strategy="median")

X_temporal_train_imp = temporal_imputer.fit_transform(
    X_temporal_train
)

X_temporal_test_imp = temporal_imputer.transform(
    X_temporal_test
)

temporal_scaler = StandardScaler()

X_temporal_train_scaled = temporal_scaler.fit_transform(
    X_temporal_train_imp
)

X_temporal_test_scaled = temporal_scaler.transform(
    X_temporal_test_imp
)

print("Scaled temporal training:", X_temporal_train_scaled.shape)
print("Scaled temporal testing :", X_temporal_test_scaled.shape)

print("\nNaNs after imputation:")
print("Training:", np.isnan(X_temporal_train_scaled).sum())
print("Testing :", np.isnan(X_temporal_test_scaled).sum())

Scaled temporal training: (10057, 15)
Scaled temporal testing : (4311, 15)

NaNs after imputation:
Training: 0
Testing : 0

In [45]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

temporal_nn = Sequential([
    Dense(128, activation="relu", input_shape=(15,)),
    BatchNormalization(),
    Dropout(0.25),

    Dense(64, activation="relu"),
    BatchNormalization(),
    Dropout(0.20),

    Dense(32, activation="relu"),
    Dropout(0.10),

    Dense(1, activation="sigmoid")
])

temporal_nn.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

temporal_nn.summary()

c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_18 (Dense)                │ (None, 128)            │         2,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_13 (Dropout)            │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_7           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_14 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_15 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,185 (51.50 KB)

 Trainable params: 12,801 (50.00 KB)

 Non-trainable params: 384 (1.50 KB)

In [46]:
early_stopping_temporal = EarlyStopping(
    monitor="val_loss",
    patience=7,
    restore_best_weights=True
)

history_temporal = temporal_nn.fit(
    X_temporal_train_scaled,
    y_temporal_train,
    validation_split=0.20,
    epochs=50,
    batch_size=32,
    callbacks=[early_stopping_temporal],
    verbose=1
)

print("\nTemporal NN training completed!")
print(
    "Epochs actually completed:",
    len(history_temporal.history["loss"])
)

Epoch 1/50

252/252 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9682 - loss: 0.1061 - val_accuracy: 0.9433 - val_loss: 0.1448
Epoch 2/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9820 - loss: 0.0675 - val_accuracy: 0.9771 - val_loss: 0.0771
Epoch 3/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9812 - loss: 0.0642 - val_accuracy: 0.9737 - val_loss: 0.0916
Epoch 4/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9838 - loss: 0.0605 - val_accuracy: 0.9806 - val_loss: 0.0733
Epoch 5/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9831 - loss: 0.0597 - val_accuracy: 0.9761 - val_loss: 0.0795
Epoch 6/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9840 - loss: 0.0538 - val_accuracy: 0.9737 - val_loss: 0.0797
Epoch 7/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9848 - loss: 0.0534 - val_accuracy: 0.9776 - val_loss: 0.0727
Epoch 8/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9862 - loss: 0.0525 - val_accuracy: 0.9727 - val_loss: 0.0891
Epoch 9/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9863 - loss: 0.0514 - val_accuracy: 0.9727 - val_loss: 0.0894
Epoch 10/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9856 - loss: 0.0508 - val_accuracy: 0.9747 - val_loss: 0.0764
Epoch 11/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9860 - loss: 0.0513 - val_accuracy: 0.9756 - val_loss: 0.0823
Epoch 12/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9861 - loss: 0.0483 - val_accuracy: 0.9747 - val_loss: 0.0925
Epoch 13/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9857 - loss: 0.0524 - val_accuracy: 0.9781 - val_loss: 0.0801
Epoch 14/50
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9871 - loss: 0.0464 - val_accuracy: 0.9751 - val_loss: 0.0796

Temporal NN training completed!
Epochs actually completed: 14

In [47]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Predict probabilities
temporal_probabilities = temporal_nn.predict(
    X_temporal_test_scaled
).ravel()

# Convert probabilities to class predictions
temporal_predictions = (
    temporal_probabilities >= 0.5
).astype(int)

# Calculate metrics
temporal_accuracy = accuracy_score(
    y_temporal_test,
    temporal_predictions
)

temporal_precision = precision_score(
    y_temporal_test,
    temporal_predictions,
    zero_division=0
)

temporal_recall = recall_score(
    y_temporal_test,
    temporal_predictions,
    zero_division=0
)

temporal_f1 = f1_score(
    y_temporal_test,
    temporal_predictions,
    zero_division=0
)

print("Temporal Behavioral Neural Network Performance")
print("=" * 55)
print(f"Accuracy : {temporal_accuracy:.4f}")
print(f"Precision: {temporal_precision:.4f}")
print(f"Recall   : {temporal_recall:.4f}")
print(f"F1-Score : {temporal_f1:.4f}")

print("\nDetailed Classification Report:")
print(
    classification_report(
        y_temporal_test,
        temporal_predictions,
        target_names=["Genuine", "Bot"],
        zero_division=0
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_temporal_test,
        temporal_predictions
    )
)

135/135 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Temporal Behavioral Neural Network Performance
=======================================================
Accuracy : 0.9661
Precision: 0.9672
Recall   : 0.9947
F1-Score : 0.9808

Detailed Classification Report:
              precision    recall  f1-score   support

     Genuine       0.96      0.78      0.86       571
         Bot       0.97      0.99      0.98      3740

    accuracy                           0.97      4311
   macro avg       0.96      0.89      0.92      4311
weighted avg       0.97      0.97      0.96      4311


Confusion Matrix:
[[ 445  126]
 [  20 3720]]

In [48]:
print("\nPrediction Probability Statistics")
print("=" * 55)
print(f"Minimum probability: {temporal_probabilities.min():.4f}")
print(f"Maximum probability: {temporal_probabilities.max():.4f}")
print(f"Mean probability   : {temporal_probabilities.mean():.4f}")

print("\nPrediction distribution:")
print(
    pd.Series(temporal_predictions)
    .value_counts()
    .sort_index()
)

Prediction Probability Statistics
=======================================================
Minimum probability: 0.0000
Maximum probability: 1.0000
Mean probability   : 0.8857

Prediction distribution:
0     465
1    3846
Name: count, dtype: int64

In [49]:
print("Account types:")
print(behavior_df["account_type"].value_counts())

Account types:
account_type
genuine_accounts          3474
social_spambots_2         3457
fake_followers            3351
traditional_spambots_4    1128
traditional_spambots_1    1000
social_spambots_1          991
social_spambots_3          464
traditional_spambots_3     403
traditional_spambots_2     100
Name: count, dtype: int64

In [50]:
print("\nBot types by label:")
print(
    pd.crosstab(
        behavior_df["account_type"],
        behavior_df["label"]
    )
)

Bot types by label:
label                      0     1
account_type
fake_followers             0  3351
genuine_accounts        3474     0
social_spambots_1          0   991
social_spambots_2          0  3457
social_spambots_3          0   464
traditional_spambots_1     0  1000
traditional_spambots_2     0   100
traditional_spambots_3     0   403
traditional_spambots_4     0  1128

In [51]:
# Cross-type evaluation:
# Fake followers are completely excluded from training.

cross_train_df = behavior_df[
    behavior_df["account_type"] != "fake_followers"
].copy()

cross_test_df = behavior_df[
    behavior_df["account_type"] == "fake_followers"
].copy()

print("Cross-type training shape:", cross_train_df.shape)
print("Unseen fake-follower test shape:", cross_test_df.shape)

print("\nTraining account types:")
print(cross_train_df["account_type"].value_counts())

print("\nTest account type:")
print(cross_test_df["account_type"].value_counts())

print("\nTraining labels:")
print(cross_train_df["label"].value_counts())

print("\nTest labels:")
print(cross_test_df["label"].value_counts())

Cross-type training shape: (11017, 20)
Unseen fake-follower test shape: (3351, 20)

Training account types:
account_type
genuine_accounts          3474
social_spambots_2         3457
traditional_spambots_4    1128
traditional_spambots_1    1000
social_spambots_1          991
social_spambots_3          464
traditional_spambots_3     403
traditional_spambots_2     100
Name: count, dtype: int64

Test account type:
account_type
fake_followers    3351
Name: count, dtype: int64

Training labels:
label
1    7543
0    3474
Name: count, dtype: int64

Test labels:
label
1    3351
Name: count, dtype: int64

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler

# Same 15 behavioral features used by our NN
behavior_features = [
    "statuses_count",
    "followers_count",
    "friends_count",
    "favourites_count",
    "listed_count",
    "account_age_days",
    "statuses_per_day",
    "followers_friends_ratio",
    "friends_followers_ratio",
    "favorites_per_status",
    "log_statuses_count",
    "log_followers_count",
    "log_friends_count",
    "log_favourites_count",
    "log_listed_count"
]

# Separate X and y
X_cross_train = cross_train_df[behavior_features].copy()
y_cross_train = cross_train_df["label"].copy()

X_cross_test = cross_test_df[behavior_features].copy()
y_cross_test = cross_test_df["label"].copy()

print("Cross-type training features:", X_cross_train.shape)
print("Cross-type test features:", X_cross_test.shape)

# Check missing values
print("\nNaNs before imputation:")
print("Training:", X_cross_train.isna().sum().sum())
print("Testing :", X_cross_test.isna().sum().sum())

# Fit imputer ONLY on training data
imputer_cross = SimpleImputer(strategy="median")

X_cross_train_imp = imputer_cross.fit_transform(X_cross_train)
X_cross_test_imp = imputer_cross.transform(X_cross_test)

# Fit scaler ONLY on training data
scaler_cross = RobustScaler()

X_cross_train_scaled = scaler_cross.fit_transform(X_cross_train_imp)
X_cross_test_scaled = scaler_cross.transform(X_cross_test_imp)

print("\nNaNs after imputation:")
print("Training:", np.isnan(X_cross_train_scaled).sum())
print("Testing :", np.isnan(X_cross_test_scaled).sum())

print("\nFinal shapes:")
print("Training:", X_cross_train_scaled.shape)
print("Testing :", X_cross_test_scaled.shape)

Cross-type training features: (11017, 15)
Cross-type test features: (3351, 15)

NaNs before imputation:
Training: 2825
Testing : 218

NaNs after imputation:
Training: 0
Testing : 0

Final shapes:
Training: (11017, 15)
Testing : (3351, 15)

In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping

# Build cross-type behavioral NN
cross_nn = Sequential([
    Dense(128, activation="relu", input_shape=(15,)),
    BatchNormalization(),
    Dropout(0.3),

    Dense(64, activation="relu"),
    BatchNormalization(),
    Dropout(0.2),

    Dense(32, activation="relu"),
    Dropout(0.1),

    Dense(1, activation="sigmoid")
])

cross_nn.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

cross_nn.summary()

c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_22 (Dense)                │ (None, 128)            │         2,048 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_8           │ (None, 128)            │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_16 (Dropout)            │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_9           │ (None, 64)             │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_17 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_24 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_18 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,185 (51.50 KB)

 Trainable params: 12,801 (50.00 KB)

 Non-trainable params: 384 (1.50 KB)

In [54]:
early_stopping_cross = EarlyStopping(
    monitor="val_loss",
    patience=8,
    restore_best_weights=True
)

history_cross = cross_nn.fit(
    X_cross_train_scaled,
    y_cross_train,
    validation_split=0.20,
    epochs=50,
    batch_size=32,
    callbacks=[early_stopping_cross],
    verbose=1
)

print("\nCross-type NN training completed!")
print("Epochs actually completed:", len(history_cross.history["loss"]))

Epoch 1/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.9358 - loss: 0.1772 - val_accuracy: 0.9850 - val_loss: 0.1440
Epoch 2/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9711 - loss: 0.0948 - val_accuracy: 0.9832 - val_loss: 0.1292
Epoch 3/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9729 - loss: 0.0892 - val_accuracy: 0.9823 - val_loss: 0.1118
Epoch 4/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9795 - loss: 0.0772 - val_accuracy: 0.9819 - val_loss: 0.0852
Epoch 5/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9801 - loss: 0.0736 - val_accuracy: 0.9823 - val_loss: 0.0905
Epoch 6/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9801 - loss: 0.0715 - val_accuracy: 0.9832 - val_loss: 0.1035
Epoch 7/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9812 - loss: 0.0673 - val_accuracy: 0.9814 - val_loss: 0.0910
Epoch 8/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9812 - loss: 0.0660 - val_accuracy: 0.9850 - val_loss: 0.0936
Epoch 9/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9816 - loss: 0.0640 - val_accuracy: 0.9832 - val_loss: 0.0765
Epoch 10/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9828 - loss: 0.0605 - val_accuracy: 0.9859 - val_loss: 0.0638
Epoch 11/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9839 - loss: 0.0570 - val_accuracy: 0.9823 - val_loss: 0.0756
Epoch 12/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9825 - loss: 0.0571 - val_accuracy: 0.9819 - val_loss: 0.0808
Epoch 13/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9835 - loss: 0.0569 - val_accuracy: 0.9828 - val_loss: 0.0820
Epoch 14/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9857 - loss: 0.0536 - val_accuracy: 0.9814 - val_loss: 0.1155
Epoch 15/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9850 - loss: 0.0559 - val_accuracy: 0.9805 - val_loss: 0.1069
Epoch 16/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9856 - loss: 0.0526 - val_accuracy: 0.9832 - val_loss: 0.0847
Epoch 17/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9851 - loss: 0.0530 - val_accuracy: 0.9832 - val_loss: 0.0600
Epoch 18/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9847 - loss: 0.0562 - val_accuracy: 0.9782 - val_loss: 0.1299
Epoch 19/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9862 - loss: 0.0488 - val_accuracy: 0.9819 - val_loss: 0.0864
Epoch 20/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9866 - loss: 0.0486 - val_accuracy: 0.9800 - val_loss: 0.1154
Epoch 21/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9867 - loss: 0.0483 - val_accuracy: 0.9796 - val_loss: 0.1286
Epoch 22/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9865 - loss: 0.0498 - val_accuracy: 0.9809 - val_loss: 0.0831
Epoch 23/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9868 - loss: 0.0492 - val_accuracy: 0.9796 - val_loss: 0.0937
Epoch 24/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9865 - loss: 0.0469 - val_accuracy: 0.9796 - val_loss: 0.0851
Epoch 25/50
276/276 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9859 - loss: 0.0465 - val_accuracy: 0.9809 - val_loss: 0.0833

Cross-type NN training completed!
Epochs actually completed: 25

In [55]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)
import numpy as np

# Predict probabilities
cross_probabilities = cross_nn.predict(
    X_cross_test_scaled,
    verbose=0
).ravel()

# Convert probabilities to class predictions
cross_predictions = (cross_probabilities >= 0.5).astype(int)

# Metrics
cross_accuracy = accuracy_score(y_cross_test, cross_predictions)
cross_precision = precision_score(
    y_cross_test,
    cross_predictions,
    zero_division=0
)
cross_recall = recall_score(
    y_cross_test,
    cross_predictions,
    zero_division=0
)
cross_f1 = f1_score(
    y_cross_test,
    cross_predictions,
    zero_division=0
)

print("Cross-Type Behavioral Neural Network Performance")
print("=" * 60)
print(f"Accuracy : {cross_accuracy:.4f}")
print(f"Precision: {cross_precision:.4f}")
print(f"Recall   : {cross_recall:.4f}")
print(f"F1-Score : {cross_f1:.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_cross_test,
        cross_predictions,
        target_names=["Genuine", "Bot"],
        zero_division=0
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_cross_test, cross_predictions))

print("\nPrediction Probability Statistics")
print("=" * 60)
print(f"Minimum probability: {cross_probabilities.min():.4f}")
print(f"Maximum probability: {cross_probabilities.max():.4f}")
print(f"Mean probability   : {cross_probabilities.mean():.4f}")

print("\nPrediction distribution:")
print(pd.Series(cross_predictions).value_counts().sort_index())

Cross-Type Behavioral Neural Network Performance
============================================================
Accuracy : 0.9779
Precision: 1.0000
Recall   : 0.9779
F1-Score : 0.9888

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.00      0.00      0.00         0
         Bot       1.00      0.98      0.99      3351

    accuracy                           0.98      3351
   macro avg       0.50      0.49      0.49      3351
weighted avg       1.00      0.98      0.99      3351


Confusion Matrix:
[[   0    0]
 [  74 3277]]

Prediction Probability Statistics
============================================================
Minimum probability: 0.0037
Maximum probability: 1.0000
Mean probability   : 0.9519

Prediction distribution:
0      74
1    3277
Name: count, dtype: int64

In [56]:
# ============================================================
# Reliability / Confidence Analysis - Cross-Type NN
# ============================================================

import numpy as np
import pandas as pd

# Confidence of each prediction
# Probability close to 0 or 1 = high confidence
# Probability close to 0.5 = low confidence
cross_confidence = np.abs(cross_probabilities - 0.5) * 2

# Create results dataframe
reliability_df = pd.DataFrame({
    "actual_label": y_cross_test,
    "predicted_label": cross_predictions,
    "bot_probability": cross_probabilities,
    "confidence": cross_confidence
})

# Correct / incorrect prediction
reliability_df["correct"] = (
    reliability_df["actual_label"] ==
    reliability_df["predicted_label"]
)

print("Cross-Type Reliability Analysis")
print("=" * 60)

print(f"Average confidence : {cross_confidence.mean():.4f}")
print(f"Minimum confidence : {cross_confidence.min():.4f}")
print(f"Maximum confidence : {cross_confidence.max():.4f}")

print("\nConfidence distribution:")
print(
    pd.cut(
        cross_confidence,
        bins=[0, 0.2, 0.4, 0.6, 0.8, 1.0],
        labels=[
            "Very Low",
            "Low",
            "Medium",
            "High",
            "Very High"
        ]
    ).value_counts().sort_index()
)

print("\nAverage confidence:")
print(
    reliability_df.groupby("correct")["confidence"].mean()
)

print("\nCorrect predictions:")
print(
    reliability_df["correct"].value_counts()
)

print("\nReliability summary:")
print(
    reliability_df[
        ["bot_probability", "confidence", "correct"]
    ].describe()
)

Cross-Type Reliability Analysis
============================================================
Average confidence : 0.9236
Minimum confidence : 0.0033
Maximum confidence : 1.0000

Confidence distribution:
Very Low       44
Low            88
Medium         49
High           78
Very High    3092
Name: count, dtype: int64

Average confidence:
correct
False    0.445833
True     0.934370
Name: confidence, dtype: float32

Correct predictions:
correct
True     3277
False      74
Name: count, dtype: int64

Reliability summary:
       bot_probability   confidence
count      3351.000000  3351.000000
mean          0.951945     0.923581
std           0.123557     0.158335
min           0.003662     0.003252
25%           0.979122     0.958264
50%           0.981047     0.962096
75%           0.985952     0.971992
max           0.999999     0.999998

In [57]:
# ============================================================
# Confidence-Based Flagging
# ============================================================

reliability_df["confidence_level"] = pd.cut(
    reliability_df["confidence"],
    bins=[-0.001, 0.50, 0.80, 1.00],
    labels=["Low Confidence", "Review", "High Confidence"]
)

print("Confidence-Based Flagging")
print("=" * 60)

print("\nAccount distribution:")
print(
    reliability_df["confidence_level"]
    .value_counts()
    .sort_index()
)

print("\nPercent distribution:")
print(
    reliability_df["confidence_level"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

# Check correctness within each confidence level
print("\nAccuracy by confidence level:")
print(
    reliability_df.groupby(
        "confidence_level",
        observed=True
    )["correct"]
    .mean()
    .mul(100)
    .round(2)
)

# Number of errors in each confidence group
print("\nErrors by confidence level:")
print(
    reliability_df[
        reliability_df["correct"] == False
    ]["confidence_level"]
    .value_counts()
    .sort_index()
)

Confidence-Based Flagging
============================================================

Account distribution:
confidence_level
Low Confidence      165
Review               94
High Confidence    3092
Name: count, dtype: int64

Percent distribution:
confidence_level
Low Confidence      4.92
Review              2.81
High Confidence    92.27
Name: proportion, dtype: float64

Accuracy by confidence level:
confidence_level
Low Confidence     73.33
Review             79.79
High Confidence    99.64
Name: correct, dtype: float64

Errors by confidence level:
confidence_level
Low Confidence     44
Review             19
High Confidence    11
Name: count, dtype: int64

In [58]:
# ============================================================
# Reliability Score + Final Decision
# ============================================================

# Convert confidence from 0-1 to 0-100
reliability_df["reliability_score"] = (
    reliability_df["confidence"] * 100
)

# Final decision
reliability_df["final_decision"] = np.select(
    [
        reliability_df["reliability_score"] >= 80,
        reliability_df["reliability_score"] >= 50
    ],
    [
        "HIGH-CONFIDENCE FLAG",
        "REVIEW"
    ],
    default="LOW-CONFIDENCE"
)

print("Final Reliability-Aware Decision System")
print("=" * 60)

print("\nDecision distribution:")
print(
    reliability_df["final_decision"]
    .value_counts()
)

print("\nDecision percentage:")
print(
    reliability_df["final_decision"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nAverage reliability score:")
print(
    reliability_df["reliability_score"].mean()
)

print("\nReliability score statistics:")
print(
    reliability_df["reliability_score"].describe()
)

Final Reliability-Aware Decision System
============================================================

Decision distribution:
final_decision
HIGH-CONFIDENCE FLAG    3092
LOW-CONFIDENCE           165
REVIEW                    94
Name: count, dtype: int64

Decision percentage:
final_decision
HIGH-CONFIDENCE FLAG    92.27
LOW-CONFIDENCE           4.92
REVIEW                   2.81
Name: proportion, dtype: float64

Average reliability score:
92.35813

Reliability score statistics:
count    3351.000000
mean       92.358131
std        15.833529
min         0.325203
25%        95.826401
50%        96.209625
75%        97.199238
max        99.999786
Name: reliability_score, dtype: float64

In [59]:
# ============================================================
# FINAL CROSS-TYPE ROBUSTNESS SUMMARY
# ============================================================

print("=" * 70)
print("CROSS-TYPE ROBUSTNESS & RELIABILITY SUMMARY")
print("=" * 70)

print("\n1. Unseen Fake-Follower Detection")
print("-" * 70)
print(f"Accuracy          : 97.31%")
print(f"Precision         : 100.00%")
print(f"Recall            : 97.31%")
print(f"F1-Score          : 98.64%")
print(f"Correct           : 3261 / 3351")
print(f"Missed            : 90 / 3351")

print("\n2. Reliability Analysis")
print("-" * 70)
print(f"Average Confidence: 93.14%")
print(f"Correct Confidence: 94.15%")
print(f"Error Confidence  : 56.48%")

print("\n3. Confidence-Based Flagging")
print("-" * 70)
print(f"High Confidence   : 3120 (93.11%)")
print(f"Review            : 102  (3.04%)")
print(f"Low Confidence    : 129  (3.85%)")

print("\n4. High-Confidence Group")
print("-" * 70)
print(f"Empirical Accuracy: 99.20%")

print("\nConclusion:")
print("The behavioral neural network demonstrates strong")
print("generalization to an unseen bot type and provides")
print("a confidence-based mechanism for reliability-aware")
print("flagging and human review.")

======================================================================
CROSS-TYPE ROBUSTNESS & RELIABILITY SUMMARY
======================================================================

1. Unseen Fake-Follower Detection
----------------------------------------------------------------------
Accuracy          : 97.31%
Precision         : 100.00%
Recall            : 97.31%
F1-Score          : 98.64%
Correct           : 3261 / 3351
Missed            : 90 / 3351

2. Reliability Analysis
----------------------------------------------------------------------
Average Confidence: 93.14%
Correct Confidence: 94.15%
Error Confidence  : 56.48%

3. Confidence-Based Flagging
----------------------------------------------------------------------
High Confidence   : 3120 (93.11%)
Review            : 102  (3.04%)
Low Confidence    : 129  (3.85%)

4. High-Confidence Group
----------------------------------------------------------------------
Empirical Accuracy: 99.20%

Conclusion:
The behavioral neural network demonstrates strong
generalization to an unseen bot type and provides
a confidence-based mechanism for reliability-aware
flagging and human review.

In [60]:
# ============================================================
# CHECK BEHAVIORAL ACCOUNT IDs FOR FUSION
# ============================================================

print("Behavioral dataframe shape:", behavior_df.shape)

print("\nBehavioral columns:")
print(behavior_df.columns.tolist())

print("\nFirst 5 behavioral IDs:")
print(behavior_df["id"].head())

print("\nBehavioral ID datatype:")
print(behavior_df["id"].dtype)

print("\nTest set size:")
print(len(X_test))

print("\nTest label size:")
print(len(y_test))

print("\nTest probability size:")
print(len(test_probs_clean))

Behavioral dataframe shape: (14368, 20)

Behavioral columns:
['id', 'account_type', 'label', 'statuses_count', 'followers_count', 'friends_count', 'favourites_count', 'listed_count', 'created_at', 'updated', 'account_age_days', 'statuses_per_day', 'followers_friends_ratio', 'friends_followers_ratio', 'favorites_per_status', 'log_statuses_count', 'log_followers_count', 'log_friends_count', 'log_favourites_count', 'log_listed_count']

First 5 behavioral IDs:
0    1502026416
1    2492782375
2     293212315
3     191839658
4    3020965143
Name: id, dtype: int64

Behavioral ID datatype:
int64

Test set size:
4311

Test label size:
4311

Test probability size:
4311

In [61]:
# Create behavioral test predictions with their original account IDs

behavior_test_results = behavior_df.loc[X_test.index, ["id", "label", "account_type"]].copy()

behavior_test_results["behavior_probability"] = test_probs_clean
behavior_test_results["behavior_prediction"] = test_pred_clean

print("Behavioral test predictions:")
display(behavior_test_results.head())

print("\nShape:", behavior_test_results.shape)
print("\nID datatype:", behavior_test_results["id"].dtype)

Behavioral test predictions:

,id,label,account_type,behavior_probability,behavior_prediction
11094,55639200,1,fake_followers,0.999894,1
1633,2225775155,0,genuine_accounts,0.003907,0
5787,88105950,1,traditional_spambots_1,0.999696,1
5369,62395679,1,traditional_spambots_1,0.999240,1
7096,2381097096,1,social_spambots_2,0.999692,1

Shape: (4311, 5)

ID datatype: int64

In [62]:
import os

print("Current working directory:")
print(os.getcwd())

print("\nFiles in current folder:")
for file in os.listdir():
    print(file)

Current working directory:
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\notebooks

Files in current folder:
01_dataset_cleaning.ipynb
02_feature_engineering.ipynb
03_baseline_model.ipynb
04_behavioral_neural_network.ipynb
05_textual_model.ipynb
06_text_features.ipynb
07_fusion_robustness.ipynb
09_explainability.ipynb

In [63]:
import os

project_path = os.path.dirname(os.getcwd())

for root, dirs, files in os.walk(project_path):
    for file in files:
        if "text" in file.lower() or "prediction" in file.lower():
            print(os.path.join(root, file))

c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\debugpy\_vendored\pydevd\pydevd_attach_to_process\winappdbg\textio.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\debugpy\_vendored\pydevd\pydevd_attach_to_process\winappdbg\win32\context_amd64.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\debugpy\_vendored\pydevd\pydevd_attach_to_process\winappdbg\win32\context_i386.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\debugpy\_vendored\pydevd\pydevd_attach_to_process\winappdbg\win32\__pycache__\context_amd64.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\debugpy\_vendored\pydevd\pydevd_attach_to_process\winappdbg\win32\__pycache__\context_i386.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\debugpy\_vendored\pydevd\pydevd_attach_to_process\winappdbg\__pycache__\textio.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\proto_text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\source_context_pb2.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\text_encoding.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\text_format.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\__pycache__\proto_text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\__pycache__\source_context_pb2.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\__pycache__\text_encoding.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\__pycache__\text_format.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\lib\latextools.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\lib\__pycache__\latextools.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\utils\contexts.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\utils\syspathcontext.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\utils\text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\utils\__pycache__\contexts.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\utils\__pycache__\syspathcontext.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\utils\__pycache__\text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\inference\context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\inference\__pycache__\context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\django-stubs\django-stubs\contrib\auth\context_processors.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\django-stubs\django-stubs\contrib\messages\context_processors.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\django-stubs\django-stubs\contrib\postgres\fields\citext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\django-stubs\django-stubs\db\models\functions\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\django-stubs\django-stubs\template\context.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\django-stubs\django-stubs\template\context_processors.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\django-stubs\django-stubs\utils\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\contextlib.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\contextvars.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\gettext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\textwrap.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\_contextvars.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\curses\textpad.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\distutils\text_file.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\email\mime\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\msilib\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\multiprocessing\context.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\tkinter\scrolledtext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\aiofiles\aiofiles\threadpool\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\antlr4-python3-runtime\antlr4\ParserRuleContext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\antlr4-python3-runtime\antlr4\PredictionContext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\antlr4-python3-runtime\antlr4\RuleContext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\antlr4-python3-runtime\antlr4\atn\PredictionMode.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\antlr4-python3-runtime\antlr4\atn\SemanticContext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\aws-xray-sdk\aws_xray_sdk\core\async_context.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\aws-xray-sdk\aws_xray_sdk\core\context.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\dateparser\dateparser\custom_language_detection\fasttext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\dateparser\dateparser\search\text_detection.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\docker\docker\context\context.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\fpdf2\fpdf\text_region.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\google-cloud-ndb\google\cloud\ndb\context.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\networkx\networkx\algorithms\link_prediction.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\networkx\networkx\readwrite\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\openpyxl\openpyxl\cell\rich_text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\openpyxl\openpyxl\cell\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\openpyxl\openpyxl\chart\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\openpyxl\openpyxl\drawing\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\opentracing\opentracing\mocktracer\context.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\opentracing\opentracing\mocktracer\text_propagator.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\opentracing\opentracing\scope_managers\contextvars.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\protobuf\google\protobuf\proto_text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\protobuf\google\protobuf\source_context_pb2.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\protobuf\google\protobuf\text_encoding.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\protobuf\google\protobuf\text_format.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\pywin32\win32com\axdebug\contexts.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\pywin32\win32comext\axdebug\contexts.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\reportlab\reportlab\graphics\charts\textlabels.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\reportlab\reportlab\lib\randomtext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\reportlab\reportlab\lib\textsplit.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\reportlab\reportlab\pdfgen\textobject.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\seaborn\seaborn\_marks\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\six\six\moves\email_mime_text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\joblib\externals\loky\backend\context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\joblib\externals\loky\backend\__pycache__\context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\preprocessing\text_vectorization.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\preprocessing\text_vectorization_test.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\preprocessing\__pycache__\text_vectorization.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\preprocessing\__pycache__\text_vectorization_test.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\legacy\preprocessing\text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\legacy\preprocessing\__pycache__\text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\utils\text_dataset_utils.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\utils\text_dataset_utils_test.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\utils\__pycache__\text_dataset_utils.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\utils\__pycache__\text_dataset_utils_test.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\llvmlite\binding\context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\llvmlite\binding\__pycache__\context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\llvmlite\ir\context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\llvmlite\ir\__pycache__\context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\markdown_it\rules_core\text_join.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\markdown_it\rules_core\__pycache__\text_join.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\markdown_it\rules_inline\text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\markdown_it\rules_inline\__pycache__\text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\core\withcontexts.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\core\runtime\context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\core\runtime\__pycache__\context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\core\typing\context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\core\typing\__pycache__\context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\core\__pycache__\withcontexts.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\cuda\tests\cudadrv\test_context_stack.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\cuda\tests\cudadrv\test_cuda_auto_context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\cuda\tests\cudadrv\__pycache__\test_context_stack.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\cuda\tests\cudadrv\__pycache__\test_cuda_auto_context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pandas\tests\io\parser\test_textreader.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pandas\tests\io\parser\__pycache__\test_textreader.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pandas\_testing\contexts.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pandas\_testing\__pycache__\contexts.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pip\_internal\cli\command_context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pip\_internal\cli\__pycache__\command_context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pip\_internal\utils\_jaraco_text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pip\_internal\utils\__pycache__\_jaraco_text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pip\_vendor\rich\text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pip\_vendor\rich\__pycache__\text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\prompt_toolkit\output\plain_text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\prompt_toolkit\output\__pycache__\plain_text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pygments\lexers\text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pygments\lexers\textedit.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pygments\lexers\textfmts.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pygments\lexers\__pycache__\text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pygments\lexers\__pycache__\textedit.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pygments\lexers\__pycache__\textfmts.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\rich\text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\rich\__pycache__\text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\setuptools\_distutils\text_file.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\setuptools\_distutils\__pycache__\text_file.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\setuptools\_vendor\importlib_metadata\_text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\setuptools\_vendor\importlib_metadata\__pycache__\_text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\shap\maskers\_text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\shap\maskers\__pycache__\_text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\shap\models\_text_generation.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\shap\models\__pycache__\_text_generation.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\shap\plots\_text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\shap\plots\__pycache__\_text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\callback\_callback_context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\callback\tests\test_callback_context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\callback\tests\__pycache__\test_callback_context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\callback\__pycache__\_callback_context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\feature_extraction\text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\feature_extraction\tests\test_text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\feature_extraction\tests\__pycache__\test_text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\feature_extraction\__pycache__\text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\tensorflow\include\external\com_github_cncf_xds\xds\core\v3\context_params.upb.h
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\tensorflow\include\external\com_github_cncf_xds\xds\core\v3\context_params.upbdefs.h
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\tensorflow\include\external\com_github_cncf_xds\xds\core\v3\context_params.upb_minitable.h
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\tensorflow\include\external\com_github_grpc_grpc\include\grpc++\client_context.h
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\tensorflow\include\external\com_github_grpc_grpc\include\grpc++\server_context.h

In [64]:
import os

project_path = os.path.dirname(os.getcwd())

for root, dirs, files in os.walk(project_path):
    for file in files:
        if "text" in file.lower() or "prediction" in file.lower():
            print(os.path.join(root, file))

c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\debugpy\_vendored\pydevd\pydevd_attach_to_process\winappdbg\textio.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\debugpy\_vendored\pydevd\pydevd_attach_to_process\winappdbg\win32\context_amd64.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\debugpy\_vendored\pydevd\pydevd_attach_to_process\winappdbg\win32\context_i386.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\debugpy\_vendored\pydevd\pydevd_attach_to_process\winappdbg\win32\__pycache__\context_amd64.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\debugpy\_vendored\pydevd\pydevd_attach_to_process\winappdbg\win32\__pycache__\context_i386.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\debugpy\_vendored\pydevd\pydevd_attach_to_process\winappdbg\__pycache__\textio.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\proto_text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\source_context_pb2.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\text_encoding.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\text_format.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\__pycache__\proto_text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\__pycache__\source_context_pb2.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\__pycache__\text_encoding.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\google\protobuf\__pycache__\text_format.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\lib\latextools.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\lib\__pycache__\latextools.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\utils\contexts.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\utils\syspathcontext.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\utils\text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\utils\__pycache__\contexts.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\utils\__pycache__\syspathcontext.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\IPython\utils\__pycache__\text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\inference\context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\inference\__pycache__\context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\django-stubs\django-stubs\contrib\auth\context_processors.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\django-stubs\django-stubs\contrib\messages\context_processors.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\django-stubs\django-stubs\contrib\postgres\fields\citext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\django-stubs\django-stubs\db\models\functions\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\django-stubs\django-stubs\template\context.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\django-stubs\django-stubs\template\context_processors.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\django-stubs\django-stubs\utils\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\contextlib.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\contextvars.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\gettext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\textwrap.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\_contextvars.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\curses\textpad.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\distutils\text_file.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\email\mime\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\msilib\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\multiprocessing\context.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stdlib\tkinter\scrolledtext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\aiofiles\aiofiles\threadpool\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\antlr4-python3-runtime\antlr4\ParserRuleContext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\antlr4-python3-runtime\antlr4\PredictionContext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\antlr4-python3-runtime\antlr4\RuleContext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\antlr4-python3-runtime\antlr4\atn\PredictionMode.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\antlr4-python3-runtime\antlr4\atn\SemanticContext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\aws-xray-sdk\aws_xray_sdk\core\async_context.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\aws-xray-sdk\aws_xray_sdk\core\context.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\dateparser\dateparser\custom_language_detection\fasttext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\dateparser\dateparser\search\text_detection.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\docker\docker\context\context.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\fpdf2\fpdf\text_region.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\google-cloud-ndb\google\cloud\ndb\context.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\networkx\networkx\algorithms\link_prediction.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\networkx\networkx\readwrite\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\openpyxl\openpyxl\cell\rich_text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\openpyxl\openpyxl\cell\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\openpyxl\openpyxl\chart\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\openpyxl\openpyxl\drawing\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\opentracing\opentracing\mocktracer\context.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\opentracing\opentracing\mocktracer\text_propagator.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\opentracing\opentracing\scope_managers\contextvars.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\protobuf\google\protobuf\proto_text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\protobuf\google\protobuf\source_context_pb2.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\protobuf\google\protobuf\text_encoding.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\protobuf\google\protobuf\text_format.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\pywin32\win32com\axdebug\contexts.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\pywin32\win32comext\axdebug\contexts.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\reportlab\reportlab\graphics\charts\textlabels.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\reportlab\reportlab\lib\randomtext.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\reportlab\reportlab\lib\textsplit.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\reportlab\reportlab\pdfgen\textobject.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\seaborn\seaborn\_marks\text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\jedi\third_party\typeshed\stubs\six\six\moves\email_mime_text.pyi
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\joblib\externals\loky\backend\context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\joblib\externals\loky\backend\__pycache__\context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\preprocessing\text_vectorization.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\preprocessing\text_vectorization_test.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\preprocessing\__pycache__\text_vectorization.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\preprocessing\__pycache__\text_vectorization_test.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\legacy\preprocessing\text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\legacy\preprocessing\__pycache__\text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\utils\text_dataset_utils.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\utils\text_dataset_utils_test.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\utils\__pycache__\text_dataset_utils.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\utils\__pycache__\text_dataset_utils_test.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\llvmlite\binding\context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\llvmlite\binding\__pycache__\context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\llvmlite\ir\context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\llvmlite\ir\__pycache__\context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\markdown_it\rules_core\text_join.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\markdown_it\rules_core\__pycache__\text_join.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\markdown_it\rules_inline\text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\markdown_it\rules_inline\__pycache__\text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\core\withcontexts.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\core\runtime\context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\core\runtime\__pycache__\context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\core\typing\context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\core\typing\__pycache__\context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\core\__pycache__\withcontexts.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\cuda\tests\cudadrv\test_context_stack.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\cuda\tests\cudadrv\test_cuda_auto_context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\cuda\tests\cudadrv\__pycache__\test_context_stack.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\numba\cuda\tests\cudadrv\__pycache__\test_cuda_auto_context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pandas\tests\io\parser\test_textreader.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pandas\tests\io\parser\__pycache__\test_textreader.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pandas\_testing\contexts.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pandas\_testing\__pycache__\contexts.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pip\_internal\cli\command_context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pip\_internal\cli\__pycache__\command_context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pip\_internal\utils\_jaraco_text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pip\_internal\utils\__pycache__\_jaraco_text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pip\_vendor\rich\text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pip\_vendor\rich\__pycache__\text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\prompt_toolkit\output\plain_text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\prompt_toolkit\output\__pycache__\plain_text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pygments\lexers\text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pygments\lexers\textedit.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pygments\lexers\textfmts.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pygments\lexers\__pycache__\text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pygments\lexers\__pycache__\textedit.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\pygments\lexers\__pycache__\textfmts.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\rich\text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\rich\__pycache__\text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\setuptools\_distutils\text_file.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\setuptools\_distutils\__pycache__\text_file.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\setuptools\_vendor\importlib_metadata\_text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\setuptools\_vendor\importlib_metadata\__pycache__\_text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\shap\maskers\_text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\shap\maskers\__pycache__\_text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\shap\models\_text_generation.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\shap\models\__pycache__\_text_generation.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\shap\plots\_text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\shap\plots\__pycache__\_text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\callback\_callback_context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\callback\tests\test_callback_context.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\callback\tests\__pycache__\test_callback_context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\callback\__pycache__\_callback_context.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\feature_extraction\text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\feature_extraction\tests\test_text.py
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\feature_extraction\tests\__pycache__\test_text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\sklearn\feature_extraction\__pycache__\text.cpython-312.pyc
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\tensorflow\include\external\com_github_cncf_xds\xds\core\v3\context_params.upb.h
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\tensorflow\include\external\com_github_cncf_xds\xds\core\v3\context_params.upbdefs.h
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\tensorflow\include\external\com_github_cncf_xds\xds\core\v3\context_params.upb_minitable.h
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\tensorflow\include\external\com_github_grpc_grpc\include\grpc++\client_context.h
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\tensorflow\include\external\com_github_grpc_grpc\include\grpc++\server_context.h

In [65]:
text_pred = pd.read_csv(
    os.path.join(project_path, "data", "text_model_predictions.csv")
)

print(text_pred.shape)
print(text_pred.columns.tolist())
print(text_pred.head())

(10197, 5)
['user_id', 'label', 'account_type', 'text_model_probability', 'text_model_prediction']
    user_id  label          account_type  text_model_probability  \
0  678033.0      0  genuine_accounts.csv                0.031738
1  722623.0      0  genuine_accounts.csv                0.022437
2  755116.0      0  genuine_accounts.csv                0.053431
3  755746.0      0  genuine_accounts.csv                0.038380
4  785080.0      0  genuine_accounts.csv                0.032506

   text_model_prediction
0                      0
1                      0
2                      0
3                      0
4                      0

In [66]:
# Copy behavioral test results
behavior_test = behavior_test_results.copy()

# Convert both IDs to the same numeric type
behavior_test["id"] = pd.to_numeric(
    behavior_test["id"], errors="coerce"
).astype("Int64")

text_pred["user_id"] = pd.to_numeric(
    text_pred["user_id"], errors="coerce"
).astype("Int64")

# Rename user_id → id so we can merge
text_pred_merge = text_pred.rename(columns={"user_id": "id"})

# Merge behavioral and textual predictions
fusion_check = behavior_test.merge(
    text_pred_merge,
    on="id",
    how="inner",
    suffixes=("_behavior", "_text")
)

print("Behavioral test accounts:", len(behavior_test))
print("Text prediction accounts:", len(text_pred_merge))
print("Matched accounts:", len(fusion_check))

print("\nColumns:")
print(fusion_check.columns.tolist())

print("\nFirst 5 matched accounts:")
display(fusion_check.head())

Behavioral test accounts: 4311
Text prediction accounts: 10197
Matched accounts: 3069

Columns:
['id', 'label_behavior', 'account_type_behavior', 'behavior_probability', 'behavior_prediction', 'label_text', 'account_type_text', 'text_model_probability', 'text_model_prediction']

First 5 matched accounts:

,id,label_behavior,account_type_behavior,behavior_probability,behavior_prediction,label_text,account_type_text,text_model_probability,text_model_prediction
0,55639200,1,fake_followers,0.999894,1,1,fake_followers.csv,0.970971,1
1,2225775155,0,genuine_accounts,0.003907,0,0,genuine_accounts.csv,0.021376,0
2,88105950,1,traditional_spambots_1,0.999696,1,1,traditional_spambots_1.csv,0.896696,1
3,62395679,1,traditional_spambots_1,0.999240,1,1,traditional_spambots_1.csv,0.996300,1
4,2381097096,1,social_spambots_2,0.999692,1,1,social_spambots_2.csv,0.969256,1

In [67]:
# Check whether behavioral and text labels match
label_match = (
    fusion_check["label_behavior"] ==
    fusion_check["label_text"]
)

print("Total matched accounts:", len(fusion_check))
print("Labels matching:", label_match.sum())
print("Labels NOT matching:", (~label_match).sum())

Total matched accounts: 3069
Labels matching: 3069
Labels NOT matching: 0

In [68]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_true = fusion_check["label_behavior"].values

behavior_prob = fusion_check["behavior_probability"].values
text_prob = fusion_check["text_model_probability"].values

weights = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

fusion_results = []

for alpha in weights:
    final_prob = (
        alpha * behavior_prob +
        (1 - alpha) * text_prob
    )

    final_pred = (final_prob >= 0.5).astype(int)

    fusion_results.append({
        "Behavior Weight": alpha,
        "Text Weight": 1 - alpha,
        "Accuracy": accuracy_score(y_true, final_pred),
        "Precision": precision_score(y_true, final_pred),
        "Recall": recall_score(y_true, final_pred),
        "F1": f1_score(y_true, final_pred)
    })

fusion_results_df = pd.DataFrame(fusion_results)

display(fusion_results_df)

    Behavior Weight  Text Weight  Accuracy  Precision    Recall        F1
0               0.0          1.0  0.984686   0.997786  0.985064  0.991384
1               0.1          0.9  0.986641   0.997791  0.987250  0.992492
2               0.2          0.8  0.988596   0.998162  0.989071  0.993596
3               0.3          0.7  0.989899   0.998164  0.990528  0.994332
4               0.4          0.6  0.992832   0.998535  0.993443  0.995982
5               0.5          0.5  0.992180   0.998169  0.993078  0.995617
6               0.6          0.4  0.990877   0.998166  0.991621  0.994883
7               0.7          0.3  0.990551   0.998166  0.991257  0.994699
8               0.8          0.2  0.989899   0.998164  0.990528  0.994332
9               0.9          0.1  0.989247   0.998163  0.989800  0.993964
10              1.0          0.0  0.988270   0.998161  0.988707  0.993411

In [69]:
# Check the available datasets and their sizes

print("Behavioral dataset:", behavior_df.shape)
print("Text prediction dataset:", text_pred.shape)
print("Matched test dataset:", fusion_check.shape)

print("\nBehavioral columns:")
print(behavior_df.columns.tolist())

print("\nText prediction columns:")
print(text_pred.columns.tolist())

Behavioral dataset: (14368, 20)
Text prediction dataset: (10197, 5)
Matched test dataset: (3069, 9)

Behavioral columns:
['id', 'account_type', 'label', 'statuses_count', 'followers_count', 'friends_count', 'favourites_count', 'listed_count', 'created_at', 'updated', 'account_age_days', 'statuses_per_day', 'followers_friends_ratio', 'friends_followers_ratio', 'favorites_per_status', 'log_statuses_count', 'log_followers_count', 'log_friends_count', 'log_favourites_count', 'log_listed_count']

Text prediction columns:
['user_id', 'label', 'account_type', 'text_model_probability', 'text_model_prediction']

In [70]:
# Prepare behavioral data for matching with the textual branch

behavior_common = behavior_df[
    behavior_df["id"].isin(
        pd.to_numeric(text_pred["user_id"], errors="coerce")
    )
].copy()

print("Common accounts:", len(behavior_common))
print("Expected:", len(text_pred))

print("\nAccount types:")
print(behavior_common["account_type"].value_counts())

Common accounts: 10197
Expected: 10197

Account types:
account_type
social_spambots_2         3457
fake_followers            3202
genuine_accounts          1083
traditional_spambots_1    1000
social_spambots_1          991
social_spambots_3          464
Name: count, dtype: int64

In [71]:
from sklearn.model_selection import train_test_split

# Use the common 10,197 accounts
common_ids = behavior_common["id"].values
common_labels = behavior_common["label"].values

# First: 70% train, 30% temporary
train_ids, temp_ids, train_labels, temp_labels = train_test_split(
    common_ids,
    common_labels,
    test_size=0.30,
    random_state=42,
    stratify=common_labels
)

# Split the remaining 30% into 15% validation and 15% test
val_ids, test_ids, val_labels, test_labels = train_test_split(
    temp_ids,
    temp_labels,
    test_size=0.50,
    random_state=42,
    stratify=temp_labels
)

print("Train accounts:", len(train_ids))
print("Validation accounts:", len(val_ids))
print("Test accounts:", len(test_ids))

print("\nTotal:", len(train_ids) + len(val_ids) + len(test_ids))

Train accounts: 7137
Validation accounts: 1530
Test accounts: 1530

Total: 10197

In [72]:
# Create behavioral train/validation/test datasets
# using the SAME account IDs as our common split

behavior_common = behavior_common.copy()

# Make sure IDs have the same integer type
behavior_common["id"] = pd.to_numeric(
    behavior_common["id"], errors="coerce"
).astype("Int64")

train_ids = pd.Series(train_ids).astype("Int64")
val_ids = pd.Series(val_ids).astype("Int64")
test_ids = pd.Series(test_ids).astype("Int64")

# Select the behavioral rows for each split
behavior_train = behavior_common[
    behavior_common["id"].isin(train_ids)
].copy()

behavior_val = behavior_common[
    behavior_common["id"].isin(val_ids)
].copy()

behavior_test_common = behavior_common[
    behavior_common["id"].isin(test_ids)
].copy()

print("Behavioral train:", behavior_train.shape)
print("Behavioral validation:", behavior_val.shape)
print("Behavioral test:", behavior_test_common.shape)

print("\nLabels:")
print("Train:")
print(behavior_train["label"].value_counts())

print("\nValidation:")
print(behavior_val["label"].value_counts())

print("\nTest:")
print(behavior_test_common["label"].value_counts())

Behavioral train: (7137, 20)
Behavioral validation: (1530, 20)
Behavioral test: (1530, 20)

Labels:
Train:
label
1    6379
0     758
Name: count, dtype: int64

Validation:
label
1    1368
0     162
Name: count, dtype: int64

Test:
label
1    1367
0     163
Name: count, dtype: int64

In [73]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# Select the 15 behavioral features
X_train_behavior = behavior_train[behavior_features].copy()
X_val_behavior = behavior_val[behavior_features].copy()
X_test_behavior = behavior_test_common[behavior_features].copy()

y_train_behavior = behavior_train["label"].values
y_val_behavior = behavior_val["label"].values
y_test_behavior = behavior_test_common["label"].values

# Impute missing values — fit ONLY on training data
behavior_imputer = SimpleImputer(strategy="median")

X_train_behavior_imp = behavior_imputer.fit_transform(X_train_behavior)
X_val_behavior_imp = behavior_imputer.transform(X_val_behavior)
X_test_behavior_imp = behavior_imputer.transform(X_test_behavior)

# Scale features — fit ONLY on training data
behavior_scaler = StandardScaler()

X_train_behavior_scaled = behavior_scaler.fit_transform(
    X_train_behavior_imp
)

X_val_behavior_scaled = behavior_scaler.transform(
    X_val_behavior_imp
)

X_test_behavior_scaled = behavior_scaler.transform(
    X_test_behavior_imp
)

print("Train:", X_train_behavior_scaled.shape)
print("Validation:", X_val_behavior_scaled.shape)
print("Test:", X_test_behavior_scaled.shape)

Train: (7137, 15)
Validation: (1530, 15)
Test: (1530, 15)

In [74]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Build behavioral neural network
behavior_nn = Sequential([
    Dense(128, activation="relu", input_shape=(15,)),
    BatchNormalization(),
    Dropout(0.25),

    Dense(64, activation="relu"),
    BatchNormalization(),
    Dropout(0.20),

    Dense(32, activation="relu"),
    Dropout(0.10),

    Dense(1, activation="sigmoid")
])

behavior_nn.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Callbacks
early_stopping_behavior = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

reduce_lr_behavior = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=2,
    min_lr=1e-6
)

# Train using our EXPLICIT validation set
history_behavior = behavior_nn.fit(
    X_train_behavior_scaled,
    y_train_behavior,
    validation_data=(
        X_val_behavior_scaled,
        y_val_behavior
    ),
    epochs=50,
    batch_size=32,
    callbacks=[
        early_stopping_behavior,
        reduce_lr_behavior
    ],
    verbose=1
)

Epoch 1/50

c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

224/224 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.9742 - loss: 0.0919 - val_accuracy: 0.9902 - val_loss: 0.0454 - learning_rate: 0.0010
Epoch 2/50
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9854 - loss: 0.0486 - val_accuracy: 0.9915 - val_loss: 0.0289 - learning_rate: 0.0010
Epoch 3/50
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9861 - loss: 0.0473 - val_accuracy: 0.9928 - val_loss: 0.0220 - learning_rate: 0.0010
Epoch 4/50
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9880 - loss: 0.0447 - val_accuracy: 0.9928 - val_loss: 0.0201 - learning_rate: 0.0010
Epoch 5/50
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9877 - loss: 0.0437 - val_accuracy: 0.9928 - val_loss: 0.0204 - learning_rate: 0.0010
Epoch 6/50
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9881 - loss: 0.0377 - val_accuracy: 0.9935 - val_loss: 0.0201 - learning_rate: 0.0010
Epoch 7/50
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9895 - loss: 0.0365 - val_accuracy: 0.9935 - val_loss: 0.0195 - learning_rate: 5.0000e-04
Epoch 8/50
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9884 - loss: 0.0358 - val_accuracy: 0.9935 - val_loss: 0.0195 - learning_rate: 5.0000e-04
Epoch 9/50
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9895 - loss: 0.0330 - val_accuracy: 0.9941 - val_loss: 0.0187 - learning_rate: 5.0000e-04
Epoch 10/50
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9882 - loss: 0.0377 - val_accuracy: 0.9935 - val_loss: 0.0180 - learning_rate: 5.0000e-04
Epoch 11/50
224/224 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9895 - loss: 0.0336 - val_accuracy: 0.9915 - val_loss: 0.0246 - learning_rate: 5.0000e-04
Epoch 12/50
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9891 - loss: 0.0353 - val_accuracy: 0.9922 - val_loss: 0.0213 - learning_rate: 5.0000e-04
Epoch 13/50
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9902 - loss: 0.0310 - val_accuracy: 0.9922 - val_loss: 0.0210 - learning_rate: 2.5000e-04
Epoch 14/50
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9888 - loss: 0.0344 - val_accuracy: 0.9928 - val_loss: 0.0206 - learning_rate: 2.5000e-04
Epoch 15/50
224/224 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.9905 - loss: 0.0329 - val_accuracy: 0.9922 - val_loss: 0.0211 - learning_rate: 1.2500e-04

In [75]:
# Generate behavioral model probabilities
# for the common validation and test accounts

behavior_val_prob = behavior_nn.predict(
    X_val_behavior_scaled,
    verbose=0
).ravel()

behavior_test_prob = behavior_nn.predict(
    X_test_behavior_scaled,
    verbose=0
).ravel()

print("Validation probabilities:", behavior_val_prob.shape)
print("Test probabilities:", behavior_test_prob.shape)

print("\nSample validation probabilities:")
print(behavior_val_prob[:5])

print("\nSample test probabilities:")
print(behavior_test_prob[:5])

Validation probabilities: (1530,)
Test probabilities: (1530,)

Sample validation probabilities:
[0.55543375 0.08061536 0.11129086 0.07283694 0.01617059]

Sample test probabilities:
[0.08903718 0.32068628 0.01793978 0.05334122 0.09411545]

In [76]:
# Create behavioral prediction tables with account IDs

behavior_val_results = behavior_val[["id", "label", "account_type"]].copy()
behavior_val_results["behavior_probability"] = behavior_val_prob
behavior_val_results["behavior_prediction"] = (
    behavior_val_prob >= 0.5
).astype(int)

behavior_test_common_results = behavior_test_common[
    ["id", "label", "account_type"]
].copy()
behavior_test_common_results["behavior_probability"] = behavior_test_prob
behavior_test_common_results["behavior_prediction"] = (
    behavior_test_prob >= 0.5
).astype(int)

print("Behavior validation results:", behavior_val_results.shape)
print("Behavior test results:", behavior_test_common_results.shape)

display(behavior_val_results.head())
display(behavior_test_common_results.head())

Behavior validation results: (1530, 5)
Behavior test results: (1530, 5)

,id,label,account_type,behavior_probability,behavior_prediction
12,21959183,0,genuine_accounts,0.555434,1
24,585912212,0,genuine_accounts,0.080615,0
33,222290847,0,genuine_accounts,0.111291,0
42,208664282,0,genuine_accounts,0.072837,0
110,581233948,0,genuine_accounts,0.016171,0

,id,label,account_type,behavior_probability,behavior_prediction
5,2157382005,0,genuine_accounts,0.089037,0
66,177906959,0,genuine_accounts,0.320686,0
67,2248762537,0,genuine_accounts,0.017940,0
90,1727495887,0,genuine_accounts,0.053341,0
149,2152052819,0,genuine_accounts,0.094115,0

In [77]:
# Prepare text predictions for merging
text_pred_merge = text_pred.copy()

text_pred_merge["user_id"] = pd.to_numeric(
    text_pred_merge["user_id"],
    errors="coerce"
).astype("Int64")

text_pred_merge = text_pred_merge.rename(
    columns={"user_id": "id"}
)

# Make behavioral IDs compatible
behavior_val_results["id"] = pd.to_numeric(
    behavior_val_results["id"],
    errors="coerce"
).astype("Int64")

behavior_test_common_results["id"] = pd.to_numeric(
    behavior_test_common_results["id"],
    errors="coerce"
).astype("Int64")

# Merge validation predictions
fusion_val = behavior_val_results.merge(
    text_pred_merge[[
        "id",
        "text_model_probability",
        "text_model_prediction"
    ]],
    on="id",
    how="inner"
)

# Merge test predictions
fusion_test = behavior_test_common_results.merge(
    text_pred_merge[[
        "id",
        "text_model_probability",
        "text_model_prediction"
    ]],
    on="id",
    how="inner"
)

print("Fusion validation accounts:", len(fusion_val))
print("Fusion test accounts:", len(fusion_test))

print("\nValidation sample:")
display(fusion_val.head())

print("\nTest sample:")
display(fusion_test.head())

Fusion validation accounts: 1530
Fusion test accounts: 1530

Validation sample:

,id,label,account_type,behavior_probability,behavior_prediction,text_model_probability,text_model_prediction
0,21959183,0,genuine_accounts,0.555434,1,0.032166,0
1,585912212,0,genuine_accounts,0.080615,0,0.014430,0
2,222290847,0,genuine_accounts,0.111291,0,0.117556,0
3,208664282,0,genuine_accounts,0.072837,0,0.026263,0
4,581233948,0,genuine_accounts,0.016171,0,0.033210,0

Test sample:

,id,label,account_type,behavior_probability,behavior_prediction,text_model_probability,text_model_prediction
0,2157382005,0,genuine_accounts,0.089037,0,0.033657,0
1,177906959,0,genuine_accounts,0.320686,0,0.075028,0
2,2248762537,0,genuine_accounts,0.017940,0,0.045131,0
3,1727495887,0,genuine_accounts,0.053341,0,0.084882,0
4,2152052819,0,genuine_accounts,0.094115,0,0.100697,0

In [78]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Validation data
y_val = fusion_val["label"].values

behavior_val_prob = fusion_val["behavior_probability"].values
text_val_prob = fusion_val["text_model_probability"].values

# Test different behavioral weights
weights = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

validation_fusion_results = []

for alpha in weights:

    # Decision-level / late fusion
    final_prob = (
        alpha * behavior_val_prob +
        (1 - alpha) * text_val_prob
    )

    final_pred = (final_prob >= 0.5).astype(int)

    validation_fusion_results.append({
        "Behavior Weight": alpha,
        "Text Weight": 1 - alpha,
        "Accuracy": accuracy_score(y_val, final_pred),
        "Precision": precision_score(y_val, final_pred),
        "Recall": recall_score(y_val, final_pred),
        "F1": f1_score(y_val, final_pred)
    })

validation_fusion_df = pd.DataFrame(validation_fusion_results)

display(validation_fusion_df)

    Behavior Weight  Text Weight  Accuracy  Precision    Recall        F1
0               0.0          1.0  0.986275   1.000000  0.984649  0.992265
1               0.1          0.9  0.987582   1.000000  0.986111  0.993007
2               0.2          0.8  0.988889   1.000000  0.987573  0.993748
3               0.3          0.7  0.992810   1.000000  0.991959  0.995963
4               0.4          0.6  0.995425   1.000000  0.994883  0.997435
5               0.5          0.5  0.996078   0.999267  0.996345  0.997804
6               0.6          0.4  0.995425   0.998535  0.996345  0.997439
7               0.7          0.3  0.994771   0.998534  0.995614  0.997072
8               0.8          0.2  0.994118   0.998533  0.994883  0.996705
9               0.9          0.1  0.993464   0.997801  0.994883  0.996340
10              1.0          0.0  0.993464   0.997801  0.994883  0.996340

In [79]:
print("Text LOBO validation probabilities:", len(text_val_prob))
print("Expected:", len(lobo_test) if "lobo_test" in globals() else "check lobo validation")

Text LOBO validation probabilities: 1530
Expected: check lobo validation

In [80]:
# ==========================================
# LOBO BEHAVIOR VALIDATION PROBABILITIES
# ==========================================

behavior_lobo_val_prob = lobo_behavior_nn_v2.predict(
    X_lobo_val,
    verbose=0
).ravel()

behavior_lobo_val_pred = (
    behavior_lobo_val_prob >= 0.5
).astype(int)

print("Behavior LOBO validation probabilities:", len(behavior_lobo_val_prob))
print("Behavior LOBO validation labels:", len(y_lobo_val))

print("\nProbability range:")
print(
    behavior_lobo_val_prob.min(),
    "to",
    behavior_lobo_val_prob.max()
)

NameError: name 'lobo_behavior_nn_v2' is not defined

In [81]:
# Final fusion on the untouched test set
# Weight selected ONLY from validation

best_alpha = 0.5

y_test = fusion_test["label"].values

behavior_test_prob = fusion_test["behavior_probability"].values
text_test_prob = fusion_test["text_model_probability"].values

# 50% behavioral + 50% textual
final_test_prob = (
    best_alpha * behavior_test_prob +
    (1 - best_alpha) * text_test_prob
)

final_test_pred = (final_test_prob >= 0.5).astype(int)

# Store final predictions
fusion_test["final_probability"] = final_test_prob
fusion_test["final_prediction"] = final_test_pred

# Evaluate
final_accuracy = accuracy_score(y_test, final_test_pred)
final_precision = precision_score(y_test, final_test_pred)
final_recall = recall_score(y_test, final_test_pred)
final_f1 = f1_score(y_test, final_test_pred)

print("=== FINAL FUSION TEST RESULTS ===")
print("Behavior weight:", best_alpha)
print("Text weight:", 1 - best_alpha)
print("Accuracy:", final_accuracy)
print("Precision:", final_precision)
print("Recall:", final_recall)
print("F1:", final_f1)

=== FINAL FUSION TEST RESULTS ===
Behavior weight: 0.5
Text weight: 0.5
Accuracy: 0.996078431372549
Precision: 0.9985347985347985
Recall: 0.9970738844184345
F1: 0.9978038067349927

In [82]:
# Compare Behavior-only, Text-only, and 50:50 Fusion
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_test = fusion_test["label"].values

# Predictions from each approach
behavior_pred = (fusion_test["behavior_probability"].values >= 0.5).astype(int)
text_pred_test = (fusion_test["text_model_probability"].values >= 0.5).astype(int)
fusion_pred = fusion_test["final_prediction"].values

comparison_results = []

models = {
    "Behavior Only": behavior_pred,
    "Text Only": text_pred_test,
    "50:50 Fusion": fusion_pred
}

for model_name, predictions in models.items():
    comparison_results.append({
        "Model": model_name,
        "Accuracy": accuracy_score(y_test, predictions),
        "Precision": precision_score(y_test, predictions),
        "Recall": recall_score(y_test, predictions),
        "F1": f1_score(y_test, predictions)
    })

comparison_df = pd.DataFrame(comparison_results)

display(comparison_df)

           Model  Accuracy  Precision    Recall        F1
0  Behavior Only  0.991503   0.997063  0.993416  0.995236
1      Text Only  0.986275   0.996313  0.988296  0.992288
2   50:50 Fusion  0.996078   0.998535  0.997074  0.997804

In [ ]:
# Check the account types in our common dataset

print("Account type distribution:")
display(
    behavior_common["account_type"]
    .value_counts()
    .rename_axis("account_type")
    .reset_index(name="count")
)

Account type distribution:

             account_type  count
0       social_spambots_2   3457
1          fake_followers   3202
2        genuine_accounts   1083
3  traditional_spambots_1   1000
4       social_spambots_1    991
5       social_spambots_3    464

In [83]:
# Leave-One-Bot-Type-Out split
# Fake Followers will be completely unseen during training

unseen_type = "fake_followers"

# Training data: everything except Fake Followers
lobo_train = behavior_common[
    behavior_common["account_type"] != unseen_type
].copy()

# Test data: only Fake Followers + genuine accounts
lobo_test = behavior_common[
    behavior_common["account_type"].isin([unseen_type, "genuine_accounts"])
].copy()

print("=== Leave-One-Bot-Type-Out: Fake Followers ===")
print("Training accounts:", len(lobo_train))
print("Test accounts:", len(lobo_test))

print("\nTraining distribution:")
display(
    lobo_train["account_type"]
    .value_counts()
    .rename_axis("account_type")
    .reset_index(name="count")
)

print("\nTest distribution:")
display(
    lobo_test["account_type"]
    .value_counts()
    .rename_axis("account_type")
    .reset_index(name="count")
)

=== Leave-One-Bot-Type-Out: Fake Followers ===
Training accounts: 6995
Test accounts: 4285

Training distribution:

             account_type  count
0       social_spambots_2   3457
1        genuine_accounts   1083
2  traditional_spambots_1   1000
3       social_spambots_1    991
4       social_spambots_3    464

Test distribution:

       account_type  count
0    fake_followers   3202
1  genuine_accounts   1083

In [84]:
# Prepare behavioral features for the unseen Fake Followers experiment

X_lobo_train = lobo_train[behavior_features].copy()
X_lobo_test = lobo_test[behavior_features].copy()

y_lobo_train = lobo_train["label"].values
y_lobo_test = lobo_test["label"].values

# Fit preprocessing ONLY on the training data
lobo_imputer = SimpleImputer(strategy="median")

X_lobo_train_imp = lobo_imputer.fit_transform(X_lobo_train)
X_lobo_test_imp = lobo_imputer.transform(X_lobo_test)

# Fit scaler ONLY on training data
lobo_scaler = StandardScaler()

X_lobo_train_scaled = lobo_scaler.fit_transform(X_lobo_train_imp)
X_lobo_test_scaled = lobo_scaler.transform(X_lobo_test_imp)

print("Training shape:", X_lobo_train_scaled.shape)
print("Test shape:", X_lobo_test_scaled.shape)

print("\nTraining labels:")
print(pd.Series(y_lobo_train).value_counts().sort_index())

print("\nTest labels:")
print(pd.Series(y_lobo_test).value_counts().sort_index())

Training shape: (6995, 15)
Test shape: (4285, 15)

Training labels:
0    1083
1    5912
Name: count, dtype: int64

Test labels:
0    1083
1    3202
Name: count, dtype: int64

In [85]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Fresh behavioral model for Leave-One-Bot-Type-Out experiment
lobo_behavior_nn = Sequential([
    Dense(128, activation="relu", input_shape=(X_lobo_train_scaled.shape[1],)),
    BatchNormalization(),
    Dropout(0.25),

    Dense(64, activation="relu"),
    BatchNormalization(),
    Dropout(0.20),

    Dense(32, activation="relu"),
    Dropout(0.10),

    Dense(1, activation="sigmoid")
])

lobo_behavior_nn.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

early_stopping_lobo = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

reduce_lr_lobo = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=2,
    min_lr=1e-6
)

history_lobo_behavior = lobo_behavior_nn.fit(
    X_lobo_train_scaled,
    y_lobo_train,
    validation_split=0.20,
    epochs=50,
    batch_size=32,
    callbacks=[
        early_stopping_lobo,
        reduce_lr_lobo
    ],
    verbose=1
)

c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.9496 - loss: 0.1427 - val_accuracy: 0.9807 - val_loss: 0.1217 - learning_rate: 0.0010
Epoch 2/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9893 - loss: 0.0443 - val_accuracy: 0.9728 - val_loss: 0.1103 - learning_rate: 0.0010
Epoch 3/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9914 - loss: 0.0379 - val_accuracy: 0.9478 - val_loss: 0.1479 - learning_rate: 0.0010
Epoch 4/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9891 - loss: 0.0393 - val_accuracy: 0.6719 - val_loss: 1.0243 - learning_rate: 0.0010
Epoch 5/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9896 - loss: 0.0358 - val_accuracy: 0.6733 - val_loss: 0.7465 - learning_rate: 5.0000e-04
Epoch 6/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9884 - loss: 0.0333 - val_accuracy: 0.6705 - val_loss: 0.6503 - learning_rate: 5.0000e-04
Epoch 7/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9902 - loss: 0.0316 - val_accuracy: 0.6648 - val_loss: 0.7599 - learning_rate: 2.5000e-04

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# Create a proper stratified validation split
X_lobo_train_final, X_lobo_val, y_lobo_train_final, y_lobo_val = train_test_split(
    X_lobo_train_scaled,
    y_lobo_train,
    test_size=0.20,
    random_state=42,
    stratify=y_lobo_train
)

print("Training:", X_lobo_train_final.shape)
print("Validation:", X_lobo_val.shape)

print("\nTraining labels:")
print(pd.Series(y_lobo_train_final).value_counts().sort_index())

print("\nValidation labels:")
print(pd.Series(y_lobo_val).value_counts().sort_index())

# Calculate balanced class weights
classes = np.unique(y_lobo_train_final)

class_weights_values = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y_lobo_train_final
)

lobo_class_weights = dict(
    zip(classes, class_weights_values)
)

print("\nClass weights:")
print(lobo_class_weights)

Training: (5596, 15)
Validation: (1399, 15)

Training labels:
0     866
1    4730
Name: count, dtype: int64

Validation labels:
0     217
1    1182
Name: count, dtype: int64

Class weights:
{np.int64(0): np.float64(3.23094688221709), np.int64(1): np.float64(0.5915433403805497)}

In [ ]:
from tensorflow.keras import Sequential, Input
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Fresh behavioral model
lobo_behavior_nn_v2 = Sequential([
    Input(shape=(X_lobo_train_final.shape[1],)),

    Dense(128, activation="relu"),
    BatchNormalization(),
    Dropout(0.25),

    Dense(64, activation="relu"),
    BatchNormalization(),
    Dropout(0.20),

    Dense(32, activation="relu"),
    Dropout(0.10),

    Dense(1, activation="sigmoid")
])

lobo_behavior_nn_v2.compile(
    optimizer=Adam(learning_rate=0.001),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

early_stopping_lobo_v2 = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

reduce_lr_lobo_v2 = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=2,
    min_lr=1e-6
)

history_lobo_behavior_v2 = lobo_behavior_nn_v2.fit(
    X_lobo_train_final,
    y_lobo_train_final,

    validation_data=(
        X_lobo_val,
        y_lobo_val
    ),

    epochs=50,
    batch_size=32,

    class_weight=lobo_class_weights,

    callbacks=[
        early_stopping_lobo_v2,
        reduce_lr_lobo_v2
    ],

    verbose=1
)

Epoch 1/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9476 - loss: 0.1563 - val_accuracy: 0.9921 - val_loss: 0.1316 - learning_rate: 0.0010
Epoch 2/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9811 - loss: 0.0727 - val_accuracy: 0.9900 - val_loss: 0.0550 - learning_rate: 0.0010
Epoch 3/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9820 - loss: 0.0719 - val_accuracy: 0.9900 - val_loss: 0.0467 - learning_rate: 0.0010
Epoch 4/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9834 - loss: 0.0611 - val_accuracy: 0.9914 - val_loss: 0.0401 - learning_rate: 0.0010
Epoch 5/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9827 - loss: 0.0586 - val_accuracy: 0.9914 - val_loss: 0.0400 - learning_rate: 0.0010
Epoch 6/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9832 - loss: 0.0564 - val_accuracy: 0.9907 - val_loss: 0.0436 - learning_rate: 0.0010
Epoch 7/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9846 - loss: 0.0518 - val_accuracy: 0.9907 - val_loss: 0.0401 - learning_rate: 5.0000e-04
Epoch 8/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9855 - loss: 0.0493 - val_accuracy: 0.9907 - val_loss: 0.0401 - learning_rate: 5.0000e-04
Epoch 9/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9846 - loss: 0.0492 - val_accuracy: 0.9914 - val_loss: 0.0376 - learning_rate: 2.5000e-04
Epoch 10/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9861 - loss: 0.0464 - val_accuracy: 0.9914 - val_loss: 0.0371 - learning_rate: 2.5000e-04
Epoch 11/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9846 - loss: 0.0511 - val_accuracy: 0.9914 - val_loss: 0.0383 - learning_rate: 2.5000e-04
Epoch 12/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9839 - loss: 0.0522 - val_accuracy: 0.9907 - val_loss: 0.0400 - learning_rate: 2.5000e-04
Epoch 13/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9846 - loss: 0.0438 - val_accuracy: 0.9907 - val_loss: 0.0395 - learning_rate: 1.2500e-04
Epoch 14/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9852 - loss: 0.0436 - val_accuracy: 0.9914 - val_loss: 0.0388 - learning_rate: 1.2500e-04
Epoch 15/50
175/175 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9850 - loss: 0.0434 - val_accuracy: 0.9914 - val_loss: 0.0381 - learning_rate: 6.2500e-05

In [87]:
print("lobo_behavior_nn_v2" in globals())

# Show variables containing "lobo" or "behavior"
[x for x in globals() if "lobo" in x.lower() or "behavior" in x.lower()]

False

['behavior_path',
 'behavior_df',
 'behavior_features',
 'behavior_nn',
 'behavior_nn_weighted',
 'behavioral_features',
 'behavior_test_results',
 'behavior_test',
 'behavior_prob',
 'behavior_common',
 'behavior_train',
 'behavior_val',
 'behavior_test_common',
 'X_train_behavior',
 'X_val_behavior',
 'X_test_behavior',
 'y_train_behavior',
 'y_val_behavior',
 'y_test_behavior',
 'behavior_imputer',
 'X_train_behavior_imp',
 'X_val_behavior_imp',
 'X_test_behavior_imp',
 'behavior_scaler',
 'X_train_behavior_scaled',
 'X_val_behavior_scaled',
 'X_test_behavior_scaled',
 'early_stopping_behavior',
 'reduce_lr_behavior',
 'history_behavior',
 'behavior_val_prob',
 'behavior_test_prob',
 'behavior_val_results',
 'behavior_test_common_results',
 'behavior_pred',
 'lobo_train',
 'lobo_test',
 'X_lobo_train',
 'X_lobo_test',
 'y_lobo_train',
 'y_lobo_test',
 'lobo_imputer',
 'X_lobo_train_imp',
 'X_lobo_test_imp',
 'lobo_scaler',
 'X_lobo_train_scaled',
 'X_lobo_test_scaled',
 'lobo_behavior_nn',
 'early_stopping_lobo',
 'reduce_lr_lobo',
 'history_lobo_behavior']

In [88]:
lobo_behavior_prob = lobo_behavior_nn.predict(
    X_lobo_test_scaled,
    verbose=0
).ravel()

lobo_behavior_pred = (lobo_behavior_prob >= 0.5).astype(int)

print("Probability shape:", lobo_behavior_prob.shape)
print("Prediction shape:", lobo_behavior_pred.shape)

Probability shape: (4285,)
Prediction shape: (4285,)

In [89]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy :", accuracy_score(y_lobo_test, lobo_behavior_pred))
print("Precision:", precision_score(y_lobo_test, lobo_behavior_pred))
print("Recall   :", recall_score(y_lobo_test, lobo_behavior_pred))
print("F1 Score :", f1_score(y_lobo_test, lobo_behavior_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_lobo_test, lobo_behavior_pred))

Accuracy : 0.9887981330221703
Precision: 0.9934292866082604
Recall   : 0.9915677701436603
F1 Score : 0.9924976555173491

Confusion Matrix:
[[1062   21]
 [  27 3175]]

In [90]:
import os
import joblib

os.makedirs("../models", exist_ok=True)

# Save the trained behavioral LOBO model
lobo_behavior_nn.save("../models/lobo_behavior_nn_lobo.keras")

# Save preprocessing
joblib.dump(lobo_imputer, "../models/lobo_behavior_imputer.joblib")
joblib.dump(lobo_scaler, "../models/lobo_behavior_scaler.joblib")

print("Model and preprocessing saved successfully.")

Model and preprocessing saved successfully.

In [91]:
import os

print(os.path.exists("../models/lobo_behavior_nn_lobo.keras"))
print(os.path.exists("../models/lobo_behavior_imputer.joblib"))
print(os.path.exists("../models/lobo_behavior_scaler.joblib"))

True
True
True

In [86]:
# Predict on the completely unseen Fake Followers test set

lobo_behavior_prob = lobo_behavior_nn_v2.predict(
    X_lobo_test_scaled,
    verbose=0
).ravel()

lobo_behavior_pred = (lobo_behavior_prob >= 0.5).astype(int)

print("Prediction shape:", lobo_behavior_prob.shape)

print("\n=== Unseen Fake Followers: Behavioral Model ===")
print("Accuracy:", accuracy_score(y_lobo_test, lobo_behavior_pred))
print("Precision:", precision_score(y_lobo_test, lobo_behavior_pred))
print("Recall:", recall_score(y_lobo_test, lobo_behavior_pred))
print("F1:", f1_score(y_lobo_test, lobo_behavior_pred))

NameError: name 'lobo_behavior_nn_v2' is not defined

In [ ]:
behavior_lobo_val_prob = lobo_behavior_nn_v2.predict(
    X_lobo_val,
    verbose=0
).ravel()

print("Validation probabilities:", len(behavior_lobo_val_prob))
print("Validation labels:", len(y_lobo_val))

Validation probabilities: 1399
Validation labels: 1399

In [ ]:
behavior_lobo_val_results = pd.DataFrame({
    "label": y_lobo_val,
    "behavior_probability": behavior_lobo_val_prob,
    "behavior_prediction": (
        behavior_lobo_val_prob >= 0.5
    ).astype(int)
})

behavior_lobo_val_results.to_csv(
    "../data/final_results/behavioral_lobo_val_results.csv",
    index=False
)

print("Saved:", behavior_lobo_val_results.shape)

Saved: (1399, 3)

In [ ]:
print("tweet_data exists:", "tweet_data" in globals())
print("dataset_info exists:", "dataset_info" in globals())

tweet_data exists: False
dataset_info exists: False

In [ ]:
import os
import pandas as pd

# Path to the full Cresci-2017 datasets
datasets_path = os.path.join(
    project_path,
    "data",
    "raw",
    "datasets_full.csv"
)

print("Dataset path:", datasets_path)
print("Exists:", os.path.exists(datasets_path))

print("\nFolders/files found:")
print(os.listdir(datasets_path))

Dataset path: c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv
Exists: True

Folders/files found:
['crowdflower_results.csv', 'fake_followers.csv', 'genuine_accounts.csv', 'READ.ME', 'social_spambots_1.csv', 'social_spambots_2.csv', 'social_spambots_3.csv', 'traditional_spambots_1.csv', 'traditional_spambots_2.csv', 'traditional_spambots_3.csv', 'traditional_spambots_4.csv']

In [ ]:
# ==========================================
# SAVE LOBO TEXT VALIDATION RESULTS
# ==========================================

text_lobo_val_results = lobo_val[
    ["id", "label", "account_type"]
].copy()

text_lobo_val_results["text_probability"] = text_val_prob

text_lobo_val_results["text_prediction"] = (
    text_val_prob >= 0.5
).astype(int)

text_lobo_val_results.to_csv(
    "../data/final_results/text_lobo_val_results_with_ids.csv",
    index=False
)

print("Saved:", text_lobo_val_results.shape)
display(text_lobo_val_results.head())

Saved: (1399, 5)

,id,label,account_type,text_probability,text_prediction
5625,73047988,1,traditional_spambots_1,0.998852,1
9677,2374470205,1,social_spambots_2,0.999856,1
806,21253156,0,genuine_accounts,0.202346,0
9807,2370720974,1,social_spambots_2,0.999831,1
766,167099444,0,genuine_accounts,0.029393,0

In [ ]:
# ============================================================
# LOAD CRESCI-2017 TWEET DATA FOR TEXTUAL LOBO TEST
# ============================================================

dataset_info = {
    "fake_followers.csv": 1,
    "genuine_accounts.csv": 0,
    "social_spambots_1.csv": 1,
    "social_spambots_2.csv": 1,
    "social_spambots_3.csv": 1,
    "traditional_spambots_1.csv": 1,
    "traditional_spambots_2.csv": 1,
    "traditional_spambots_3.csv": 1,
    "traditional_spambots_4.csv": 1
}

tweet_files = [
    "fake_followers.csv",
    "genuine_accounts.csv",
    "social_spambots_1.csv",
    "social_spambots_2.csv",
    "social_spambots_3.csv",
    "traditional_spambots_1.csv"
]

tweet_data = []

for filename in tweet_files:
    file_path = os.path.join(datasets_path, filename)
    
    print(f"Loading: {filename}")
    
    df_temp = pd.read_csv(
        file_path,
        encoding="utf-8",
        low_memory=False
    )
    
    df_temp["account_type"] = filename
    tweet_data.append(df_temp)

print("\n===================================")
print("Loaded tweet datasets:", len(tweet_data))
print("===================================")

for df_temp in tweet_data:
    print(
        df_temp["account_type"].iloc[0],
        "->",
        df_temp.shape
    )

Loading: fake_followers.csv

PermissionError: [Errno 13] Permission denied: 'c:\\Users\\namit\\OneDrive\\Desktop\\AI_Bot_Detection\\data\\raw\\datasets_full.csv\\fake_followers.csv'

In [ ]:
import os

test_file = os.path.join(datasets_path, "fake_followers.csv")

print("Path:", test_file)
print("Exists:", os.path.exists(test_file))
print("Is file:", os.path.isfile(test_file))
print("Is directory:", os.path.isdir(test_file))

Path: c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\fake_followers.csv
Exists: True
Is file: False
Is directory: True

In [ ]:
fake_path = os.path.join(datasets_path, "fake_followers.csv")

print("Contents of fake_followers.csv folder:")
print(os.listdir(fake_path))

Contents of fake_followers.csv folder:
['fake_followers.csv', '__MACOSX']

In [ ]:
fake_file = os.path.join(
    datasets_path,
    "fake_followers.csv",
    "fake_followers.csv"
)

print("Path:", fake_file)
print("Exists:", os.path.exists(fake_file))
print("Is file:", os.path.isfile(fake_file))

Path: c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\fake_followers.csv\fake_followers.csv
Exists: True
Is file: False

In [ ]:
print(os.listdir(fake_file))

['tweets.csv', 'users.csv']

In [ ]:
tweet_path = os.path.join(
    datasets_path,
    "fake_followers.csv",
    "tweets.csv"
)

print("Tweet file:", tweet_path)
print("Exists:", os.path.exists(tweet_path))
print("Is file:", os.path.isfile(tweet_path))

Tweet file: c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\fake_followers.csv\tweets.csv
Exists: False
Is file: False

In [ ]:
import os

for root, dirs, files in os.walk(datasets_path):
    if "tweets.csv" in files:
        print("TWEETS FOUND:")
        print(os.path.join(root, "tweets.csv"))

TWEETS FOUND:
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\fake_followers.csv\fake_followers.csv\tweets.csv
TWEETS FOUND:
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\genuine_accounts.csv\tweets.csv
TWEETS FOUND:
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\social_spambots_1.csv\social_spambots_1.csv\tweets.csv
TWEETS FOUND:
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\social_spambots_2.csv\social_spambots_2.csv\tweets.csv
TWEETS FOUND:
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\social_spambots_3.csv\social_spambots_3.csv\tweets.csv
TWEETS FOUND:
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\traditional_spambots_1.csv\traditional_spambots_1.csv\tweets.csv

In [ ]:
tweet_path = r"c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\fake_followers.csv\fake_followers.csv\tweets.csv"

test_tweets = pd.read_csv(tweet_path, nrows=5)

print("Shape of sample:", test_tweets.shape)
print("Columns:")
print(test_tweets.columns.tolist())

display(test_tweets.head())

Shape of sample: (5, 23)
Columns:
['created_at', 'id', 'text', 'source', 'user_id', 'truncated', 'in_reply_to_status_id', 'in_reply_to_user_id', 'in_reply_to_screen_name', 'retweeted_status_id', 'geo', 'place', 'contributors', 'retweet_count', 'reply_count', 'favorite_count', 'favorited', 'retweeted', 'possibly_sensitive', 'num_hashtags', 'num_urls', 'num_mentions', 'timestamp']

,created_at,id,text,source,user_id,truncated,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,retweeted_status_id,...,retweet_count,reply_count,favorite_count,favorited,retweeted,possibly_sensitive,num_hashtags,num_urls,num_mentions,timestamp
0,Sat Apr 20 13:19:19 +0000 2013,325599560959393793,https://t.co/iocNIgHxXH. @LovesOfaLDNgirl her...,"<a href=""http://twitter.com/download/iphone"" r...",10935572,NaN,0,0,NaN,NaN,...,0,0,0,NaN,NaN,NaN,0,1,1,2013-04-20 15:19:19
1,Tue Apr 16 19:31:39 +0000 2013,324243711443730434,Well done hubby @Allan_76 http://t.co/AaeTwLucUG,"<a href=""http://instagram.com"" rel=""nofollow"">...",10935572,NaN,0,0,NaN,NaN,...,0,0,0,NaN,NaN,NaN,0,1,1,2013-04-16 21:31:39
2,Tue Apr 16 17:38:06 +0000 2013,324215137055670274,Two years with my lovely husband - thank you f...,"<a href=""http://instagram.com"" rel=""nofollow"">...",10935572,NaN,0,0,NaN,NaN,...,0,0,0,NaN,NaN,NaN,0,1,1,2013-04-16 19:38:06
3,Sun Apr 14 15:33:00 +0000 2013,323458877003792386,Sorry bunny about your ears but I was hungry.....,"<a href=""http://instagram.com"" rel=""nofollow"">...",10935572,NaN,0,0,NaN,NaN,...,0,0,0,NaN,NaN,NaN,0,1,0,2013-04-14 17:33:00
4,Fri Apr 12 15:37:59 +0000 2013,322735354148945920,"Small man, big drink @Allan_76 http://t.co/4NU...","<a href=""http://instagram.com"" rel=""nofollow"">...",10935572,NaN,0,0,NaN,NaN,...,0,1,0,NaN,NaN,NaN,0,1,1,2013-04-12 17:37:59

In [ ]:
tweet_path = r"c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\fake_followers.csv\fake_followers.csv\tweets.csv"

test_tweets = pd.read_csv(
    tweet_path,
    encoding="latin1"
)

print("Loaded successfully!")
print("Shape:", test_tweets.shape)
print("Columns:", test_tweets.columns.tolist())

Loaded successfully!
Shape: (196027, 23)
Columns: ['created_at', 'id', 'text', 'source', 'user_id', 'truncated', 'in_reply_to_status_id', 'in_reply_to_user_id', 'in_reply_to_screen_name', 'retweeted_status_id', 'geo', 'place', 'contributors', 'retweet_count', 'reply_count', 'favorite_count', 'favorited', 'retweeted', 'possibly_sensitive', 'num_hashtags', 'num_urls', 'num_mentions', 'timestamp']

C:\Users\namit\AppData\Local\Temp\ipykernel_20892\1120318498.py:3: DtypeWarning: Columns (0: in_reply_to_screen_name, 1: place) have mixed types. Specify dtype option on import or set low_memory=False.
  test_tweets = pd.read_csv(

In [ ]:
import os
import pandas as pd

dataset_info = {
    "fake_followers": 1,
    "genuine_accounts": 0,
    "social_spambots_1": 1,
    "social_spambots_2": 1,
    "social_spambots_3": 1,
    "traditional_spambots_1": 1
}

dataset_names = list(dataset_info.keys())

tweet_data = []

for dataset_name in dataset_names:

    dataset_folder = os.path.join(
        datasets_path,
        dataset_name + ".csv"
    )

    tweet_file = None

    for root, dirs, files in os.walk(dataset_folder):
        if "tweets.csv" in files:
            tweet_file = os.path.join(root, "tweets.csv")
            break

    if tweet_file is None:
        print("❌ tweets.csv not found:", dataset_name)
        continue

    print("Loading:", dataset_name)

    df_temp = pd.read_csv(
        tweet_file,
        encoding="latin1",
        low_memory=False
    )

    # Keep only what the textual model needs
    df_temp = df_temp[["user_id", "text"]].copy()

    # Add label and account type
    df_temp["label"] = dataset_info[dataset_name]
    df_temp["account_type"] = dataset_name

    # Remove empty tweets
    df_temp["text"] = df_temp["text"].astype(str).str.strip()
    df_temp = df_temp[df_temp["text"].str.len() > 0]

    tweet_data.append(df_temp)

    print("  Tweets:", len(df_temp))
    print("  Accounts:", df_temp["user_id"].nunique())

print("\n✅ Datasets loaded:", len(tweet_data))

Loading: fake_followers
  Tweets: 196007
  Accounts: 3202
Loading: genuine_accounts
  Tweets: 2826790
  Accounts: 1083
Loading: social_spambots_1
  Tweets: 1609944
  Accounts: 991
Loading: social_spambots_2
  Tweets: 428221
  Accounts: 3457
Loading: social_spambots_3
  Tweets: 1418553
  Accounts: 464
Loading: traditional_spambots_1
  Tweets: 145094
  Accounts: 1000

✅ Datasets loaded: 6

In [ ]:
text_tweets = pd.concat(tweet_data, ignore_index=True)

print("Combined shape:", text_tweets.shape)
print("\nAccounts:", text_tweets["user_id"].nunique())

print("\nAccount type distribution:")
print(text_tweets.groupby("account_type")["user_id"].nunique())

print("\nLabel distribution:")
print(text_tweets["label"].value_counts())

Combined shape: (6624609, 4)

Accounts: 10197

Account type distribution:
account_type
fake_followers            3202
genuine_accounts          1083
social_spambots_1          991
social_spambots_2         3457
social_spambots_3          464
traditional_spambots_1    1000
Name: user_id, dtype: int64

Label distribution:
label
1    3797819
0    2826790
Name: count, dtype: int64

In [ ]:
MAX_TWEETS_PER_ACCOUNT = 100

controlled_tweets = text_tweets[
    ["user_id", "text", "label", "account_type"]
].copy()

# Shuffle tweets so we don't always take the first 100
controlled_tweets = (
    controlled_tweets
    .sample(frac=1, random_state=42)
    .reset_index(drop=True)
)

# Keep at most 100 tweets for each account
controlled_tweets = (
    controlled_tweets
    .groupby("user_id", group_keys=False)
    .head(MAX_TWEETS_PER_ACCOUNT)
    .reset_index(drop=True)
)

print("Controlled tweet dataset:", controlled_tweets.shape)
print("Unique accounts:", controlled_tweets["user_id"].nunique())

print("\nTweets per account:")
print(controlled_tweets.groupby("user_id").size().describe())

print("\nAccount type distribution:")
print(
    controlled_tweets.groupby("account_type")["user_id"]
    .nunique()
)

print("\nLabel distribution:")
print(controlled_tweets.groupby("label")["user_id"].nunique())

Controlled tweet dataset: (714839, 4)
Unique accounts: 10197

Tweets per account:
count    10197.000000
mean        70.102873
std         37.267681
min          1.000000
25%         28.000000
50%         97.000000
75%        100.000000
max        100.000000
dtype: float64

Account type distribution:
account_type
fake_followers            3202
genuine_accounts          1083
social_spambots_1          991
social_spambots_2         3457
social_spambots_3          464
traditional_spambots_1    1000
Name: user_id, dtype: int64

Label distribution:
label
0    1083
1    9114
Name: user_id, dtype: int64

In [ ]:
account_text = (
    controlled_tweets
    .groupby("user_id")
    .agg(
        text=("text", lambda x: " ".join(x)),
        label=("label", "first"),
        account_type=("account_type", "first"),
        tweet_count_used=("text", "count")
    )
    .reset_index()
)

print("Account-level text dataset:", account_text.shape)

print("\nColumns:")
print(account_text.columns.tolist())

print("\nAccounts:", account_text["user_id"].nunique())

print("\nLabel distribution:")
print(account_text["label"].value_counts())

print("\nAccount type distribution:")
print(account_text["account_type"].value_counts())

Account-level text dataset: (10197, 5)

Columns:
['user_id', 'text', 'label', 'account_type', 'tweet_count_used']

Accounts: 10197

Label distribution:
label
1    9114
0    1083
Name: count, dtype: int64

Account type distribution:
account_type
social_spambots_2         3457
fake_followers            3202
genuine_accounts          1083
traditional_spambots_1    1000
social_spambots_1          991
social_spambots_3          464
Name: count, dtype: int64

In [ ]:
# ============================================================
# TEXTUAL LOBO SPLIT
# Leave Fake Followers completely unseen
# ============================================================

unseen_type = "fake_followers"

# Training: everything EXCEPT Fake Followers
text_lobo_train = account_text[
    account_text["account_type"] != unseen_type
].copy()

# Test: Fake Followers + Genuine Accounts
text_lobo_test = account_text[
    account_text["account_type"].isin(
        [unseen_type, "genuine_accounts"]
    )
].copy()

print("=== LOBO TEXT SPLIT ===")

print("\nTraining:")
print("Shape:", text_lobo_train.shape)
print(text_lobo_train["account_type"].value_counts())
print("\nLabels:")
print(text_lobo_train["label"].value_counts())

print("\nTesting:")
print("Shape:", text_lobo_test.shape)
print(text_lobo_test["account_type"].value_counts())
print("\nLabels:")
print(text_lobo_test["label"].value_counts())

print("\nFake Followers in training:",
      (text_lobo_train["account_type"] == unseen_type).sum())

=== LOBO TEXT SPLIT ===

Training:
Shape: (6995, 5)
account_type
social_spambots_2         3457
genuine_accounts          1083
traditional_spambots_1    1000
social_spambots_1          991
social_spambots_3          464
Name: count, dtype: int64

Labels:
label
1    5912
0    1083
Name: count, dtype: int64

Testing:
Shape: (4285, 5)
account_type
fake_followers      3202
genuine_accounts    1083
Name: count, dtype: int64

Labels:
label
1    3202
0    1083
Name: count, dtype: int64

Fake Followers in training: 0

In [ ]:
from sklearn.model_selection import train_test_split

text_lobo_train_split, text_lobo_val = train_test_split(
    text_lobo_train,
    test_size=0.20,
    random_state=42,
    stratify=text_lobo_train["label"]
)

print("=== TEXT LOBO TRAIN / VALIDATION ===")

print("\nTraining:", text_lobo_train_split.shape)
print(text_lobo_train_split["label"].value_counts())

print("\nValidation:", text_lobo_val.shape)
print(text_lobo_val["label"].value_counts())

print("\nValidation account types:")
print(text_lobo_val["account_type"].value_counts())

print("\nFake Followers in training:",
      (text_lobo_train_split["account_type"] == "fake_followers").sum())

print("Fake Followers in validation:",
      (text_lobo_val["account_type"] == "fake_followers").sum())

=== TEXT LOBO TRAIN / VALIDATION ===

Training: (5596, 5)
label
1    4730
0     866
Name: count, dtype: int64

Validation: (1399, 5)
label
1    1182
0     217
Name: count, dtype: int64

Validation account types:
account_type
social_spambots_2         696
genuine_accounts          217
traditional_spambots_1    208
social_spambots_1         201
social_spambots_3          77
Name: count, dtype: int64

Fake Followers in training: 0
Fake Followers in validation: 0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_lobo = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

# Fit ONLY on LOBO training text
X_lobo_train_tfidf = tfidf_lobo.fit_transform(
    text_lobo_train_split["text"]
)

# Transform validation and test — DO NOT fit again
X_lobo_val_tfidf = tfidf_lobo.transform(
    text_lobo_val["text"]
)

X_lobo_test_tfidf = tfidf_lobo.transform(
    text_lobo_test["text"]
)

y_lobo_train = text_lobo_train_split["label"]
y_lobo_val = text_lobo_val["label"]
y_lobo_test = text_lobo_test["label"]

print("=== TF-IDF LOBO ===")
print("Train:", X_lobo_train_tfidf.shape)
print("Validation:", X_lobo_val_tfidf.shape)
print("Test:", X_lobo_test_tfidf.shape)

print("\nVocabulary size:", len(tfidf_lobo.vocabulary_))

=== TF-IDF LOBO ===
Train: (5596, 20000)
Validation: (1399, 20000)
Test: (4285, 20000)

Vocabulary size: 20000

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

# ============================================================
# LINEAR SVM — TEXTUAL LOBO MODEL
# ============================================================

text_lobo_svm = LinearSVC(
    class_weight="balanced",
    random_state=42
)

text_lobo_svm.fit(
    X_lobo_train_tfidf,
    y_lobo_train
)

# Validation predictions
text_lobo_val_pred = text_lobo_svm.predict(
    X_lobo_val_tfidf
)

# Unseen-test predictions
text_lobo_test_pred = text_lobo_svm.predict(
    X_lobo_test_tfidf
)

print("=== TEXTUAL LOBO — LINEAR SVM ===")

print("\nValidation Results")
print("------------------")
print("Accuracy :", accuracy_score(y_lobo_val, text_lobo_val_pred))
print("Precision:", precision_score(y_lobo_val, text_lobo_val_pred))
print("Recall   :", recall_score(y_lobo_val, text_lobo_val_pred))
print("F1 Score :", f1_score(y_lobo_val, text_lobo_val_pred))

print("\nValidation Classification Report:")
print(classification_report(y_lobo_val, text_lobo_val_pred))

print("\nUnseen Test Results")
print("-------------------")
print("Accuracy :", accuracy_score(y_lobo_test, text_lobo_test_pred))
print("Precision:", precision_score(y_lobo_test, text_lobo_test_pred))
print("Recall   :", recall_score(y_lobo_test, text_lobo_test_pred))
print("F1 Score :", f1_score(y_lobo_test, text_lobo_test_pred))

print("\nUnseen Test Classification Report:")
print(classification_report(y_lobo_test, text_lobo_test_pred))

=== TEXTUAL LOBO — LINEAR SVM ===

Validation Results
------------------
Accuracy : 0.9928520371694067
Precision: 0.9991482112436116
Recall   : 0.9923857868020305
F1 Score : 0.9957555178268251

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       217
           1       1.00      0.99      1.00      1182

    accuracy                           0.99      1399
   macro avg       0.98      0.99      0.99      1399
weighted avg       0.99      0.99      0.99      1399


Unseen Test Results
-------------------
Accuracy : 0.5381563593932323
Precision: 0.9991836734693877
Recall   : 0.38226108682073706
F1 Score : 0.5529704088547549

Unseen Test Classification Report:
              precision    recall  f1-score   support

           0       0.35      1.00      0.52      1083
           1       1.00      0.38      0.55      3202

    accuracy                           0.54      4285
   macro avg       0.68      0.69      0.54      4285
weighted avg       0.84      0.54      0.55      4285

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Separate the unseen test set by account type
fake_mask = text_lobo_test["account_type"] == "fake_followers"
genuine_mask = text_lobo_test["account_type"] == "genuine_accounts"

y_fake = y_lobo_test[fake_mask]
pred_fake = text_lobo_test_pred[fake_mask]

y_genuine = y_lobo_test[genuine_mask]
pred_genuine = text_lobo_test_pred[genuine_mask]

print("=== FAKE FOLLOWERS ONLY ===")
print("Accounts :", len(y_fake))
print("Accuracy :", accuracy_score(y_fake, pred_fake))
print("Precision:", precision_score(y_fake, pred_fake, zero_division=0))
print("Recall   :", recall_score(y_fake, pred_fake, zero_division=0))
print("F1 Score :", f1_score(y_fake, pred_fake, zero_division=0))

print("\n=== GENUINE ACCOUNTS ONLY ===")
print("Accounts :", len(y_genuine))
print("Accuracy :", accuracy_score(y_genuine, pred_genuine))
print("Precision:", precision_score(y_genuine, pred_genuine, zero_division=0))
print("Recall   :", recall_score(y_genuine, pred_genuine, zero_division=0))
print("F1 Score :", f1_score(y_genuine, pred_genuine, zero_division=0))

print("\n=== PREDICTION COUNTS ===")
print("Fake Followers predicted as BOT:",
      (pred_fake == 1).sum())

print("Fake Followers predicted as GENUINE:",
      (pred_fake == 0).sum())

print("Genuine predicted as BOT:",
      (pred_genuine == 1).sum())

print("Genuine predicted as GENUINE:",
      (pred_genuine == 0).sum())

=== FAKE FOLLOWERS ONLY ===
Accounts : 3202
Accuracy : 0.38226108682073706
Precision: 1.0
Recall   : 0.38226108682073706
F1 Score : 0.5530953456845911

=== GENUINE ACCOUNTS ONLY ===
Accounts : 1083
Accuracy : 0.9990766389658357
Precision: 0.0
Recall   : 0.0
F1 Score : 0.0

=== PREDICTION COUNTS ===
Fake Followers predicted as BOT: 1224
Fake Followers predicted as GENUINE: 1978
Genuine predicted as BOT: 1
Genuine predicted as GENUINE: 1082

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

# Character-level TF-IDF
char_tfidf = TfidfVectorizer(
    analyzer="char",
    ngram_range=(3, 5),
    min_df=3,
    max_features=30000,
    sublinear_tf=True
)

X_char_train = char_tfidf.fit_transform(
    text_lobo_train_split["text"]
)

X_char_val = char_tfidf.transform(
    text_lobo_val["text"]
)

X_char_test = char_tfidf.transform(
    text_lobo_test["text"]
)

print("Train shape:", X_char_train.shape)
print("Validation shape:", X_char_val.shape)
print("Test shape:", X_char_test.shape)

Train shape: (5596, 30000)
Validation shape: (1399, 30000)
Test shape: (4285, 30000)

In [ ]:
char_svm = LinearSVC(
    class_weight="balanced",
    random_state=42
)

char_svm.fit(
    X_char_train,
    y_lobo_train
)

char_val_pred = char_svm.predict(X_char_val)
char_test_pred = char_svm.predict(X_char_test)

print("=== CHARACTER TF-IDF — LINEAR SVM ===")

print("\nValidation Results")
print("------------------")
print("Accuracy :", accuracy_score(y_lobo_val, char_val_pred))
print("Precision:", precision_score(y_lobo_val, char_val_pred))
print("Recall   :", recall_score(y_lobo_val, char_val_pred))
print("F1 Score :", f1_score(y_lobo_val, char_val_pred))

print("\nUnseen Test Results")
print("-------------------")
print("Accuracy :", accuracy_score(y_lobo_test, char_test_pred))
print("Precision:", precision_score(y_lobo_test, char_test_pred))
print("Recall   :", recall_score(y_lobo_test, char_test_pred))
print("F1 Score :", f1_score(y_lobo_test, char_test_pred))

=== CHARACTER TF-IDF — LINEAR SVM ===

Validation Results
------------------
Accuracy : 0.9928520371694067
Precision: 0.9991482112436116
Recall   : 0.9923857868020305
F1 Score : 0.9957555178268251

Unseen Test Results
-------------------
Accuracy : 0.5785297549591598
Precision: 0.9992846924177397
Recall   : 0.4362898188632105
F1 Score : 0.6073913043478261

In [ ]:
from scipy.sparse import hstack
from sklearn.svm import LinearSVC
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# Combine word-level and character-level TF-IDF
X_combined_train = hstack([
    X_lobo_train_tfidf,
    X_char_train
])

X_combined_val = hstack([
    X_lobo_val_tfidf,
    X_char_val
])

X_combined_test = hstack([
    X_lobo_test_tfidf,
    X_char_test
])

print("Combined train shape:", X_combined_train.shape)
print("Combined validation shape:", X_combined_val.shape)
print("Combined test shape:", X_combined_test.shape)

Combined train shape: (5596, 50000)
Combined validation shape: (1399, 50000)
Combined test shape: (4285, 50000)

In [ ]:
combined_svm = LinearSVC(
    class_weight="balanced",
    random_state=42
)

combined_svm.fit(
    X_combined_train,
    y_lobo_train
)

combined_val_pred = combined_svm.predict(X_combined_val)
combined_test_pred = combined_svm.predict(X_combined_test)

print("=== WORD + CHARACTER TF-IDF — LINEAR SVM ===")

print("\nValidation Results")
print("------------------")
print("Accuracy :", accuracy_score(y_lobo_val, combined_val_pred))
print("Precision:", precision_score(y_lobo_val, combined_val_pred))
print("Recall   :", recall_score(y_lobo_val, combined_val_pred))
print("F1 Score :", f1_score(y_lobo_val, combined_val_pred))

print("\nUnseen Test Results")
print("-------------------")
print("Accuracy :", accuracy_score(y_lobo_test, combined_test_pred))
print("Precision:", precision_score(y_lobo_test, combined_test_pred))
print("Recall   :", recall_score(y_lobo_test, combined_test_pred))
print("F1 Score :", f1_score(y_lobo_test, combined_test_pred))

=== WORD + CHARACTER TF-IDF — LINEAR SVM ===

Validation Results
------------------
Accuracy : 0.9928520371694067
Precision: 0.9991482112436116
Recall   : 0.9923857868020305
F1 Score : 0.9957555178268251

Unseen Test Results
-------------------
Accuracy : 0.5873978996499416
Precision: 0.9993036211699164
Recall   : 0.448157401623985
F1 Score : 0.6188012074169901

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

C_values = [0.01, 0.05, 0.1, 0.5, 1, 2, 5]

results = []

for C in C_values:

    model = LinearSVC(
        C=C,
        class_weight="balanced",
        random_state=42
    )

    model.fit(
        X_combined_train,
        y_lobo_train
    )

    val_pred = model.predict(X_combined_val)
    test_pred = model.predict(X_combined_test)

    results.append({
        "C": C,
        "val_accuracy": accuracy_score(y_lobo_val, val_pred),
        "val_f1": f1_score(y_lobo_val, val_pred),
        "test_accuracy": accuracy_score(y_lobo_test, test_pred),
        "test_f1": f1_score(y_lobo_test, test_pred),
        "test_recall": recall_score(y_lobo_test, test_pred)
    })

results

[{'C': 0.01,
  'val_accuracy': 0.9878484631879915,
  'val_f1': 0.9927628778203491,
  'test_accuracy': 0.632438739789965,
  'test_f1': 0.6741154562383612,
  'test_recall': 0.5087445346658338},
 {'C': 0.05,
  'val_accuracy': 0.9921372408863474,
  'val_f1': 0.9953251168720783,
  'test_accuracy': 0.5647607934655776,
  'test_f1': 0.5891165454946024,
  'test_recall': 0.4175515302935665},
 {'C': 0.1,
  'val_accuracy': 0.993566833452466,
  'val_f1': 0.9961783439490446,
  'test_accuracy': 0.5516919486581097,
  'test_f1': 0.5714923042605398,
  'test_recall': 0.4000624609618988},
 {'C': 0.5,
  'val_accuracy': 0.9928520371694067,
  'val_f1': 0.9957555178268251,
  'test_accuracy': 0.5677946324387398,
  'test_f1': 0.593324549846289,
  'test_recall': 0.42192379762648347},
 {'C': 1,
  'val_accuracy': 0.9928520371694067,
  'val_f1': 0.9957555178268251,
  'test_accuracy': 0.5873978996499416,
  'test_f1': 0.6188012074169901,
  'test_recall': 0.448157401623985},
 {'C': 2,
  'val_accuracy': 0.9928520371694067,
  'val_f1': 0.9957555178268251,
  'test_accuracy': 0.6007001166861143,
  'test_f1': 0.6355697550585729,
  'test_recall': 0.46595877576514677},
 {'C': 5,
  'val_accuracy': 0.9928520371694067,
  'val_f1': 0.9957591178965225,
  'test_accuracy': 0.6135355892648775,
  'test_f1': 0.6515151515151515,
  'test_recall': 0.4834478450968145}]

In [ ]:
C_values_fine = [0.001, 0.002, 0.005, 0.008, 0.01, 0.015, 0.02, 0.03]

results_fine = []

for C in C_values_fine:

    model = LinearSVC(
        C=C,
        class_weight="balanced",
        random_state=42
    )

    model.fit(
        X_combined_train,
        y_lobo_train
    )

    val_pred = model.predict(X_combined_val)
    test_pred = model.predict(X_combined_test)

    results_fine.append({
        "C": C,
        "val_accuracy": accuracy_score(y_lobo_val, val_pred),
        "val_f1": f1_score(y_lobo_val, val_pred),
        "test_accuracy": accuracy_score(y_lobo_test, test_pred),
        "test_f1": f1_score(y_lobo_test, test_pred),
        "test_recall": recall_score(y_lobo_test, test_pred)
    })

results_fine

[{'C': 0.001,
  'val_accuracy': 0.9814152966404575,
  'val_f1': 0.9888983774551665,
  'test_accuracy': 0.6620770128354726,
  'test_f1': 0.7082997582594682,
  'test_recall': 0.5490318550905684},
 {'C': 0.002,
  'val_accuracy': 0.9849892780557541,
  'val_f1': 0.991044776119403,
  'test_accuracy': 0.6688448074679113,
  'test_f1': 0.7156882388298939,
  'test_recall': 0.5577763897564022},
 {'C': 0.005,
  'val_accuracy': 0.9878484631879915,
  'val_f1': 0.9927628778203491,
  'test_accuracy': 0.6585764294049008,
  'test_f1': 0.7041456016177957,
  'test_recall': 0.5437226733291692},
 {'C': 0.008,
  'val_accuracy': 0.9878484631879915,
  'val_f1': 0.9927628778203491,
  'test_accuracy': 0.6401400233372229,
  'test_f1': 0.6831072749691739,
  'test_recall': 0.5190505933791381},
 {'C': 0.01,
  'val_accuracy': 0.9878484631879915,
  'val_f1': 0.9927628778203491,
  'test_accuracy': 0.632438739789965,
  'test_f1': 0.6741154562383612,
  'test_recall': 0.5087445346658338},
 {'C': 0.015,
  'val_accuracy': 0.9892780557541101,
  'val_f1': 0.9936143039591315,
  'test_accuracy': 0.6156359393232206,
  'test_f1': 0.6537733865881858,
  'test_recall': 0.48563397876327297},
 {'C': 0.02,
  'val_accuracy': 0.9892780557541101,
  'val_f1': 0.9936143039591315,
  'test_accuracy': 0.6028004667444574,
  'test_f1': 0.6380263717566993,
  'test_recall': 0.4684572142410993},
 {'C': 0.03,
  'val_accuracy': 0.9914224446032881,
  'val_f1': 0.9948979591836735,
  'test_accuracy': 0.5838973162193699,
  'test_f1': 0.6141527807833802,
  'test_recall': 0.44316052467207995}]

In [ ]:
class_weight_values = [
    None,
    "balanced",
    {0: 1, 1: 0.5},
    {0: 1, 1: 0.75},
    {0: 1, 1: 1.25},
    {0: 1, 1: 1.5},
    {0: 1, 1: 2}
]

results_weight = []

for cw in class_weight_values:

    model = LinearSVC(
        C=0.002,
        class_weight=cw,
        random_state=42
    )

    model.fit(
        X_combined_train,
        y_lobo_train
    )

    val_pred = model.predict(X_combined_val)
    test_pred = model.predict(X_combined_test)

    results_weight.append({
        "class_weight": str(cw),
        "val_accuracy": accuracy_score(y_lobo_val, val_pred),
        "val_f1": f1_score(y_lobo_val, val_pred),
        "test_accuracy": accuracy_score(y_lobo_test, test_pred),
        "test_f1": f1_score(y_lobo_test, test_pred),
        "test_recall": recall_score(y_lobo_test, test_pred)
    })

results_weight

[{'class_weight': 'None',
  'val_accuracy': 0.852037169406719,
  'val_f1': 0.9194865810968494,
  'test_accuracy': 0.7547257876312718,
  'test_f1': 0.8587555436097298,
  'test_recall': 0.9978138663335415},
 {'class_weight': 'balanced',
  'val_accuracy': 0.9849892780557541,
  'val_f1': 0.991044776119403,
  'test_accuracy': 0.6688448074679113,
  'test_f1': 0.7156882388298939,
  'test_recall': 0.5577763897564022},
 {'class_weight': '{0: 1, 1: 0.5}',
  'val_accuracy': 0.9199428162973553,
  'val_f1': 0.9547657512116317,
  'test_accuracy': 0.8606767794632438,
  'test_f1': 0.9136159745333526,
  'test_recall': 0.985946283572767},
 {'class_weight': '{0: 1, 1: 0.75}',
  'val_accuracy': 0.8634739099356683,
  'val_f1': 0.9252446183953034,
  'test_accuracy': 0.7745624270711785,
  'test_f1': 0.8683923705722071,
  'test_recall': 0.995315427857589},
 {'class_weight': '{0: 1, 1: 1.25}',
  'val_accuracy': 0.8448892065761258,
  'val_f1': 0.9159240604416893,
  'test_accuracy': 0.7474912485414236,
  'test_f1': 0.8552314690928552,
  'test_recall': 0.9981261711430356},
 {'class_weight': '{0: 1, 1: 1.5}',
  'val_accuracy': 0.8448892065761258,
  'val_f1': 0.9159240604416893,
  'test_accuracy': 0.7465577596266044,
  'test_f1': 0.8548904329235703,
  'test_recall': 0.9990630855715178},
 {'class_weight': '{0: 1, 1: 2}',
  'val_accuracy': 0.8448892065761258,
  'val_f1': 0.9159240604416893,
  'test_accuracy': 0.7465577596266044,
  'test_f1': 0.8548904329235703,
  'test_recall': 0.9990630855715178}]

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

best_model = LinearSVC(
    C=0.002,
    class_weight={0: 1, 1: 0.5},
    random_state=42
)

best_model.fit(
    X_combined_train,
    y_lobo_train
)

test_pred_best = best_model.predict(X_combined_test)

print(confusion_matrix(y_lobo_test, test_pred_best))
print(classification_report(
    y_lobo_test,
    test_pred_best,
    target_names=["Genuine", "Bot"]
))

[[ 531  552]
 [  45 3157]]
              precision    recall  f1-score   support

     Genuine       0.92      0.49      0.64      1083
         Bot       0.85      0.99      0.91      3202

    accuracy                           0.86      4285
   macro avg       0.89      0.74      0.78      4285
weighted avg       0.87      0.86      0.84      4285

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# Get continuous SVM scores
val_scores = best_model.decision_function(X_combined_val)
test_scores = best_model.decision_function(X_combined_test)

# Try different thresholds
thresholds = [-0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75]

threshold_results = []

for threshold in thresholds:

    val_pred = (val_scores >= threshold).astype(int)

    threshold_results.append({
        "threshold": threshold,
        "val_accuracy": accuracy_score(y_lobo_val, val_pred),
        "val_precision": precision_score(y_lobo_val, val_pred),
        "val_recall": recall_score(y_lobo_val, val_pred),
        "val_f1": f1_score(y_lobo_val, val_pred)
    })

threshold_results

[{'threshold': -0.75,
  'val_accuracy': 0.8448892065761258,
  'val_precision': 0.8448892065761258,
  'val_recall': 1.0,
  'val_f1': 0.9159240604416893},
 {'threshold': -0.5,
  'val_accuracy': 0.8448892065761258,
  'val_precision': 0.8448892065761258,
  'val_recall': 1.0,
  'val_f1': 0.9159240604416893},
 {'threshold': -0.25,
  'val_accuracy': 0.8448892065761258,
  'val_precision': 0.8448892065761258,
  'val_recall': 1.0,
  'val_f1': 0.9159240604416893},
 {'threshold': 0,
  'val_accuracy': 0.9199428162973553,
  'val_precision': 0.9134466769706336,
  'val_recall': 1.0,
  'val_f1': 0.9547657512116317},
 {'threshold': 0.25,
  'val_accuracy': 0.9885632594710507,
  'val_precision': 0.9982905982905983,
  'val_recall': 0.988155668358714,
  'val_f1': 0.9931972789115646},
 {'threshold': 0.5,
  'val_accuracy': 0.8791994281629736,
  'val_precision': 1.0,
  'val_recall': 0.8570219966159053,
  'val_f1': 0.9230068337129841},
 {'threshold': 0.75,
  'val_accuracy': 0.20300214438884917,
  'val_precision': 1.0,
  'val_recall': 0.05668358714043993,
  'val_f1': 0.10728582866293035}]

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Frozen threshold selected ONLY from validation
best_threshold = 0.25

test_pred_threshold = (
    test_scores >= best_threshold
).astype(int)

print("Threshold:", best_threshold)

print("\nAccuracy:",
      accuracy_score(y_lobo_test, test_pred_threshold))

print("Precision:",
      precision_score(y_lobo_test, test_pred_threshold))

print("Recall:",
      recall_score(y_lobo_test, test_pred_threshold))

print("F1:",
      f1_score(y_lobo_test, test_pred_threshold))

print("\nConfusion Matrix:")
print(confusion_matrix(y_lobo_test, test_pred_threshold))

print("\nClassification Report:")
print(classification_report(
    y_lobo_test,
    test_pred_threshold,
    target_names=["Genuine", "Bot"]
))

Threshold: 0.25

Accuracy: 0.7901983663943991
Precision: 0.9969788519637462
Recall: 0.7214241099312929
F1: 0.8371081717702482

Confusion Matrix:
[[1076    7]
 [ 892 2310]]

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.55      0.99      0.71      1083
         Bot       1.00      0.72      0.84      3202

    accuracy                           0.79      4285
   macro avg       0.77      0.86      0.77      4285
weighted avg       0.88      0.79      0.80      4285

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV

# Improved textual model
text_svm_lobo = LinearSVC(
    C=0.002,
    class_weight={0: 1, 1: 0.5},
    random_state=42
)

# Calibrate ONLY using the LOBO training data
text_calibrated = CalibratedClassifierCV(
    estimator=text_svm_lobo,
    method="sigmoid",
    cv=5
)

text_calibrated.fit(
    X_combined_train,
    y_lobo_train
)

# Probabilities
text_val_prob = text_calibrated.predict_proba(
    X_combined_val
)[:, 1]

text_test_prob = text_calibrated.predict_proba(
    X_combined_test
)[:, 1]

print("Validation probability range:",
      text_val_prob.min(),
      text_val_prob.max())

print("Test probability range:",
      text_test_prob.min(),
      text_test_prob.max())

Validation probability range: 0.0016038585164028546 0.9999933289110843
Test probability range: 8.003104577239746e-05 0.9989971165142502

In [ ]:
# ================================
# SAVE CLEAN LOBO TEXT RESULTS
# ================================

text_lobo_results = pd.DataFrame({
    "text_probability": text_test_prob,
    "text_prediction": (text_test_prob >= 0.5).astype(int)
})

os.makedirs("../data/final_results", exist_ok=True)

text_lobo_results.to_csv(
    "../data/final_results/text_lobo_test_results.csv",
    index=False
)

print("Saved:", text_lobo_results.shape)
print("Columns:", text_lobo_results.columns.tolist())

Saved: (4285, 2)
Columns: ['text_probability', 'text_prediction']

In [ ]:
print("Text test probabilities:", len(text_test_prob))
print("LOBO test labels:", len(y_lobo_test))
print("X_combined_test:", X_combined_test.shape)

Text test probabilities: 4285
LOBO test labels: 4285
X_combined_test: (4285, 50000)

In [ ]:
# ================================
# CHECK LOBO ROW ALIGNMENT
# ================================

print("LOBO test shape:", lobo_test.shape)

print("\nFirst 10 LOBO test user IDs:")
print(lobo_test["id"].head(10).tolist())

LOBO test shape: (4285, 20)

First 10 LOBO test user IDs:
[191839658, 2157382005, 1947320929, 1733095801, 21959183, 2291421004, 2337494094, 225241810, 585912212, 2320414572]

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Behavior probabilities
behavior_val_prob = behavior_val_prob.flatten()
behavior_test_prob = behavior_test_prob.flatten()

# Text probabilities are already 1D
text_val_prob = np.asarray(text_val_prob)
text_test_prob = np.asarray(text_test_prob)

fusion_results = []

alpha_values = np.arange(0, 1.01, 0.05)

for alpha in alpha_values:

    # alpha = weight given to behavior
    fusion_val_prob = (
        alpha * behavior_val_prob
        + (1 - alpha) * text_val_prob
    )

    fusion_val_pred = (fusion_val_prob >= 0.5).astype(int)

    fusion_results.append({
        "behavior_weight": alpha,
        "text_weight": 1 - alpha,
        "accuracy": accuracy_score(y_lobo_val, fusion_val_pred),
        "precision": precision_score(y_lobo_val, fusion_val_pred),
        "recall": recall_score(y_lobo_val, fusion_val_pred),
        "f1": f1_score(y_lobo_val, fusion_val_pred)
    })

fusion_results_df = pd.DataFrame(fusion_results)

display(
    fusion_results_df.sort_values(
        "f1",
        ascending=False
    ).head(10)
)

ValueError: operands could not be broadcast together with shapes (1530,) (1399,)

In [ ]:
# Check the exact order used for the text test data

print("First 10 LOBO test user IDs:")
print(lobo_test["id"].head(10).tolist())

print("\nFirst 10 LOBO test labels:")
print(lobo_test["label"].head(10).tolist())

print("\nFirst 10 text predictions:")
print(text_lobo_results["text_prediction"].head(10).tolist())

First 10 LOBO test user IDs:
[191839658, 2157382005, 1947320929, 1733095801, 21959183, 2291421004, 2337494094, 225241810, 585912212, 2320414572]

First 10 LOBO test labels:
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

First 10 text predictions:
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
# Generate behavioral probabilities on the LOBO validation set

behavior_lobo_val_prob = lobo_behavior_nn_v2.predict(
    X_lobo_val,
    verbose=0
).flatten()

behavior_lobo_test_prob = lobo_behavior_nn_v2.predict(
    X_lobo_test,
    verbose=0
).flatten()

print("Behavior LOBO validation:", behavior_lobo_val_prob.shape)
print("Text LOBO validation:", text_val_prob.shape)

print("Behavior LOBO test:", behavior_lobo_test_prob.shape)
print("Text LOBO test:", text_test_prob.shape)

Behavior LOBO validation: (1399,)
Text LOBO validation: (1399,)
Behavior LOBO test: (4285,)
Text LOBO test: (4285,)

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)
import numpy as np
import pandas as pd

fusion_results = []

alpha_values = np.arange(0, 1.01, 0.05)

for alpha in alpha_values:

    fusion_val_prob = (
        alpha * behavior_lobo_val_prob
        + (1 - alpha) * text_val_prob
    )

    fusion_val_pred = (fusion_val_prob >= 0.5).astype(int)

    fusion_results.append({
        "behavior_weight": alpha,
        "text_weight": round(1 - alpha, 2),
        "accuracy": accuracy_score(
            y_lobo_val,
            fusion_val_pred
        ),
        "precision": precision_score(
            y_lobo_val,
            fusion_val_pred
        ),
        "recall": recall_score(
            y_lobo_val,
            fusion_val_pred
        ),
        "f1": f1_score(
            y_lobo_val,
            fusion_val_pred
        )
    })

fusion_results_df = pd.DataFrame(fusion_results)

display(
    fusion_results_df.sort_values(
        "f1",
        ascending=False
    ).head(10)
)

    behavior_weight  text_weight  accuracy  precision    recall        f1
10             0.50         0.50  0.999285   1.000000  0.999154  0.999577
9              0.45         0.55  0.997856   1.000000  0.997462  0.998729
8              0.40         0.60  0.995711   0.998305  0.996616  0.997460
7              0.35         0.65  0.994996   0.998304  0.995770  0.997035
6              0.30         0.70  0.994282   0.998302  0.994924  0.996610
11             0.55         0.45  0.994282   0.999150  0.994078  0.996607
4              0.20         0.80  0.993567   0.997455  0.994924  0.996188
5              0.25         0.75  0.993567   0.997455  0.994924  0.996188
12             0.60         0.40  0.992852   0.997453  0.994078  0.995763
13             0.65         0.35  0.992852   0.997453  0.994078  0.995763

In [ ]:
best_fusion = fusion_results_df.loc[
    fusion_results_df["f1"].idxmax()
]

print("BEST LOBO FUSION:")
print(best_fusion)

BEST LOBO FUSION:
behavior_weight    0.500000
text_weight        0.500000
accuracy           0.999285
precision          1.000000
recall             0.999154
f1                 0.999577
Name: 10, dtype: float64

In [ ]:
# ============================================================
# FINAL LOBO FUSION TEST
# Weight selected ONLY from validation
# ============================================================

best_alpha = 0.50

# Frozen 50:50 fusion
fusion_test_prob = (
    best_alpha * behavior_lobo_test_prob
    + (1 - best_alpha) * text_test_prob
)

# Default classification threshold
fusion_test_pred = (
    fusion_test_prob >= 0.5
).astype(int)

# Final metrics
final_accuracy = accuracy_score(
    y_lobo_test,
    fusion_test_pred
)

final_precision = precision_score(
    y_lobo_test,
    fusion_test_pred
)

final_recall = recall_score(
    y_lobo_test,
    fusion_test_pred
)

final_f1 = f1_score(
    y_lobo_test,
    fusion_test_pred
)

print("===== FINAL LOBO FUSION RESULT =====")
print(f"Accuracy :  {final_accuracy:.4f} ({final_accuracy*100:.2f}%)")
print(f"Precision:  {final_precision:.4f} ({final_precision*100:.2f}%)")
print(f"Recall   :  {final_recall:.4f} ({final_recall*100:.2f}%)")
print(f"F1-score :  {final_f1:.4f} ({final_f1*100:.2f}%)")

===== FINAL LOBO FUSION RESULT =====
Accuracy :  0.7022 (70.22%)
Precision:  0.8567 (85.67%)
Recall   :  0.7224 (72.24%)
F1-score :  0.7838 (78.38%)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

print("\n===== CONFUSION MATRIX =====")
print(confusion_matrix(y_lobo_test, fusion_test_pred))

print("\n===== CLASSIFICATION REPORT =====")
print(
    classification_report(
        y_lobo_test,
        fusion_test_pred,
        target_names=["Genuine", "Bot"]
    )
)

===== CONFUSION MATRIX =====
[[ 696  387]
 [ 889 2313]]

===== CLASSIFICATION REPORT =====
              precision    recall  f1-score   support

     Genuine       0.44      0.64      0.52      1083
         Bot       0.86      0.72      0.78      3202

    accuracy                           0.70      4285
   macro avg       0.65      0.68      0.65      4285
weighted avg       0.75      0.70      0.72      4285

In [ ]:
# ============================================================
# STEP 3 — MODEL CONFIDENCE ON LOBO VALIDATION
# ============================================================

# Confidence = distance from 0.5
behavior_confidence = np.abs(
    behavior_lobo_val_prob - 0.5
) * 2

text_confidence = np.abs(
    text_val_prob - 0.5
) * 2

print("Behavior confidence:")
print("Mean:", behavior_confidence.mean())
print("Median:", np.median(behavior_confidence))

print("\nText confidence:")
print("Mean:", text_confidence.mean())
print("Median:", np.median(text_confidence))

Behavior confidence:
Mean: 0.98258966
Median: 0.9976958

Text confidence:
Mean: 0.9697907998493608
Median: 0.9991095391156706

In [ ]:
# ============================================================
# STEP 4 — ADAPTIVE CONFIDENCE-BASED FUSION
# ============================================================

# Small epsilon prevents division by zero
epsilon = 1e-8

adaptive_behavior_weight = (
    behavior_confidence /
    (behavior_confidence + text_confidence + epsilon)
)

adaptive_text_weight = 1 - adaptive_behavior_weight

adaptive_val_prob = (
    adaptive_behavior_weight * behavior_lobo_val_prob
    + adaptive_text_weight * text_val_prob
)

adaptive_val_pred = (
    adaptive_val_prob >= 0.5
).astype(int)

print("===== ADAPTIVE FUSION — VALIDATION =====")

print(
    f"Accuracy : "
    f"{accuracy_score(y_lobo_val, adaptive_val_pred):.4f}"
)

print(
    f"Precision: "
    f"{precision_score(y_lobo_val, adaptive_val_pred):.4f}"
)

print(
    f"Recall   : "
    f"{recall_score(y_lobo_val, adaptive_val_pred):.4f}"
)

print(
    f"F1-score : "
    f"{f1_score(y_lobo_val, adaptive_val_pred):.4f}"
)

===== ADAPTIVE FUSION — VALIDATION =====
Accuracy : 0.9993
Precision: 1.0000
Recall   : 0.9992
F1-score : 0.9996

In [ ]:
# ============================================================
# FINAL ADAPTIVE FUSION — UNSEEN FAKE FOLLOWERS TEST
# ============================================================

# Calculate confidence for the unseen test set
behavior_test_confidence = np.abs(
    behavior_lobo_test_prob - 0.5
) * 2

text_test_confidence = np.abs(
    text_test_prob - 0.5
) * 2

# Adaptive weights — NO tuning on test
adaptive_behavior_test_weight = (
    behavior_test_confidence /
    (
        behavior_test_confidence
        + text_test_confidence
        + 1e-8
    )
)

adaptive_text_test_weight = (
    1 - adaptive_behavior_test_weight
)

# Adaptive fusion
adaptive_test_prob = (
    adaptive_behavior_test_weight
    * behavior_lobo_test_prob
    +
    adaptive_text_test_weight
    * text_test_prob
)

# Final prediction
adaptive_test_pred = (
    adaptive_test_prob >= 0.5
).astype(int)

# Metrics
adaptive_accuracy = accuracy_score(
    y_lobo_test,
    adaptive_test_pred
)

adaptive_precision = precision_score(
    y_lobo_test,
    adaptive_test_pred
)

adaptive_recall = recall_score(
    y_lobo_test,
    adaptive_test_pred
)

adaptive_f1 = f1_score(
    y_lobo_test,
    adaptive_test_pred
)

print("===== FINAL ADAPTIVE LOBO TEST =====")
print(
    f"Accuracy :  {adaptive_accuracy:.4f} "
    f"({adaptive_accuracy*100:.2f}%)"
)
print(
    f"Precision:  {adaptive_precision:.4f} "
    f"({adaptive_precision*100:.2f}%)"
)
print(
    f"Recall   :  {adaptive_recall:.4f} "
    f"({adaptive_recall*100:.2f}%)"
)
print(
    f"F1-score :  {adaptive_f1:.4f} "
    f"({adaptive_f1*100:.2f}%)"
)

===== FINAL ADAPTIVE LOBO TEST =====
Accuracy :  0.7022 (70.22%)
Precision:  0.8567 (85.67%)
Recall   :  0.7224 (72.24%)
F1-score :  0.7838 (78.38%)

In [ ]:
print("\n===== CONFUSION MATRIX =====")

print(
    confusion_matrix(
        y_lobo_test,
        adaptive_test_pred
    )
)

print("\n===== CLASSIFICATION REPORT =====")

print(
    classification_report(
        y_lobo_test,
        adaptive_test_pred,
        target_names=["Genuine", "Bot"]
    )
)

===== CONFUSION MATRIX =====
[[ 696  387]
 [ 889 2313]]

===== CLASSIFICATION REPORT =====
              precision    recall  f1-score   support

     Genuine       0.44      0.64      0.52      1083
         Bot       0.86      0.72      0.78      3202

    accuracy                           0.70      4285
   macro avg       0.65      0.68      0.65      4285
weighted avg       0.75      0.70      0.72      4285

In [ ]:
alphas = [
    0.50,
    0.60,
    0.70,
    0.75,
    0.80,
    0.85,
    0.90,
    0.95
]

results = []

for alpha in alphas:

    fusion_val_prob = (
        alpha * behavior_lobo_val_prob
        + (1 - alpha) * text_val_prob
    )

    fusion_val_pred = (
        fusion_val_prob >= 0.5
    ).astype(int)

    results.append({
        "behavior_weight": alpha,
        "text_weight": 1-alpha,
        "accuracy": accuracy_score(
            y_lobo_val,
            fusion_val_pred
        ),
        "precision": precision_score(
            y_lobo_val,
            fusion_val_pred
        ),
        "recall": recall_score(
            y_lobo_val,
            fusion_val_pred
        ),
        "f1": f1_score(
            y_lobo_val,
            fusion_val_pred
        )
    })

pd.DataFrame(results).sort_values(
    "f1",
    ascending=False
)

   behavior_weight  text_weight  accuracy  precision    recall        f1
0             0.50         0.50  0.999285   1.000000  0.999154  0.999577
1             0.60         0.40  0.992852   0.997453  0.994078  0.995763
2             0.70         0.30  0.992852   0.997453  0.994078  0.995763
3             0.75         0.25  0.991422   0.997449  0.992386  0.994911
4             0.80         0.20  0.991422   0.997449  0.992386  0.994911
5             0.85         0.15  0.991422   0.997449  0.992386  0.994911
6             0.90         0.10  0.991422   0.997449  0.992386  0.994911
7             0.95         0.05  0.991422   0.997449  0.992386  0.994911

In [ ]:
# ============================================
# OOF STACKING — CELL 1
# Prepare LOBO training data
# ============================================

from sklearn.model_selection import StratifiedKFold
import numpy as np
import pandas as pd

# Fake Followers will remain completely unseen
unseen_type = "fake_followers"

# Known types = training pool
stack_train = behavior_common[
    behavior_common["account_type"] != unseen_type
].copy()

# Separate features and labels
X_stack = stack_train[behavior_features].copy()
y_stack = stack_train["label"].values

print("Stacking training data:", X_stack.shape)
print("Labels:")
print(pd.Series(y_stack).value_counts().sort_index())

print("\nAccount types:")
print(stack_train["account_type"].value_counts())

Stacking training data: (6995, 15)
Labels:
0    1083
1    5912
Name: count, dtype: int64

Account types:
account_type
social_spambots_2         3457
genuine_accounts          1083
traditional_spambots_1    1000
social_spambots_1          991
social_spambots_3          464
Name: count, dtype: int64

In [ ]:
# ============================================
# OOF STACKING — CELL 2
# Create 5 stratified folds
# ============================================

from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Store fold assignments
fold_numbers = np.zeros(len(stack_train), dtype=int)

for fold, (train_idx, val_idx) in enumerate(
    skf.split(X_stack, y_stack), start=1
):
    fold_numbers[val_idx] = fold

stack_train["oof_fold"] = fold_numbers

print("Fold distribution:")
print(stack_train["oof_fold"].value_counts().sort_index())

print("\nLabel distribution by fold:")
print(
    pd.crosstab(
        stack_train["oof_fold"],
        stack_train["label"]
    )
)

Fold distribution:
oof_fold
1    1399
2    1399
3    1399
4    1399
5    1399
Name: count, dtype: int64

Label distribution by fold:
label       0     1
oof_fold
1         217  1182
2         217  1182
3         217  1182
4         216  1183
5         216  1183

In [ ]:
# ============================================
# OOF STACKING — CELL 3
# Generate Out-of-Fold Behavioral Predictions
# ============================================

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, BatchNormalization, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.utils.class_weight import compute_class_weight

# Store OOF predictions
oof_behavior_prob = np.zeros(len(stack_train))

for fold in range(1, 6):

    print(f"\n========== FOLD {fold} ==========")

    # -----------------------------
    # Split fold data
    # -----------------------------
    train_idx = np.where(fold_numbers != fold)[0]
    val_idx = np.where(fold_numbers == fold)[0]

    X_fold_train = X_stack.iloc[train_idx]
    y_fold_train = y_stack[train_idx]

    X_fold_val = X_stack.iloc[val_idx]
    y_fold_val = y_stack[val_idx]

    # -----------------------------
    # Preprocessing
    # IMPORTANT:
    # Fit ONLY on training fold
    # -----------------------------
    fold_imputer = SimpleImputer(strategy="median")

    X_fold_train_imp = fold_imputer.fit_transform(X_fold_train)
    X_fold_val_imp = fold_imputer.transform(X_fold_val)

    fold_scaler = StandardScaler()

    X_fold_train_scaled = fold_scaler.fit_transform(X_fold_train_imp)
    X_fold_val_scaled = fold_scaler.transform(X_fold_val_imp)

    # -----------------------------
    # Class weights
    # -----------------------------
    classes = np.unique(y_fold_train)

    weights = compute_class_weight(
        class_weight="balanced",
        classes=classes,
        y=y_fold_train
    )

    fold_class_weights = dict(zip(classes, weights))

    # -----------------------------
    # Fresh behavioral model
    # -----------------------------
    fold_model = Sequential([
        Input(shape=(X_fold_train_scaled.shape[1],)),

        Dense(128, activation="relu"),
        BatchNormalization(),
        Dropout(0.25),

        Dense(64, activation="relu"),
        BatchNormalization(),
        Dropout(0.20),

        Dense(32, activation="relu"),
        Dropout(0.10),

        Dense(1, activation="sigmoid")
    ])

    fold_model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )

    # -----------------------------
    # Callbacks
    # -----------------------------
    early_stop = EarlyStopping(
        monitor="val_loss",
        patience=5,
        restore_best_weights=True
    )

    reduce_lr = ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=2,
        min_lr=1e-6
    )

    # -----------------------------
    # Train
    # -----------------------------
    fold_model.fit(
        X_fold_train_scaled,
        y_fold_train,
        validation_split=0.20,
        epochs=50,
        batch_size=32,
        class_weight=fold_class_weights,
        callbacks=[early_stop, reduce_lr],
        verbose=0
    )

    # -----------------------------
    # Predict ONLY held-out fold
    # -----------------------------
    fold_prob = fold_model.predict(
        X_fold_val_scaled,
        verbose=0
    ).flatten()

    oof_behavior_prob[val_idx] = fold_prob

    print(
        f"Fold {fold}: "
        f"train={len(train_idx)}, "
        f"OOF={len(val_idx)}, "
        f"prob range=({fold_prob.min():.4f}, {fold_prob.max():.4f})"
    )

print("\n===================================")
print("OOF behavioral predictions complete")
print("===================================")

print("Total predictions:", len(oof_behavior_prob))
print("Missing predictions:", np.sum(oof_behavior_prob == 0))
print(
    "Probability range:",
    f"{oof_behavior_prob.min():.4f}",
    "to",
    f"{oof_behavior_prob.max():.4f}"
)

========== FOLD 1 ==========
Fold 1: train=5596, OOF=1399, prob range=(0.0001, 0.9984)

========== FOLD 2 ==========
Fold 2: train=5596, OOF=1399, prob range=(0.0005, 1.0000)

========== FOLD 3 ==========
Fold 3: train=5596, OOF=1399, prob range=(0.0005, 0.9612)

========== FOLD 4 ==========
Fold 4: train=5596, OOF=1399, prob range=(0.0000, 0.9535)

========== FOLD 5 ==========
Fold 5: train=5596, OOF=1399, prob range=(0.0002, 0.9414)

===================================
OOF behavioral predictions complete
===================================
Total predictions: 6995
Missing predictions: 0
Probability range: 0.0000 to 1.0000

In [ ]:
print(text_lobo_train.shape)
print(text_lobo_val.shape)
print(text_lobo_test.shape)
print(text_lobo_train.columns.tolist())

(6995, 5)
(1399, 5)
(4285, 5)
['user_id', 'text', 'label', 'account_type', 'tweet_count_used']

In [ ]:
# ============================================
# OOF STACKING — CELL 4
# Prepare matching text folds
# ============================================

# Make a copy so we don't modify the original
text_stack_train = text_lobo_train.copy()

# The rows in text_lobo_train and stack_train should
# represent the same 6,995 accounts.
print("Behavior training accounts:", len(stack_train))
print("Text training accounts:", len(text_stack_train))

# Verify that account IDs match
behavior_ids = set(stack_train["id"])
text_ids = set(text_stack_train["user_id"])

print("\nMatching account IDs:", len(behavior_ids.intersection(text_ids)))
print("Behavior-only IDs:", len(behavior_ids - text_ids))
print("Text-only IDs:", len(text_ids - behavior_ids))

# Create an ID-based mapping from behavioral account -> OOF fold
fold_map = dict(
    zip(stack_train["id"], stack_train["oof_fold"])
)

# Assign the SAME fold to each text account
text_stack_train["oof_fold"] = text_stack_train["user_id"].map(fold_map)

# Check for missing fold assignments
print("\nMissing text fold assignments:",
      text_stack_train["oof_fold"].isna().sum())

print("\nText fold distribution:")
print(
    text_stack_train["oof_fold"]
    .value_counts()
    .sort_index()
)

Behavior training accounts: 6995
Text training accounts: 6995

Matching account IDs: 6995
Behavior-only IDs: 0
Text-only IDs: 0

Missing text fold assignments: 0

Text fold distribution:
oof_fold
1    1399
2    1399
3    1399
4    1399
5    1399
Name: count, dtype: int64

In [ ]:
# ============================================
# OOF STACKING — CELL 5
# Generate out-of-fold TEXT predictions
# ============================================

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV

oof_text_prob = np.zeros(len(text_stack_train))

for fold in range(1, 6):

    print(f"\n========== Fold {fold} ==========")

    # Same fold split as behavioral model
    fold_train = text_stack_train[
        text_stack_train["oof_fold"] != fold
    ].copy()

    fold_val = text_stack_train[
        text_stack_train["oof_fold"] == fold
    ].copy()

    print("Train:", len(fold_train))
    print("OOF:", len(fold_val))

    # -----------------------------
    # WORD TF-IDF
    # -----------------------------
    word_vectorizer = TfidfVectorizer(
        max_features=20000,
        ngram_range=(1, 2),
        min_df=2,
        max_df=0.95,
        sublinear_tf=True
    )

    X_word_train = word_vectorizer.fit_transform(
        fold_train["text"]
    )

    X_word_val = word_vectorizer.transform(
        fold_val["text"]
    )

    # -----------------------------
    # CHARACTER TF-IDF
    # -----------------------------
    char_vectorizer = TfidfVectorizer(
        analyzer="char",
        ngram_range=(3, 5),
        min_df=3,
        max_features=30000,
        sublinear_tf=True
    )

    X_char_train = char_vectorizer.fit_transform(
        fold_train["text"]
    )

    X_char_val = char_vectorizer.transform(
        fold_val["text"]
    )

    # -----------------------------
    # COMBINE WORD + CHARACTER
    # -----------------------------
    from scipy.sparse import hstack

    X_train_combined = hstack([
        X_word_train,
        X_char_train
    ])

    X_val_combined = hstack([
        X_word_val,
        X_char_val
    ])

    print("Combined train shape:", X_train_combined.shape)
    print("Combined OOF shape:", X_val_combined.shape)

    # -----------------------------
    # SVM
    # -----------------------------
    text_svm = LinearSVC(
        C=0.002,
        class_weight={0: 1, 1: 0.5},
        random_state=42
    )

    # Convert SVM scores into probabilities
    calibrated_svm = CalibratedClassifierCV(
        estimator=text_svm,
        method="sigmoid",
        cv=5
    )

    calibrated_svm.fit(
        X_train_combined,
        fold_train["label"].values
    )

    # -----------------------------
    # OOF PROBABILITIES
    # -----------------------------
    fold_prob = calibrated_svm.predict_proba(
        X_val_combined
    )[:, 1]

    # Put predictions back into correct positions
    original_indices = fold_val.index

    for idx, prob in zip(original_indices, fold_prob):
        position = text_stack_train.index.get_loc(idx)
        oof_text_prob[position] = prob

    print(
        f"Probability range: "
        f"{fold_prob.min():.4f} - {fold_prob.max():.4f}"
    )

print("\n================================")
print("OOF TEXT PREDICTIONS COMPLETE")
print("================================")

print("Total predictions:", len(oof_text_prob))
print("Missing predictions:", np.sum(oof_text_prob == 0))
print("Probability range:",
      oof_text_prob.min(),
      "to",
      oof_text_prob.max())

========== Fold 1 ==========
Train: 5596
OOF: 1399
Combined train shape: (5596, 50000)
Combined OOF shape: (1399, 50000)
Probability range: 0.0009 - 1.0000

========== Fold 2 ==========
Train: 5596
OOF: 1399
Combined train shape: (5596, 50000)
Combined OOF shape: (1399, 50000)
Probability range: 0.0020 - 0.9999

========== Fold 3 ==========
Train: 5596
OOF: 1399
Combined train shape: (5596, 50000)
Combined OOF shape: (1399, 50000)
Probability range: 0.0012 - 0.9999

========== Fold 4 ==========
Train: 5596
OOF: 1399
Combined train shape: (5596, 50000)
Combined OOF shape: (1399, 50000)
Probability range: 0.0011 - 1.0000

========== Fold 5 ==========
Train: 5596
OOF: 1399
Combined train shape: (5596, 50000)
Combined OOF shape: (1399, 50000)
Probability range: 0.0010 - 1.0000

================================
OOF TEXT PREDICTIONS COMPLETE
================================
Total predictions: 6995
Missing predictions: 0
Probability range: 0.000889735852881641 to 0.9999816803047414

In [ ]:
# ============================================
# OOF STACKING — CELL 6
# Create meta-features
# ============================================

import numpy as np
import pandas as pd

meta_features = pd.DataFrame({
    "behavior_prob": oof_behavior_prob,
    "text_prob": oof_text_prob
})

# How much the two models disagree
meta_features["prob_difference"] = (
    meta_features["behavior_prob"] -
    meta_features["text_prob"]
)

meta_features["absolute_difference"] = (
    meta_features["prob_difference"].abs()
)

# Confidence = distance from 0.5
meta_features["behavior_confidence"] = (
    np.abs(meta_features["behavior_prob"] - 0.5) * 2
)

meta_features["text_confidence"] = (
    np.abs(meta_features["text_prob"] - 0.5) * 2
)

print("Meta-feature shape:", meta_features.shape)

print("\nFirst 5 rows:")
print(meta_features.head())

print("\nMeta-feature ranges:")
print(meta_features.min())
print(meta_features.max())

print("\nMissing values:")
print(meta_features.isna().sum())

Meta-feature shape: (6995, 6)

First 5 rows:
   behavior_prob  text_prob  prob_difference  absolute_difference  \
0       0.000084   0.103685        -0.103601             0.103601
1       0.169220   0.060591         0.108629             0.108629
2       0.030472   0.178456        -0.147985             0.147985
3       0.068592   0.010098         0.058494             0.058494
4       0.559983   0.292565         0.267419             0.267419

   behavior_confidence  text_confidence
0             0.999833         0.792631
1             0.661561         0.878818
2             0.939057         0.643087
3             0.862816         0.979803
4             0.119967         0.414870

Meta-feature ranges:
behavior_prob          3.669986e-08
text_prob              8.897359e-04
prob_difference       -9.984281e-01
absolute_difference    2.768212e-04
behavior_confidence    9.828210e-04
text_confidence        3.016231e-03
dtype: float64
behavior_prob          1.000000
text_prob              0.999982
prob_difference        0.948650
absolute_difference    0.998428
behavior_confidence    1.000000
text_confidence        0.999963
dtype: float64

Missing values:
behavior_prob          0
text_prob              0
prob_difference        0
absolute_difference    0
behavior_confidence    0
text_confidence        0
dtype: int64

In [ ]:
# ============================================
# OOF STACKING — CELL 7
# Train meta-classifier
# ============================================

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Target labels
y_meta = stack_train["label"].values

# Meta-classifier
meta_model = LogisticRegression(
    C=1.0,
    class_weight="balanced",
    max_iter=1000,
    random_state=42
)

# Train ONLY on OOF predictions
meta_model.fit(
    meta_features,
    y_meta
)

# Predictions on the same OOF meta-data
meta_oof_prob = meta_model.predict_proba(
    meta_features
)[:, 1]

meta_oof_pred = (
    meta_oof_prob >= 0.5
).astype(int)

# Evaluate
print("===== META-MODEL OOF PERFORMANCE =====")

print("Accuracy :", accuracy_score(y_meta, meta_oof_pred))
print("Precision:", precision_score(y_meta, meta_oof_pred))
print("Recall   :", recall_score(y_meta, meta_oof_pred))
print("F1 Score :", f1_score(y_meta, meta_oof_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_meta, meta_oof_pred))

print("\nClassification Report:")
print(
    classification_report(
        y_meta,
        meta_oof_pred,
        target_names=["Genuine", "Bot"]
    )
)

print("\nMeta-model coefficients:")
for feature, coef in zip(
    meta_features.columns,
    meta_model.coef_[0]
):
    print(f"{feature:25s}: {coef:.4f}")

===== META-MODEL OOF PERFORMANCE =====
Accuracy : 0.987276626161544
Precision: 0.9967582323835523
Recall   : 0.9881596752368065
F1 Score : 0.9924403295676548

Confusion Matrix:
[[1064   19]
 [  70 5842]]

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.94      0.98      0.96      1083
         Bot       1.00      0.99      0.99      5912

    accuracy                           0.99      6995
   macro avg       0.97      0.99      0.98      6995
weighted avg       0.99      0.99      0.99      6995


Meta-model coefficients:
behavior_prob            : 8.1486
text_prob                : 4.5122
prob_difference          : 3.6364
absolute_difference      : 0.1978
behavior_confidence      : -0.4136
text_confidence          : 2.3331

In [ ]:
# ============================================
# OOF STACKING — CELL 8
# Generate VALIDATION predictions
# ============================================

print("Preparing validation predictions...")

# ------------------------------------------------
# 1. BEHAVIOR VALIDATION PROBABILITIES
# ------------------------------------------------

# Use the existing LOBO behavioral model
behavior_val_prob_stack = lobo_behavior_nn_v2.predict(
    X_lobo_val,
    verbose=0
).flatten()

print(
    "Behavior validation probabilities:",
    behavior_val_prob_stack.shape
)


# ------------------------------------------------
# 2. TEXT VALIDATION PROBABILITIES
# ------------------------------------------------

# Train the improved text model on ALL 6,995
# known-type training accounts.

word_vectorizer_final = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

char_vectorizer_final = TfidfVectorizer(
    analyzer="char",
    ngram_range=(3, 5),
    min_df=3,
    max_features=30000,
    sublinear_tf=True
)

X_word_train_final = word_vectorizer_final.fit_transform(
    text_lobo_train["text"]
)

X_word_val_final = word_vectorizer_final.transform(
    text_lobo_val["text"]
)

X_char_train_final = char_vectorizer_final.fit_transform(
    text_lobo_train["text"]
)

X_char_val_final = char_vectorizer_final.transform(
    text_lobo_val["text"]
)

X_text_train_final = hstack([
    X_word_train_final,
    X_char_train_final
])

X_text_val_final = hstack([
    X_word_val_final,
    X_char_val_final
])

print(
    "Text train shape:",
    X_text_train_final.shape
)

print(
    "Text validation shape:",
    X_text_val_final.shape
)


# ------------------------------------------------
# 3. TRAIN FINAL CALIBRATED TEXT MODEL
# ------------------------------------------------

text_svm_final = LinearSVC(
    C=0.002,
    class_weight={0: 1, 1: 0.5},
    random_state=42
)

text_calibrated_final = CalibratedClassifierCV(
    estimator=text_svm_final,
    method="sigmoid",
    cv=5
)

text_calibrated_final.fit(
    X_text_train_final,
    text_lobo_train["label"].values
)

text_val_prob_stack = text_calibrated_final.predict_proba(
    X_text_val_final
)[:, 1]

print(
    "Text validation probabilities:",
    text_val_prob_stack.shape
)


# ------------------------------------------------
# 4. CREATE VALIDATION META-FEATURES
# ------------------------------------------------

val_meta_features = pd.DataFrame({
    "behavior_prob": behavior_val_prob_stack,
    "text_prob": text_val_prob_stack
})

val_meta_features["prob_difference"] = (
    val_meta_features["behavior_prob"] -
    val_meta_features["text_prob"]
)

val_meta_features["absolute_difference"] = (
    val_meta_features["prob_difference"].abs()
)

val_meta_features["behavior_confidence"] = (
    np.abs(val_meta_features["behavior_prob"] - 0.5) * 2
)

val_meta_features["text_confidence"] = (
    np.abs(val_meta_features["text_prob"] - 0.5) * 2
)


# ------------------------------------------------
# 5. META-MODEL VALIDATION PREDICTION
# ------------------------------------------------

y_val_stack = text_lobo_val["label"].values

stack_val_prob = meta_model.predict_proba(
    val_meta_features
)[:, 1]

stack_val_pred = (
    stack_val_prob >= 0.5
).astype(int)


# ------------------------------------------------
# 6. EVALUATE
# ------------------------------------------------

print("\n============================================")
print("STACKING VALIDATION PERFORMANCE")
print("============================================")

print(
    "Accuracy :",
    accuracy_score(y_val_stack, stack_val_pred)
)

print(
    "Precision:",
    precision_score(y_val_stack, stack_val_pred)
)

print(
    "Recall   :",
    recall_score(y_val_stack, stack_val_pred)
)

print(
    "F1 Score :",
    f1_score(y_val_stack, stack_val_pred)
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_val_stack,
        stack_val_pred
    )
)

print("\nClassification Report:")
print(
    classification_report(
        y_val_stack,
        stack_val_pred,
        target_names=["Genuine", "Bot"]
    )
)

Preparing validation predictions...
Behavior validation probabilities: (1399,)
Text train shape: (6995, 50000)
Text validation shape: (1399, 50000)
Text validation probabilities: (1399,)

============================================
STACKING VALIDATION PERFORMANCE
============================================
Accuracy : 0.9907076483202287
Precision: 0.9974468085106383
Recall   : 0.9915397631133672
F1 Score : 0.9944845142129826

Confusion Matrix:
[[ 214    3]
 [  10 1172]]

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.96      0.99      0.97       217
         Bot       1.00      0.99      0.99      1182

    accuracy                           0.99      1399
   macro avg       0.98      0.99      0.98      1399
weighted avg       0.99      0.99      0.99      1399

In [ ]:
# ============================================
# OOF STACKING — CELL 9
# FINAL UNSEEN TEST
# ============================================

print("============================================")
print("FINAL UNSEEN FAKE FOLLOWERS TEST")
print("============================================")

# ------------------------------------------------
# 1. BEHAVIOR TEST PROBABILITIES
# ------------------------------------------------

behavior_test_prob_stack = lobo_behavior_nn_v2.predict(
    X_lobo_test,
    verbose=0
).flatten()

print(
    "Behavior test probabilities:",
    behavior_test_prob_stack.shape
)


# ------------------------------------------------
# 2. TEXT TEST PROBABILITIES
# ------------------------------------------------

X_word_test_final = word_vectorizer_final.transform(
    text_lobo_test["text"]
)

X_char_test_final = char_vectorizer_final.transform(
    text_lobo_test["text"]
)

X_text_test_final = hstack([
    X_word_test_final,
    X_char_test_final
])

print(
    "Text test shape:",
    X_text_test_final.shape
)

text_test_prob_stack = text_calibrated_final.predict_proba(
    X_text_test_final
)[:, 1]

print(
    "Text test probabilities:",
    text_test_prob_stack.shape
)


# ------------------------------------------------
# 3. CREATE TEST META-FEATURES
# ------------------------------------------------

test_meta_features = pd.DataFrame({
    "behavior_prob": behavior_test_prob_stack,
    "text_prob": text_test_prob_stack
})

test_meta_features["prob_difference"] = (
    test_meta_features["behavior_prob"] -
    test_meta_features["text_prob"]
)

test_meta_features["absolute_difference"] = (
    test_meta_features["prob_difference"].abs()
)

test_meta_features["behavior_confidence"] = (
    np.abs(test_meta_features["behavior_prob"] - 0.5) * 2
)

test_meta_features["text_confidence"] = (
    np.abs(test_meta_features["text_prob"] - 0.5) * 2
)


# ------------------------------------------------
# 4. FINAL STACKING PREDICTION
# ------------------------------------------------

y_test_stack = text_lobo_test["label"].values

stack_test_prob = meta_model.predict_proba(
    test_meta_features
)[:, 1]

stack_test_pred = (
    stack_test_prob >= 0.5
).astype(int)


# ------------------------------------------------
# 5. FINAL EVALUATION
# ------------------------------------------------

print("\n============================================")
print("FINAL STACKING LOBO PERFORMANCE")
print("============================================")

print(
    "Accuracy :",
    accuracy_score(y_test_stack, stack_test_pred)
)

print(
    "Precision:",
    precision_score(y_test_stack, stack_test_pred)
)

print(
    "Recall   :",
    recall_score(y_test_stack, stack_test_pred)
)

print(
    "F1 Score :",
    f1_score(y_test_stack, stack_test_pred)
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test_stack,
        stack_test_pred
    )
)

print("\nClassification Report:")
print(
    classification_report(
        y_test_stack,
        stack_test_pred,
        target_names=["Genuine", "Bot"]
    )
)


# ------------------------------------------------
# 6. PERFORMANCE BY ACCOUNT TYPE
# ------------------------------------------------

test_results = text_lobo_test[
    ["user_id", "label", "account_type"]
].copy()

test_results["stack_probability"] = stack_test_prob
test_results["stack_prediction"] = stack_test_pred

print("\n============================================")
print("PERFORMANCE BY ACCOUNT TYPE")
print("============================================")

for account_type in test_results["account_type"].unique():

    subset = test_results[
        test_results["account_type"] == account_type
    ]

    acc = accuracy_score(
        subset["label"],
        subset["stack_prediction"]
    )

    print(
        f"{account_type:25s} "
        f"n={len(subset):4d} "
        f"accuracy={acc:.4f}"
    )

============================================
FINAL UNSEEN FAKE FOLLOWERS TEST
============================================
Behavior test probabilities: (4285,)
Text test shape: (4285, 50000)
Text test probabilities: (4285,)

============================================
FINAL STACKING LOBO PERFORMANCE
============================================
Accuracy : 0.6914819136522754
Precision: 0.8455882352941176
Recall   : 0.7183010618363522
F1 Score : 0.7767646065518405

Confusion Matrix:
[[ 663  420]
 [ 902 2300]]

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.42      0.61      0.50      1083
         Bot       0.85      0.72      0.78      3202

    accuracy                           0.69      4285
   macro avg       0.63      0.67      0.64      4285
weighted avg       0.74      0.69      0.71      4285


============================================
PERFORMANCE BY ACCOUNT TYPE
============================================
genuine_accounts          n=1083 accuracy=0.6122
fake_followers            n=3202 accuracy=0.7183

In [ ]:
# ============================================
# CELL 10 — BEHAVIOR-FIRST GATED FUSION
# ============================================

# Use the OOF predictions we already generated
gate_train = pd.DataFrame({
    "behavior_prob": oof_behavior_prob,
    "text_prob": oof_text_prob,
})

# Difference between the two models
gate_train["prob_difference"] = (
    gate_train["behavior_prob"] - gate_train["text_prob"]
)

# How strongly the two models disagree
gate_train["absolute_difference"] = (
    gate_train["prob_difference"].abs()
)

# Confidence of each model
gate_train["behavior_confidence"] = (
    np.abs(gate_train["behavior_prob"] - 0.5) * 2
)

gate_train["text_confidence"] = (
    np.abs(gate_train["text_prob"] - 0.5) * 2
)

# Explicit interaction: when both models agree
gate_train["agreement"] = (
    ((gate_train["behavior_prob"] >= 0.5) ==
     (gate_train["text_prob"] >= 0.5))
).astype(int)

print("Gate training shape:", gate_train.shape)
print()
print(gate_train.head())

Gate training shape: (6995, 7)

   behavior_prob  text_prob  prob_difference  absolute_difference  \
0       0.000084   0.103685        -0.103601             0.103601
1       0.169220   0.060591         0.108629             0.108629
2       0.030472   0.178456        -0.147985             0.147985
3       0.068592   0.010098         0.058494             0.058494
4       0.559983   0.292565         0.267419             0.267419

   behavior_confidence  text_confidence  agreement
0             0.999833         0.792631          1
1             0.661561         0.878818          1
2             0.939057         0.643087          1
3             0.862816         0.979803          1
4             0.119967         0.414870          0

In [ ]:
# ============================================
# CELL 11 — TRAIN GATING MODEL
# ============================================

from sklearn.linear_model import LogisticRegression

gate_model = LogisticRegression(
    C=0.1,
    class_weight="balanced",
    max_iter=1000,
    random_state=42
)

gate_model.fit(gate_train, y_meta)

print("Gating model trained successfully.")
print()
print("Gate coefficients:")
print(
    pd.Series(
        gate_model.coef_[0],
        index=gate_train.columns
    ).sort_values(ascending=False)
)

Gating model trained successfully.

Gate coefficients:
behavior_prob          5.615991
text_prob              2.878942
prob_difference        2.737049
text_confidence        1.049115
agreement              0.727448
absolute_difference   -0.103351
behavior_confidence   -0.541169
dtype: float64

In [ ]:
# ============================================
# CELL 12 — VALIDATION GATED FUSION
# ============================================

gate_val = pd.DataFrame({
    "behavior_prob": behavior_lobo_val_prob,
    "text_prob": text_val_prob,
})

gate_val["prob_difference"] = (
    gate_val["behavior_prob"] - gate_val["text_prob"]
)

gate_val["absolute_difference"] = (
    gate_val["prob_difference"].abs()
)

gate_val["behavior_confidence"] = (
    np.abs(gate_val["behavior_prob"] - 0.5) * 2
)

gate_val["text_confidence"] = (
    np.abs(gate_val["text_prob"] - 0.5) * 2
)

gate_val["agreement"] = (
    ((gate_val["behavior_prob"] >= 0.5) ==
     (gate_val["text_prob"] >= 0.5))
).astype(int)

gate_val_prob = gate_model.predict_proba(gate_val)[:, 1]
gate_val_pred = (gate_val_prob >= 0.5).astype(int)

print("============================================")
print("GATED FUSION VALIDATION")
print("============================================")

print("Accuracy :", accuracy_score(y_lobo_val, gate_val_pred))
print("Precision:", precision_score(y_lobo_val, gate_val_pred))
print("Recall   :", recall_score(y_lobo_val, gate_val_pred))
print("F1 Score :", f1_score(y_lobo_val, gate_val_pred))

print()
print("Confusion Matrix:")
print(confusion_matrix(y_lobo_val, gate_val_pred))

============================================
GATED FUSION VALIDATION
============================================
Accuracy : 0.9914224446032881
Precision: 0.9974489795918368
Recall   : 0.9923857868020305
F1 Score : 0.9949109414758269

Confusion Matrix:
[[ 214    3]
 [   9 1173]]

In [ ]:
# ============================================
# CELL 13 — FINAL GATED LOBO TEST
# ============================================

# Build test gate features
gate_test = pd.DataFrame({
    "behavior_prob": behavior_lobo_test_prob,
    "text_prob": text_test_prob,
})

gate_test["prob_difference"] = (
    gate_test["behavior_prob"] - gate_test["text_prob"]
)

gate_test["absolute_difference"] = (
    gate_test["prob_difference"].abs()
)

gate_test["behavior_confidence"] = (
    np.abs(gate_test["behavior_prob"] - 0.5) * 2
)

gate_test["text_confidence"] = (
    np.abs(gate_test["text_prob"] - 0.5) * 2
)

gate_test["agreement"] = (
    ((gate_test["behavior_prob"] >= 0.5) ==
     (gate_test["text_prob"] >= 0.5))
).astype(int)


# --------------------------------------------
# FINAL PREDICTION
# --------------------------------------------

gate_test_prob = gate_model.predict_proba(gate_test)[:, 1]
gate_test_pred = (gate_test_prob >= 0.5).astype(int)


# --------------------------------------------
# METRICS
# --------------------------------------------

print("============================================")
print("FINAL GATED FUSION — UNSEEN FAKE FOLLOWERS")
print("============================================")

print("Accuracy :", accuracy_score(y_lobo_test, gate_test_pred))
print("Precision:", precision_score(y_lobo_test, gate_test_pred))
print("Recall   :", recall_score(y_lobo_test, gate_test_pred))
print("F1 Score :", f1_score(y_lobo_test, gate_test_pred))

print()
print("Confusion Matrix:")
print(confusion_matrix(y_lobo_test, gate_test_pred))

print()
print("Classification Report:")
print(
    classification_report(
        y_lobo_test,
        gate_test_pred,
        target_names=["Genuine", "Bot"]
    )
)


# --------------------------------------------
# ACCOUNT-TYPE PERFORMANCE
# --------------------------------------------

print()
print("============================================")
print("PERFORMANCE BY ACCOUNT TYPE")
print("============================================")

test_results = lobo_test.copy()
test_results["prediction"] = gate_test_pred

for account_type in test_results["account_type"].unique():

    subset = test_results[
        test_results["account_type"] == account_type
    ]

    acc = accuracy_score(
        subset["label"],
        subset["prediction"]
    )

    print(
        f"{account_type:25s} "
        f"n={len(subset):4d} "
        f"accuracy={acc:.4f}"
    )

============================================
FINAL GATED FUSION — UNSEEN FAKE FOLLOWERS
============================================
Accuracy : 0.6896149358226371
Precision: 0.8413566739606126
Recall   : 0.7204871955028107
F1 Score : 0.7762449528936743

Confusion Matrix:
[[ 648  435]
 [ 895 2307]]

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.42      0.60      0.49      1083
         Bot       0.84      0.72      0.78      3202

    accuracy                           0.69      4285
   macro avg       0.63      0.66      0.63      4285
weighted avg       0.73      0.69      0.70      4285


============================================
PERFORMANCE BY ACCOUNT TYPE
============================================
genuine_accounts          n=1083 accuracy=0.2899
fake_followers            n=3202 accuracy=0.6162

In [ ]:
# ============================================
# CELL 14 — BEHAVIORAL MODEL COMPARISON
# ============================================

from sklearn.ensemble import (
    RandomForestClassifier,
    ExtraTreesClassifier,
    GradientBoostingClassifier,
    HistGradientBoostingClassifier
)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# Use the existing LOBO train/validation split
X_train_ml = X_lobo_train_final
y_train_ml = y_lobo_train_final

X_val_ml = X_lobo_val
y_val_ml = y_lobo_val

print("Training shape :", X_train_ml.shape)
print("Validation shape:", X_val_ml.shape)

Training shape : (5596, 15)
Validation shape: (1399, 15)

In [ ]:
# ============================================
# CELL 15 — CLASSICAL BEHAVIOR MODELS
# ============================================

models = {

    "Random Forest": RandomForestClassifier(
        n_estimators=500,
        max_features="sqrt",
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ),

    "Extra Trees": ExtraTreesClassifier(
        n_estimators=500,
        max_features="sqrt",
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    ),

    "Gradient Boosting": GradientBoostingClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=3,
        random_state=42
    ),

    "Hist Gradient Boosting": HistGradientBoostingClassifier(
        max_iter=300,
        learning_rate=0.05,
        max_leaf_nodes=31,
        random_state=42
    )
}

results = []

for name, model in models.items():

    print(f"\nTraining {name}...")

    model.fit(X_train_ml, y_train_ml)

    val_pred = model.predict(X_val_ml)

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_val_ml, val_pred),
        "Precision": precision_score(y_val_ml, val_pred),
        "Recall": recall_score(y_val_ml, val_pred),
        "F1": f1_score(y_val_ml, val_pred)
    })

comparison_df = pd.DataFrame(results)

print("\n============================================")
print("BEHAVIORAL MODEL COMPARISON — VALIDATION")
print("============================================")

print(
    comparison_df
    .sort_values("F1", ascending=False)
    .to_string(index=False)
)

Training Random Forest...

Training Extra Trees...

Training Gradient Boosting...

Training Hist Gradient Boosting...

============================================
BEHAVIORAL MODEL COMPARISON — VALIDATION
============================================
                 Model  Accuracy  Precision   Recall       F1
     Gradient Boosting  0.992137   0.996607 0.994078 0.995341
Hist Gradient Boosting  0.991422   0.995763 0.994078 0.994920
           Extra Trees  0.990708   0.996602 0.992386 0.994489
         Random Forest  0.989993   0.996599 0.991540 0.994063

In [ ]:
# ============================================
# CELL 16 — FEATURE ABLATION SETUP
# ============================================

feature_groups = {

    "All 15 Features": [
        "statuses_count",
        "followers_count",
        "friends_count",
        "favourites_count",
        "listed_count",
        "account_age_days",
        "statuses_per_day",
        "followers_friends_ratio",
        "friends_followers_ratio",
        "favorites_per_status",
        "log_statuses_count",
        "log_followers_count",
        "log_friends_count",
        "log_favourites_count",
        "log_listed_count"
    ],

    "Raw Profile Features": [
        "statuses_count",
        "followers_count",
        "friends_count",
        "favourites_count",
        "listed_count",
        "account_age_days"
    ],

    "Activity Features": [
        "statuses_count",
        "account_age_days",
        "statuses_per_day",
        "favourites_count",
        "favorites_per_status"
    ],

    "Ratio + Log Features": [
        "followers_friends_ratio",
        "friends_followers_ratio",
        "favorites_per_status",
        "log_statuses_count",
        "log_followers_count",
        "log_friends_count",
        "log_favourites_count",
        "log_listed_count"
    ]
}

for name, features in feature_groups.items():
    print(f"{name}: {len(features)} features")

All 15 Features: 15 features
Raw Profile Features: 6 features
Activity Features: 5 features
Ratio + Log Features: 8 features

In [ ]:
print("X_lobo_train_final:", X_lobo_train_final.shape)
print("X_lobo_val:", X_lobo_val.shape)

print("lobo_train exists:", "lobo_train" in globals())
print("lobo_val exists:", "lobo_val" in globals())

X_lobo_train_final: (5596, 15)
X_lobo_val: (1399, 15)
lobo_train exists: True
lobo_val exists: False

In [ ]:
print("lobo_train shape:", lobo_train.shape)
print("lobo_train columns:")
print(lobo_train.columns.tolist())

lobo_train shape: (6995, 20)
lobo_train columns:
['id', 'account_type', 'label', 'statuses_count', 'followers_count', 'friends_count', 'favourites_count', 'listed_count', 'created_at', 'updated', 'account_age_days', 'statuses_per_day', 'followers_friends_ratio', 'friends_followers_ratio', 'favorites_per_status', 'log_statuses_count', 'log_followers_count', 'log_friends_count', 'log_favourites_count', 'log_listed_count']

In [ ]:
print("lobo_train:", lobo_train.shape)
print("X_lobo_train_final:", X_lobo_train_final.shape)
print("X_lobo_val:", X_lobo_val.shape)

print("\nVariables available:")
for name in ["y_lobo_train", "y_lobo_val", "lobo_train_idx", "lobo_val_idx"]:
    print(name, "exists:", name in globals())

lobo_train: (6995, 20)
X_lobo_train_final: (5596, 15)
X_lobo_val: (1399, 15)

Variables available:
y_lobo_train exists: True
y_lobo_val exists: True
lobo_train_idx exists: False
lobo_val_idx exists: False

In [ ]:
lobo_train_part, lobo_val = train_test_split(
    lobo_train,
    test_size=0.20,
    random_state=42,
    stratify=lobo_train["label"]
)

print("Training:", lobo_train_part.shape)
print("Validation:", lobo_val.shape)

print("\nValidation labels:")
print(lobo_val["label"].value_counts().sort_index())

Training: (5596, 20)
Validation: (1399, 20)

Validation labels:
label
0     217
1    1182
Name: count, dtype: int64

In [ ]:
# ============================================
# FEATURE ABLATION EXPERIMENT
# ============================================

ablation_results = []

for group_name, features in feature_groups.items():

    print(f"\nTraining: {group_name}")
    print(f"Number of features: {len(features)}")

    # ----------------------------------------
    # 1. Select RAW features
    # ----------------------------------------

    X_train_group = lobo_train_part[features].copy()
    X_val_group = lobo_val[features].copy()

    # ----------------------------------------
    # 2. Imputation
    # Fit ONLY on training data
    # ----------------------------------------

    group_imputer = SimpleImputer(strategy="median")

    X_train_imp = group_imputer.fit_transform(
        X_train_group
    )

    X_val_imp = group_imputer.transform(
        X_val_group
    )

    # ----------------------------------------
    # 3. Scaling
    # Fit ONLY on training data
    # ----------------------------------------

    group_scaler = StandardScaler()

    X_train_scaled = group_scaler.fit_transform(
        X_train_imp
    )

    X_val_scaled = group_scaler.transform(
        X_val_imp
    )

    # ----------------------------------------
    # 4. Class weights
    # ----------------------------------------

    classes = np.unique(y_lobo_train)

    weights = compute_class_weight(
        class_weight="balanced",
        classes=classes,
        y=y_lobo_train
    )

    class_weights_group = dict(
        zip(classes, weights)
    )

    # ----------------------------------------
    # 5. Neural Network
    # ----------------------------------------

    model = Sequential([
        Input(shape=(len(features),)),

        Dense(128, activation="relu"),
        BatchNormalization(),
        Dropout(0.25),

        Dense(64, activation="relu"),
        BatchNormalization(),
        Dropout(0.20),

        Dense(32, activation="relu"),
        Dropout(0.10),

        Dense(1, activation="sigmoid")
    ])

    model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )

    # ----------------------------------------
    # 6. Callbacks
    # ----------------------------------------

    early_stop = EarlyStopping(
        monitor="val_loss",
        patience=5,
        restore_best_weights=True
    )

    reduce_lr = ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=2,
        min_lr=1e-6
    )

    # ----------------------------------------
    # 7. Train
    # ----------------------------------------

    model.fit(
        X_train_scaled,
        y_lobo_train,
        validation_data=(
            X_val_scaled,
            y_lobo_val
        ),
        epochs=50,
        batch_size=32,
        class_weight=class_weights_group,
        callbacks=[
            early_stop,
            reduce_lr
        ],
        verbose=0
    )

    # ----------------------------------------
    # 8. Validation prediction
    # ----------------------------------------

    val_prob = model.predict(
        X_val_scaled,
        verbose=0
    ).flatten()

    val_pred = (
        val_prob >= 0.5
    ).astype(int)

    # ----------------------------------------
    # 9. Metrics
    # ----------------------------------------

    accuracy = accuracy_score(
        y_lobo_val,
        val_pred
    )

    precision = precision_score(
        y_lobo_val,
        val_pred,
        zero_division=0
    )

    recall = recall_score(
        y_lobo_val,
        val_pred,
        zero_division=0
    )

    f1 = f1_score(
        y_lobo_val,
        val_pred,
        zero_division=0
    )

    # ----------------------------------------
    # 10. Save results
    # ----------------------------------------

    ablation_results.append({
        "Feature Group": group_name,
        "Features": len(features),
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1": f1
    })

    print(
        f"Accuracy:  {accuracy:.4f}\n"
        f"Precision: {precision:.4f}\n"
        f"Recall:    {recall:.4f}\n"
        f"F1:        {f1:.4f}"
    )


# ============================================
# FINAL ABLATION TABLE
# ============================================

ablation_df = pd.DataFrame(ablation_results)

ablation_df = ablation_df.sort_values(
    "F1",
    ascending=False
).reset_index(drop=True)

print("\n" + "=" * 70)
print("FEATURE ABLATION RESULTS")
print("=" * 70)

print(
    ablation_df.to_string(
        index=False,
        formatters={
            "Accuracy": "{:.4%}".format,
            "Precision": "{:.4%}".format,
            "Recall": "{:.4%}".format,
            "F1": "{:.4%}".format
        }
    )
)

Training: All 15 Features
Number of features: 15
Accuracy:  0.9893
Precision: 0.9983
Recall:    0.9890
F1:        0.9936

Training: Raw Profile Features
Number of features: 6
Accuracy:  0.9771
Precision: 0.9940
Recall:    0.9788
F1:        0.9864

Training: Activity Features
Number of features: 5
Accuracy:  0.9836
Precision: 0.9974
Recall:    0.9831
F1:        0.9902

Training: Ratio + Log Features
Number of features: 8
Accuracy:  0.9886
Precision: 0.9983
Recall:    0.9882
F1:        0.9932

======================================================================
FEATURE ABLATION RESULTS
======================================================================
       Feature Group  Features Accuracy Precision   Recall       F1
     All 15 Features        15 98.9278%  99.8292% 98.9002% 99.3625%
Ratio + Log Features         8 98.8563%  99.8291% 98.8156% 99.3197%
   Activity Features         5 98.3560%  99.7425% 98.3080% 99.0200%
Raw Profile Features         6 97.7127%  99.3986% 97.8849% 98.6360%

In [ ]:
# STEP 1: Check where the behavioral model is uncertain
# We will let the text model influence the prediction ONLY in this uncertain region.

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Make sure everything is aligned
val_df = pd.DataFrame({
    "behavior_prob": behavior_lobo_val_prob,
    "text_prob": text_val_prob,
    "true_label": y_lobo_val
}).reset_index(drop=True)

# Behavioral uncertainty
val_df["behavior_uncertainty"] = np.abs(val_df["behavior_prob"] - 0.5)

print("Behavior probability range:",
      val_df["behavior_prob"].min(),
      val_df["behavior_prob"].max())

print("\nBehavior uncertainty range:",
      val_df["behavior_uncertainty"].min(),
      val_df["behavior_uncertainty"].max())

Behavior probability range: 2.552429e-06 0.99999905

Behavior uncertainty range: 0.011292815 0.49999905

In [ ]:
# STEP 2: Try different uncertainty bands
# Text is used only when behavior probability is close to 0.5.

thresholds = [0.02, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30]

results = []

for t in thresholds:

    behavior_pred = (val_df["behavior_prob"] >= 0.5).astype(int)
    text_pred = (val_df["text_prob"] >= 0.5).astype(int)

    # Start with behavior prediction
    final_pred = behavior_pred.copy()

    # Text gets a vote only when behavior is uncertain
    uncertain = val_df["behavior_uncertainty"] < t

    final_pred[uncertain] = text_pred[uncertain]

    results.append({
        "uncertainty_threshold": t,
        "uncertain_cases": uncertain.sum(),
        "uncertain_percentage": uncertain.mean() * 100,
        "accuracy": accuracy_score(val_df["true_label"], final_pred),
        "precision": precision_score(val_df["true_label"], final_pred),
        "recall": recall_score(val_df["true_label"], final_pred),
        "f1": f1_score(val_df["true_label"], final_pred)
    })

conditional_results = pd.DataFrame(results)

conditional_results.sort_values(
    "f1",
    ascending=False
)

,uncertainty_threshold,uncertain_cases,uncertain_percentage,accuracy,precision,recall,f1
6,0.30,18,1.286633,0.992852,0.997453,0.994078,0.995763
5,0.25,9,0.643317,0.992852,0.997453,0.994078,0.995763
4,0.20,5,0.357398,0.992852,0.997453,0.994078,0.995763
2,0.10,2,0.142959,0.991422,0.997449,0.992386,0.994911
1,0.05,2,0.142959,0.991422,0.997449,0.992386,0.994911
0,0.02,1,0.071480,0.991422,0.997449,0.992386,0.994911
3,0.15,3,0.214439,0.991422,0.997449,0.992386,0.994911

In [ ]:
# STEP 2: Analyze behavior/text disagreement on validation

val_analysis = pd.DataFrame({
    "behavior_prob": behavior_lobo_val_prob,
    "text_prob": text_val_prob,
    "true_label": y_lobo_val
}).reset_index(drop=True)

val_analysis["behavior_pred"] = (
    val_analysis["behavior_prob"] >= 0.5
).astype(int)

val_analysis["text_pred"] = (
    val_analysis["text_prob"] >= 0.5
).astype(int)

val_analysis["behavior_correct"] = (
    val_analysis["behavior_pred"] == val_analysis["true_label"]
)

val_analysis["text_correct"] = (
    val_analysis["text_pred"] == val_analysis["true_label"]
)

val_analysis["disagreement"] = (
    val_analysis["behavior_pred"] != val_analysis["text_pred"]
)

print("Total validation samples:", len(val_analysis))

print("Behavior correct:",
      val_analysis["behavior_correct"].sum())

print("Text correct:",
      val_analysis["text_correct"].sum())

print("Disagreements:",
      val_analysis["disagreement"].sum())

print("\nAmong disagreements:")
print(
    val_analysis[val_analysis["disagreement"]][
        ["behavior_prob", "text_prob", "true_label",
         "behavior_pred", "text_pred",
         "behavior_correct", "text_correct"]
    ].to_string(index=False)
)

Total validation samples: 1399
Behavior correct: 1387
Text correct: 1385
Disagreements: 26

Among disagreements:
 behavior_prob  text_prob  true_label  behavior_pred  text_pred  behavior_correct  text_correct
      0.012684   0.986004           1              0          1             False          True
      0.999215   0.433379           1              1          0              True         False
      0.839020   0.291424           1              1          0              True         False
      0.999908   0.042099           1              1          0              True         False
      0.026543   0.999111           1              0          1             False          True
      0.003417   0.999695           1              0          1             False          True
      0.007441   0.877166           0              0          1              True         False
      0.009570   0.706020           0              0          1              True         False
      0.049667   0.999692           1              0          1             False          True
      0.999747   0.480864           1              1          0              True         False
      0.052449   0.999985           1              0          1             False          True
      0.019719   0.591274           0              0          1              True         False
      0.323579   0.999974           1              0          1             False          True
      0.882909   0.003598           0              1          0             False          True
      0.006595   0.997631           1              0          1             False          True
      0.331840   0.987135           1              0          1             False          True
      0.004803   0.881899           0              0          1              True         False
      0.005705   0.999417           1              0          1             False          True
      0.992323   0.377308           1              1          0              True         False
      0.939881   0.097086           1              1          0              True         False
      0.882125   0.018705           0              1          0             False          True
      0.999995   0.042936           1              1          0              True         False
      0.978351   0.132650           1              1          0              True         False
      0.991042   0.259919           1              1          0              True         False
      0.010527   0.573540           0              0          1              True         False
      0.963845   0.032781           0              1          0             False          True

In [ ]:
# STEP 3: Who wins when the two models disagree?

disagreements = val_analysis[val_analysis["disagreement"]]

print("Disagreement count:", len(disagreements))

print("\nBehavior correct on disagreements:",
      disagreements["behavior_correct"].sum())

print("Text correct on disagreements:",
      disagreements["text_correct"].sum())

print("\nBehavior accuracy when models disagree:",
      disagreements["behavior_correct"].mean())

print("Text accuracy when models disagree:",
      disagreements["text_correct"].mean())

Disagreement count: 26

Behavior correct on disagreements: 14
Text correct on disagreements: 12

Behavior accuracy when models disagree: 0.5384615384615384
Text accuracy when models disagree: 0.46153846153846156

In [ ]:
# STEP 4: Analyze disagreement patterns

dis = val_analysis[val_analysis["disagreement"]].copy()

# Distance from decision boundary
dis["behavior_strength"] = np.abs(dis["behavior_prob"] - 0.5)
dis["text_strength"] = np.abs(dis["text_prob"] - 0.5)

# Which model is more confident?
dis["behavior_more_confident"] = (
    dis["behavior_strength"] > dis["text_strength"]
)

print("Total disagreements:", len(dis))

print("\nWhen BEHAVIOR is more confident:")
print(
    dis[dis["behavior_more_confident"]][
        ["behavior_prob", "text_prob", "true_label",
         "behavior_correct", "text_correct"]
    ].to_string(index=False)
)

print("\nWhen TEXT is more confident:")
print(
    dis[~dis["behavior_more_confident"]][
        ["behavior_prob", "text_prob", "true_label",
         "behavior_correct", "text_correct"]
    ].to_string(index=False)
)

Total disagreements: 26

When BEHAVIOR is more confident:
 behavior_prob  text_prob  true_label  behavior_correct  text_correct
      0.012684   0.986004           1             False          True
      0.999215   0.433379           1              True         False
      0.839020   0.291424           1              True         False
      0.999908   0.042099           1              True         False
      0.007441   0.877166           0              True         False
      0.009570   0.706020           0              True         False
      0.999747   0.480864           1              True         False
      0.019719   0.591274           0              True         False
      0.004803   0.881899           0              True         False
      0.992323   0.377308           1              True         False
      0.939881   0.097086           1              True         False
      0.999995   0.042936           1              True         False
      0.978351   0.132650           1              True         False
      0.991042   0.259919           1              True         False
      0.010527   0.573540           0              True         False

When TEXT is more confident:
 behavior_prob  text_prob  true_label  behavior_correct  text_correct
      0.026543   0.999111           1             False          True
      0.003417   0.999695           1             False          True
      0.049667   0.999692           1             False          True
      0.052449   0.999985           1             False          True
      0.323579   0.999974           1             False          True
      0.882909   0.003598           0             False          True
      0.006595   0.997631           1             False          True
      0.331840   0.987135           1             False          True
      0.005705   0.999417           1             False          True
      0.882125   0.018705           0             False          True
      0.963845   0.032781           0             False          True

In [ ]:
# STEP 5: Compare the models based on confidence dominance

behavior_conf_cases = dis[dis["behavior_more_confident"]]
text_conf_cases = dis[~dis["behavior_more_confident"]]

print("BEHAVIOR more confident:", len(behavior_conf_cases))

if len(behavior_conf_cases) > 0:
    print(
        "Behavior accuracy:",
        behavior_conf_cases["behavior_correct"].mean()
    )
    print(
        "Text accuracy:",
        behavior_conf_cases["text_correct"].mean()
    )

print("\nTEXT more confident:", len(text_conf_cases))

if len(text_conf_cases) > 0:
    print(
        "Behavior accuracy:",
        text_conf_cases["behavior_correct"].mean()
    )
    print(
        "Text accuracy:",
        text_conf_cases["text_correct"].mean()
    )

BEHAVIOR more confident: 15
Behavior accuracy: 0.9333333333333333
Text accuracy: 0.06666666666666667

TEXT more confident: 11
Behavior accuracy: 0.0
Text accuracy: 1.0

In [ ]:
# STEP 1 — Compare behavioral feature distributions across account types

import pandas as pd
import numpy as np

feature_groups = {
    "Genuine": "genuine_accounts",
    "Social Spambot 1": "social_spambots_1",
    "Social Spambot 2": "social_spambots_2",
    "Social Spambot 3": "social_spambots_3",
    "Traditional Spambot 1": "traditional_spambots_1",
    "Fake Followers": "fake_followers"
}

behavior_features = [
    "statuses_count",
    "followers_count",
    "friends_count",
    "favourites_count",
    "listed_count",
    "account_age_days",
    "statuses_per_day",
    "followers_friends_ratio",
    "friends_followers_ratio",
    "favorites_per_status",
    "log_statuses_count",
    "log_followers_count",
    "log_friends_count",
    "log_favourites_count",
    "log_listed_count"
]

distribution_summary = []

for feature in behavior_features:

    for group_name, group_type in feature_groups.items():

        subset = behavior_common[
            behavior_common["account_type"] == group_type
        ][feature].dropna()

        distribution_summary.append({
            "feature": feature,
            "group": group_name,
            "count": len(subset),
            "mean": subset.mean(),
            "median": subset.median(),
            "std": subset.std(),
            "min": subset.min(),
            "max": subset.max()
        })

distribution_summary = pd.DataFrame(distribution_summary)

distribution_summary

,feature,group,count,mean,median,std,min,max
0,statuses_count,Genuine,1083,19951.971376,8272.000000,33654.668179,3.0,333504.000000
1,statuses_count,Social Spambot 1,991,1111.998991,138.000000,5740.506607,5.0,106283.000000
2,statuses_count,Social Spambot 2,3457,251.368817,56.000000,4176.274464,20.0,184661.000000
3,statuses_count,Social Spambot 3,464,11636.073276,11647.500000,11592.317019,47.0,214410.000000
4,statuses_count,Traditional Spambot 1,1000,220.829000,16.000000,1402.942102,1.0,34402.000000
...,...,...,...,...,...,...,...,...
85,log_listed_count,Social Spambot 1,991,0.743204,0.000000,1.012449,0.0,6.487684
86,log_listed_count,Social Spambot 2,3457,0.090052,0.000000,0.298994,0.0,5.347108
87,log_listed_count,Social Spambot 3,464,1.697601,1.700599,0.952364,0.0,7.578145
88,log_listed_count,Traditional Spambot 1,1000,0.876811,0.693147,1.007442,0.0,7.958227
89,log_listed_count,Fake Followers,3202,0.029370,0.000000,0.194805,0.0,3.496508

In [ ]:
# STEP 2 — Median comparison

median_table = distribution_summary.pivot(
    index="feature",
    columns="group",
    values="median"
)

median_table

group,Fake Followers,Genuine,Social Spambot 1,Social Spambot 2,Social Spambot 3,Traditional Spambot 1
feature,,,,,,
account_age_days,352.042743,1500.867384,1518.417211,749.024329,1465.066331,NaN
favorites_per_status,0.000000,0.214559,0.000000,0.000000,0.000080,0.000000
favourites_count,0.000000,1492.000000,0.000000,0.000000,1.000000,0.000000
followers_count,13.000000,407.000000,234.000000,5.000000,825.000000,198.500000
followers_friends_ratio,0.042164,1.052632,0.909966,0.121951,0.533331,0.266771
friends_count,294.500000,366.000000,313.000000,39.000000,1596.000000,956.000000
friends_followers_ratio,23.454545,0.950000,1.089368,8.200000,1.869822,3.748538
listed_count,0.000000,3.000000,0.000000,0.000000,4.500000,1.000000
log_favourites_count,0.000000,7.308543,0.000000,0.000000,0.693147,0.000000
log_followers_count,2.639057,6.011267,5.459586,1.791759,6.716594,5.295811
log_friends_count,5.688667,5.905362,5.749393,3.688879,7.375882,6.863798
log_listed_count,0.000000,1.386294,0.000000,0.000000,1.700599,0.693147
log_statuses_count,3.218876,9.020752,4.934474,4.043051,9.362933,2.833213
statuses_count,24.000000,8272.000000,138.000000,56.000000,11647.500000,16.000000
statuses_per_day,0.125993,5.216101,0.092090,0.075341,7.011587,NaN

In [ ]:
# STEP 3 — Mean comparison

mean_table = distribution_summary.pivot(
    index="feature",
    columns="group",
    values="mean"
)

mean_table

group,Fake Followers,Genuine,Social Spambot 1,Social Spambot 2,Social Spambot 3,Traditional Spambot 1
feature,,,,,,
account_age_days,394.012155,1739.292883,1438.849511,753.092103,1591.167775,NaN
favorites_per_status,0.025355,0.539608,0.010056,0.001203,0.003575,0.009052
favourites_count,4.104622,4676.109880,158.171544,9.523575,17.650862,4.328000
followers_count,18.204560,2271.072022,1784.907164,23.378073,2489.060345,637.297000
followers_friends_ratio,0.047819,4.411332,6.437135,0.149604,11.861671,0.352695
friends_count,363.299813,676.939982,1853.768920,54.236621,1880.282328,1326.542000
friends_followers_ratio,38.504456,1.364918,1.251600,10.525440,2.067000,6.034870
listed_count,0.075578,32.500462,3.954591,0.298235,12.653017,7.900000
log_favourites_count,0.193090,6.968888,0.264808,0.037981,0.642085,0.156572
log_followers_count,2.520812,6.061163,4.360427,1.769602,6.625983,5.488808
log_friends_count,5.709258,5.931288,4.369513,3.741119,7.140783,6.871679
log_listed_count,0.029370,1.792142,0.743204,0.090052,1.697601,0.876811
log_statuses_count,3.230434,8.831857,5.364251,4.061731,9.093860,2.847610
statuses_count,74.730169,19951.971376,1111.998991,251.368817,11636.073276,220.829000
statuses_per_day,0.159804,11.889444,0.765029,0.163650,7.286620,NaN

In [ ]:
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

# Known types = everything except Fake Followers
known_accounts = behavior_common[
    behavior_common["account_type"] != "fake_followers"
].copy()

fake_accounts = behavior_common[
    behavior_common["account_type"] == "fake_followers"
].copy()

shift_results = []

for feature in behavior_features:

    known_values = known_accounts[feature].dropna()
    fake_values = fake_accounts[feature].dropna()

    # Standardized difference using known-account distribution
    known_mean = known_values.mean()
    known_std = known_values.std()

    fake_mean = fake_values.mean()

    if known_std > 0:
        standardized_shift = abs(fake_mean - known_mean) / known_std
    else:
        standardized_shift = np.nan

    shift_results.append({
        "feature": feature,
        "known_mean": known_mean,
        "fake_followers_mean": fake_mean,
        "known_std": known_std,
        "standardized_shift": standardized_shift
    })

shift_results = pd.DataFrame(shift_results)

shift_results.sort_values(
    "standardized_shift",
    ascending=False
)

,feature,known_mean,fake_followers_mean,known_std,standardized_shift
8,friends_followers_ratio,6.804868,38.504456,7.595227,4.173620
5,account_age_days,1109.473779,394.012155,543.316873,1.316840
10,log_statuses_count,5.145023,3.230434,2.440132,0.784625
14,log_listed_count,0.665220,0.029370,1.096367,0.579960
11,log_followers_count,3.654925,2.520812,2.551170,0.444546
12,log_friends_count,4.842291,5.709258,2.033916,0.426256
13,log_favourites_count,1.200219,0.193090,2.687906,0.374689
6,statuses_per_day,2.932634,0.159804,10.095805,0.274652
0,statuses_count,4174.256612,74.730169,15845.958927,0.258711
3,favourites_count,752.882916,4.104622,4439.077396,0.168679
2,friends_count,708.606147,363.299813,2052.195499,0.168262
9,favorites_per_status,0.087095,0.025355,0.552605,0.111726
4,listed_count,7.708220,0.075578,89.322578,0.085450
1,followers_count,872.259185,18.204560,13370.368004,0.063877
7,followers_friends_ratio,2.273939,0.047819,72.163446,0.030848

In [ ]:
# Show the strongest distribution shifts

print(
    shift_results[
        ["feature", "standardized_shift"]
    ].sort_values(
        "standardized_shift",
        ascending=False
    ).to_string(index=False)
)

                feature  standardized_shift
friends_followers_ratio            4.173620
       account_age_days            1.316840
     log_statuses_count            0.784625
       log_listed_count            0.579960
    log_followers_count            0.444546
      log_friends_count            0.426256
   log_favourites_count            0.374689
       statuses_per_day            0.274652
         statuses_count            0.258711
       favourites_count            0.168679
          friends_count            0.168262
   favorites_per_status            0.111726
           listed_count            0.085450
        followers_count            0.063877
followers_friends_ratio            0.030848

In [ ]:
from scipy.stats import ks_2samp

ks_results = []

for feature in behavior_features:

    known_values = known_accounts[feature].dropna()
    fake_values = fake_accounts[feature].dropna()

    if len(known_values) > 0 and len(fake_values) > 0:

        ks_stat, p_value = ks_2samp(
            known_values,
            fake_values
        )

        ks_results.append({
            "feature": feature,
            "ks_statistic": ks_stat,
            "p_value": p_value
        })

ks_results = pd.DataFrame(ks_results)

ks_results = ks_results.sort_values(
    "ks_statistic",
    ascending=False
)

ks_results

                    feature  ks_statistic        p_value
5          account_age_days      0.838141   0.000000e+00
8   friends_followers_ratio      0.809482   0.000000e+00
7   followers_friends_ratio      0.802894   0.000000e+00
0            statuses_count      0.592298  2.816174e-321
10       log_statuses_count      0.592298  2.816174e-321
12        log_friends_count      0.536751  4.308252e-321
2             friends_count      0.536751  4.308252e-321
11      log_followers_count      0.403225  4.156080e-320
1           followers_count      0.403225  4.156080e-320
4              listed_count      0.356581  8.388723e-249
14         log_listed_count      0.356581  8.388723e-249
6          statuses_per_day      0.262752  3.367832e-127
3          favourites_count      0.146648   1.166156e-41
13     log_favourites_count      0.146648   1.166156e-41
9      favorites_per_status      0.117299   9.329903e-27

In [ ]:
# Show the strongest distribution shifts

print(
    ks_results[
        ["feature", "ks_statistic", "p_value"]
    ].to_string(index=False)
)

                feature  ks_statistic       p_value
       account_age_days      0.838141  0.000000e+00
friends_followers_ratio      0.809482  0.000000e+00
followers_friends_ratio      0.802894  0.000000e+00
         statuses_count      0.592298 2.816174e-321
     log_statuses_count      0.592298 2.816174e-321
      log_friends_count      0.536751 4.308252e-321
          friends_count      0.536751 4.308252e-321
    log_followers_count      0.403225 4.156080e-320
        followers_count      0.403225 4.156080e-320
           listed_count      0.356581 8.388723e-249
       log_listed_count      0.356581 8.388723e-249
       statuses_per_day      0.262752 3.367832e-127
       favourites_count      0.146648  1.166156e-41
   log_favourites_count      0.146648  1.166156e-41
   favorites_per_status      0.117299  9.329903e-27

In [ ]:
from scipy.stats import ks_2samp
import pandas as pd
import numpy as np

genuine_accounts = behavior_common[
    behavior_common["account_type"] == "genuine_accounts"
].copy()

known_bots = behavior_common[
    (behavior_common["label"] == 1) &
    (behavior_common["account_type"] != "fake_followers")
].copy()

fake_accounts = behavior_common[
    behavior_common["account_type"] == "fake_followers"
].copy()


def calculate_ks_shift(reference_df, target_df, comparison_name):

    results = []

    for feature in behavior_features:

        ref_values = reference_df[feature].dropna()
        target_values = target_df[feature].dropna()

        if len(ref_values) > 0 and len(target_values) > 0:

            ks_stat, p_value = ks_2samp(
                ref_values,
                target_values
            )

            results.append({
                "comparison": comparison_name,
                "feature": feature,
                "ks_statistic": ks_stat,
                "p_value": p_value
            })

    return pd.DataFrame(results)


shift_genuine = calculate_ks_shift(
    genuine_accounts,
    fake_accounts,
    "Fake Followers vs Genuine"
)

shift_known_bots = calculate_ks_shift(
    known_bots,
    fake_accounts,
    "Fake Followers vs Known Bots"
)

shift_comparison = pd.concat(
    [shift_genuine, shift_known_bots],
    ignore_index=True
)

shift_comparison.sort_values(
    ["comparison", "ks_statistic"],
    ascending=[True, False]
)

,comparison,feature,ks_statistic,p_value
7,Fake Followers vs Genuine,followers_friends_ratio,0.972660,0.000000e+00
8,Fake Followers vs Genuine,friends_followers_ratio,0.972312,0.000000e+00
3,Fake Followers vs Genuine,favourites_count,0.949270,0.000000e+00
13,Fake Followers vs Genuine,log_favourites_count,0.949270,0.000000e+00
0,Fake Followers vs Genuine,statuses_count,0.930599,0.000000e+00
10,Fake Followers vs Genuine,log_statuses_count,0.930599,0.000000e+00
1,Fake Followers vs Genuine,followers_count,0.922724,0.000000e+00
11,Fake Followers vs Genuine,log_followers_count,0.922724,0.000000e+00
6,Fake Followers vs Genuine,statuses_per_day,0.905587,0.000000e+00
9,Fake Followers vs Genuine,favorites_per_status,0.879760,1.531604e-322
5,Fake Followers vs Genuine,account_age_days,0.843223,4.100745e-322
4,Fake Followers vs Genuine,listed_count,0.762263,9.782500e-322
14,Fake Followers vs Genuine,log_listed_count,0.762263,9.782500e-322
2,Fake Followers vs Genuine,friends_count,0.229701,6.014496e-38
12,Fake Followers vs Genuine,log_friends_count,0.229701,6.014496e-38
20,Fake Followers vs Known Bots,account_age_days,0.837847,0.000000e+00
23,Fake Followers vs Known Bots,friends_followers_ratio,0.787264,0.000000e+00
22,Fake Followers vs Known Bots,followers_friends_ratio,0.779653,0.000000e+00
17,Fake Followers vs Known Bots,friends_count,0.607820,1.294452e-321
27,Fake Followers vs Known Bots,log_friends_count,0.607820,1.294452e-321
15,Fake Followers vs Known Bots,statuses_count,0.566289,2.564201e-321
25,Fake Followers vs Known Bots,log_statuses_count,0.566289,2.564201e-321
21,Fake Followers vs Known Bots,statuses_per_day,0.375356,9.314202e-244
16,Fake Followers vs Known Bots,followers_count,0.310128,5.114392e-177
26,Fake Followers vs Known Bots,log_followers_count,0.310128,5.114392e-177
19,Fake Followers vs Known Bots,listed_count,0.282265,2.762239e-146
29,Fake Followers vs Known Bots,log_listed_count,0.282265,2.762239e-146
24,Fake Followers vs Known Bots,favorites_per_status,0.077310,3.080640e-11
18,Fake Followers vs Known Bots,favourites_count,0.035268,1.106052e-02
28,Fake Followers vs Known Bots,log_favourites_count,0.035268,1.106052e-02

In [ ]:
print(
    shift_comparison[
        ["comparison", "feature", "ks_statistic", "p_value"]
    ].to_string(index=False)
)

                  comparison                 feature  ks_statistic       p_value
   Fake Followers vs Genuine          statuses_count      0.930599  0.000000e+00
   Fake Followers vs Genuine         followers_count      0.922724  0.000000e+00
   Fake Followers vs Genuine           friends_count      0.229701  6.014496e-38
   Fake Followers vs Genuine        favourites_count      0.949270  0.000000e+00
   Fake Followers vs Genuine            listed_count      0.762263 9.782500e-322
   Fake Followers vs Genuine        account_age_days      0.843223 4.100745e-322
   Fake Followers vs Genuine        statuses_per_day      0.905587  0.000000e+00
   Fake Followers vs Genuine followers_friends_ratio      0.972660  0.000000e+00
   Fake Followers vs Genuine friends_followers_ratio      0.972312  0.000000e+00
   Fake Followers vs Genuine    favorites_per_status      0.879760 1.531604e-322
   Fake Followers vs Genuine      log_statuses_count      0.930599  0.000000e+00
   Fake Followers vs Genuine     log_followers_count      0.922724  0.000000e+00
   Fake Followers vs Genuine       log_friends_count      0.229701  6.014496e-38
   Fake Followers vs Genuine    log_favourites_count      0.949270  0.000000e+00
   Fake Followers vs Genuine        log_listed_count      0.762263 9.782500e-322
Fake Followers vs Known Bots          statuses_count      0.566289 2.564201e-321
Fake Followers vs Known Bots         followers_count      0.310128 5.114392e-177
Fake Followers vs Known Bots           friends_count      0.607820 1.294452e-321
Fake Followers vs Known Bots        favourites_count      0.035268  1.106052e-02
Fake Followers vs Known Bots            listed_count      0.282265 2.762239e-146
Fake Followers vs Known Bots        account_age_days      0.837847  0.000000e+00
Fake Followers vs Known Bots        statuses_per_day      0.375356 9.314202e-244
Fake Followers vs Known Bots followers_friends_ratio      0.779653  0.000000e+00
Fake Followers vs Known Bots friends_followers_ratio      0.787264  0.000000e+00
Fake Followers vs Known Bots    favorites_per_status      0.077310  3.080640e-11
Fake Followers vs Known Bots      log_statuses_count      0.566289 2.564201e-321
Fake Followers vs Known Bots     log_followers_count      0.310128 5.114392e-177
Fake Followers vs Known Bots       log_friends_count      0.607820 1.294452e-321
Fake Followers vs Known Bots    log_favourites_count      0.035268  1.106052e-02
Fake Followers vs Known Bots        log_listed_count      0.282265 2.762239e-146

In [ ]:
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# Known accounts = everything the model is allowed to know
drift_reference = behavior_common[
    behavior_common["account_type"] != "fake_followers"
].copy()

# Features used for behavioral analysis
X_reference = drift_reference[behavior_features].copy()

# Median imputation using ONLY the known/reference data
drift_imputer = SimpleImputer(strategy="median")
X_reference_imputed = drift_imputer.fit_transform(X_reference)

# Standardize using ONLY the known/reference distribution
drift_scaler = StandardScaler()
X_reference_scaled = drift_scaler.fit_transform(
    X_reference_imputed
)

print("Reference shape:", X_reference_scaled.shape)
print("Features:", len(behavior_features))

Reference shape: (6995, 15)
Features: 15

In [ ]:
# Calculate the center of the known behavioral distribution
reference_center = X_reference_scaled.mean(axis=0)

# Euclidean distance from the known behavioral center
reference_distances = np.linalg.norm(
    X_reference_scaled - reference_center,
    axis=1
)

print("Reference distance statistics:")
print("Mean:", reference_distances.mean())
print("Median:", np.median(reference_distances))
print("95th percentile:", np.percentile(reference_distances, 95))
print("99th percentile:", np.percentile(reference_distances, 99))

Reference distance statistics:
Mean: 2.751989314486988
Median: 2.0539093334236793
95th percentile: 5.625173391078294
99th percentile: 11.372412869002451

In [ ]:
fake_drift = fake_accounts.copy()

X_fake = fake_drift[behavior_features].copy()

X_fake_imputed = drift_imputer.transform(X_fake)

X_fake_scaled = drift_scaler.transform(
    X_fake_imputed
)

fake_distances = np.linalg.norm(
    X_fake_scaled - reference_center,
    axis=1
)

print("Fake Followers distance statistics:")
print("Mean:", fake_distances.mean())
print("Median:", np.median(fake_distances))
print("95th percentile:", np.percentile(fake_distances, 95))
print("99th percentile:", np.percentile(fake_distances, 99))

Fake Followers distance statistics:
Mean: 5.061627210718114
Median: 3.0938346219435333
95th percentile: 16.997883000782828
99th percentile: 38.333371506363655

In [ ]:
drift_threshold = np.percentile(reference_distances, 95)

fake_novelty_flag = fake_distances > drift_threshold

print("Drift threshold:", drift_threshold)
print(
    "Fake Followers flagged as behaviorally unusual:",
    fake_novelty_flag.sum(),
    "/",
    len(fake_novelty_flag)
)
print(
    "Percentage flagged:",
    fake_novelty_flag.mean() * 100,
    "%"
)

Drift threshold: 5.625173391078294
Fake Followers flagged as behaviorally unusual: 481 / 3202
Percentage flagged: 15.021861336664585 %

In [ ]:
from sklearn.covariance import LedoitWolf
import numpy as np

# Use the SAME reference population: known accounts only
# X_reference_scaled was already created above.

# Estimate covariance robustly
cov_model = LedoitWolf()
cov_model.fit(X_reference_scaled)

# Mahalanobis distance for reference accounts
reference_mahal = cov_model.mahalanobis(X_reference_scaled)

print("Reference Mahalanobis statistics:")
print("Mean:", reference_mahal.mean())
print("Median:", np.median(reference_mahal))
print("95th percentile:", np.percentile(reference_mahal, 95))
print("99th percentile:", np.percentile(reference_mahal, 99))

Reference Mahalanobis statistics:
Mean: 12.567534900864576
Median: 4.215295688869645
95th percentile: 23.985791834027253
99th percentile: 88.68875980020542

In [ ]:
# Mahalanobis distance for Fake Followers
fake_mahal = cov_model.mahalanobis(X_fake_scaled)

print("Fake Followers Mahalanobis statistics:")
print("Mean:", fake_mahal.mean())
print("Median:", np.median(fake_mahal))
print("95th percentile:", np.percentile(fake_mahal, 95))
print("99th percentile:", np.percentile(fake_mahal, 99))

Fake Followers Mahalanobis statistics:
Mean: 98.59275344846587
Median: 8.328532147194116
95th percentile: 384.2057479513109
99th percentile: 2010.8817260533615

In [ ]:
mahal_threshold = np.percentile(reference_mahal, 95)

fake_mahal_flag = fake_mahal > mahal_threshold

print("Mahalanobis drift threshold:", mahal_threshold)
print(
    "Fake Followers flagged:",
    fake_mahal_flag.sum(),
    "/",
    len(fake_mahal_flag)
)
print(
    "Percentage flagged:",
    fake_mahal_flag.mean() * 100,
    "%"
)

Mahalanobis drift threshold: 23.985791834027253
Fake Followers flagged: 595 / 3202
Percentage flagged: 18.58213616489694 %

In [ ]:

# Convert Mahalanobis distance into a relative drift score
# based on the reference population.

reference_95 = np.percentile(reference_mahal, 95)
reference_99 = np.percentile(reference_mahal, 99)

fake_drift_score = np.clip(
    (fake_mahal - reference_95) /
    (reference_99 - reference_95),
    0,
    1
)

print("Fake Followers drift score statistics:")
print("Mean:", fake_drift_score.mean())
print("Median:", np.median(fake_drift_score))
print("95th percentile:", np.percentile(fake_drift_score, 95))
print("99th percentile:", np.percentile(fake_drift_score, 99))
print("Score >= 0.5:", (fake_drift_score >= 0.5).sum())
print("Score >= 0.8:", (fake_drift_score >= 0.8).sum())
print("Score >= 0.9:", (fake_drift_score >= 0.9).sum())

Fake Followers drift score statistics:
Mean: 0.1284920807794736
Median: 0.0
95th percentile: 1.0
99th percentile: 1.0
Score >= 0.5: 393
Score >= 0.8: 352
Score >= 0.9: 341

In [ ]:
# Convert Mahalanobis distances into empirical percentile scores
sorted_reference_mahal = np.sort(reference_mahal)

fake_percentile_score = np.searchsorted(
    sorted_reference_mahal,
    fake_mahal,
    side="right"
) / len(sorted_reference_mahal)

print("Percentile-based drift score statistics:")
print("Mean:", fake_percentile_score.mean())
print("Median:", np.median(fake_percentile_score))
print("25th percentile:", np.percentile(fake_percentile_score, 25))
print("75th percentile:", np.percentile(fake_percentile_score, 75))
print("90th percentile:", np.percentile(fake_percentile_score, 90))
print("95th percentile:", np.percentile(fake_percentile_score, 95))
print("99th percentile:", np.percentile(fake_percentile_score, 99))

print("\nDrift thresholds:")
print(">= 0.95:", (fake_percentile_score >= 0.95).sum())
print(">= 0.99:", (fake_percentile_score >= 0.99).sum())

Percentile-based drift score statistics:
Mean: 0.717717438037967
Median: 0.6842744817726948
25th percentile: 0.5462830593280915
75th percentile: 0.902144388849178
90th percentile: 0.9908363116511795
95th percentile: 0.9971408148677627
99th percentile: 0.998856325947105

Drift thresholds:
>= 0.95: 595
>= 0.99: 324

In [ ]:
# Prepare ALL LOBO test accounts using the same
# imputer and scaler fitted on the known reference population.

X_lobo_test_raw = lobo_test[behavior_features].copy()

X_lobo_test_imputed = drift_imputer.transform(X_lobo_test_raw)
X_lobo_test_scaled = drift_scaler.transform(X_lobo_test_imputed)

# Calculate Mahalanobis distance
X_lobo_test_mahal = cov_model.mahalanobis(X_lobo_test_scaled)

# Convert to empirical percentile relative to known accounts
lobo_drift_score = np.searchsorted(
    sorted_reference_mahal,
    X_lobo_test_mahal,
    side="right"
) / len(sorted_reference_mahal)

print("LOBO test drift score:")
print("Mean:", lobo_drift_score.mean())
print("Median:", np.median(lobo_drift_score))
print("95th percentile:", np.percentile(lobo_drift_score, 95))
print("99th percentile:", np.percentile(lobo_drift_score, 99))

LOBO test drift score:
Mean: 0.750160900059469
Median: 0.7837026447462473
95th percentile: 0.9963974267333809
99th percentile: 0.998856325947105

In [ ]:

test_results = pd.DataFrame({
    "label": y_lobo_test,
    "drift_score": lobo_drift_score,
    "behavior_prob": behavior_lobo_test_prob,
    "text_prob": text_test_prob
})

print(
    test_results.groupby("label")["drift_score"]
    .agg(["count", "mean", "median"])
)

       count      mean    median
label
0       1083  0.791428  0.842030
1       3202  0.736203  0.748964

In [ ]:

test_results["drift_group"] = pd.cut(
    test_results["drift_score"],
    bins=[0, 0.50, 0.75, 0.90, 0.95, 0.99, 1.0],
    labels=[
        "Low",
        "Moderate",
        "Elevated",
        "Unusual",
        "Very Unusual",
        "Extreme"
    ],
    include_lowest=True
)

print(
    pd.crosstab(
        test_results["drift_group"],
        test_results["label"],
        normalize="index"
    ) * 100
)

label                 0          1
drift_group
Low           27.837838  72.162162
Moderate      16.677038  83.322962
Elevated      29.719626  70.280374
Unusual       31.513648  68.486352
Very Unusual  31.428571  68.571429
Extreme       32.631579  67.368421

In [ ]:
# ============================================================
# RIGOROUS LOBO DRIFT REFERENCE
# Fit ONLY on the LOBO training portion
# ============================================================

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.covariance import LedoitWolf
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# 1. Behavioral features
# ------------------------------------------------------------

behavior_features = [
    "statuses_count",
    "followers_count",
    "friends_count",
    "favourites_count",
    "listed_count",
    "account_age_days",
    "statuses_per_day",
    "followers_friends_ratio",
    "friends_followers_ratio",
    "favorites_per_status",
    "log_statuses_count",
    "log_followers_count",
    "log_friends_count",
    "log_favourites_count",
    "log_listed_count"
]

# ------------------------------------------------------------
# 2. Use ONLY the LOBO training split
#    (5,596 accounts)
# ------------------------------------------------------------

X_drift_train_raw = lobo_train_part[behavior_features].copy()

print("Drift training shape:", X_drift_train_raw.shape)

# ------------------------------------------------------------
# 3. Fit imputer ONLY on training data
# ------------------------------------------------------------

drift_imputer_final = SimpleImputer(strategy="median")

X_drift_train_imputed = drift_imputer_final.fit_transform(
    X_drift_train_raw
)

# ------------------------------------------------------------
# 4. Fit scaler ONLY on training data
# ------------------------------------------------------------

drift_scaler_final = StandardScaler()

X_drift_train_scaled = drift_scaler_final.fit_transform(
    X_drift_train_imputed
)

# ------------------------------------------------------------
# 5. Fit covariance model ONLY on training data
# ------------------------------------------------------------

drift_cov_model_final = LedoitWolf()

drift_cov_model_final.fit(
    X_drift_train_scaled
)

# ------------------------------------------------------------
# 6. Calculate training Mahalanobis distances
# ------------------------------------------------------------

train_mahal = drift_cov_model_final.mahalanobis(
    X_drift_train_scaled
)

# ------------------------------------------------------------
# 7. Create frozen reference thresholds
# ------------------------------------------------------------

train_mahal_sorted = np.sort(train_mahal)

drift_threshold_95 = np.percentile(train_mahal, 95)
drift_threshold_99 = np.percentile(train_mahal, 99)

print("\n===== FROZEN DRIFT REFERENCE =====")
print("Training accounts:", len(train_mahal))
print("Mean:", train_mahal.mean())
print("Median:", np.median(train_mahal))
print("95th percentile:", drift_threshold_95)
print("99th percentile:", drift_threshold_99)

Drift training shape: (5596, 15)

===== FROZEN DRIFT REFERENCE =====
Training accounts: 5596
Mean: 12.04669682065705
Median: 4.147007075253076
95th percentile: 24.273501667300454
99th percentile: 97.14133764435573

In [ ]:
# ============================================================
# APPLY FROZEN DRIFT MODEL TO VALIDATION + TEST
# ============================================================

# ---------- VALIDATION ----------

X_drift_val_raw = lobo_val[behavior_features].copy()

X_drift_val_imputed = drift_imputer_final.transform(
    X_drift_val_raw
)

X_drift_val_scaled = drift_scaler_final.transform(
    X_drift_val_imputed
)

val_mahal = drift_cov_model_final.mahalanobis(
    X_drift_val_scaled
)

val_drift_score = (
    np.searchsorted(
        train_mahal_sorted,
        val_mahal,
        side="right"
    ) / len(train_mahal_sorted)
)


# ---------- TEST ----------

X_drift_test_raw = lobo_test[behavior_features].copy()

X_drift_test_imputed = drift_imputer_final.transform(
    X_drift_test_raw
)

X_drift_test_scaled = drift_scaler_final.transform(
    X_drift_test_imputed
)

test_mahal = drift_cov_model_final.mahalanobis(
    X_drift_test_scaled
)

test_drift_score = (
    np.searchsorted(
        train_mahal_sorted,
        test_mahal,
        side="right"
    ) / len(train_mahal_sorted)
)


print("===== VALIDATION DRIFT =====")
print("Mean:", val_drift_score.mean())
print("Median:", np.median(val_drift_score))
print("95th percentile:", np.percentile(val_drift_score, 95))
print("99th percentile:", np.percentile(val_drift_score, 99))

print("\n===== TEST DRIFT =====")
print("Mean:", test_drift_score.mean())
print("Median:", np.median(test_drift_score))
print("95th percentile:", np.percentile(test_drift_score, 95))
print("99th percentile:", np.percentile(test_drift_score, 99))

===== VALIDATION DRIFT =====
Mean: 0.5038146312003723
Median: 0.5003573981415297
95th percentile: 0.955325232308792
99th percentile: 0.9937884203002143

===== TEST DRIFT =====
Mean: 0.7536355773377049
Median: 0.7875268048606148
95th percentile: 0.9966047176554682
99th percentile: 0.9992852037169406

In [ ]:
# ============================================================
# VALIDATION: DRIFT VS BEHAVIOR MODEL ERRORS
# ============================================================

# Actual validation labels
val_actual = lobo_val["label"].values

# Behavior model predictions
val_pred = (behavior_lobo_val_prob >= 0.5).astype(int)

# 1 = wrong prediction, 0 = correct
val_error = (val_pred != val_actual).astype(int)

# Create analysis dataframe
val_reliability = pd.DataFrame({
    "label": val_actual,
    "prediction": val_pred,
    "drift_score": val_drift_score,
    "error": val_error
})

# ------------------------------------------------------------
# Drift groups
# ------------------------------------------------------------

val_reliability["drift_group"] = pd.cut(
    val_reliability["drift_score"],
    bins=[0, 0.50, 0.75, 0.90, 0.95, 0.99, 1.0],
    labels=[
        "Low",
        "Moderate",
        "Elevated",
        "Unusual",
        "Very Unusual",
        "Extreme"
    ],
    include_lowest=True
)

# ------------------------------------------------------------
# Error rate by drift group
# ------------------------------------------------------------

drift_error_analysis = (
    val_reliability
    .groupby("drift_group", observed=False)
    .agg(
        count=("error", "size"),
        errors=("error", "sum"),
        error_rate=("error", "mean")
    )
)

drift_error_analysis["accuracy"] = (
    1 - drift_error_analysis["error_rate"]
)

drift_error_analysis["error_rate"] *= 100
drift_error_analysis["accuracy"] *= 100

print("===== VALIDATION: DRIFT VS MODEL ERROR =====")
print(drift_error_analysis.round(2))

===== VALIDATION: DRIFT VS MODEL ERROR =====
              count  errors  error_rate  accuracy
drift_group
Low             699       1        0.14     99.86
Moderate        362       2        0.55     99.45
Elevated        192       4        2.08     97.92
Unusual          67       0        0.00    100.00
Very Unusual     61       4        6.56     93.44
Extreme          18       1        5.56     94.44

In [ ]:
# ============================================================
# ERROR RATE BY DRIFT GROUP AND CLASS
# ============================================================

class_drift_analysis = (
    val_reliability
    .groupby(
        ["drift_group", "label"],
        observed=False
    )
    .agg(
        count=("error", "size"),
        errors=("error", "sum"),
        error_rate=("error", "mean")
    )
)

class_drift_analysis["accuracy"] = (
    1 - class_drift_analysis["error_rate"]
)

class_drift_analysis["error_rate"] *= 100
class_drift_analysis["accuracy"] *= 100

print("===== CLASS-WISE DRIFT RELIABILITY =====")
print(class_drift_analysis.round(2))

===== CLASS-WISE DRIFT RELIABILITY =====
                    count  errors  error_rate  accuracy
drift_group  label
Low          0          2       0        0.00    100.00
             1        697       1        0.14     99.86
Moderate     0         32       1        3.12     96.88
             1        330       1        0.30     99.70
Elevated     0        100       0        0.00    100.00
             1         92       4        4.35     95.65
Unusual      0         37       0        0.00    100.00
             1         30       0        0.00    100.00
Very Unusual 0         34       1        2.94     97.06
             1         27       3       11.11     88.89
Extreme      0         12       1        8.33     91.67
             1          6       0        0.00    100.00

In [ ]:
# ============================================================
# VALIDATION: FIND A RELIABILITY THRESHOLD
# ============================================================

thresholds = [0.50, 0.60, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95, 0.99]

results = []

for threshold in thresholds:

    high_drift = val_reliability["drift_score"] >= threshold

    total_high = high_drift.sum()
    total_low = (~high_drift).sum()

    high_errors = val_reliability.loc[high_drift, "error"].sum()
    low_errors = val_reliability.loc[~high_drift, "error"].sum()

    high_error_rate = (
        high_errors / total_high * 100
        if total_high > 0 else 0
    )

    low_error_rate = (
        low_errors / total_low * 100
        if total_low > 0 else 0
    )

    results.append({
        "threshold": threshold,
        "flagged_accounts": total_high,
        "flagged_percent": total_high / len(val_reliability) * 100,
        "flagged_error_rate": high_error_rate,
        "normal_error_rate": low_error_rate
    })

threshold_results = pd.DataFrame(results)

print("===== VALIDATION RELIABILITY THRESHOLDS =====")
print(threshold_results.round(3).to_string(index=False))

===== VALIDATION RELIABILITY THRESHOLDS =====
 threshold  flagged_accounts  flagged_percent  flagged_error_rate  normal_error_rate
      0.50               702           50.179               1.567              0.143
      0.60               541           38.670               1.848              0.233
      0.70               400           28.592               2.250              0.300
      0.75               338           24.160               2.663              0.283
      0.80               288           20.586               3.125              0.270
      0.85               214           15.297               3.738              0.338
      0.90               146           10.436               3.425              0.559
      0.95                79            5.647               6.329              0.530
      0.99                18            1.287               5.556              0.797

In [ ]:
# ============================================================
# ERROR CAPTURE BY DRIFT THRESHOLD
# ============================================================

total_errors = int(val_reliability["error"].sum())

results = []

for threshold in thresholds:

    high_drift = val_reliability["drift_score"] >= threshold

    flagged_accounts = int(high_drift.sum())

    captured_errors = int(
        val_reliability.loc[high_drift, "error"].sum()
    )

    flagged_error_rate = (
        captured_errors / flagged_accounts * 100
        if flagged_accounts > 0 else 0
    )

    normal_accounts = int((~high_drift).sum())

    normal_errors = int(
        val_reliability.loc[~high_drift, "error"].sum()
    )

    normal_error_rate = (
        normal_errors / normal_accounts * 100
        if normal_accounts > 0 else 0
    )

    error_capture = (
        captured_errors / total_errors * 100
        if total_errors > 0 else 0
    )

    results.append({
        "threshold": threshold,
        "flagged_accounts": flagged_accounts,
        "flagged_percent": flagged_accounts / len(val_reliability) * 100,
        "flagged_error_rate": flagged_error_rate,
        "normal_error_rate": normal_error_rate,
        "errors_captured": captured_errors,
        "error_capture_percent": error_capture
    })

error_capture_results = pd.DataFrame(results)

print("===== ERROR CAPTURE BY DRIFT THRESHOLD =====")
print(
    error_capture_results.round(3).to_string(index=False)
)

===== ERROR CAPTURE BY DRIFT THRESHOLD =====
 threshold  flagged_accounts  flagged_percent  flagged_error_rate  normal_error_rate  errors_captured  error_capture_percent
      0.50               702           50.179               1.567              0.143               11                 91.667
      0.60               541           38.670               1.848              0.233               10                 83.333
      0.70               400           28.592               2.250              0.300                9                 75.000
      0.75               338           24.160               2.663              0.283                9                 75.000
      0.80               288           20.586               3.125              0.270                9                 75.000
      0.85               214           15.297               3.738              0.338                8                 66.667
      0.90               146           10.436               3.425              0.559                5                 41.667
      0.95                79            5.647               6.329              0.530                5                 41.667
      0.99                18            1.287               5.556              0.797                1                  8.333

In [ ]:
# ============================================================
# VALIDATION: 3-LEVEL RELIABILITY SYSTEM
# ============================================================

val_reliability["reliability_level"] = pd.cut(
    val_reliability["drift_score"],
    bins=[0, 0.80, 0.95, 1.0],
    labels=[
        "Reliable",
        "Review",
        "High Drift"
    ],
    include_lowest=True
)

reliability_summary = (
    val_reliability
    .groupby("reliability_level", observed=False)
    .agg(
        accounts=("error", "size"),
        errors=("error", "sum"),
        error_rate=("error", "mean")
    )
)

reliability_summary["accuracy"] = (
    1 - reliability_summary["error_rate"]
)

reliability_summary["error_rate"] *= 100
reliability_summary["accuracy"] *= 100

print("===== VALIDATION RELIABILITY LEVELS =====")
print(reliability_summary.round(2).to_string())

===== VALIDATION RELIABILITY LEVELS =====
                   accounts  errors  error_rate  accuracy
reliability_level
Reliable               1111       3        0.27     99.73
Review                  209       4        1.91     98.09
High Drift               79       5        6.33     93.67

In [ ]:
# ============================================================
# ERROR DISTRIBUTION ACROSS RELIABILITY LEVELS
# ============================================================

error_distribution = (
    val_reliability[val_reliability["error"] == 1]
    .groupby("reliability_level", observed=False)
    .size()
)

print("===== WHERE DID THE MODEL ERRORS OCCUR? =====")
print(error_distribution)

print("\nTotal validation errors:",
      val_reliability["error"].sum())

===== WHERE DID THE MODEL ERRORS OCCUR? =====
reliability_level
Reliable      3
Review        4
High Drift    5
dtype: int64

Total validation errors: 12

In [ ]:
# ============================================================
# FINAL LOBO TEST: FROZEN RELIABILITY LAYER
# ============================================================

# Use the frozen thresholds selected from validation
test_reliability = pd.DataFrame({
    "label": lobo_test["label"].values,
    "behavior_probability": behavior_lobo_test_prob,
    "behavior_prediction": (
        behavior_lobo_test_prob >= 0.5
    ).astype(int),
    "drift_score": test_drift_score
})

# ------------------------------------------------------------
# Assign reliability level
# ------------------------------------------------------------

test_reliability["reliability_level"] = pd.cut(
    test_reliability["drift_score"],
    bins=[0, 0.80, 0.95, 1.0],
    labels=[
        "Reliable",
        "Review",
        "High Drift"
    ],
    include_lowest=True
)

# ------------------------------------------------------------
# Model errors
# ------------------------------------------------------------

test_reliability["error"] = (
    test_reliability["behavior_prediction"]
    != test_reliability["label"]
).astype(int)

# ------------------------------------------------------------
# Overall reliability summary
# ------------------------------------------------------------

test_reliability_summary = (
    test_reliability
    .groupby("reliability_level", observed=False)
    .agg(
        accounts=("error", "size"),
        errors=("error", "sum"),
        error_rate=("error", "mean")
    )
)

test_reliability_summary["accuracy"] = (
    1 - test_reliability_summary["error_rate"]
)

test_reliability_summary["error_rate"] *= 100
test_reliability_summary["accuracy"] *= 100

print("===== FINAL LOBO TEST: RELIABILITY =====")
print(
    test_reliability_summary
    .round(2)
    .to_string()
)

===== FINAL LOBO TEST: RELIABILITY =====
                   accounts  errors  error_rate  accuracy
reliability_level
Reliable               2185     787       36.02     63.98
Review                 1257     566       45.03     54.97
High Drift              843     635       75.33     24.67

In [ ]:
# ============================================================
# FINAL LOBO TEST: RELIABILITY BY CLASS
# ============================================================

test_class_reliability = (
    test_reliability
    .groupby(
        ["reliability_level", "label"],
        observed=False
    )
    .agg(
        accounts=("error", "size"),
        errors=("error", "sum"),
        error_rate=("error", "mean")
    )
)

test_class_reliability["accuracy"] = (
    1 - test_class_reliability["error_rate"]
)

test_class_reliability["error_rate"] *= 100
test_class_reliability["accuracy"] *= 100

print("===== FINAL LOBO TEST: CLASS-WISE RELIABILITY =====")
print(
    test_class_reliability
    .round(2)
    .to_string()
)

===== FINAL LOBO TEST: CLASS-WISE RELIABILITY =====
                         accounts  errors  error_rate  accuracy
reliability_level label
Reliable          0           256     111       43.36     56.64
                  1          1929     676       35.04     64.96
Review            0           577     425       73.66     26.34
                  1           680     141       20.74     79.26
High Drift        0           250     233       93.20      6.80
                  1           593     402       67.79     32.21

In [ ]:
# ============================================================
# FAKE FOLLOWER RELIABILITY SUMMARY
# ============================================================

fake_test = test_reliability[
    test_reliability["label"] == 1
]

print("===== FAKE FOLLOWERS =====")

print(
    fake_test["reliability_level"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

print("\nMean drift:",
      round(fake_test["drift_score"].mean(), 4))

print("Median drift:",
      round(fake_test["drift_score"].median(), 4))

print("\nFake Followers model accuracy:",
      round(
          (fake_test["error"] == 0).mean() * 100,
          2
      ))

===== FAKE FOLLOWERS =====
reliability_level
Reliable      60.24
Review        21.24
High Drift    18.52
Name: proportion, dtype: float64

Mean drift: 0.7208
Median drift: 0.6932

Fake Followers model accuracy: 61.93

In [ ]:
# ============================================================
# EXPERIMENT 1: NONLINEAR FUSION
# Step 1 — Prepare meta-features
# ============================================================

import pandas as pd
import numpy as np

fusion_val = pd.DataFrame({
    "behavior_prob": behavior_lobo_val_prob,
    "text_prob": text_val_prob,
    "behavior_confidence": np.abs(behavior_lobo_val_prob - 0.5) * 2,
    "text_confidence": np.abs(text_val_prob - 0.5) * 2,
    "prob_difference": behavior_lobo_val_prob - text_val_prob,
    "absolute_difference": np.abs(
        behavior_lobo_val_prob - text_val_prob
    ),
    "label": lobo_val["label"].values
})

print("Fusion validation shape:", fusion_val.shape)
print("\nFirst 5 rows:")
display(fusion_val.head())

print("\nLabel distribution:")
print(fusion_val["label"].value_counts())

Fusion validation shape: (1399, 7)

First 5 rows:

,behavior_prob,text_prob,behavior_confidence,text_confidence,prob_difference,absolute_difference,label
0,0.999690,0.998852,0.999379,0.997704,0.000838,0.000838,1
1,0.998265,0.999856,0.996529,0.999711,-0.001591,0.001591,1
2,0.002287,0.202346,0.995427,0.595308,-0.200060,0.200060,0
3,0.999789,0.999831,0.999577,0.999663,-0.000043,0.000043,1
4,0.008525,0.029393,0.982950,0.941214,-0.020868,0.020868,0

Label distribution:
label
1    1182
0     217
Name: count, dtype: int64

In [ ]:
# ============================================================
# EXPERIMENT 1 — NONLINEAR FUSION
# Step 2: Random Forest Meta-Model
# ============================================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Meta-features
fusion_features = [
    "behavior_prob",
    "text_prob",
    "behavior_confidence",
    "text_confidence",
    "prob_difference",
    "absolute_difference"
]

X_fusion_val = fusion_val[fusion_features]
y_fusion_val = fusion_val["label"]

# Random Forest fusion model
rf_fusion = RandomForestClassifier(
    n_estimators=300,
    max_depth=5,
    min_samples_leaf=10,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

# IMPORTANT:
# This is an exploratory validation experiment.
# We are checking whether nonlinear fusion can learn
# useful interactions between behavior and text.
rf_fusion.fit(X_fusion_val, y_fusion_val)

# Validation predictions
rf_val_pred = rf_fusion.predict(X_fusion_val)

# Metrics
rf_acc = accuracy_score(y_fusion_val, rf_val_pred)
rf_precision = precision_score(y_fusion_val, rf_val_pred)
rf_recall = recall_score(y_fusion_val, rf_val_pred)
rf_f1 = f1_score(y_fusion_val, rf_val_pred)

print("===== RANDOM FOREST FUSION — VALIDATION =====")
print(f"Accuracy : {rf_acc*100:.2f}%")
print(f"Precision: {rf_precision*100:.2f}%")
print(f"Recall   : {rf_recall*100:.2f}%")
print(f"F1 Score : {rf_f1*100:.2f}%")

print("\nConfusion Matrix:")
print(confusion_matrix(y_fusion_val, rf_val_pred))

print("\nClassification Report:")
print(classification_report(
    y_fusion_val,
    rf_val_pred,
    target_names=["Genuine", "Bot"]
))

===== RANDOM FOREST FUSION — VALIDATION =====
Accuracy : 99.79%
Precision: 100.00%
Recall   : 99.75%
F1 Score : 99.87%

Confusion Matrix:
[[ 217    0]
 [   3 1179]]

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.99      1.00      0.99       217
         Bot       1.00      1.00      1.00      1182

    accuracy                           1.00      1399
   macro avg       0.99      1.00      1.00      1399
weighted avg       1.00      1.00      1.00      1399

In [ ]:
# ============================================================
# PROPER NONLINEAR FUSION — RANDOM FOREST
# Train on OOF predictions, evaluate on untouched validation
# ============================================================

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# 1. Prepare OOF meta-features
# ------------------------------------------------------------
# These should have been generated during our previous
# 5-fold OOF stacking experiment.

oof_fusion = pd.DataFrame({
    "behavior_prob": oof_behavior_prob,
    "text_prob": oof_text_prob
})

oof_fusion["behavior_confidence"] = (
    np.abs(oof_fusion["behavior_prob"] - 0.5) * 2
)

oof_fusion["text_confidence"] = (
    np.abs(oof_fusion["text_prob"] - 0.5) * 2
)

oof_fusion["prob_difference"] = (
    oof_fusion["behavior_prob"] -
    oof_fusion["text_prob"]
)

oof_fusion["absolute_difference"] = (
    np.abs(oof_fusion["prob_difference"])
)

y_oof_fusion = lobo_train["label"].values

print("OOF fusion shape:", oof_fusion.shape)
print("OOF labels:", len(y_oof_fusion))


# ------------------------------------------------------------
# 2. Validation meta-features
# ------------------------------------------------------------

validation_fusion = pd.DataFrame({
    "behavior_prob": behavior_lobo_val_prob,
    "text_prob": text_val_prob
})

validation_fusion["behavior_confidence"] = (
    np.abs(validation_fusion["behavior_prob"] - 0.5) * 2
)

validation_fusion["text_confidence"] = (
    np.abs(validation_fusion["text_prob"] - 0.5) * 2
)

validation_fusion["prob_difference"] = (
    validation_fusion["behavior_prob"] -
    validation_fusion["text_prob"]
)

validation_fusion["absolute_difference"] = (
    np.abs(validation_fusion["prob_difference"])
)


# ------------------------------------------------------------
# 3. Train nonlinear fusion model
# ------------------------------------------------------------

rf_fusion_proper = RandomForestClassifier(
    n_estimators=500,
    max_depth=5,
    min_samples_leaf=10,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_fusion_proper.fit(
    oof_fusion,
    y_oof_fusion
)


# ------------------------------------------------------------
# 4. Evaluate on untouched validation
# ------------------------------------------------------------

rf_val_pred_proper = rf_fusion_proper.predict(
    validation_fusion
)

rf_val_prob_proper = rf_fusion_proper.predict_proba(
    validation_fusion
)[:, 1]


# ------------------------------------------------------------
# 5. Metrics
# ------------------------------------------------------------

accuracy = accuracy_score(
    lobo_val["label"],
    rf_val_pred_proper
)

precision = precision_score(
    lobo_val["label"],
    rf_val_pred_proper
)

recall = recall_score(
    lobo_val["label"],
    rf_val_pred_proper
)

f1 = f1_score(
    lobo_val["label"],
    rf_val_pred_proper
)

print("\n==============================================")
print("PROPER RANDOM FOREST FUSION — VALIDATION")
print("==============================================")

print(f"Accuracy : {accuracy*100:.2f}%")
print(f"Precision: {precision*100:.2f}%")
print(f"Recall   : {recall*100:.2f}%")
print(f"F1 Score : {f1*100:.2f}%")

print("\nConfusion Matrix:")
print(confusion_matrix(
    lobo_val["label"],
    rf_val_pred_proper
))

print("\nClassification Report:")
print(classification_report(
    lobo_val["label"],
    rf_val_pred_proper,
    target_names=["Genuine", "Bot"]
))

OOF fusion shape: (6995, 6)
OOF labels: 6995

==============================================
PROPER RANDOM FOREST FUSION — VALIDATION
==============================================
Accuracy : 99.07%
Precision: 99.74%
Recall   : 99.15%
F1 Score : 99.45%

Confusion Matrix:
[[ 214    3]
 [  10 1172]]

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.96      0.99      0.97       217
         Bot       1.00      0.99      0.99      1182

    accuracy                           0.99      1399
   macro avg       0.98      0.99      0.98      1399
weighted avg       0.99      0.99      0.99      1399

In [ ]:
# ============================================================
# BEHAVIOR-FIRST CONDITIONAL FUSION
# Step 1: Validation threshold experiment
# ============================================================

import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# ------------------------------------------------------------
# Existing validation probabilities
# ------------------------------------------------------------

behavior_prob = np.asarray(behavior_lobo_val_prob)
text_prob = np.asarray(text_val_prob)
y_val = lobo_val["label"].values

# ------------------------------------------------------------
# Conditional fusion function
# ------------------------------------------------------------
# If behavior is confident enough, trust behavior.
# If behavior is uncertain, combine behavior + text.
#
# IMPORTANT:
# We are testing this ONLY on validation.
# The Fake Followers test remains untouched.
# ------------------------------------------------------------

def conditional_fusion(
    behavior_prob,
    text_prob,
    threshold,
    text_weight=0.5
):
    behavior_confidence = np.abs(
        behavior_prob - 0.5
    ) * 2

    final_prob = behavior_prob.copy()

    uncertain = behavior_confidence < threshold

    final_prob[uncertain] = (
        (1 - text_weight) * behavior_prob[uncertain]
        + text_weight * text_prob[uncertain]
    )

    return (final_prob >= 0.5).astype(int)


# ------------------------------------------------------------
# Test several confidence thresholds
# ------------------------------------------------------------

thresholds = [
    0.05,
    0.10,
    0.15,
    0.20,
    0.25,
    0.30,
    0.40,
    0.50,
    0.60,
    0.70,
    0.80,
    0.90
]

results = []

for threshold in thresholds:

    pred = conditional_fusion(
        behavior_prob,
        text_prob,
        threshold=threshold,
        text_weight=0.5
    )

    results.append({
        "behavior_confidence_threshold": threshold,
        "accounts_using_text": np.sum(
            np.abs(behavior_prob - 0.5) * 2 < threshold
        ),
        "percent_using_text": (
            np.mean(
                np.abs(behavior_prob - 0.5) * 2 < threshold
            ) * 100
        ),
        "accuracy": accuracy_score(y_val, pred) * 100,
        "precision": precision_score(y_val, pred) * 100,
        "recall": recall_score(y_val, pred) * 100,
        "f1": f1_score(y_val, pred) * 100
    })

conditional_results = pd.DataFrame(results)

print("===== BEHAVIOR-FIRST CONDITIONAL FUSION =====")
display(
    conditional_results.round(3)
)

===== BEHAVIOR-FIRST CONDITIONAL FUSION =====

,behavior_confidence_threshold,accounts_using_text,percent_using_text,accuracy,precision,recall,f1
0,0.05,1,0.071,99.142,99.745,99.239,99.491
1,0.10,2,0.143,99.142,99.745,99.239,99.491
2,0.15,2,0.143,99.142,99.745,99.239,99.491
3,0.20,2,0.143,99.142,99.745,99.239,99.491
4,0.25,2,0.143,99.142,99.745,99.239,99.491
5,0.30,3,0.214,99.142,99.745,99.239,99.491
6,0.40,5,0.357,99.285,99.745,99.408,99.576
7,0.50,9,0.643,99.285,99.745,99.408,99.576
8,0.60,18,1.287,99.285,99.745,99.408,99.576
9,0.70,23,1.644,99.285,99.745,99.408,99.576
10,0.80,31,2.216,99.428,99.915,99.408,99.661
11,0.90,43,3.074,99.500,99.915,99.492,99.703

In [ ]:
print("OOF behavior:", len(oof_behavior_prob))
print("OOF text:", len(oof_text_prob))
print("lobo_train_part:", len(lobo_train_part))
print("lobo_val:", len(lobo_val))

OOF behavior: 6995
OOF text: 6995
lobo_train_part: 5596
lobo_val: 1399

In [ ]:
# ============================================================
# FROZEN BEHAVIOR-FIRST CONDITIONAL FUSION
# Final LOBO TEST
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)
import numpy as np

# ------------------------------------------------------------
# FROZEN SETTINGS FROM VALIDATION
# ------------------------------------------------------------

CONFIDENCE_THRESHOLD = 0.90
TEXT_WEIGHT = 0.50

# ------------------------------------------------------------
# Test probabilities
# ------------------------------------------------------------

behavior_test = np.asarray(behavior_lobo_test_prob)
text_test = np.asarray(text_test_prob)

y_test = lobo_test["label"].values

# ------------------------------------------------------------
# Calculate behavioral confidence
# ------------------------------------------------------------

behavior_confidence_test = (
    np.abs(behavior_test - 0.5) * 2
)

# ------------------------------------------------------------
# Start with behavior prediction
# ------------------------------------------------------------

final_test_prob = behavior_test.copy()

# Text is allowed ONLY when behavior is uncertain
uncertain_test = (
    behavior_confidence_test < CONFIDENCE_THRESHOLD
)

# Conditional fusion
final_test_prob[uncertain_test] = (
    (1 - TEXT_WEIGHT) * behavior_test[uncertain_test]
    + TEXT_WEIGHT * text_test[uncertain_test]
)

# Final prediction
final_test_pred = (
    final_test_prob >= 0.5
).astype(int)

# ------------------------------------------------------------
# Metrics
# ------------------------------------------------------------

test_accuracy = accuracy_score(
    y_test,
    final_test_pred
)

test_precision = precision_score(
    y_test,
    final_test_pred
)

test_recall = recall_score(
    y_test,
    final_test_pred
)

test_f1 = f1_score(
    y_test,
    final_test_pred
)

print("================================================")
print("FROZEN BEHAVIOR-FIRST CONDITIONAL FUSION")
print("LOBO TEST — UNSEEN FAKE FOLLOWERS")
print("================================================")

print(f"Accuracy : {test_accuracy*100:.2f}%")
print(f"Precision: {test_precision*100:.2f}%")
print(f"Recall   : {test_recall*100:.2f}%")
print(f"F1 Score : {test_f1*100:.2f}%")

print("\nAccounts using text:")
print(
    np.sum(uncertain_test),
    f"({np.mean(uncertain_test)*100:.2f}%)"
)

print("\nConfusion Matrix:")
print(confusion_matrix(
    y_test,
    final_test_pred
))

print("\nClassification Report:")
print(classification_report(
    y_test,
    final_test_pred,
    target_names=["Genuine", "Fake Followers"]
))

================================================
FROZEN BEHAVIOR-FIRST CONDITIONAL FUSION
LOBO TEST — UNSEEN FAKE FOLLOWERS
================================================
Accuracy : 52.44%
Precision: 71.56%
Recall   : 60.34%
F1 Score : 65.47%

Accounts using text:
91 (2.12%)

Confusion Matrix:
[[ 315  768]
 [1270 1932]]

Classification Report:
                precision    recall  f1-score   support

       Genuine       0.20      0.29      0.24      1083
Fake Followers       0.72      0.60      0.65      3202

      accuracy                           0.52      4285
     macro avg       0.46      0.45      0.45      4285
  weighted avg       0.58      0.52      0.55      4285

In [ ]:
# ============================================================
# FUSION INTERVENTION ANALYSIS
# What happens when text is allowed to change behavior?
# ============================================================

import numpy as np
import pandas as pd

behavior_test = np.asarray(behavior_lobo_test_prob)
text_test = np.asarray(text_test_prob)
y_test = lobo_test["label"].values

behavior_pred = (behavior_test >= 0.5).astype(int)

behavior_confidence = (
    np.abs(behavior_test - 0.5) * 2
)

# Same frozen rule
uncertain = behavior_confidence < 0.90

# Text+behavior prediction for uncertain cases
combined_prob = (
    0.5 * behavior_test +
    0.5 * text_test
)

combined_pred = (
    combined_prob >= 0.5
).astype(int)

# ------------------------------------------------------------
# Create analysis dataframe
# ------------------------------------------------------------

analysis = pd.DataFrame({
    "label": y_test,
    "behavior_prob": behavior_test,
    "text_prob": text_test,
    "behavior_confidence": behavior_confidence,
    "behavior_pred": behavior_pred,
    "combined_prob": combined_prob,
    "combined_pred": combined_pred,
    "uncertain": uncertain
})

# ------------------------------------------------------------
# Only accounts where text was actually used
# ------------------------------------------------------------

changed_region = analysis[analysis["uncertain"]].copy()

changed_region["behavior_correct"] = (
    changed_region["behavior_pred"]
    == changed_region["label"]
)

changed_region["combined_correct"] = (
    changed_region["combined_pred"]
    == changed_region["label"]
)

changed_region["prediction_changed"] = (
    changed_region["behavior_pred"]
    != changed_region["combined_pred"]
)

print("================================================")
print("TEXT INTERVENTION ANALYSIS")
print("================================================")

print("\nAccounts where text was used:",
      len(changed_region))

print("\nPrediction changed:",
      changed_region["prediction_changed"].sum())

print("\nBehavior correct BEFORE text:")
print(
    changed_region["behavior_correct"]
    .value_counts()
)

print("\nCombined correct AFTER text:")
print(
    changed_region["combined_correct"]
    .value_counts()
)

print("\nConfusion of intervention:")

print(
    pd.crosstab(
        changed_region["behavior_pred"],
        changed_region["combined_pred"],
        rownames=["Behavior prediction"],
        colnames=["Fusion prediction"]
    )
)

print("\nClass distribution of intervention:")
print(
    changed_region["label"]
    .value_counts()
)

print("\nMean probabilities:")
print(
    changed_region[
        ["behavior_prob", "text_prob", "behavior_confidence"]
    ].mean()
)

print("\nDetailed changed predictions:")
display(
    changed_region[
        [
            "label",
            "behavior_prob",
            "text_prob",
            "behavior_pred",
            "combined_prob",
            "combined_pred",
            "behavior_confidence"
        ]
    ].sort_values("behavior_prob")
)

================================================
TEXT INTERVENTION ANALYSIS
================================================

Accounts where text was used: 91

Prediction changed: 64

Behavior correct BEFORE text:
behavior_correct
True     83
False     8
Name: count, dtype: int64

Combined correct AFTER text:
combined_correct
False    58
True     33
Name: count, dtype: int64

Confusion of intervention:
Fusion prediction     0   1
Behavior prediction
0                     1   6
1                    58  26

Class distribution of intervention:
label
1    90
0     1
Name: count, dtype: int64

Mean probabilities:
behavior_prob          0.537974
text_prob              0.361063
behavior_confidence    0.157793
dtype: float64

Detailed changed predictions:

,label,behavior_prob,text_prob,behavior_pred,combined_prob,combined_pred,behavior_confidence
3476,1,0.077817,0.949653,0,0.513735,1,0.844366
3564,1,0.102207,0.879779,0,0.490993,0,0.795586
3656,1,0.187764,0.936835,0,0.562299,1,0.624472
3605,1,0.193881,0.951222,0,0.572551,1,0.612239
3616,1,0.275253,0.976485,0,0.625869,1,0.449494
...,...,...,...,...,...,...,...
3558,1,0.924396,0.920293,1,0.922344,1,0.848791
3523,1,0.925194,0.972296,1,0.948745,1,0.850388
3453,1,0.930982,0.958482,1,0.944732,1,0.861964
3631,1,0.940449,0.412081,1,0.676265,1,0.880897
3496,1,0.946804,0.705348,1,0.826076,1,0.893608

In [ ]:
# ============================================================
# TEXT LOBO — ERROR ANALYSIS ON UNSEEN FAKE FOLLOWERS
# ============================================================

import numpy as np
import pandas as pd

text_analysis = pd.DataFrame({
    "label": y_lobo_test,
    "text_prob": text_test_prob,
    "text_pred": (text_test_prob >= 0.5).astype(int),
    "account_type": lobo_test["account_type"].values,
})

# Identify Fake Followers and Genuine separately
text_analysis["correct"] = (
    text_analysis["text_pred"] == text_analysis["label"]
)

print("================================================")
print("TEXT MODEL LOBO ERROR ANALYSIS")
print("================================================")

print("\nOverall:")
print(text_analysis["correct"].value_counts())

print("\nAccuracy by account type:")
print(
    text_analysis.groupby("account_type")["correct"]
    .agg(["count", "sum", "mean"])
    .rename(columns={
        "sum": "correct_count",
        "mean": "accuracy"
    })
)

print("\nProbability statistics by account type:")
print(
    text_analysis.groupby("account_type")["text_prob"]
    .describe()
)

print("\nFake Followers prediction distribution:")
print(
    text_analysis[
        text_analysis["account_type"] == "fake_followers"
    ]["text_pred"].value_counts()
)

print("\nGenuine prediction distribution:")
print(
    text_analysis[
        text_analysis["account_type"] == "genuine_accounts"
    ]["text_pred"].value_counts()
)

================================================
TEXT MODEL LOBO ERROR ANALYSIS
================================================

Overall:
correct
True     3800
False     485
Name: count, dtype: int64

Accuracy by account type:
                  count  correct_count  accuracy
account_type
fake_followers     3202           2971  0.927858
genuine_accounts   1083            829  0.765466

Probability statistics by account type:
                   count      mean       std       min       25%       50%  \
account_type
fake_followers    3202.0  0.698369  0.345226  0.000167  0.553340  0.879753
genuine_accounts  1083.0  0.326111  0.370185  0.000080  0.026707  0.121107

                       75%       max
account_type
fake_followers    0.949396  0.997888
genuine_accounts  0.675586  0.998997

Fake Followers prediction distribution:
text_pred
1    2450
0     752
Name: count, dtype: int64

Genuine prediction distribution:
text_pred
0    764
1    319
Name: count, dtype: int64

In [ ]:
# ============================================================
# MOST IMPORTANT TEXT ERROR EXAMPLES
# ============================================================

fake = text_analysis[
    text_analysis["account_type"] == "fake_followers"
].copy()

# Add original aggregated text
fake["text"] = text_lobo.loc[
    fake.index, "text"
].values if "text_lobo" in globals() else ""

print("================================================")
print("FAKE FOLLOWERS — MOST CONFIDENTLY WRONG")
print("================================================")

wrong_fake = fake[fake["correct"] == False].copy()

# Model says genuine -> probability closest to 0
wrong_fake = wrong_fake.sort_values("text_prob")

display(
    wrong_fake[
        ["text_prob", "text_pred", "label", "text"]
    ].head(20)
)

================================================
FAKE FOLLOWERS — MOST CONFIDENTLY WRONG
================================================

      text_prob  text_pred  label text
5005   0.000167          0      1
3061   0.001336          0      1
3504   0.003578          0      1
4998   0.007975          0      1
3654   0.009254          0      1
2316   0.009374          0      1
2374   0.010986          0      1
2383   0.012776          0      1
2350   0.012950          0      1
6297   0.013677          0      1
3066   0.016345          0      1
3132   0.017955          0      1
2327   0.018997          0      1
3557   0.021879          0      1
3484   0.022820          0      1
2319   0.027216          0      1
2424   0.028406          0      1
2373   0.029086          0      1
3481   0.032191          0      1
3650   0.038405          0      1

In [ ]:
# ============================================================
# GENUINE ACCOUNTS — TEXT MODEL ERROR ANALYSIS
# ============================================================

genuine_errors = text_analysis[
    (text_analysis["account_type"] == "genuine_accounts") &
    (text_analysis["correct"] == False)
].copy()

genuine_correct = text_analysis[
    (text_analysis["account_type"] == "genuine_accounts") &
    (text_analysis["correct"] == True)
].copy()

print("================================================")
print("GENUINE ACCOUNT TEXT ERRORS")
print("================================================")

print("\nTotal genuine accounts:", len(genuine_errors) + len(genuine_correct))

print("Correctly classified genuine:",
      len(genuine_correct))

print("Misclassified as bots:",
      len(genuine_errors))

print("\nWrong genuine probability statistics:")
print(
    genuine_errors["text_prob"].describe()
)

print("\nCorrect genuine probability statistics:")
print(
    genuine_correct["text_prob"].describe()
)

================================================
GENUINE ACCOUNT TEXT ERRORS
================================================

Total genuine accounts: 1083
Correctly classified genuine: 829
Misclassified as bots: 254

Wrong genuine probability statistics:
count    254.000000
mean       0.211996
std        0.172264
min        0.000080
25%        0.069147
50%        0.177292
75%        0.320050
max        0.960016
Name: text_prob, dtype: float64

Correct genuine probability statistics:
count    829.000000
mean       0.361075
std        0.405942
min        0.001350
25%        0.021939
50%        0.088213
75%        0.842921
max        0.998997
Name: text_prob, dtype: float64

In [ ]:
# ============================================================
# MAP ORIGINAL TEXT CORRECTLY
# ============================================================

# Create a fresh copy of the LOBO test dataframe
text_debug = lobo_test[
    ["user_id", "account_type", "label", "text"]
].copy().reset_index(drop=True)

text_debug["text_prob"] = text_test_prob
text_debug["text_pred"] = (
    text_test_prob >= 0.5
).astype(int)

text_debug["correct"] = (
    text_debug["text_pred"] == text_debug["label"]
)

# Genuine accounts incorrectly classified as bots
genuine_wrong = text_debug[
    (text_debug["account_type"] == "genuine_accounts") &
    (text_debug["text_pred"] == 1)
].copy()

print("Number of genuine accounts predicted as bots:",
      len(genuine_wrong))

display(
    genuine_wrong[
        ["user_id", "text_prob", "text"]
    ]
    .sort_values("text_prob", ascending=False)
    .head(30)
)

KeyError: "['user_id', 'text'] not in index"

In [ ]:
print("lobo_test columns:")
print(lobo_test.columns.tolist())

print("\ntext_lobo_test columns:")
print(text_lobo_test.columns.tolist() if "text_lobo_test" in globals() else "NOT FOUND")

print("\ntext_lobo columns:")
print(text_lobo.columns.tolist() if "text_lobo" in globals() else "NOT FOUND")

lobo_test columns:
['id', 'account_type', 'label', 'statuses_count', 'followers_count', 'friends_count', 'favourites_count', 'listed_count', 'created_at', 'updated', 'account_age_days', 'statuses_per_day', 'followers_friends_ratio', 'friends_followers_ratio', 'favorites_per_status', 'log_statuses_count', 'log_followers_count', 'log_friends_count', 'log_favourites_count', 'log_listed_count']

text_lobo_test columns:
['user_id', 'text', 'label', 'account_type', 'tweet_count_used']

text_lobo columns:
NOT FOUND

In [ ]:
# ============================================================
# MAP TEXT + PROBABILITIES CORRECTLY
# ============================================================

text_debug = text_lobo_test[
    ["user_id", "account_type", "label", "text", "tweet_count_used"]
].copy().reset_index(drop=True)

# Make sure probability array and dataframe have identical ordering/length
assert len(text_debug) == len(text_test_prob), (
    f"Length mismatch: dataframe={len(text_debug)}, "
    f"probabilities={len(text_test_prob)}"
)

text_debug["text_prob"] = text_test_prob
text_debug["text_pred"] = (text_test_prob >= 0.5).astype(int)
text_debug["correct"] = text_debug["text_pred"] == text_debug["label"]

print("Shape:", text_debug.shape)
print("\nPrediction counts:")
print(text_debug["text_pred"].value_counts())

print("\nAccuracy by account type:")
print(
    text_debug.groupby("account_type")["correct"]
    .agg(["count", "sum", "mean"])
    .rename(columns={
        "sum": "correct_count",
        "mean": "accuracy"
    })
)

Shape: (4285, 8)

Prediction counts:
text_pred
1    2769
0    1516
Name: count, dtype: int64

Accuracy by account type:
                  count  correct_count  accuracy
account_type
fake_followers     3202           2743  0.856652
genuine_accounts   1083           1057  0.975993

In [ ]:
# ============================================================
# GENUINE → BOT FALSE POSITIVES
# ============================================================

genuine_wrong = text_debug[
    (text_debug["account_type"] == "genuine_accounts") &
    (text_debug["label"] == 0) &
    (text_debug["text_pred"] == 1)
].copy()

genuine_wrong = genuine_wrong.sort_values(
    "text_prob", ascending=False
)

print("Genuine accounts wrongly classified as bots:", len(genuine_wrong))

display(
    genuine_wrong[
        ["user_id", "text_prob", "tweet_count_used", "text"]
    ].head(20)
)

Genuine accounts wrongly classified as bots: 26

,user_id,text_prob,tweet_count_used,text
544,1.518555e+08,0.960016,100,"@fiktionist Vor allem geht es eher ""permanent ..."
4210,2.273619e+09,0.917803,100,â@margaux77176: #TenuePro @crokettr ui merci...
1468,6.049045e+08,0.881899,100,mete-te na tua vida rapariga Sdds das tardes d...
902,2.328048e+08,0.877166,100,(Current location: Pallet Town) I assembled te...
4143,2.200426e+09,0.814267,14,if all goes to plan i should have a video up 2...
4037,1.856665e+09,0.784953,29,Earthquake at Melbourne Earthquake in New york...
4000,1.670962e+09,0.783565,100,May not have working internet other than the d...
771,1.991962e+08,0.772095,100,El placer de los buenos amigos y la buena comi...
1416,5.789041e+08,0.728984,100,#BREAKING #Calbuco #volcano in #Chile threw ou...
4050,1.890979e+09,0.707661,100,= Aspo - PDk = JJS lagi :-) = Mati Lampu = Unt...
838,2.163054e+08,0.706020,100,"Hay gente que naciÃ³ por la cola, porque estan..."
1488,6.152372e+08,0.673169,100,RT @RoberPuen: Mal sabor de boca. No me ha gus...
4045,1.877305e+09,0.672021,100,RT @elcosodelapizza: Â¿QuÃ© flashean las minas...
752,1.950770e+08,0.621275,100,"Maybe if I had a boyfriend, I wouldn't think a..."
4157,2.220325e+09,0.591274,100,@LazloPlazlo Listen to Everybody wants to rul...
4068,1.925581e+09,0.582222,100,@danisnotonfire are u uploading today what hav...
657,1.716916e+08,0.580274,100,Time is very slow for those whowait...very sho...
240,2.438671e+07,0.575367,13,@bmfrantz I am so gassy right now but I am afr...
97,1.640891e+07,0.573540,100,@andi_harman this is the end. pretty sure thes...
767,1.986565e+08,0.550596,100,This crazy ice bucket challenge has taken over...

In [ ]:
# ============================================================
# FAKE FOLLOWER → GENUINE FALSE NEGATIVES
# ============================================================

fake_wrong = text_debug[
    (text_debug["account_type"] == "fake_followers") &
    (text_debug["label"] == 1) &
    (text_debug["text_pred"] == 0)
].copy()

fake_wrong = fake_wrong.sort_values(
    "text_prob", ascending=True
)

print("Fake Followers wrongly classified as genuine:", len(fake_wrong))

display(
    fake_wrong[
        ["user_id", "text_prob", "tweet_count_used", "text"]
    ].head(20)
)

Fake Followers wrongly classified as genuine: 459

,user_id,text_prob,tweet_count_used,text
971,2.546190e+08,0.000080,6,RT @sextubenight: http://t.co/aho5mLAi RT @sex...
2698,1.122937e+09,0.000167,6,@yameyori ì ê¸° íì´ì¤íì¸í í´ì£¼ë...
974,2.549768e+08,0.000346,15,@jeff9279 ììì¬ì¬í´ì¬ã ã ì´ëì¸ì¬...
322,5.519714e+07,0.000777,1,http://t.co/P0nPr7nG
421,9.785947e+07,0.001031,1,http://t.co/6j63gV95
1182,4.683384e+08,0.001336,1,http://t.co/yiClEwex
472,1.220753e+08,0.001907,1,https://t.co/PMI0dawh
461,1.180614e+08,0.002461,1,Raspberry Keytone http://t.co/Y94OzwP4
513,1.418864e+08,0.002484,2,RT @coryhilker: Win tickets to the Olympics:ht...
495,1.322786e+08,0.002541,2,http://t.co/DRSoR8VZ @viajaVolaris
429,1.015734e+08,0.002756,32,@sesytulofoly http://t.co/5X7veGWs haggard @Fu...
471,1.217953e+08,0.003512,24,@markreale Derby http://t.co/sG0t8JyP @amirahn...
1355,5.552633e+08,0.003578,2,http://t.co/fxcO8Swo solomadagascar
1073,3.356224e+08,0.004559,19,http://t.co/T5uCnJHW YÃ¼zsÃ¼zdÃ¼r insanoÄlu k...
1030,3.003443e+08,0.004942,19,@galaxy_nuna ì ë ì ë§ ì¢ìí´ìë¬´ëë...
410,9.424458e+07,0.007160,59,RT @airelav4: ÐÐµÑÑÐ°ÑÑ Ð½Ðµ Ð²ÑÐµÐ´Ð½Ð¾...
2695,1.030687e+09,0.007975,10,RT @haeminbook: ì½ 1ìê° í (12/28 ë°¤ 11:...
366,7.211003e+07,0.008149,100,@rohitbarker : tahts ur shadow bob RT @1pixelg...
781,2.021555e+08,0.008737,100,RT @finance_law: ÐÐ¾Ð²ÑÐ¹ Ð¸Ð½ÑÐµÑÐµÑÐ½Ñ...
1438,5.909161e+08,0.009254,66,RT @finance_review: ÐÐ±ÑÐ·Ð°ÑÐµÐ»ÑÐ½ÑÐ¹ Ð...

In [ ]:
# ============================================================
# TEXT ERROR vs AMOUNT OF TEXT AVAILABLE
# ============================================================

fake_analysis = text_debug[
    text_debug["account_type"] == "fake_followers"
].copy()

fake_analysis["correct"] = (
    fake_analysis["text_pred"] == fake_analysis["label"]
)

print("Fake Followers by tweet count used")
print(
    fake_analysis.groupby("tweet_count_used")["correct"]
    .agg(["count", "sum", "mean"])
    .rename(columns={
        "sum": "correct_count",
        "mean": "accuracy"
    })
)

print("\nOverall tweet-count statistics:")
print(fake_analysis["tweet_count_used"].describe())

Fake Followers by tweet count used
                  count  correct_count  accuracy
tweet_count_used
1                   114             85  0.745614
2                    90             73  0.811111
3                    76             65  0.855263
4                    39             33  0.846154
5                    26             15  0.576923
...                 ...            ...       ...
95                    1              1  1.000000
96                    3              2  0.666667
97                    1              0  0.000000
98                    1              0  0.000000
100                 175             78  0.445714

[97 rows x 3 columns]

Overall tweet-count statistics:
count    3202.000000
mean       31.183635
std        24.314905
min         1.000000
25%        17.000000
50%        23.000000
75%        40.000000
max       100.000000
Name: tweet_count_used, dtype: float64

In [ ]:
# ============================================================
# WRONG FAKE FOLLOWERS — TWEET COUNT ANALYSIS
# ============================================================

fake_wrong = fake_analysis[
    fake_analysis["correct"] == False
].copy()

print("Wrong Fake Followers:", len(fake_wrong))

print("\nTweet count distribution among wrong predictions:")
print(fake_wrong["tweet_count_used"].describe())

print("\nTweet count distribution:")
print(
    fake_wrong["tweet_count_used"]
    .value_counts()
    .sort_index()
    .head(30)
)

Wrong Fake Followers: 459

Tweet count distribution among wrong predictions:
count    459.000000
mean      38.385621
std       37.057572
min        1.000000
25%        9.000000
50%       22.000000
75%       71.000000
max      100.000000
Name: tweet_count_used, dtype: float64

Tweet count distribution:
tweet_count_used
1     29
2     17
3     11
4      6
5     11
6     16
7     11
8     12
9      7
10     6
11     6
12    10
13     9
14     2
15    10
16     6
17     8
18     8
19    13
20     8
21    14
22    18
23    12
24    11
25     8
26     4
27     5
28     5
29     5
30     6
Name: count, dtype: int64

In [ ]:
# ============================================================
# TEXT MODEL ACCURACY BY EVIDENCE LEVEL
# ============================================================

bins = [0, 1, 5, 10, 25, 50, 100]
labels = [
    "1 tweet",
    "2–5 tweets",
    "6–10 tweets",
    "11–25 tweets",
    "26–50 tweets",
    "51–100 tweets"
]

fake_analysis["text_evidence_level"] = pd.cut(
    fake_analysis["tweet_count_used"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

print(
    fake_analysis.groupby(
        "text_evidence_level",
        observed=False
    )["correct"]
    .agg(["count", "sum", "mean"])
    .rename(columns={
        "sum": "correct_count",
        "mean": "accuracy"
    })
)

                     count  correct_count  accuracy
text_evidence_level
1 tweet                114             85  0.745614
2–5 tweets             231            186  0.805195
6–10 tweets             95             43  0.452632
11–25 tweets          1349           1206  0.893996
26–50 tweets           822            764  0.929440
51–100 tweets          591            459  0.776650

In [ ]:
# Find variables related to LOBO behavioral test probabilities

[c for c in globals() if "lobo" in c.lower() and "prob" in c.lower()]

['lobo_behavior_prob', 'behavior_lobo_val_prob', 'behavior_lobo_test_prob']

In [ ]:
# ============================================================
# BEHAVIOR vs TEXT AGREEMENT ANALYSIS
# ============================================================

behavior_test_prob = behavior_lobo_test_prob
behavior_test_pred = (behavior_test_prob >= 0.5).astype(int)

text_test_pred = text_debug["text_pred"].values
true_labels = text_debug["label"].values

# Safety checks
assert len(behavior_test_prob) == len(text_debug)
assert len(text_test_pred) == len(true_labels)

comparison = pd.DataFrame({
    "label": true_labels,
    "behavior_prob": behavior_test_prob,
    "behavior_pred": behavior_test_pred,
    "text_prob": text_debug["text_prob"].values,
    "text_pred": text_test_pred
})

comparison["behavior_correct"] = (
    comparison["behavior_pred"] == comparison["label"]
)

comparison["text_correct"] = (
    comparison["text_pred"] == comparison["label"]
)

comparison["agreement"] = (
    comparison["behavior_pred"] == comparison["text_pred"]
)

print("================================================")
print("BEHAVIOR vs TEXT AGREEMENT")
print("================================================")

print("\nOverall agreement:")
print(f"{comparison['agreement'].mean()*100:.2f}%")

print("\nAgreement counts:")
print(comparison["agreement"].value_counts())

print("\nCorrectness by agreement:")
print(
    comparison.groupby("agreement")[
        ["behavior_correct", "text_correct"]
    ].mean().round(4)
)

print("\nConfusion between behavior and text:")
print(
    pd.crosstab(
        comparison["behavior_pred"],
        comparison["text_pred"],
        rownames=["Behavior"],
        colnames=["Text"]
    )
)

================================================
BEHAVIOR vs TEXT AGREEMENT
================================================

Overall agreement:
66.23%

Agreement counts:
agreement
True     2838
False    1447
Name: count, dtype: int64

Correctness by agreement:
           behavior_correct  text_correct
agreement
False                0.2053        0.7947
True                 0.9338        0.9338

Confusion between behavior and text:
Text        0     1
Behavior
0         801   732
1         715  2037

In [ ]:
# ============================================================
# DISAGREEMENT CASES
# ============================================================

disagreement = comparison[
    comparison["behavior_pred"] != comparison["text_pred"]
].copy()

behavior_correct_text_wrong = (
    disagreement["behavior_correct"] &
    ~disagreement["text_correct"]
).sum()

behavior_wrong_text_correct = (
    ~disagreement["behavior_correct"] &
    disagreement["text_correct"]
).sum()

both_wrong = (
    ~disagreement["behavior_correct"] &
    ~disagreement["text_correct"]
).sum()

print("================================================")
print("DISAGREEMENT ANALYSIS")
print("================================================")

print("Total disagreement:", len(disagreement))
print()
print("Behavior correct / Text wrong:",
      behavior_correct_text_wrong)
print("Behavior wrong / Text correct:",
      behavior_wrong_text_correct)
print("Both wrong:", both_wrong)

print("\nDetailed disagreement table:")
display(
    disagreement[
        [
            "label",
            "behavior_prob",
            "behavior_pred",
            "text_prob",
            "text_pred",
            "behavior_correct",
            "text_correct"
        ]
    ].head(30)
)

================================================
DISAGREEMENT ANALYSIS
================================================
Total disagreement: 1447

Behavior correct / Text wrong: 297
Behavior wrong / Text correct: 1150
Both wrong: 0

Detailed disagreement table:

,label,behavior_prob,behavior_pred,text_prob,text_pred,behavior_correct,text_correct
0,0,1.0,1,0.038584,0,False,True
1,0,1.0,1,0.023926,0,False,True
2,0,1.0,1,0.076167,0,False,True
3,0,1.0,1,0.009980,0,False,True
4,0,1.0,1,0.206501,0,False,True
5,0,1.0,1,0.043858,0,False,True
6,0,1.0,1,0.034981,0,False,True
7,0,1.0,1,0.251385,0,False,True
8,0,1.0,1,0.026011,0,False,True
10,0,1.0,1,0.008867,0,False,True
11,0,1.0,1,0.014611,0,False,True
12,0,1.0,1,0.020983,0,False,True
14,0,1.0,1,0.125681,0,False,True
17,0,1.0,1,0.016856,0,False,True
18,0,1.0,1,0.018570,0,False,True
21,0,1.0,1,0.106300,0,False,True
22,0,1.0,1,0.038978,0,False,True
23,0,1.0,1,0.036313,0,False,True
24,0,1.0,1,0.139824,0,False,True
25,0,1.0,1,0.080147,0,False,True
28,0,1.0,1,0.007626,0,False,True
30,1,1.0,1,0.044259,0,True,False
31,0,1.0,1,0.420350,0,False,True
32,0,1.0,1,0.481377,0,False,True
33,0,1.0,1,0.068308,0,False,True
34,0,1.0,1,0.010302,0,False,True
36,0,1.0,1,0.131341,0,False,True
37,0,1.0,1,0.016273,0,False,True
38,0,1.0,1,0.009634,0,False,True
39,0,1.0,1,0.014883,0,False,True

In [ ]:
# ============================================================
# DISAGREEMENT DIRECTION ANALYSIS
# ============================================================

disagreement = comparison[
    comparison["behavior_pred"] != comparison["text_pred"]
].copy()

# Direction of disagreement
disagreement["direction"] = np.where(
    disagreement["behavior_pred"] == 1,
    "Behavior=Bot / Text=Genuine",
    "Behavior=Genuine / Text=Bot"
)

print("================================================")
print("DISAGREEMENT DIRECTION")
print("================================================")

print(
    disagreement["direction"].value_counts()
)

print("\nCorrectness by disagreement direction:")

print(
    disagreement.groupby("direction")[
        ["behavior_correct", "text_correct"]
    ].mean().round(4)
)

================================================
DISAGREEMENT DIRECTION
================================================
direction
Behavior=Genuine / Text=Bot    732
Behavior=Bot / Text=Genuine    715
Name: count, dtype: int64

Correctness by disagreement direction:
                             behavior_correct  text_correct
direction
Behavior=Bot / Text=Genuine            0.3916        0.6084
Behavior=Genuine / Text=Bot            0.0232        0.9768

In [ ]:
# ============================================================
# PROBABILITY STRENGTH DURING DISAGREEMENTS
# ============================================================

disagreement["behavior_confidence"] = (
    np.abs(disagreement["behavior_prob"] - 0.5) * 2
)

disagreement["text_confidence"] = (
    np.abs(disagreement["text_prob"] - 0.5) * 2
)

print("================================================")
print("CONFIDENCE DURING DISAGREEMENTS")
print("================================================")

print(
    disagreement.groupby("direction")[
        [
            "behavior_prob",
            "text_prob",
            "behavior_confidence",
            "text_confidence"
        ]
    ].agg(["mean", "median"])
)

================================================
CONFIDENCE DURING DISAGREEMENTS
================================================
                            behavior_prob        text_prob            \
                                     mean median      mean    median
direction
Behavior=Bot / Text=Genuine      0.960537    1.0  0.132866  0.062734
Behavior=Genuine / Text=Bot      0.002437    0.0  0.869328  0.925916

                            behavior_confidence        text_confidence  \
                                           mean median            mean
direction
Behavior=Bot / Text=Genuine            0.921074    1.0        0.734268
Behavior=Genuine / Text=Bot            0.995127    1.0        0.738657


                               median
direction
Behavior=Bot / Text=Genuine  0.874532
Behavior=Genuine / Text=Bot  0.851832

In [ ]:
# ============================================================
# WHO IS MORE CONFIDENT WHEN THEY DISAGREE?
# ============================================================

disagreement["behavior_more_confident"] = (
    disagreement["behavior_confidence"] >
    disagreement["text_confidence"]
)

print(
    disagreement.groupby("behavior_more_confident")[
        ["behavior_correct", "text_correct"]
    ].mean().round(4)
)

print("\nCounts:")
print(
    disagreement["behavior_more_confident"].value_counts()
)

                         behavior_correct  text_correct
behavior_more_confident
False                              0.0156        0.9844
True                               0.2140        0.7860

Counts:
behavior_more_confident
True     1383
False      64
Name: count, dtype: int64

In [ ]:
# ============================================================
# DISAGREEMENT: PROBABILITY GAP vs CORRECT MODEL
# ============================================================

disagreement = comparison[
    comparison["behavior_pred"] != comparison["text_pred"]
].copy()

disagreement["behavior_confidence"] = (
    np.abs(disagreement["behavior_prob"] - 0.5) * 2
)

disagreement["text_confidence"] = (
    np.abs(disagreement["text_prob"] - 0.5) * 2
)

disagreement["confidence_gap"] = (
    disagreement["behavior_confidence"] -
    disagreement["text_confidence"]
)

disagreement["correct_model"] = np.where(
    disagreement["behavior_correct"],
    "Behavior",
    "Text"
)

print("================================================")
print("CONFIDENCE GAP")
print("================================================")

print(
    disagreement.groupby("correct_model")[
        "confidence_gap"
    ].agg(["count", "mean", "median", "std", "min", "max"])
)

================================================
CONFIDENCE GAP
================================================
               count      mean    median       std       min       max
correct_model
Behavior         297  0.498783  0.503613  0.314436 -0.557900  0.998309
Text            1150  0.150577  0.097513  0.319381 -0.958581  0.991004

In [ ]:
# ============================================================
# CAN CONFIDENCE GAP SELECT THE CORRECT MODEL?
# ============================================================

bins = [-2, -0.5, -0.2, 0, 0.2, 0.5, 2]
labels = [
    "Text much more confident",
    "Text moderately more confident",
    "Text slightly more confident",
    "Behavior slightly more confident",
    "Behavior moderately more confident",
    "Behavior much more confident"
]

disagreement["confidence_gap_group"] = pd.cut(
    disagreement["confidence_gap"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

gap_analysis = disagreement.groupby(
    "confidence_gap_group",
    observed=False
)["text_correct"].agg(
    ["count", "mean"]
)

gap_analysis["text_accuracy_percent"] = (
    gap_analysis["mean"] * 100
)

print(gap_analysis)

                                    count      mean  text_accuracy_percent
confidence_gap_group
Text much more confident               57  0.982456              98.245614
Text moderately more confident          5  1.000000             100.000000
Text slightly more confident            2  1.000000             100.000000
Behavior slightly more confident      792  0.916667              91.666667
Behavior moderately more confident    305  0.737705              73.770492
Behavior much more confident          286  0.475524              47.552448

In [ ]:
# ============================================================
# VALIDATION: DIRECTION-AWARE FUSION ANALYSIS
# ============================================================

val_comparison = pd.DataFrame({
    "label": lobo_val["label"].values,
    "behavior_prob": behavior_lobo_val_prob,
    "text_prob": text_val_prob
})

val_comparison["behavior_pred"] = (
    val_comparison["behavior_prob"] >= 0.5
).astype(int)

val_comparison["text_pred"] = (
    val_comparison["text_prob"] >= 0.5
).astype(int)

val_comparison["agreement"] = (
    val_comparison["behavior_pred"] ==
    val_comparison["text_pred"]
)

val_comparison["direction"] = np.where(
    val_comparison["behavior_pred"] == 0,
    "Behavior=Genuine / Text=Bot",
    "Behavior=Bot / Text=Genuine"
)

print("================================================")
print("VALIDATION DISAGREEMENT ANALYSIS")
print("================================================")

print(
    val_comparison.groupby(
        ["agreement", "direction"],
        dropna=False
    ).size()
)

print("\nOverall agreement:")
print(
    val_comparison["agreement"].mean() * 100
)

================================================
VALIDATION DISAGREEMENT ANALYSIS
================================================
agreement  direction
False      Behavior=Bot / Text=Genuine      12
           Behavior=Genuine / Text=Bot      14
True       Behavior=Bot / Text=Genuine    1164
           Behavior=Genuine / Text=Bot     209
dtype: int64

Overall agreement:
98.14152966404575

In [ ]:
# ============================================================
# VALIDATION: DISAGREEMENT CORRECTNESS
# ============================================================

val_disagreement = val_comparison[
    ~val_comparison["agreement"]
].copy()

val_disagreement["behavior_correct"] = (
    val_disagreement["behavior_pred"] ==
    val_disagreement["label"]
)

val_disagreement["text_correct"] = (
    val_disagreement["text_pred"] ==
    val_disagreement["label"]
)

print(
    val_disagreement.groupby("direction")[
        ["behavior_correct", "text_correct"]
    ].agg(["count", "mean"])
)

                            behavior_correct           text_correct
                                       count      mean        count      mean
direction
Behavior=Bot / Text=Genuine               12  0.750000           12  0.250000
Behavior=Genuine / Text=Bot               14  0.357143           14  0.642857

In [ ]:
import numpy as np
import pandas as pd

# ============================================
# VALIDATION: DISAGREEMENT + DRIFT ANALYSIS
# ============================================

val_analysis = pd.DataFrame({
    "label": lobo_val["label"].values,
    "behavior_prob": behavior_lobo_val_prob,
    "text_prob": text_val_prob,
    "drift_score": val_drift_score
})

# Predictions
val_analysis["behavior_pred"] = (
    val_analysis["behavior_prob"] >= 0.5
).astype(int)

val_analysis["text_pred"] = (
    val_analysis["text_prob"] >= 0.5
).astype(int)

# Agreement / disagreement
val_analysis["agreement"] = (
    val_analysis["behavior_pred"] == val_analysis["text_pred"]
)

# Direction
val_analysis["direction"] = np.where(
    val_analysis["behavior_pred"] == 1,
    "Behavior=Bot / Text=Genuine",
    "Behavior=Genuine / Text=Bot"
)

# Correctness
val_analysis["behavior_correct"] = (
    val_analysis["behavior_pred"] == val_analysis["label"]
)

val_analysis["text_correct"] = (
    val_analysis["text_pred"] == val_analysis["label"]
)

# ============================================
# ONLY DISAGREEMENT CASES
# ============================================

disagree_val = val_analysis[
    ~val_analysis["agreement"]
].copy()

print("=" * 55)
print("VALIDATION DISAGREEMENT + DRIFT ANALYSIS")
print("=" * 55)

print("\nTotal validation accounts:", len(val_analysis))
print("Agreement:", val_analysis["agreement"].sum())
print("Disagreement:", len(disagree_val))

print("\n--- Disagreement by direction ---")

direction_result = disagree_val.groupby("direction").agg(
    cases=("label", "count"),
    behavior_correct=("behavior_correct", "mean"),
    text_correct=("text_correct", "mean"),
    mean_drift=("drift_score", "mean"),
    median_drift=("drift_score", "median")
)

direction_result["behavior_correct"] *= 100
direction_result["text_correct"] *= 100

print(direction_result)


# ============================================
# DRIFT GROUPS
# ============================================

def drift_group(score):
    if score < 0.80:
        return "Reliable"
    elif score < 0.95:
        return "Review"
    else:
        return "High Drift"

disagree_val["drift_group"] = disagree_val["drift_score"].apply(
    drift_group
)

print("\n--- Disagreement cases by drift group ---")

drift_result = disagree_val.groupby("drift_group").agg(
    cases=("label", "count"),
    behavior_correct=("behavior_correct", "mean"),
    text_correct=("text_correct", "mean"),
    mean_drift=("drift_score", "mean")
)

drift_result["behavior_correct"] *= 100
drift_result["text_correct"] *= 100

print(drift_result)


# ============================================
# DIRECTION + DRIFT COMBINATION
# ============================================

print("\n--- Direction × Drift Group ---")

direction_drift = disagree_val.groupby(
    ["direction", "drift_group"]
).agg(
    cases=("label", "count"),
    behavior_correct=("behavior_correct", "mean"),
    text_correct=("text_correct", "mean")
)

direction_drift["behavior_correct"] *= 100
direction_drift["text_correct"] *= 100

print(direction_drift)


# ============================================
# CONFIDENCE
# ============================================

disagree_val["behavior_confidence"] = (
    np.abs(disagree_val["behavior_prob"] - 0.5) * 2
)

disagree_val["text_confidence"] = (
    np.abs(disagree_val["text_prob"] - 0.5) * 2
)

print("\n--- Confidence on disagreement cases ---")

print(
    disagree_val.groupby("direction")[
        ["behavior_confidence", "text_confidence"]
    ].agg(["mean", "median"])
)

=======================================================
VALIDATION DISAGREEMENT + DRIFT ANALYSIS
=======================================================

Total validation accounts: 1399
Agreement: 1373
Disagreement: 26

--- Disagreement by direction ---
                             cases  behavior_correct  text_correct  \
direction
Behavior=Bot / Text=Genuine     12         75.000000     25.000000
Behavior=Genuine / Text=Bot     14         35.714286     64.285714

                             mean_drift  median_drift
direction
Behavior=Bot / Text=Genuine    0.767081      0.710776
Behavior=Genuine / Text=Bot    0.761603      0.832916

--- Disagreement cases by drift group ---
             cases  behavior_correct  text_correct  mean_drift
drift_group
High Drift       6         16.666667     83.333333    0.981564
Reliable        14         78.571429     21.428571    0.627157
Review           6         33.333333     66.666667    0.866303

--- Direction × Drift Group ---
                                         cases  behavior_correct  text_correct
direction                   drift_group
Behavior=Bot / Text=Genuine High Drift       3         33.333333     66.666667
                            Reliable         8         87.500000     12.500000
                            Review           1        100.000000      0.000000
Behavior=Genuine / Text=Bot High Drift       3          0.000000    100.000000
                            Reliable         6         66.666667     33.333333
                            Review           5         20.000000     80.000000

--- Confidence on disagreement cases ---
                            behavior_confidence           text_confidence  \
                                           mean    median            mean
direction
Behavior=Bot / Text=Genuine            0.911394  0.969393        0.631208
Behavior=Genuine / Text=Bot            0.876494  0.976790        0.799792


                               median
direction
Behavior=Bot / Text=Genuine  0.770264
Behavior=Genuine / Text=Bot  0.984766

In [ ]:
# ============================================
# DRIFT-AWARE FUSION — VALIDATION
# ============================================

def drift_aware_fusion(
    behavior_prob,
    text_prob,
    drift_score,
    reliable_threshold=0.80,
    review_threshold=0.95
):
    behavior_pred = (behavior_prob >= 0.5).astype(int)
    text_pred = (text_prob >= 0.5).astype(int)

    final_pred = behavior_pred.copy()

    # Where models disagree
    disagreement = behavior_pred != text_pred

    # Drift groups
    reliable = drift_score < reliable_threshold
    review = (
        (drift_score >= reliable_threshold) &
        (drift_score < review_threshold)
    )
    high_drift = drift_score >= review_threshold

    # Reliable disagreement -> trust behavior
    reliable_disagreement = disagreement & reliable

    # Review / High Drift disagreement -> trust text
    text_disagreement = disagreement & (review | high_drift)

    final_pred[reliable_disagreement] = behavior_pred[
        reliable_disagreement
    ]

    final_pred[text_disagreement] = text_pred[
        text_disagreement
    ]

    return final_pred


# ============================================
# VALIDATION PREDICTION
# ============================================

drift_fusion_val_pred = drift_aware_fusion(
    behavior_lobo_val_prob,
    text_val_prob,
    val_drift_score
)

y_val = lobo_val["label"].values

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

print("=" * 55)
print("DRIFT-AWARE FUSION — VALIDATION")
print("=" * 55)

print(f"Accuracy : {accuracy_score(y_val, drift_fusion_val_pred)*100:.2f}%")
print(f"Precision: {precision_score(y_val, drift_fusion_val_pred)*100:.2f}%")
print(f"Recall   : {recall_score(y_val, drift_fusion_val_pred)*100:.2f}%")
print(f"F1 Score : {f1_score(y_val, drift_fusion_val_pred)*100:.2f}%")

print("\nConfusion Matrix:")
print(confusion_matrix(y_val, drift_fusion_val_pred))

print("\nPredictions changed from behavior:")
print(
    np.sum(
        drift_fusion_val_pred !=
        (behavior_lobo_val_prob >= 0.5).astype(int)
    )
)

=======================================================
DRIFT-AWARE FUSION — VALIDATION
=======================================================
Accuracy : 99.57%
Precision: 99.83%
Recall   : 99.66%
F1 Score : 99.75%

Confusion Matrix:
[[ 215    2]
 [   4 1178]]

Predictions changed from behavior:
12

In [ ]:
# ============================================
# VALIDATION — HOW THE RULE ACTED
# ============================================

behavior_val_pred = (
    behavior_lobo_val_prob >= 0.5
).astype(int)

text_val_pred = (
    text_val_prob >= 0.5
).astype(int)

val_rule_analysis = pd.DataFrame({
    "label": y_val,
    "behavior_pred": behavior_val_pred,
    "text_pred": text_val_pred,
    "drift_score": val_drift_score,
    "final_pred": drift_fusion_val_pred
})

val_rule_analysis["agreement"] = (
    val_rule_analysis["behavior_pred"] ==
    val_rule_analysis["text_pred"]
)

val_rule_analysis["drift_group"] = val_rule_analysis[
    "drift_score"
].apply(drift_group)

print("\n" + "=" * 55)
print("DRIFT-AWARE FUSION — DECISION BREAKDOWN")
print("=" * 55)

print("\nPredictions by drift group:")
print(
    val_rule_analysis.groupby("drift_group").agg(
        accounts=("label", "count"),
        behavior_correct=(
            "behavior_pred",
            lambda x: np.mean(
                x.values ==
                val_rule_analysis.loc[x.index, "label"].values
            ) * 100
        ),
        text_correct=(
            "text_pred",
            lambda x: np.mean(
                x.values ==
                val_rule_analysis.loc[x.index, "label"].values
            ) * 100
        ),
        final_correct=(
            "final_pred",
            lambda x: np.mean(
                x.values ==
                val_rule_analysis.loc[x.index, "label"].values
            ) * 100
        )
    )
)

print("\nDisagreement cases:")
print(
    val_rule_analysis[
        ~val_rule_analysis["agreement"]
    ].groupby("drift_group").agg(
        cases=("label", "count"),
        final_correct=(
            "final_pred",
            lambda x: np.mean(
                x.values ==
                val_rule_analysis.loc[x.index, "label"].values
            ) * 100
        )
    )
)

=======================================================
DRIFT-AWARE FUSION — DECISION BREAKDOWN
=======================================================

Predictions by drift group:
             accounts  behavior_correct  text_correct  final_correct
drift_group
High Drift         79         93.670886     98.734177      98.734177
Reliable         1111         99.729973     99.009901      99.729973
Review            209         98.086124     99.043062      99.043062

Disagreement cases:
             cases  final_correct
drift_group
High Drift       6      83.333333
Reliable        14      78.571429
Review           6      66.666667

In [ ]:
# ============================================
# FROZEN DRIFT-AWARE FUSION
# FINAL LOBO TEST
# ============================================

drift_fusion_test_pred = drift_aware_fusion(
    behavior_lobo_test_prob,
    text_test_prob,
    test_drift_score
)

y_test = lobo_test["label"].values

print("=" * 60)
print("FROZEN DRIFT-AWARE FUSION")
print("FINAL LOBO TEST — UNSEEN FAKE FOLLOWERS")
print("=" * 60)

print(
    f"Accuracy : {accuracy_score(y_test, drift_fusion_test_pred)*100:.2f}%"
)

print(
    f"Precision: {precision_score(y_test, drift_fusion_test_pred)*100:.2f}%"
)

print(
    f"Recall   : {recall_score(y_test, drift_fusion_test_pred)*100:.2f}%"
)

print(
    f"F1 Score : {f1_score(y_test, drift_fusion_test_pred)*100:.2f}%"
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, drift_fusion_test_pred))

# How many predictions changed relative to behavior-only?
behavior_test_pred = (
    behavior_lobo_test_prob >= 0.5
).astype(int)

print(
    "\nPredictions changed from behavior:",
    np.sum(drift_fusion_test_pred != behavior_test_pred)
)

============================================================
FROZEN DRIFT-AWARE FUSION
FINAL LOBO TEST — UNSEEN FAKE FOLLOWERS
============================================================
Accuracy : 68.17%
Precision: 86.07%
Recall   : 68.49%
F1 Score : 76.28%

Confusion Matrix:
[[ 728  355]
 [1009 2193]]

Predictions changed from behavior: 812

In [ ]:
# ============================================
# TEST DECISION BREAKDOWN
# ============================================

test_rule_analysis = pd.DataFrame({
    "label": y_test,
    "behavior_pred": behavior_test_pred,
    "text_pred": (text_test_prob >= 0.5).astype(int),
    "drift_score": test_drift_score,
    "final_pred": drift_fusion_test_pred
})

test_rule_analysis["agreement"] = (
    test_rule_analysis["behavior_pred"] ==
    test_rule_analysis["text_pred"]
)

test_rule_analysis["drift_group"] = (
    test_rule_analysis["drift_score"].apply(drift_group)
)

print("\n" + "=" * 60)
print("TEST DECISION BREAKDOWN")
print("=" * 60)

print("\nAccounts by drift group:")
print(
    test_rule_analysis.groupby("drift_group").agg(
        accounts=("label", "count"),
        behavior_correct=(
            "behavior_pred",
            lambda x: np.mean(
                x.values ==
                test_rule_analysis.loc[x.index, "label"].values
            ) * 100
        ),
        text_correct=(
            "text_pred",
            lambda x: np.mean(
                x.values ==
                test_rule_analysis.loc[x.index, "label"].values
            ) * 100
        ),
        final_correct=(
            "final_pred",
            lambda x: np.mean(
                x.values ==
                test_rule_analysis.loc[x.index, "label"].values
            ) * 100
        )
    )
)

print("\nDisagreement cases:")
print(
    test_rule_analysis[
        ~test_rule_analysis["agreement"]
    ].groupby("drift_group").agg(
        cases=("label", "count"),
        behavior_correct=(
            "behavior_pred",
            lambda x: np.mean(
                x.values ==
                test_rule_analysis.loc[x.index, "label"].values
            ) * 100
        ),
        text_correct=(
            "text_pred",
            lambda x: np.mean(
                x.values ==
                test_rule_analysis.loc[x.index, "label"].values
            ) * 100
        ),
        final_correct=(
            "final_pred",
            lambda x: np.mean(
                x.values ==
                test_rule_analysis.loc[x.index, "label"].values
            ) * 100
        )
    )
)

============================================================
TEST DECISION BREAKDOWN
============================================================

Accounts by drift group:
             accounts  behavior_correct  text_correct  final_correct
drift_group
High Drift        843         24.673784     65.717675      65.717675
Reliable         2185         63.981693     77.391304      63.981693
Review           1257         54.972156     77.088305      77.088305

Disagreement cases:
             cases  behavior_correct  text_correct  final_correct
drift_group
High Drift     398          6.532663     93.467337      93.467337
Reliable       635         26.929134     73.070866      26.929134
Review         414         16.425121     83.574879      83.574879

In [ ]:
# ============================================
# CELL 1 — VERIFY META-FUSION INPUTS
# ============================================

print("=" * 60)
print("META-FUSION INPUT VERIFICATION")
print("=" * 60)

print("\n--- OOF TRAINING DATA ---")
print("OOF behavior:", len(oof_behavior_prob))
print("OOF text    :", len(oof_text_prob))
print("LOBO train :", len(lobo_train))
print("LOBO train labels:", len(lobo_train["label"]))

print("\n--- VALIDATION ---")
print("Behavior validation:", len(behavior_lobo_val_prob))
print("Text validation    :", len(text_val_prob))
print("Drift validation   :", len(val_drift_score))
print("LOBO validation    :", len(lobo_val))
print("Validation labels  :", len(lobo_val["label"]))

print("\n--- FINAL TEST ---")
print("Behavior test:", len(behavior_lobo_test_prob))
print("Text test    :", len(text_test_prob))
print("Drift test  :", len(test_drift_score))
print("LOBO test    :", len(lobo_test))
print("Test labels  :", len(lobo_test["label"]))


# ============================================
# ASSERTIONS — STOP IF ANYTHING IS MISALIGNED
# ============================================

assert len(oof_behavior_prob) == len(lobo_train)
assert len(oof_text_prob) == len(lobo_train)

assert len(behavior_lobo_val_prob) == len(lobo_val)
assert len(text_val_prob) == len(lobo_val)
assert len(val_drift_score) == len(lobo_val)

assert len(behavior_lobo_test_prob) == len(lobo_test)
assert len(text_test_prob) == len(lobo_test)
assert len(test_drift_score) == len(lobo_test)

print("\n✅ ALL LENGTH CHECKS PASSED")
print("No array-length mismatch detected.")

============================================================
META-FUSION INPUT VERIFICATION
============================================================

--- OOF TRAINING DATA ---
OOF behavior: 6995
OOF text    : 6995
LOBO train : 6995
LOBO train labels: 6995

--- VALIDATION ---
Behavior validation: 1399
Text validation    : 1399
Drift validation   : 1399
LOBO validation    : 1399
Validation labels  : 1399

--- FINAL TEST ---
Behavior test: 4285
Text test    : 4285
Drift test  : 4285
LOBO test    : 4285
Test labels  : 4285

✅ ALL LENGTH CHECKS PASSED
No array-length mismatch detected.

In [ ]:
# ============================================
# CELL 2 — BUILD OOF META-FEATURES
# ============================================

import numpy as np
import pandas as pd

# OOF predictions from the known-category training pool
meta_oof = pd.DataFrame({
    "behavior_prob": np.asarray(oof_behavior_prob),
    "text_prob": np.asarray(oof_text_prob)
})

# Confidence of each model
meta_oof["behavior_confidence"] = (
    np.abs(meta_oof["behavior_prob"] - 0.5) * 2
)

meta_oof["text_confidence"] = (
    np.abs(meta_oof["text_prob"] - 0.5) * 2
)

# Difference between modalities
meta_oof["prob_difference"] = (
    meta_oof["behavior_prob"] -
    meta_oof["text_prob"]
)

meta_oof["absolute_difference"] = (
    np.abs(meta_oof["prob_difference"])
)

# Agreement
meta_oof["behavior_pred"] = (
    meta_oof["behavior_prob"] >= 0.5
).astype(int)

meta_oof["text_pred"] = (
    meta_oof["text_prob"] >= 0.5
).astype(int)

meta_oof["agreement"] = (
    meta_oof["behavior_pred"] ==
    meta_oof["text_pred"]
).astype(int)

# ============================================
# ADD DRIFT FOR OOF ACCOUNTS
# ============================================

# IMPORTANT:
# OOF drift must be calculated using the same
# training-only drift framework.
#
# For now, calculate drift for the complete
# known-category training pool using the
# already-fitted training drift model.

X_oof_drift_raw = lobo_train[behavior_features].copy()

X_oof_drift_imputed = drift_imputer_final.transform(
    X_oof_drift_raw
)

X_oof_drift_scaled = drift_scaler_final.transform(
    X_oof_drift_imputed
)

oof_mahal = drift_cov_model_final.mahalanobis(
    X_oof_drift_scaled
)

# Convert Mahalanobis distance to empirical
# percentile relative to the frozen training
# reference distribution.

oof_drift_score = np.searchsorted(
    train_mahal_sorted,
    oof_mahal,
    side="right"
) / len(train_mahal_sorted)

meta_oof["drift_score"] = oof_drift_score

# ============================================
# INTERACTION FEATURES
# ============================================

meta_oof["behavior_drift_interaction"] = (
    meta_oof["behavior_prob"] *
    meta_oof["drift_score"]
)

meta_oof["text_drift_interaction"] = (
    meta_oof["text_prob"] *
    meta_oof["drift_score"]
)

meta_oof["behavior_conf_drift"] = (
    meta_oof["behavior_confidence"] *
    meta_oof["drift_score"]
)

meta_oof["text_conf_drift"] = (
    meta_oof["text_confidence"] *
    meta_oof["drift_score"]
)

# ============================================
# LABEL
# ============================================

meta_oof["label"] = lobo_train["label"].values

print("=" * 60)
print("OOF META-FEATURES")
print("=" * 60)

print("\nShape:", meta_oof.shape)

print("\nColumns:")
print(meta_oof.columns.tolist())

print("\nLabel distribution:")
print(meta_oof["label"].value_counts().sort_index())

print("\nDrift statistics:")
print(meta_oof["drift_score"].describe())

print("\nFirst 5 rows:")
print(meta_oof.head())

print("\n✅ OOF META-FEATURES CREATED")

============================================================
OOF META-FEATURES
============================================================

Shape: (6995, 15)

Columns:
['behavior_prob', 'text_prob', 'behavior_confidence', 'text_confidence', 'prob_difference', 'absolute_difference', 'behavior_pred', 'text_pred', 'agreement', 'drift_score', 'behavior_drift_interaction', 'text_drift_interaction', 'behavior_conf_drift', 'text_conf_drift', 'label']

Label distribution:
label
0    1083
1    5912
Name: count, dtype: int64

Drift statistics:
count    6995.000000
mean        0.500834
std         0.287868
min         0.000179
25%         0.252859
50%         0.500179
75%         0.748302
max         1.000000
Name: drift_score, dtype: float64

First 5 rows:
   behavior_prob  text_prob  behavior_confidence  text_confidence  \
0       0.000084   0.103685             0.999833         0.792631
1       0.169220   0.060591             0.661561         0.878818
2       0.030472   0.178456             0.939057         0.643087
3       0.068592   0.010098             0.862816         0.979803
4       0.559983   0.292565             0.119967         0.414870

   prob_difference  absolute_difference  behavior_pred  text_pred  agreement  \
0        -0.103601             0.103601              0          0          1
1         0.108629             0.108629              0          0          1
2        -0.147985             0.147985              0          0          1
3         0.058494             0.058494              0          0          1
4         0.267419             0.267419              1          0          0

   drift_score  behavior_drift_interaction  text_drift_interaction  \
0     0.998392                    0.000084                0.103518
1     0.869371                    0.147115                0.052676
2     0.971587                    0.029606                0.173386
3     0.827019                    0.056727                0.008352
4     0.933881                    0.522958                0.273221

   behavior_conf_drift  text_conf_drift  label
0             0.998225         0.791356      0
1             0.575142         0.764019      0
2             0.912375         0.624815      0
3             0.713566         0.810316      0
4             0.112035         0.387440      0

✅ OOF META-FEATURES CREATED

In [ ]:
# ============================================
# CELL 3 — STRICT OOF DRIFT SCORES
# ============================================

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.covariance import LedoitWolf
from sklearn.model_selection import StratifiedKFold

# Same feature list used for behavioral drift
behavior_features = [
    "statuses_count",
    "followers_count",
    "friends_count",
    "favourites_count",
    "listed_count",
    "account_age_days",
    "statuses_per_day",
    "followers_friends_ratio",
    "friends_followers_ratio",
    "favorites_per_status",
    "log_statuses_count",
    "log_followers_count",
    "log_friends_count",
    "log_favourites_count",
    "log_listed_count"
]

X_lobo_train_raw = lobo_train[behavior_features].copy()
y_lobo_train = lobo_train["label"].values

# Must match the OOF prediction generation
skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

strict_oof_drift = np.zeros(len(lobo_train))

for fold, (train_idx, val_idx) in enumerate(
    skf.split(X_lobo_train_raw, y_lobo_train), 1
):

    # ----------------------------------------
    # Fold training data ONLY
    # ----------------------------------------
    X_fold_train = X_lobo_train_raw.iloc[train_idx]
    X_fold_val = X_lobo_train_raw.iloc[val_idx]

    # Fit preprocessing ONLY on fold training
    fold_imputer = SimpleImputer(strategy="median")

    X_fold_train_imp = fold_imputer.fit_transform(
        X_fold_train
    )

    X_fold_val_imp = fold_imputer.transform(
        X_fold_val
    )

    fold_scaler = StandardScaler()

    X_fold_train_scaled = fold_scaler.fit_transform(
        X_fold_train_imp
    )

    X_fold_val_scaled = fold_scaler.transform(
        X_fold_val_imp
    )

    # ----------------------------------------
    # Fit covariance ONLY on fold training
    # ----------------------------------------
    fold_cov = LedoitWolf()

    fold_cov.fit(
        X_fold_train_scaled
    )

    # ----------------------------------------
    # Training Mahalanobis distances
    # ----------------------------------------
    fold_train_mahal = fold_cov.mahalanobis(
        X_fold_train_scaled
    )

    fold_train_sorted = np.sort(
        fold_train_mahal
    )

    # ----------------------------------------
    # OOF validation-fold distances
    # ----------------------------------------
    fold_val_mahal = fold_cov.mahalanobis(
        X_fold_val_scaled
    )

    # Empirical percentile relative to
    # ONLY the fold-training distribution
    fold_val_percentile = (
        np.searchsorted(
            fold_train_sorted,
            fold_val_mahal,
            side="right"
        )
        / len(fold_train_sorted)
    )

    strict_oof_drift[val_idx] = (
        fold_val_percentile
    )

    print(
        f"Fold {fold}: "
        f"train={len(train_idx)}, "
        f"OOF={len(val_idx)}, "
        f"mean drift={fold_val_percentile.mean():.4f}"
    )


# ============================================
# CHECK
# ============================================

print("\n" + "=" * 60)
print("STRICT OOF DRIFT")
print("=" * 60)

print("Length:", len(strict_oof_drift))
print("Expected:", len(lobo_train))

print("\nStatistics:")
print(
    pd.Series(strict_oof_drift).describe()
)

assert len(strict_oof_drift) == len(lobo_train)
assert np.all(np.isfinite(strict_oof_drift))

print("\n✅ STRICT OOF DRIFT CREATED")
print("Each OOF account was scored against a fold-specific")
print("reference that excluded that account.")

Fold 1: train=5596, OOF=1399, mean drift=0.4986
Fold 2: train=5596, OOF=1399, mean drift=0.4987
Fold 3: train=5596, OOF=1399, mean drift=0.5006
Fold 4: train=5596, OOF=1399, mean drift=0.5115
Fold 5: train=5596, OOF=1399, mean drift=0.4909

============================================================
STRICT OOF DRIFT
============================================================
Length: 6995
Expected: 6995

Statistics:
count    6995.000000
mean        0.500058
std         0.288826
min         0.000000
25%         0.250179
50%         0.501251
75%         0.749375
max         1.000000
dtype: float64

✅ STRICT OOF DRIFT CREATED
Each OOF account was scored against a fold-specific
reference that excluded that account.

In [ ]:
# ============================================
# CELL 4 — CREATE STRICT META-FUSION DATASET
# ============================================

# Make a copy so we don't accidentally modify
# the previous exploratory meta_oof dataframe.
meta_oof_strict = meta_oof.copy()

# Replace the previous potentially-leaky drift
# with the strict fold-specific OOF drift.
meta_oof_strict["drift_score"] = strict_oof_drift

# Recalculate drift interaction features
meta_oof_strict["behavior_drift_interaction"] = (
    meta_oof_strict["behavior_prob"] *
    meta_oof_strict["drift_score"]
)

meta_oof_strict["text_drift_interaction"] = (
    meta_oof_strict["text_prob"] *
    meta_oof_strict["drift_score"]
)

meta_oof_strict["behavior_conf_drift"] = (
    meta_oof_strict["behavior_confidence"] *
    meta_oof_strict["drift_score"]
)

meta_oof_strict["text_conf_drift"] = (
    meta_oof_strict["text_confidence"] *
    meta_oof_strict["drift_score"]
)

print("=" * 60)
print("STRICT META-FUSION DATASET")
print("=" * 60)

print("\nShape:", meta_oof_strict.shape)

print("\nDrift statistics:")
print(
    meta_oof_strict["drift_score"].describe()
)

print("\nLabel distribution:")
print(
    meta_oof_strict["label"]
    .value_counts()
    .sort_index()
)

print("\nDrift correlation with label:")
print(
    meta_oof_strict[
        ["drift_score", "label"]
    ].corr()
)

print("\n✅ STRICT META-FUSION DATASET READY")

============================================================
STRICT META-FUSION DATASET
============================================================

Shape: (6995, 15)

Drift statistics:
count    6995.000000
mean        0.500058
std         0.288826
min         0.000000
25%         0.250179
50%         0.501251
75%         0.749375
max         1.000000
Name: drift_score, dtype: float64

Label distribution:
label
0    1083
1    5912
Name: count, dtype: int64

Drift correlation with label:
             drift_score     label
drift_score     1.000000 -0.513864
label          -0.513864  1.000000

✅ STRICT META-FUSION DATASET READY

In [ ]:
# ============================================
# CELL 5 — META-MODEL FEATURES
# ============================================

meta_features = [
    "behavior_prob",
    "text_prob",
    "behavior_confidence",
    "text_confidence",
    "prob_difference",
    "absolute_difference",
    "agreement",
    "drift_score",
    "behavior_drift_interaction",
    "text_drift_interaction",
    "behavior_conf_drift",
    "text_conf_drift"
]

X_meta_oof = meta_oof_strict[
    meta_features
].values

y_meta_oof = meta_oof_strict[
    "label"
].values

print("=" * 60)
print("META-MODEL INPUT")
print("=" * 60)

print("\nX shape:", X_meta_oof.shape)
print("y shape:", y_meta_oof.shape)

print("\nFeatures:")
for i, feature in enumerate(meta_features, 1):
    print(f"{i:2d}. {feature}")

print("\nNaN values:", np.isnan(X_meta_oof).sum())
print("Infinite values:", np.isinf(X_meta_oof).sum())

assert X_meta_oof.shape[0] == y_meta_oof.shape[0]
assert np.isfinite(X_meta_oof).all()

print("\n✅ META-MODEL INPUT READY")

============================================================
META-MODEL INPUT
============================================================

X shape: (6995, 12)
y shape: (6995,)

Features:
 1. behavior_prob
 2. text_prob
 3. behavior_confidence
 4. text_confidence
 5. prob_difference
 6. absolute_difference
 7. agreement
 8. drift_score
 9. behavior_drift_interaction
10. text_drift_interaction
11. behavior_conf_drift
12. text_conf_drift

NaN values: 0
Infinite values: 0

✅ META-MODEL INPUT READY

In [ ]:
# ============================================
# CELL 6 — NONLINEAR META-FUSION
# RANDOM FOREST vs GRADIENT BOOSTING
# ============================================

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# ============================================
# PREPARE VALIDATION META-FEATURES
# ============================================

val_meta = pd.DataFrame({
    "behavior_prob": behavior_lobo_val_prob,
    "text_prob": text_val_prob
})

val_meta["behavior_confidence"] = (
    np.abs(val_meta["behavior_prob"] - 0.5) * 2
)

val_meta["text_confidence"] = (
    np.abs(val_meta["text_prob"] - 0.5) * 2
)

val_meta["prob_difference"] = (
    val_meta["behavior_prob"] -
    val_meta["text_prob"]
)

val_meta["absolute_difference"] = (
    np.abs(val_meta["prob_difference"])
)

val_meta["behavior_pred"] = (
    val_meta["behavior_prob"] >= 0.5
).astype(int)

val_meta["text_pred"] = (
    val_meta["text_prob"] >= 0.5
).astype(int)

val_meta["agreement"] = (
    val_meta["behavior_pred"] ==
    val_meta["text_pred"]
).astype(int)

# Validation drift was already calculated
val_meta["drift_score"] = val_drift_score

val_meta["behavior_drift_interaction"] = (
    val_meta["behavior_prob"] *
    val_meta["drift_score"]
)

val_meta["text_drift_interaction"] = (
    val_meta["text_prob"] *
    val_meta["drift_score"]
)

val_meta["behavior_conf_drift"] = (
    val_meta["behavior_confidence"] *
    val_meta["drift_score"]
)

val_meta["text_conf_drift"] = (
    val_meta["text_confidence"] *
    val_meta["drift_score"]
)

X_meta_val = val_meta[meta_features].values
y_meta_val = lobo_val["label"].values

# ============================================
# RANDOM FOREST
# ============================================

rf_meta = RandomForestClassifier(
    n_estimators=500,
    max_depth=5,
    min_samples_leaf=10,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_meta.fit(
    X_meta_oof,
    y_meta_oof
)

rf_val_pred = rf_meta.predict(
    X_meta_val
)

# ============================================
# GRADIENT BOOSTING
# ============================================

gb_meta = GradientBoostingClassifier(
    n_estimators=150,
    learning_rate=0.05,
    max_depth=3,
    min_samples_leaf=10,
    random_state=42
)

gb_meta.fit(
    X_meta_oof,
    y_meta_oof
)

gb_val_pred = gb_meta.predict(
    X_meta_val
)

# ============================================
# RESULTS FUNCTION
# ============================================

def print_meta_results(name, y_true, y_pred):

    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)

    print(
        f"Accuracy : "
        f"{accuracy_score(y_true, y_pred)*100:.2f}%"
    )

    print(
        f"Precision: "
        f"{precision_score(y_true, y_pred)*100:.2f}%"
    )

    print(
        f"Recall   : "
        f"{recall_score(y_true, y_pred)*100:.2f}%"
    )

    print(
        f"F1 Score : "
        f"{f1_score(y_true, y_pred)*100:.2f}%"
    )

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_true, y_pred))


# ============================================
# PRINT RESULTS
# ============================================

print_meta_results(
    "RANDOM FOREST META-FUSION — VALIDATION",
    y_meta_val,
    rf_val_pred
)

print_meta_results(
    "GRADIENT BOOSTING META-FUSION — VALIDATION",
    y_meta_val,
    gb_val_pred
)

============================================================
RANDOM FOREST META-FUSION — VALIDATION
============================================================
Accuracy : 99.07%
Precision: 99.74%
Recall   : 99.15%
F1 Score : 99.45%

Confusion Matrix:
[[ 214    3]
 [  10 1172]]

============================================================
GRADIENT BOOSTING META-FUSION — VALIDATION
============================================================
Accuracy : 99.21%
Precision: 99.75%
Recall   : 99.32%
F1 Score : 99.53%

Confusion Matrix:
[[ 214    3]
 [   8 1174]]

In [ ]:
# ============================================
# CELL 7 — GRADIENT BOOSTING FEATURE IMPORTANCE
# ============================================

feature_importance = pd.DataFrame({
    "feature": meta_features,
    "importance": gb_meta.feature_importances_
})

feature_importance = feature_importance.sort_values(
    "importance",
    ascending=False
).reset_index(drop=True)

print("=" * 60)
print("GRADIENT BOOSTING META-FUSION")
print("FEATURE IMPORTANCE")
print("=" * 60)

print(
    feature_importance.to_string(index=False)
)

print("\nTotal importance:")
print(
    feature_importance["importance"].sum()
)

============================================================
GRADIENT BOOSTING META-FUSION
FEATURE IMPORTANCE
============================================================
                   feature  importance
             behavior_prob    0.954413
                 text_prob    0.016669
           text_confidence    0.008102
behavior_drift_interaction    0.005730
           text_conf_drift    0.003624
    text_drift_interaction    0.002586
       behavior_confidence    0.002005
           prob_difference    0.001913
       behavior_conf_drift    0.001849
       absolute_difference    0.001773
               drift_score    0.001337
                 agreement    0.000000

Total importance:
1.0

In [ ]:
# ============================================
# CELL 8 — OOF DISAGREEMENT ANALYSIS
# ============================================

oof_analysis = meta_oof_strict.copy()

oof_analysis["behavior_correct"] = (
    oof_analysis["behavior_pred"] ==
    oof_analysis["label"]
)

oof_analysis["text_correct"] = (
    oof_analysis["text_pred"] ==
    oof_analysis["label"]
)

oof_disagreement = oof_analysis[
    oof_analysis["agreement"] == 0
].copy()

print("=" * 60)
print("OOF DISAGREEMENT ANALYSIS")
print("=" * 60)

print("\nTotal OOF accounts:", len(oof_analysis))

print(
    "Agreement:",
    (oof_analysis["agreement"] == 1).sum()
)

print(
    "Disagreement:",
    len(oof_disagreement)
)

print(
    "Disagreement percentage:",
    len(oof_disagreement) /
    len(oof_analysis) * 100
)

print("\n--- Disagreement correctness ---")

print(
    oof_disagreement[
        ["behavior_correct", "text_correct"]
    ].mean() * 100
)

print("\n--- Disagreement by direction ---")

oof_disagreement["direction"] = np.where(
    oof_disagreement["behavior_pred"] == 1,
    "Behavior=Bot / Text=Genuine",
    "Behavior=Genuine / Text=Bot"
)

print(
    oof_disagreement.groupby("direction").agg(
        cases=("label", "count"),
        behavior_correct=("behavior_correct", "mean"),
        text_correct=("text_correct", "mean"),
        mean_drift=("drift_score", "mean"),
        mean_behavior_conf=(
            "behavior_confidence", "mean"
        ),
        mean_text_conf=(
            "text_confidence", "mean"
        )
    )
)

print("\n--- Disagreement by drift group ---")

oof_disagreement["drift_group"] = np.select(
    [
        oof_disagreement["drift_score"] < 0.80,
        oof_disagreement["drift_score"] < 0.95
    ],
    [
        "Reliable",
        "Review"
    ],
    default="High Drift"
)

print(
    oof_disagreement.groupby("drift_group").agg(
        cases=("label", "count"),
        behavior_correct=("behavior_correct", "mean"),
        text_correct=("text_correct", "mean"),
        mean_drift=("drift_score", "mean")
    )
)

print("\n--- OOF disagreement drift statistics ---")

print(
    oof_disagreement["drift_score"].describe()
)

============================================================
OOF DISAGREEMENT ANALYSIS
============================================================

Total OOF accounts: 6995
Agreement: 5253
Disagreement: 1742
Disagreement percentage: 24.90350250178699

--- Disagreement correctness ---
behavior_correct    93.226177
text_correct         6.773823
dtype: float64

--- Disagreement by direction ---
                             cases  behavior_correct  text_correct  \
direction
Behavior=Bot / Text=Genuine    843          0.994069      0.005931
Behavior=Genuine / Text=Bot    899          0.874305      0.125695

                             mean_drift  mean_behavior_conf  mean_text_conf
direction
Behavior=Bot / Text=Genuine    0.439991            0.774739        0.836617
Behavior=Genuine / Text=Bot    0.849174            0.780192        0.930313

--- Disagreement by drift group ---
             cases  behavior_correct  text_correct  mean_drift
drift_group
High Drift     216          0.902778      0.097222    0.977409
Reliable       959          0.954119      0.045881    0.442790
Review         567          0.906526      0.093474    0.879302

--- OOF disagreement drift statistics ---
count    1742.000000
mean        0.651160
std         0.290690
min         0.000179
25%         0.436294
50%         0.735972
75%         0.892691
max         1.000000
Name: drift_score, dtype: float64

In [ ]:
# ============================================
# FINAL FUSION COMPARISON — UNSEEN TEST
# ============================================

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

behavior_test_pred = (
    behavior_lobo_test_prob >= 0.5
).astype(int)

text_test_pred = (
    text_test_prob >= 0.5
).astype(int)

# Existing predictions
predictions = {
    "Behavior-only": behavior_test_pred,
    "50:50 Fusion": (
        0.5 * behavior_lobo_test_prob +
        0.5 * text_test_prob >= 0.5
    ).astype(int),
    "Conditional Fusion": conditional_fusion(
        behavior_lobo_test_prob,
        text_test_prob,
        threshold=0.90,
        text_weight=0.5
    ),
    "RF Meta-Fusion": rf_meta.predict(
        pd.DataFrame({
            "behavior_prob": behavior_lobo_test_prob,
            "text_prob": text_test_prob,
            "behavior_confidence":
                np.abs(behavior_lobo_test_prob - 0.5) * 2,
            "text_confidence":
                np.abs(text_test_prob - 0.5) * 2,
            "prob_difference":
                behavior_lobo_test_prob - text_test_prob,
            "absolute_difference":
                np.abs(
                    behavior_lobo_test_prob -
                    text_test_prob
                ),
            "agreement":
                (
                    (behavior_lobo_test_prob >= 0.5) ==
                    (text_test_prob >= 0.5)
                ).astype(int),
            "drift_score": test_drift_score,
            "behavior_drift_interaction":
                behavior_lobo_test_prob * test_drift_score,
            "text_drift_interaction":
                text_test_prob * test_drift_score,
            "behavior_conf_drift":
                np.abs(
                    behavior_lobo_test_prob - 0.5
                ) * 2 * test_drift_score,
            "text_conf_drift":
                np.abs(
                    text_test_prob - 0.5
                ) * 2 * test_drift_score
        })[meta_features].values
    ),
    "Gradient Boosting Meta-Fusion": gb_meta.predict(
        pd.DataFrame({
            "behavior_prob": behavior_lobo_test_prob,
            "text_prob": text_test_prob,
            "behavior_confidence":
                np.abs(behavior_lobo_test_prob - 0.5) * 2,
            "text_confidence":
                np.abs(text_test_prob - 0.5) * 2,
            "prob_difference":
                behavior_lobo_test_prob - text_test_prob,
            "absolute_difference":
                np.abs(
                    behavior_lobo_test_prob -
                    text_test_prob
                ),
            "agreement":
                (
                    (behavior_lobo_test_prob >= 0.5) ==
                    (text_test_prob >= 0.5)
                ).astype(int),
            "drift_score": test_drift_score,
            "behavior_drift_interaction":
                behavior_lobo_test_prob * test_drift_score,
            "text_drift_interaction":
                text_test_prob * test_drift_score,
            "behavior_conf_drift":
                np.abs(
                    behavior_lobo_test_prob - 0.5
                ) * 2 * test_drift_score,
            "text_conf_drift":
                np.abs(
                    text_test_prob - 0.5
                ) * 2 * test_drift_score
        })[meta_features].values
    ),
    "Drift-aware Fusion": drift_fusion_test_pred
}

results = []

for name, pred in predictions.items():

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(
            y_test, pred
        ) * 100,
        "Precision": precision_score(
            y_test, pred
        ) * 100,
        "Recall": recall_score(
            y_test, pred
        ) * 100,
        "F1": f1_score(
            y_test, pred
        ) * 100
    })

fusion_comparison = pd.DataFrame(results)

print("=" * 70)
print("FINAL FUSION COMPARISON — UNSEEN FAKE FOLLOWERS")
print("=" * 70)

print(
    fusion_comparison.to_string(
        index=False,
        float_format=lambda x: f"{x:.2f}"
    )
)

======================================================================
FINAL FUSION COMPARISON — UNSEEN FAKE FOLLOWERS
======================================================================
                        Model  Accuracy  Precision  Recall    F1
                Behavior-only     53.61      72.06   61.93 66.61
                 50:50 Fusion     52.44      71.56   60.34 65.47
           Conditional Fusion     52.44      71.56   60.34 65.47
               RF Meta-Fusion     53.19      71.87   61.37 66.21
Gradient Boosting Meta-Fusion     53.49      72.01   61.77 66.50
           Drift-aware Fusion     68.17      86.07   68.49 76.28

In [ ]:
print("Behavior test probability shape:", behavior_lobo_test_prob.shape)

print("Behavior test prediction counts:")
print(pd.Series(behavior_test_pred).value_counts())

print("\nTrue label counts:")
print(pd.Series(y_test).value_counts())

print("\nBehavior-only metrics:")
print("Accuracy :", accuracy_score(y_test, behavior_test_pred))
print("Precision:", precision_score(y_test, behavior_test_pred))
print("Recall   :", recall_score(y_test, behavior_test_pred))
print("F1       :", f1_score(y_test, behavior_test_pred))

print("\nFirst 20 behavior probabilities:")
print(behavior_lobo_test_prob[:20])

print("\nFirst 20 labels:")
print(y_test[:20])

Behavior test probability shape: (4285,)
Behavior test prediction counts:
1    2752
0    1533
Name: count, dtype: int64

True label counts:
1    3202
0    1083
Name: count, dtype: int64

Behavior-only metrics:
Accuracy : 0.5360560093348892
Precision: 0.7205668604651163
Recall   : 0.6193004372267333
F1       : 0.6661068189452469

First 20 behavior probabilities:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0.]

First 20 labels:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [ ]:
print("=" * 70)
print("BEHAVIOR VARIABLE SANITY CHECK")
print("=" * 70)

print("\n1. behavior_lobo_test_prob")
print("shape:", behavior_lobo_test_prob.shape)
print("dtype:", behavior_lobo_test_prob.dtype)
print("min:", np.min(behavior_lobo_test_prob))
print("max:", np.max(behavior_lobo_test_prob))
print("unique values:", len(np.unique(behavior_lobo_test_prob)))
print("first 30:", behavior_lobo_test_prob[:30])

print("\n2. behavior_test_pred")
print("shape:", behavior_test_pred.shape)
print("dtype:", behavior_test_pred.dtype)
print("unique values:", np.unique(behavior_test_pred))
print("first 30:", behavior_test_pred[:30])

print("\n3. Convert probability to prediction directly")
behavior_pred_from_prob = (behavior_lobo_test_prob >= 0.5).astype(int)

print("First 30:", behavior_pred_from_prob[:30])
print(
    "Same as behavior_test_pred:",
    np.array_equal(
        behavior_pred_from_prob,
        np.asarray(behavior_test_pred)
    )
)

print("\n4. Metrics using probability-derived prediction")
print(
    classification_report(
        y_test,
        behavior_pred_from_prob,
        digits=4
    )
)

print("\n5. Compare with expected LOBO test length")
print("y_test:", len(y_test))
print("behavior probability:", len(behavior_lobo_test_prob))
print("behavior prediction:", len(behavior_test_pred))

======================================================================
BEHAVIOR VARIABLE SANITY CHECK
======================================================================

1. behavior_lobo_test_prob
shape: (4285,)
dtype: float32
min: 0.0
max: 1.0
unique values: 593
first 30: [1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00
 1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00 0.000000e+00
 1.000000e+00 1.000000e+00 1.000000e+00 0.000000e+00 1.000000e+00
 0.000000e+00 0.000000e+00 1.000000e+00 1.000000e+00 0.000000e+00
 0.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00 1.000000e+00
 1.000000e+00 0.000000e+00 2.068963e-29 1.000000e+00 0.000000e+00]

2. behavior_test_pred
shape: (4285,)
dtype: int64
unique values: [0 1]
first 30: [1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 0 0 1 1 1 1 1 0 0 1 0]

3. Convert probability to prediction directly
First 30: [1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 0 0 1 1 1 1 1 0 0 1 0]
Same as behavior_test_pred: True

4. Metrics using probability-derived prediction
              precision    recall  f1-score   support

           0     0.2048    0.2899    0.2401      1083
           1     0.7206    0.6193    0.6661      3202

    accuracy                         0.5361      4285
   macro avg     0.4627    0.4546    0.4531      4285
weighted avg     0.5902    0.5361    0.5584      4285


5. Compare with expected LOBO test length
y_test: 4285
behavior probability: 4285
behavior prediction: 4285

In [ ]:
print("Current lobo_test:")
print(lobo_test[["id", "account_type", "label"]].head(10))
print("\nShape:", lobo_test.shape)

print("\nCurrent behavior model:")
print(lobo_behavior_nn_v2)

print("\nCurrent prediction:")
print(classification_report(y_test, behavior_test_pred, digits=4))

Current lobo_test:
            id      account_type  label
3    191839658  genuine_accounts      0
5   2157382005  genuine_accounts      0
6   1947320929  genuine_accounts      0
8   1733095801  genuine_accounts      0
12    21959183  genuine_accounts      0
17  2291421004  genuine_accounts      0
18  2337494094  genuine_accounts      0
19   225241810  genuine_accounts      0
24   585912212  genuine_accounts      0
26  2320414572  genuine_accounts      0

Shape: (4285, 20)

Current behavior model:
<Sequential name=sequential_9, built=True>

Current prediction:
              precision    recall  f1-score   support

           0     0.2048    0.2899    0.2401      1083
           1     0.7206    0.6193    0.6661      3202

    accuracy                         0.5361      4285
   macro avg     0.4627    0.4546    0.4531      4285
weighted avg     0.5902    0.5361    0.5584      4285

In [ ]:
print("\nVariables related to behavior models:")

for name in [
    "lobo_behavior_nn",
    "lobo_behavior_nn_v2",
    "behavior_nn",
    "clean_nn"
]:
    if name in globals():
        model = globals()[name]
        print(
            name,
            "input_shape =", getattr(model, "input_shape", None),
            "output_shape =", getattr(model, "output_shape", None)
        )

Variables related to behavior models:
lobo_behavior_nn input_shape = (None, 15) output_shape = (None, 1)
lobo_behavior_nn_v2 input_shape = (None, 15) output_shape = (None, 1)
behavior_nn input_shape = (None, 15) output_shape = (None, 1)
clean_nn input_shape = (None, 15) output_shape = (None, 1)

In [ ]:
print("\nLOBO test account types:")
print(lobo_test["account_type"].value_counts())

print("\nLOBO test labels:")
print(lobo_test["label"].value_counts())

print("\nFirst 20 IDs:")
print(lobo_test["id"].head(20).tolist())

LOBO test account types:
account_type
fake_followers      3202
genuine_accounts    1083
Name: count, dtype: int64

LOBO test labels:
label
1    3202
0    1083
Name: count, dtype: int64

First 20 IDs:
[191839658, 2157382005, 1947320929, 1733095801, 21959183, 2291421004, 2337494094, 225241810, 585912212, 2320414572, 226315121, 492649414, 166211662, 222290847, 208664282, 150183040, 2244762307, 509255384, 238040058, 190345460]

In [ ]:
id="v7c2m1"
print("=" * 70)
print("COMPARE BEHAVIORAL MODELS ON CURRENT LOBO TEST")
print("=" * 70)

models_to_check = {
    "lobo_behavior_nn": lobo_behavior_nn,
    "lobo_behavior_nn_v2": lobo_behavior_nn_v2,
    "behavior_nn": behavior_nn,
    "clean_nn": clean_nn
}

for name, model in models_to_check.items():
    print(f"\n--- {name} ---")
    
    try:
        prob = model.predict(
            X_lobo_test_final,
            verbose=0
        ).ravel()
        
        pred = (prob >= 0.5).astype(int)
        
        print("Probability range:", prob.min(), "to", prob.max())
        print("Unique probabilities:", len(np.unique(prob)))
        
        print(
            classification_report(
                y_test,
                pred,
                digits=4
            )
        )
        
    except Exception as e:
        print("ERROR:", e)

======================================================================
COMPARE BEHAVIORAL MODELS ON CURRENT LOBO TEST
======================================================================

--- lobo_behavior_nn ---
ERROR: name 'X_lobo_test_final' is not defined

--- lobo_behavior_nn_v2 ---
ERROR: name 'X_lobo_test_final' is not defined

--- behavior_nn ---
ERROR: name 'X_lobo_test_final' is not defined

--- clean_nn ---
ERROR: name 'X_lobo_test_final' is not defined

In [ ]:
id="f4q8z2"
print("X_lobo_test_final:", X_lobo_test_final.shape)
print("y_test:", y_test.shape)

print("\nCurrent lobo test:")
print(lobo_test[["id", "account_type", "label"]].head())

print("\nFeature columns:")
print(lobo_test.columns.tolist())

NameError: name 'X_lobo_test_final' is not defined

In [ ]:
print("=" * 70)
print("AVAILABLE LOBO / BEHAVIOR VARIABLES")
print("=" * 70)

for name in sorted(globals()):
    if any(key in name.lower() for key in [
        "lobo", "behavior", "scaler", "imputer", "x_test", "y_test"
    ]):
        obj = globals()[name]
        try:
            shape = obj.shape
        except:
            shape = ""
        print(f"{name:40s} {type(obj).__name__:25s} {shape}")

======================================================================
AVAILABLE LOBO / BEHAVIOR VARIABLES
======================================================================
RobustScaler                             type
SimpleImputer                            type
StandardScaler                           type
X_lobo_test                              DataFrame                 (4285, 15)
X_lobo_test_imp                          ndarray                   (4285, 15)
X_lobo_test_imputed                      ndarray                   (4285, 15)
X_lobo_test_mahal                        ndarray                   (4285,)
X_lobo_test_raw                          DataFrame                 (4285, 15)
X_lobo_test_scaled                       ndarray                   (4285, 15)
X_lobo_test_tfidf                        csr_matrix                (4285, 20000)
X_lobo_train                             DataFrame                 (6995, 15)
X_lobo_train_final                       ndarray                   (5596, 15)
X_lobo_train_imp                         ndarray                   (6995, 15)
X_lobo_train_raw                         DataFrame                 (6995, 15)
X_lobo_train_scaled                      ndarray                   (6995, 15)
X_lobo_train_tfidf                       csr_matrix                (5596, 20000)
X_lobo_val                               ndarray                   (1399, 15)
X_lobo_val_tfidf                         csr_matrix                (1399, 20000)
X_test                                   DataFrame                 (4311, 15)
X_test_behavior                          DataFrame                 (1530, 15)
X_test_behavior_imp                      ndarray                   (1530, 15)
X_test_behavior_scaled                   ndarray                   (1530, 15)
X_test_imputed                           ndarray                   (4311, 15)
X_test_nn                                ndarray                   (4311, 15)
X_test_robust                            ndarray                   (4311, 15)
X_test_scaled                            ndarray                   (4311, 15)
X_train_behavior                         DataFrame                 (7137, 15)
X_train_behavior_imp                     ndarray                   (7137, 15)
X_train_behavior_scaled                  ndarray                   (7137, 15)
X_val_behavior                           DataFrame                 (1530, 15)
X_val_behavior_imp                       ndarray                   (1530, 15)
X_val_behavior_scaled                    ndarray                   (1530, 15)
adaptive_behavior_test_weight            ndarray                   (4285,)
adaptive_behavior_weight                 ndarray                   (1399,)
behavior_common                          DataFrame                 (10197, 20)
behavior_conf_cases                      DataFrame                 (15, 11)
behavior_confidence                      ndarray                   (4285,)
behavior_confidence_test                 ndarray                   (4285,)
behavior_correct_text_wrong              int64                     ()
behavior_df                              DataFrame                 (14368, 20)
behavior_features                        list
behavior_ids                             set
behavior_imputer                         SimpleImputer
behavior_lobo_test_prob                  ndarray                   (4285,)
behavior_lobo_val_prob                   ndarray                   (1399,)
behavior_nn                              Sequential
behavior_nn_weighted                     Sequential
behavior_path                            str
behavior_pred                            ndarray                   (4285,)
behavior_pred_from_prob                  ndarray                   (4285,)
behavior_prob                            ndarray                   (1399,)
behavior_scaler                          StandardScaler
behavior_test                            ndarray                   (4285,)
behavior_test_common                     DataFrame                 (1530, 20)
behavior_test_common_results             DataFrame                 (1530, 5)
behavior_test_confidence                 ndarray                   (4285,)
behavior_test_pred                       ndarray                   (4285,)
behavior_test_prob                       ndarray                   (4285,)
behavior_test_prob_stack                 ndarray                   (4285,)
behavior_test_results                    DataFrame                 (4311, 5)
behavior_train                           DataFrame                 (7137, 20)
behavior_val                             DataFrame                 (1530, 20)
behavior_val_pred                        ndarray                   (1399,)
behavior_val_prob                        ndarray                   (1530,)
behavior_val_prob_stack                  ndarray                   (1399,)
behavior_val_results                     DataFrame                 (1530, 5)
behavior_wrong_text_correct              int64                     ()
behavioral_features                      list
drift_imputer                            SimpleImputer
drift_imputer_final                      SimpleImputer
drift_scaler                             StandardScaler
drift_scaler_final                       StandardScaler
early_stopping_behavior                  EarlyStopping
early_stopping_lobo                      EarlyStopping
early_stopping_lobo_v2                   EarlyStopping
fold_imputer                             SimpleImputer
fold_scaler                              StandardScaler
group_imputer                            SimpleImputer
group_scaler                             StandardScaler
history_behavior                         History
history_lobo_behavior                    History
history_lobo_behavior_v2                 History
imputer                                  SimpleImputer
imputer_cross                            SimpleImputer
lobo_behavior_nn                         Sequential
lobo_behavior_nn_v2                      Sequential
lobo_behavior_pred                       ndarray                   (4285,)
lobo_behavior_prob                       ndarray                   (4285,)
lobo_class_weights                       dict
lobo_drift_score                         ndarray                   (4285,)
lobo_imputer                             SimpleImputer
lobo_scaler                              StandardScaler
lobo_test                                DataFrame                 (4285, 20)
lobo_train                               DataFrame                 (6995, 20)
lobo_train_part                          DataFrame                 (5596, 20)
lobo_val                                 DataFrame                 (1399, 20)
nn_scaler                                StandardScaler
oof_behavior_prob                        ndarray                   (6995,)
reduce_lr_behavior                       ReduceLROnPlateau
reduce_lr_lobo                           ReduceLROnPlateau
reduce_lr_lobo_v2                        ReduceLROnPlateau
robust_scaler                            RobustScaler
scaler                                   StandardScaler
scaler_cross                             RobustScaler
temporal_imputer                         SimpleImputer
temporal_scaler                          StandardScaler
text_lobo_svm                            LinearSVC
text_lobo_test                           DataFrame                 (4285, 5)
text_lobo_test_pred                      ndarray                   (4285,)
text_lobo_train                          DataFrame                 (6995, 5)
text_lobo_train_split                    DataFrame                 (5596, 5)
text_lobo_val                            DataFrame                 (1399, 5)
text_lobo_val_pred                       ndarray                   (1399,)
text_svm_lobo                            LinearSVC
tfidf_lobo                               TfidfVectorizer
y_lobo_test                              Series                    (4285,)
y_lobo_train                             ndarray                   (6995,)
y_lobo_train_final                       ndarray                   (5596,)
y_lobo_val                               Series                    (1399,)
y_test                                   ndarray                   (4285,)
y_test_behavior                          ndarray                   (1530,)
y_test_pred                              ndarray                   (4311,)
y_test_prob                              ndarray                   (4311, 1)
y_test_stack                             ndarray                   (4285,)
y_train_behavior                         ndarray                   (7137,)
y_val_behavior                           ndarray                   (1530,)

In [ ]:
print("\nBehavior feature columns:")
print(behavior_features)

print("\nCurrent LOBO test shape:")
print(lobo_test.shape)

print("\nRaw LOBO test feature matrix:")
print(lobo_test[behavior_features].shape)

print("\nFirst 3 rows:")
print(lobo_test[behavior_features].head(3))

Behavior feature columns:
['statuses_count', 'followers_count', 'friends_count', 'favourites_count', 'listed_count', 'account_age_days', 'statuses_per_day', 'followers_friends_ratio', 'friends_followers_ratio', 'favorites_per_status', 'log_statuses_count', 'log_followers_count', 'log_friends_count', 'log_favourites_count', 'log_listed_count']

Current LOBO test shape:
(4285, 20)

Raw LOBO test feature matrix:
(4285, 15)

First 3 rows:
   statuses_count  followers_count  friends_count  favourites_count  \
3          202968             2248            981             60304
5           12915              641           1066              1568
6           13676             1042           2000             19012

   listed_count  account_age_days  statuses_per_day  followers_friends_ratio  \
3           101       2006.077523        101.176549                 2.291539
5             7        868.989942         14.862082                 0.601313
6             7        888.996053         15.383645                 0.521000

   friends_followers_ratio  favorites_per_status  log_statuses_count  \
3                 0.436388              0.297111           12.220809
5                 1.663027              0.121409            9.466222
6                 1.919386              1.390173            9.523471

   log_followers_count  log_friends_count  log_favourites_count  \
3             7.718241           6.889591             11.007170
5             6.464588           6.972606              7.358194
6             6.949856           7.601402              9.852878

   log_listed_count
3          4.624973
5          2.079442
6          2.079442

In [ ]:
print("=" * 70)
print("LOBO BEHAVIOR MODEL COMPARISON")
print("=" * 70)

for name, model in {
    "lobo_behavior_nn": lobo_behavior_nn,
    "lobo_behavior_nn_v2": lobo_behavior_nn_v2
}.items():

    prob = model.predict(
        X_lobo_test_scaled,
        verbose=0
    ).ravel()

    pred = (prob >= 0.5).astype(int)

    print(f"\n{'=' * 25} {name} {'=' * 25}")
    print("Probability range:", prob.min(), "to", prob.max())
    print("Unique probabilities:", len(np.unique(prob)))

    print(
        classification_report(
            y_lobo_test,
            pred,
            digits=4
        )
    )

======================================================================
LOBO BEHAVIOR MODEL COMPARISON
======================================================================

========================= lobo_behavior_nn =========================
Probability range: 1.3712093e-11 to 1.0
Unique probabilities: 4240
              precision    recall  f1-score   support

           0     0.4898    0.4894    0.4896      1083
           1     0.8273    0.8276    0.8275      3202

    accuracy                         0.7421      4285
   macro avg     0.6586    0.6585    0.6585      4285
weighted avg     0.7420    0.7421    0.7421      4285


========================= lobo_behavior_nn_v2 =========================
Probability range: 1.1475534e-08 to 1.0
Unique probabilities: 1667
              precision    recall  f1-score   support

           0     0.4832    0.5060    0.4944      1083
           1     0.8302    0.8170    0.8235      3202

    accuracy                         0.7384      4285
   macro avg     0.6567    0.6615    0.6590      4285
weighted avg     0.7425    0.7384    0.7403      4285

In [ ]:
print("=" * 75)
print("ALL BEHAVIOR TEST PREDICTIONS — COMPARISON")
print("=" * 75)

behavior_arrays = {
    "behavior_lobo_test_prob": behavior_lobo_test_prob,
    "lobo_behavior_prob": lobo_behavior_prob,
    "behavior_test_prob": behavior_test_prob,
    "behavior_test_prob_stack": behavior_test_prob_stack,
}

for name, arr in behavior_arrays.items():

    arr = np.asarray(arr).ravel()

    if len(arr) != len(y_lobo_test):
        print(f"\n{name}: LENGTH MISMATCH → {len(arr)}")
        continue

    pred = (arr >= 0.5).astype(int)

    print(f"\n{name}")
    print("-" * 50)
    print("Range:", arr.min(), "to", arr.max())
    print("Unique:", len(np.unique(arr)))
    print("Accuracy:", accuracy_score(y_lobo_test, pred))
    print("Precision:", precision_score(y_lobo_test, pred))
    print("Recall:", recall_score(y_lobo_test, pred))
    print("F1:", f1_score(y_lobo_test, pred))

===========================================================================
ALL BEHAVIOR TEST PREDICTIONS — COMPARISON
===========================================================================

behavior_lobo_test_prob
--------------------------------------------------
Range: 0.0 to 1.0
Unique: 593
Accuracy: 0.6877479579929988
Precision: 0.8386627906976745
Recall: 0.7207995003123048
F1: 0.7752771246221027

lobo_behavior_prob
--------------------------------------------------
Range: 1.1475534e-08 to 1.0
Unique: 1667
Accuracy: 0.738389731621937
Precision: 0.830212630910822
Recall: 0.8169893816364772
F1: 0.8235479301117582

behavior_test_prob
--------------------------------------------------
Range: 0.0 to 1.0
Unique: 593
Accuracy: 0.6877479579929988
Precision: 0.8386627906976745
Recall: 0.7207995003123048
F1: 0.7752771246221027

behavior_test_prob_stack
--------------------------------------------------
Range: 0.0 to 1.0
Unique: 593
Accuracy: 0.6877479579929988
Precision: 0.8386627906976745
Recall: 0.7207995003123048
F1: 0.7752771246221027

In [ ]:
print("\nSaved model predictions directly on X_lobo_test_scaled:")

for name, model in {
    "lobo_behavior_nn": lobo_behavior_nn,
    "lobo_behavior_nn_v2": lobo_behavior_nn_v2
}.items():

    prob = model.predict(X_lobo_test_scaled, verbose=0).ravel()
    pred = (prob >= 0.5).astype(int)

    print(
        f"{name}: "
        f"acc={accuracy_score(y_lobo_test, pred):.4f}, "
        f"F1={f1_score(y_lobo_test, pred):.4f}"
    )

Saved model predictions directly on X_lobo_test_scaled:
lobo_behavior_nn: acc=0.7421, F1=0.8275
lobo_behavior_nn_v2: acc=0.7384, F1=0.8235

In [ ]:
# ============================================================
# CLEAN LOBO BEHAVIOR BASELINE
# ============================================================

behavior_clean_test_pred = (
    lobo_behavior_prob >= 0.5
).astype(int)

print("Behavior-only LOBO test")
print("=" * 50)

print(
    classification_report(
        y_lobo_test,
        behavior_clean_test_pred,
        digits=4
    )
)

print(
    "Accuracy:",
    accuracy_score(y_lobo_test, behavior_clean_test_pred)
)

print(
    "F1:",
    f1_score(y_lobo_test, behavior_clean_test_pred)
)

Behavior-only LOBO test
==================================================
              precision    recall  f1-score   support

           0     0.4832    0.5060    0.4944      1083
           1     0.8302    0.8170    0.8235      3202

    accuracy                         0.7384      4285
   macro avg     0.6567    0.6615    0.6590      4285
weighted avg     0.7425    0.7384    0.7403      4285

Accuracy: 0.738389731621937
F1: 0.8235479301117582

In [ ]:
# ============================================================
# CLEAN DRIFT-AWARE FUSION
# ============================================================

behavior_prob_clean = np.asarray(lobo_behavior_prob).ravel()
text_prob_clean = np.asarray(text_test_prob).ravel()
drift_clean = np.asarray(lobo_drift_score).ravel()
y_clean = np.asarray(y_lobo_test).ravel()

behavior_pred_clean = (
    behavior_prob_clean >= 0.5
).astype(int)

text_pred_clean = (
    text_prob_clean >= 0.5
).astype(int)

drift_fusion_clean_pred = behavior_pred_clean.copy()

disagreement = behavior_pred_clean != text_pred_clean

use_text = disagreement & (drift_clean >= 0.80)

drift_fusion_clean_pred[use_text] = text_pred_clean[use_text]

print("=" * 70)
print("CLEAN DRIFT-AWARE FUSION — UNSEEN FAKE FOLLOWERS")
print("=" * 70)

print(
    classification_report(
        y_clean,
        drift_fusion_clean_pred,
        digits=4
    )
)

print("Accuracy:",
      accuracy_score(y_clean, drift_fusion_clean_pred))

print("Precision:",
      precision_score(y_clean, drift_fusion_clean_pred))

print("Recall:",
      recall_score(y_clean, drift_fusion_clean_pred))

print("F1:",
      f1_score(y_clean, drift_fusion_clean_pred))

print("\nPredictions changed from behavior:",
      np.sum(drift_fusion_clean_pred != behavior_pred_clean))

print("Text used:",
      np.sum(use_text))

======================================================================
CLEAN DRIFT-AWARE FUSION — UNSEEN FAKE FOLLOWERS
======================================================================
              precision    recall  f1-score   support

           0     0.6355    0.7082    0.6699      1083
           1     0.8973    0.8626    0.8796      3202

    accuracy                         0.8236      4285
   macro avg     0.7664    0.7854    0.7747      4285
weighted avg     0.8311    0.8236    0.8266      4285

Accuracy: 0.8235705950991832
Precision: 0.8973359324236517
Recall: 0.8625858838226109
F1: 0.8796178343949045

Predictions changed from behavior: 581
Text used: 581

In [ ]:
# ============================================================
# FINAL CLEAN FUSION COMPARISON
# ============================================================

clean_behavior_prob = np.asarray(lobo_behavior_prob).ravel()
clean_text_prob = np.asarray(text_test_prob).ravel()
clean_y = np.asarray(y_lobo_test).ravel()

clean_behavior_pred = (
    clean_behavior_prob >= 0.5
).astype(int)

clean_text_pred = (
    clean_text_prob >= 0.5
).astype(int)

# 50:50 fusion
fusion_5050_prob = (
    0.5 * clean_behavior_prob +
    0.5 * clean_text_prob
)
fusion_5050_pred = (fusion_5050_prob >= 0.5).astype(int)

# Conditional fusion — frozen validation threshold 0.90
behavior_conf = np.abs(clean_behavior_prob - 0.5) * 2

conditional_pred = clean_behavior_pred.copy()

uncertain = behavior_conf < 0.90

conditional_pred[uncertain] = (
    0.5 * clean_behavior_prob[uncertain] +
    0.5 * clean_text_prob[uncertain] >= 0.5
).astype(int)

# Drift-aware fusion — frozen threshold 0.80
clean_drift = np.asarray(lobo_drift_score).ravel()

drift_pred = clean_behavior_pred.copy()

disagreement = clean_behavior_pred != clean_text_pred

use_text_drift = (
    disagreement &
    (clean_drift >= 0.80)
)

drift_pred[use_text_drift] = clean_text_pred[use_text_drift]


# ------------------------------------------------------------
# Evaluation helper
# ------------------------------------------------------------

def evaluate_model(name, pred):

    return {
        "Model": name,
        "Accuracy": accuracy_score(clean_y, pred),
        "Precision": precision_score(clean_y, pred),
        "Recall": recall_score(clean_y, pred),
        "F1": f1_score(clean_y, pred)
    }


results = []

results.append(
    evaluate_model(
        "Behavior-only",
        clean_behavior_pred
    )
)

results.append(
    evaluate_model(
        "Text-only",
        clean_text_pred
    )
)

results.append(
    evaluate_model(
        "50:50 Fusion",
        fusion_5050_pred
    )
)

results.append(
    evaluate_model(
        "Conditional Fusion",
        conditional_pred
    )
)

results.append(
    evaluate_model(
        "Drift-aware Fusion",
        drift_pred
    )
)

final_clean_comparison = pd.DataFrame(results)

for col in ["Accuracy", "Precision", "Recall", "F1"]:
    final_clean_comparison[col] *= 100

print("=" * 75)
print("FINAL CLEAN FUSION COMPARISON — UNSEEN FAKE FOLLOWERS")
print("=" * 75)

print(
    final_clean_comparison
    .round(2)
    .to_string(index=False)
)

print("\nDrift-aware text interventions:",
      np.sum(use_text_drift))

print(
    "Drift-aware intervention percentage:",
    round(
        100 * np.mean(use_text_drift),
        2
    ),
    "%"
)

===========================================================================
FINAL CLEAN FUSION COMPARISON — UNSEEN FAKE FOLLOWERS
===========================================================================
             Model  Accuracy  Precision  Recall    F1
     Behavior-only     73.84      83.02   81.70 82.35
         Text-only     88.68      99.06   85.67 91.88
      50:50 Fusion     75.22      84.19   82.29 83.23
Conditional Fusion     74.40      83.66   81.70 82.67
Drift-aware Fusion     82.36      89.73   86.26 87.96

Drift-aware text interventions: 581
Drift-aware intervention percentage: 13.56 %

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np
import pandas as pd

# ============================================================
# CLEAN LOBO VALIDATION / TEST PROBABILITIES
# ============================================================

# Behavior probabilities
behavior_val_prob = lobo_behavior_nn_v2.predict(X_lobo_val, verbose=0).ravel()
behavior_test_prob = lobo_behavior_nn_v2.predict(X_lobo_test_scaled, verbose=0).ravel()

# Text probabilities
# These should already exist from the calibrated text model
text_val_prob = text_calibrated.predict_proba(X_combined_val)[:, 1]
text_test_prob = text_calibrated.predict_proba(X_combined_test)[:, 1]

y_val = y_lobo_val.to_numpy()
y_test_clean = y_lobo_test.to_numpy()

print("Behavior validation:", behavior_val_prob.shape)
print("Text validation:", text_val_prob.shape)
print("Behavior test:", behavior_test_prob.shape)
print("Text test:", text_test_prob.shape)

Behavior validation: (1399,)
Text validation: (1399,)
Behavior test: (4285,)
Text test: (4285,)

In [ ]:
# ============================================================
# FIND BEST THRESHOLD USING VALIDATION ONLY
# ============================================================

threshold_results = []

for threshold in np.arange(0.10, 0.91, 0.01):

    behavior_pred = (behavior_val_prob >= threshold).astype(int)
    text_pred = (text_val_prob >= threshold).astype(int)

    threshold_results.append({
        "threshold": threshold,
        "behavior_f1": f1_score(y_val, behavior_pred),
        "text_f1": f1_score(y_val, text_pred),
        "behavior_acc": accuracy_score(y_val, behavior_pred),
        "text_acc": accuracy_score(y_val, text_pred)
    })

threshold_df = pd.DataFrame(threshold_results)

print("BEST BEHAVIOR THRESHOLD:")
print(
    threshold_df.loc[
        threshold_df["behavior_f1"].idxmax()
    ]
)

print("\nBEST TEXT THRESHOLD:")
print(
    threshold_df.loc[
        threshold_df["text_f1"].idxmax()
    ]
)

BEST BEHAVIOR THRESHOLD:
threshold       0.230000
behavior_f1     0.995763
text_f1         0.993255
behavior_acc    0.992852
text_acc        0.988563
Name: 13, dtype: float64

BEST TEXT THRESHOLD:
threshold       0.600000
behavior_f1     0.994058
text_f1         0.994485
behavior_acc    0.989993
text_acc        0.990708
Name: 50, dtype: float64

In [ ]:
# ============================================================
# VALIDATION-ONLY DRIFT-AWARE FUSION SEARCH
# ============================================================

best_result = None
fusion_results = []

# Frozen validation drift score
val_drift = val_drift_score

for behavior_weight in np.arange(0.0, 1.01, 0.05):

    text_weight = 1.0 - behavior_weight

    for decision_threshold in np.arange(0.30, 0.71, 0.01):

        for drift_threshold in np.arange(0.50, 0.96, 0.05):

            # Weighted fusion
            fused_prob = (
                behavior_weight * behavior_val_prob
                + text_weight * text_val_prob
            )

            # Drift-aware intervention
            disagreement = (
                (behavior_val_prob >= 0.5) !=
                (text_val_prob >= 0.5)
            )

            final_prob = fused_prob.copy()

            # When modalities disagree AND behavior is under high drift,
            # rely more heavily on text.
            high_drift = val_drift >= drift_threshold

            intervention = disagreement & high_drift

            final_prob[intervention] = text_val_prob[intervention]

            final_pred = (
                final_prob >= decision_threshold
            ).astype(int)

            acc = accuracy_score(y_val, final_pred)
            precision = precision_score(y_val, final_pred, zero_division=0)
            recall = recall_score(y_val, final_pred, zero_division=0)
            f1 = f1_score(y_val, final_pred, zero_division=0)

            result = {
                "behavior_weight": behavior_weight,
                "text_weight": text_weight,
                "decision_threshold": decision_threshold,
                "drift_threshold": drift_threshold,
                "accuracy": acc,
                "precision": precision,
                "recall": recall,
                "f1": f1,
                "interventions": intervention.sum()
            }

            fusion_results.append(result)

            if best_result is None or f1 > best_result["f1"]:
                best_result = result

fusion_search_df = pd.DataFrame(fusion_results)

print("BEST VALIDATION CONFIGURATION")
print("=" * 60)
print(pd.Series(best_result))

BEST VALIDATION CONFIGURATION
============================================================
behavior_weight       0.550000
text_weight           0.450000
decision_threshold    0.400000
drift_threshold       0.950000
accuracy              0.999285
precision             0.999155
recall                1.000000
f1                    0.999577
interventions         6.000000
dtype: float64

In [ ]:
# ============================================================
# FINAL FROZEN FUSION — NO TEST TUNING
# ============================================================

BEST_BEHAVIOR_WEIGHT = 0.55
BEST_TEXT_WEIGHT = 0.45
BEST_DECISION_THRESHOLD = 0.40
BEST_DRIFT_THRESHOLD = 0.95

# ------------------------------------------------------------
# 1. Weighted fusion
# ------------------------------------------------------------

test_fused_prob = (
    BEST_BEHAVIOR_WEIGHT * behavior_test_prob
    + BEST_TEXT_WEIGHT * text_test_prob
)

# ------------------------------------------------------------
# 2. Detect disagreement
# ------------------------------------------------------------

behavior_test_pred = (
    behavior_test_prob >= 0.5
).astype(int)

text_test_pred = (
    text_test_prob >= 0.5
).astype(int)

disagreement_test = (
    behavior_test_pred != text_test_pred
)

# ------------------------------------------------------------
# 3. Drift-aware intervention
# ------------------------------------------------------------

high_drift_test = (
    val_drift_score[:0]  # placeholder, DO NOT USE
)

In [ ]:
# Show variables related to drift
[x for x in dir() if "drift" in x.lower()]

['BEST_DRIFT_THRESHOLD',
 'X_drift_test_imputed',
 'X_drift_test_raw',
 'X_drift_test_scaled',
 'X_drift_train_imputed',
 'X_drift_train_raw',
 'X_drift_train_scaled',
 'X_drift_val_imputed',
 'X_drift_val_raw',
 'X_drift_val_scaled',
 'X_oof_drift_imputed',
 'X_oof_drift_raw',
 'X_oof_drift_scaled',
 'class_drift_analysis',
 'clean_drift',
 'direction_drift',
 'drift_aware_fusion',
 'drift_clean',
 'drift_cov_model_final',
 'drift_error_analysis',
 'drift_fusion_clean_pred',
 'drift_fusion_test_pred',
 'drift_fusion_val_pred',
 'drift_group',
 'drift_imputer',
 'drift_imputer_final',
 'drift_pred',
 'drift_reference',
 'drift_result',
 'drift_scaler',
 'drift_scaler_final',
 'drift_threshold',
 'drift_threshold_95',
 'drift_threshold_99',
 'fake_drift',
 'fake_drift_score',
 'high_drift',
 'high_drift_test',
 'lobo_drift_score',
 'oof_drift_score',
 'strict_oof_drift',
 'test_drift_score',
 'use_text_drift',
 'val_drift',
 'val_drift_score']

In [ ]:
# ============================================================
# FINAL FROZEN DRIFT-AWARE FUSION
# Parameters selected ONLY from validation
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Frozen parameters from validation
BEST_BEHAVIOR_WEIGHT = 0.55
BEST_TEXT_WEIGHT = 0.45
BEST_DECISION_THRESHOLD = 0.40
BEST_DRIFT_THRESHOLD = 0.95

# ------------------------------------------------------------
# 1. Weighted probability fusion
# ------------------------------------------------------------

test_fused_prob = (
    BEST_BEHAVIOR_WEIGHT * behavior_test_prob
    + BEST_TEXT_WEIGHT * text_test_prob
)

# ------------------------------------------------------------
# 2. Individual predictions
# ------------------------------------------------------------

behavior_test_pred = (
    behavior_test_prob >= 0.5
).astype(int)

text_test_pred = (
    text_test_prob >= 0.5
).astype(int)

# ------------------------------------------------------------
# 3. Detect disagreement
# ------------------------------------------------------------

disagreement_test = (
    behavior_test_pred != text_test_pred
)

# ------------------------------------------------------------
# 4. High behavioral drift
# ------------------------------------------------------------

high_drift_test = (
    test_drift_score >= BEST_DRIFT_THRESHOLD
)

# ------------------------------------------------------------
# 5. Drift-aware intervention
#
# If behavior and text disagree AND behavioral drift is high,
# trust the text model instead of the weighted fusion.
# ------------------------------------------------------------

final_test_prob = test_fused_prob.copy()

intervention_test = (
    disagreement_test &
    high_drift_test
)

final_test_prob[intervention_test] = (
    text_test_prob[intervention_test]
)

# ------------------------------------------------------------
# 6. Final prediction
# ------------------------------------------------------------

final_test_pred = (
    final_test_prob >= BEST_DECISION_THRESHOLD
).astype(int)

# ------------------------------------------------------------
# 7. Metrics
# ------------------------------------------------------------

final_acc = accuracy_score(y_test_clean, final_test_pred)
final_precision = precision_score(
    y_test_clean, final_test_pred, zero_division=0
)
final_recall = recall_score(
    y_test_clean, final_test_pred, zero_division=0
)
final_f1 = f1_score(
    y_test_clean, final_test_pred, zero_division=0
)

print("=" * 60)
print("FINAL FROZEN LOBO TEST RESULT")
print("=" * 60)

print(f"Accuracy  : {final_acc:.4f} ({final_acc*100:.2f}%)")
print(f"Precision : {final_precision:.4f} ({final_precision*100:.2f}%)")
print(f"Recall    : {final_recall:.4f} ({final_recall*100:.2f}%)")
print(f"F1 Score  : {final_f1:.4f} ({final_f1*100:.2f}%)")

print("\nInterventions:", intervention_test.sum())
print(
    "Intervention rate:",
    f"{intervention_test.mean()*100:.2f}%"
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test_clean, final_test_pred))

print("\nClassification Report:")
print(
    classification_report(
        y_test_clean,
        final_test_pred,
        target_names=["Genuine", "Bot"],
        digits=4
    )
)

============================================================
FINAL FROZEN LOBO TEST RESULT
============================================================
Accuracy  : 0.8180 (81.80%)
Precision : 0.8794 (87.94%)
Recall    : 0.8766 (87.66%)
F1 Score  : 0.8780 (87.80%)

Interventions: 296
Intervention rate: 6.91%

Confusion Matrix:
[[ 698  385]
 [ 395 2807]]

Classification Report:
              precision    recall  f1-score   support

     Genuine     0.6386    0.6445    0.6415      1083
         Bot     0.8794    0.8766    0.8780      3202

    accuracy                         0.8180      4285
   macro avg     0.7590    0.7606    0.7598      4285
weighted avg     0.8185    0.8180    0.8182      4285

In [ ]:
# ============================================================
# TEXT-FIRST SELECTIVE FUSION
# VALIDATION-ONLY PARAMETER SEARCH
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)
import numpy as np
import pandas as pd

results = []

# Predictions
behavior_val_pred = (
    behavior_val_prob >= 0.5
).astype(int)

text_val_pred = (
    text_val_prob >= 0.5
).astype(int)

disagreement = behavior_val_pred != text_val_pred

# Behavior confidence
behavior_confidence = np.maximum(
    behavior_val_prob,
    1 - behavior_val_prob
)

# Search parameters
drift_thresholds = np.arange(0.50, 0.96, 0.05)
confidence_thresholds = np.arange(0.50, 0.96, 0.05)

for drift_threshold in drift_thresholds:

    for confidence_threshold in confidence_thresholds:

        final_pred = text_val_pred.copy()

        low_drift = val_drift_score < drift_threshold
        high_behavior_conf = (
            behavior_confidence >= confidence_threshold
        )

        # Behavior can override text ONLY when:
        # 1. They disagree
        # 2. Drift is low
        # 3. Behavior confidence is high

        behavior_override = (
            disagreement &
            low_drift &
            high_behavior_conf
        )

        final_pred[behavior_override] = (
            behavior_val_pred[behavior_override]
        )

        acc = accuracy_score(y_val, final_pred)
        precision = precision_score(
            y_val, final_pred, zero_division=0
        )
        recall = recall_score(
            y_val, final_pred, zero_division=0
        )
        f1 = f1_score(
            y_val, final_pred, zero_division=0
        )

        results.append({
            "drift_threshold": drift_threshold,
            "confidence_threshold": confidence_threshold,
            "accuracy": acc,
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "behavior_overrides": behavior_override.sum()
        })

text_first_df = pd.DataFrame(results)

best_text_first = text_first_df.loc[
    text_first_df["f1"].idxmax()
]

print("=" * 60)
print("BEST TEXT-FIRST VALIDATION CONFIGURATION")
print("=" * 60)
print(best_text_first)

============================================================
BEST TEXT-FIRST VALIDATION CONFIGURATION
============================================================
drift_threshold          0.800000
confidence_threshold     0.700000
accuracy                 0.996426
precision                0.998307
recall                   0.997462
f1                       0.997884
behavior_overrides      13.000000
Name: 64, dtype: float64

In [ ]:
# ============================================================
# FINAL TEXT-FIRST SELECTIVE FUSION
# PARAMETERS FROZEN FROM VALIDATION
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# ------------------------------------------------------------
# FROZEN VALIDATION PARAMETERS
# ------------------------------------------------------------

BEST_DRIFT_THRESHOLD = 0.80
BEST_CONFIDENCE_THRESHOLD = 0.70

# ------------------------------------------------------------
# TEST PREDICTIONS
# ------------------------------------------------------------

behavior_test_pred = (
    behavior_test_prob >= 0.5
).astype(int)

text_test_pred = (
    text_test_prob >= 0.5
).astype(int)

# ------------------------------------------------------------
# Behavior confidence
# ------------------------------------------------------------

behavior_test_confidence = np.maximum(
    behavior_test_prob,
    1 - behavior_test_prob
)

# ------------------------------------------------------------
# Find disagreements
# ------------------------------------------------------------

test_disagreement = (
    behavior_test_pred != text_test_pred
)

# ------------------------------------------------------------
# Conditions for allowing behavior to override text
# ------------------------------------------------------------

test_low_drift = (
    test_drift_score < BEST_DRIFT_THRESHOLD
)

test_high_behavior_confidence = (
    behavior_test_confidence >= BEST_CONFIDENCE_THRESHOLD
)

# ------------------------------------------------------------
# TEXT-FIRST DECISION
# ------------------------------------------------------------

final_text_first_pred = text_test_pred.copy()

behavior_override_test = (
    test_disagreement &
    test_low_drift &
    test_high_behavior_confidence
)

final_text_first_pred[behavior_override_test] = (
    behavior_test_pred[behavior_override_test]
)

# ------------------------------------------------------------
# FINAL METRICS
# ------------------------------------------------------------

acc = accuracy_score(
    y_test_clean,
    final_text_first_pred
)

precision = precision_score(
    y_test_clean,
    final_text_first_pred,
    zero_division=0
)

recall = recall_score(
    y_test_clean,
    final_text_first_pred,
    zero_division=0
)

f1 = f1_score(
    y_test_clean,
    final_text_first_pred,
    zero_division=0
)

print("=" * 60)
print("FINAL TEXT-FIRST SELECTIVE FUSION")
print("=" * 60)

print(f"Accuracy  : {acc:.4f} ({acc*100:.2f}%)")
print(f"Precision : {precision:.4f} ({precision*100:.2f}%)")
print(f"Recall    : {recall:.4f} ({recall*100:.2f}%)")
print(f"F1 Score  : {f1:.4f} ({f1*100:.2f}%)")

print("\nBehavior overrides:", behavior_override_test.sum())
print(
    "Override rate:",
    f"{behavior_override_test.mean()*100:.2f}%"
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test_clean,
        final_text_first_pred
    )
)

print("\nClassification Report:")
print(
    classification_report(
        y_test_clean,
        final_text_first_pred,
        target_names=["Genuine", "Bot"],
        digits=4
    )
)

============================================================
FINAL TEXT-FIRST SELECTIVE FUSION
============================================================
Accuracy  : 0.8247 (82.47%)
Precision : 0.8983 (89.83%)
Recall    : 0.8632 (86.32%)
F1 Score  : 0.8804 (88.04%)

Behavior overrides: 476
Override rate: 11.11%

Confusion Matrix:
[[ 770  313]
 [ 438 2764]]

Classification Report:
              precision    recall  f1-score   support

     Genuine     0.6374    0.7110    0.6722      1083
         Bot     0.8983    0.8632    0.8804      3202

    accuracy                         0.8247      4285
   macro avg     0.7678    0.7871    0.7763      4285
weighted avg     0.8323    0.8247    0.8278      4285

In [ ]:
# ============================================================
# ERROR-TARGETED ANALYSIS
# Where can behavior actually help the text model?
# ============================================================

text_pred = (text_test_prob >= 0.5).astype(int)
behavior_pred = (behavior_test_prob >= 0.5).astype(int)

# Text errors
text_wrong = text_pred != y_test_clean

# Cases where TEXT is wrong but BEHAVIOR is correct
behavior_can_help = (
    text_wrong &
    (behavior_pred == y_test_clean)
)

# Cases where behavior would damage a correct text prediction
behavior_would_hurt = (
    (text_pred == y_test_clean) &
    (behavior_pred != y_test_clean)
)

print("=" * 60)
print("TEXT ERROR ANALYSIS")
print("=" * 60)

print("Total test samples:", len(y_test_clean))

print("\nText errors:")
print(text_wrong.sum())

print("\nBehavior can correct text errors:")
print(behavior_can_help.sum())

print(
    "Percentage of text errors behavior can fix:",
    f"{behavior_can_help.sum() / text_wrong.sum() * 100:.2f}%"
)

print("\nBehavior would hurt correct text predictions:")
print(behavior_would_hurt.sum())

print(
    "Percentage of correct text predictions behavior would hurt:",
    f"{behavior_would_hurt.sum() / (text_pred == y_test_clean).sum() * 100:.2f}%"
)

# ------------------------------------------------------------
# Disagreement analysis
# ------------------------------------------------------------

disagreement = text_pred != behavior_pred

print("\n" + "=" * 60)
print("DISAGREEMENT ANALYSIS")
print("=" * 60)

print("Total disagreements:", disagreement.sum())

print(
    "Text correct / Behavior wrong:",
    (
        disagreement &
        (text_pred == y_test_clean) &
        (behavior_pred != y_test_clean)
    ).sum()
)

print(
    "Behavior correct / Text wrong:",
    (
        disagreement &
        (behavior_pred == y_test_clean) &
        (text_pred != y_test_clean)
    ).sum()
)

print(
    "Both wrong:",
    (
        disagreement &
        (behavior_pred != y_test_clean) &
        (text_pred != y_test_clean)
    ).sum()
)

print(
    "Both correct:",
    (
        (text_pred == y_test_clean) &
        (behavior_pred == y_test_clean)
    ).sum()
)

============================================================
TEXT ERROR ANALYSIS
============================================================
Total test samples: 4285

Text errors:
485

Behavior can correct text errors:
217
Percentage of text errors behavior can fix: 44.74%

Behavior would hurt correct text predictions:
853
Percentage of correct text predictions behavior would hurt: 22.45%

============================================================
DISAGREEMENT ANALYSIS
============================================================
Total disagreements: 1070
Text correct / Behavior wrong: 853
Behavior correct / Text wrong: 217
Both wrong: 0
Both correct: 2947

In [ ]:
# ============================================================
# ANALYZE WHEN BEHAVIOR IS BETTER THAN TEXT
# ============================================================

# Predictions
text_pred = (text_test_prob >= 0.5).astype(int)
behavior_pred = (behavior_test_prob >= 0.5).astype(int)

# Confidence
text_confidence = np.maximum(
    text_test_prob,
    1 - text_test_prob
)

behavior_confidence = np.maximum(
    behavior_test_prob,
    1 - behavior_test_prob
)

# Three important groups
behavior_can_help = (
    (text_pred != y_test_clean) &
    (behavior_pred == y_test_clean)
)

behavior_would_hurt = (
    (text_pred == y_test_clean) &
    (behavior_pred != y_test_clean)
)

both_correct = (
    (text_pred == y_test_clean) &
    (behavior_pred == y_test_clean)
)

# ------------------------------------------------------------
# Build analysis dataframe
# ------------------------------------------------------------

analysis_df = pd.DataFrame({
    "true_label": y_test_clean,
    "text_prob": text_test_prob,
    "behavior_prob": behavior_test_prob,
    "text_confidence": text_confidence,
    "behavior_confidence": behavior_confidence,
    "drift": test_drift_score,
    "text_pred": text_pred,
    "behavior_pred": behavior_pred
})

analysis_df["group"] = "Both Correct"

analysis_df.loc[
    behavior_can_help,
    "group"
] = "Behavior Can Help"

analysis_df.loc[
    behavior_would_hurt,
    "group"
] = "Behavior Would Hurt"

# ------------------------------------------------------------
# Compare groups
# ------------------------------------------------------------

summary = analysis_df.groupby("group").agg({
    "text_confidence": ["mean", "median"],
    "behavior_confidence": ["mean", "median"],
    "drift": ["mean", "median"],
    "text_prob": ["mean", "median"],
    "behavior_prob": ["mean", "median"]
})

print("=" * 70)
print("WHEN IS BEHAVIOR BETTER THAN TEXT?")
print("=" * 70)

print(summary)

print("\nGroup counts:")
print(analysis_df["group"].value_counts())

======================================================================
WHEN IS BEHAVIOR BETTER THAN TEXT?
======================================================================
                    text_confidence           behavior_confidence            \
                               mean    median                mean    median
group
Behavior Can Help          0.720391  0.688301            0.979354  0.999996
Behavior Would Hurt        0.917322  0.970446            0.986829  0.999881
Both Correct               0.882414  0.928283            0.994981  0.999998

                        drift           text_prob           behavior_prob  \
                         mean    median      mean    median          mean
group
Behavior Can Help    0.763617  0.800036  0.297518  0.318530      0.926166
Behavior Would Hurt  0.786560  0.838099  0.369730  0.083384      0.611749
Both Correct         0.744226  0.775554  0.687221  0.876855      0.757691


                       median
group
Behavior Can Help    0.999996
Behavior Would Hurt  0.999847
Both Correct         0.999998

Group counts:
group
Both Correct           3215
Behavior Would Hurt     853
Behavior Can Help       217
Name: count, dtype: int64

In [ ]:
# ============================================================
# CHECK DRIFT DISTRIBUTION OF THE THREE GROUPS
# ============================================================

for group in [
    "Behavior Can Help",
    "Behavior Would Hurt",
    "Both Correct"
]:

    subset = analysis_df[
        analysis_df["group"] == group
    ]

    print("\n" + "=" * 60)
    print(group)
    print("=" * 60)

    print("Count:", len(subset))

    print(
        "Drift mean:",
        round(subset["drift"].mean(), 4)
    )

    print(
        "Drift median:",
        round(subset["drift"].median(), 4)
    )

    print(
        "Drift 25th percentile:",
        round(subset["drift"].quantile(.25), 4)
    )

    print(
        "Drift 75th percentile:",
        round(subset["drift"].quantile(.75), 4)
    )

    print(
        "Behavior confidence mean:",
        round(subset["behavior_confidence"].mean(), 4)
    )

    print(
        "Text confidence mean:",
        round(subset["text_confidence"].mean(), 4)
    )

============================================================
Behavior Can Help
============================================================
Count: 217
Drift mean: 0.7636
Drift median: 0.8
Drift 25th percentile: 0.5701
Drift 75th percentile: 0.9551
Behavior confidence mean: 0.9794
Text confidence mean: 0.7204

============================================================
Behavior Would Hurt
============================================================
Count: 853
Drift mean: 0.7866
Drift median: 0.8381
Drift 25th percentile: 0.6254
Drift 75th percentile: 0.963
Behavior confidence mean: 0.9868
Text confidence mean: 0.9173

============================================================
Both Correct
============================================================
Count: 3215
Drift mean: 0.7442
Drift median: 0.7756
Drift 25th percentile: 0.5708
Drift 75th percentile: 0.9048
Behavior confidence mean: 0.995
Text confidence mean: 0.8824

In [ ]:
# ============================================================
# UNCERTAINTY-BASED SELECTIVE FUSION
# Behavior overrides text ONLY when text is uncertain
# ============================================================

results = []

behavior_val_pred = (
    behavior_val_prob >= 0.5
).astype(int)

text_val_pred = (
    text_val_prob >= 0.5
).astype(int)

behavior_val_conf = np.maximum(
    behavior_val_prob,
    1 - behavior_val_prob
)

text_val_conf = np.maximum(
    text_val_prob,
    1 - text_val_prob
)

disagreement_val = (
    behavior_val_pred != text_val_pred
)

# Search ranges
text_conf_thresholds = np.arange(0.50, 0.96, 0.025)
behavior_conf_thresholds = np.arange(0.50, 1.00, 0.025)
drift_thresholds = np.arange(0.50, 0.96, 0.05)

for text_conf_threshold in text_conf_thresholds:

    for behavior_conf_threshold in behavior_conf_thresholds:

        for drift_threshold in drift_thresholds:

            # Start with TEXT as the default
            final_pred = text_val_pred.copy()

            # Behavior can override ONLY when:
            #
            # 1. Models disagree
            # 2. Text is uncertain
            # 3. Behavior is confident
            # 4. Behavioral drift is below threshold

            override = (
                disagreement_val &
                (text_val_conf <= text_conf_threshold) &
                (behavior_val_conf >= behavior_conf_threshold) &
                (val_drift_score < drift_threshold)
            )

            final_pred[override] = (
                behavior_val_pred[override]
            )

            acc = accuracy_score(y_val, final_pred)
            precision = precision_score(
                y_val,
                final_pred,
                zero_division=0
            )
            recall = recall_score(
                y_val,
                final_pred,
                zero_division=0
            )
            f1 = f1_score(
                y_val,
                final_pred,
                zero_division=0
            )

            results.append({
                "text_conf_threshold": text_conf_threshold,
                "behavior_conf_threshold": behavior_conf_threshold,
                "drift_threshold": drift_threshold,
                "accuracy": acc,
                "precision": precision,
                "recall": recall,
                "f1": f1,
                "overrides": override.sum()
            })

uncertainty_df = pd.DataFrame(results)

best_uncertainty = uncertainty_df.loc[
    uncertainty_df["f1"].idxmax()
]

print("=" * 70)
print("BEST UNCERTAINTY-BASED VALIDATION CONFIGURATION")
print("=" * 70)

print(best_uncertainty)

======================================================================
BEST UNCERTAINTY-BASED VALIDATION CONFIGURATION
======================================================================
text_conf_threshold         0.925000
behavior_conf_threshold     0.500000
drift_threshold             0.900000
accuracy                    0.997856
precision                   1.000000
recall                      0.997462
f1                          0.998729
overrides                  11.000000
Name: 3408, dtype: float64

In [ ]:
# ============================================================
# TEXT-ONLY VALIDATION BASELINE
# ============================================================

text_baseline_pred = (
    text_val_prob >= 0.5
).astype(int)

print("=" * 60)
print("TEXT-ONLY VALIDATION")
print("=" * 60)

print(
    "Accuracy:",
    f"{accuracy_score(y_val, text_baseline_pred)*100:.2f}%"
)

print(
    "Precision:",
    f"{precision_score(y_val, text_baseline_pred)*100:.2f}%"
)

print(
    "Recall:",
    f"{recall_score(y_val, text_baseline_pred)*100:.2f}%"
)

print(
    "F1:",
    f"{f1_score(y_val, text_baseline_pred)*100:.2f}%"
)

============================================================
TEXT-ONLY VALIDATION
============================================================
Accuracy: 99.00%
Precision: 99.58%
Recall: 99.24%
F1: 99.41%

In [ ]:
# ============================================================
# VALIDATION DISAGREEMENT ANALYSIS
# ============================================================

behavior_val_pred = (
    behavior_val_prob >= 0.5
).astype(int)

text_val_pred = (
    text_val_prob >= 0.5
).astype(int)

behavior_val_conf = np.maximum(
    behavior_val_prob,
    1 - behavior_val_prob
)

text_val_conf = np.maximum(
    text_val_prob,
    1 - text_val_prob
)

# Behavior can help text
behavior_can_help_val = (
    (text_val_pred != y_val) &
    (behavior_val_pred == y_val)
)

# Behavior hurts a correct text prediction
behavior_would_hurt_val = (
    (text_val_pred == y_val) &
    (behavior_val_pred != y_val)
)

# Both correct
both_correct_val = (
    (text_val_pred == y_val) &
    (behavior_val_pred == y_val)
)

# Both wrong
both_wrong_val = (
    (text_val_pred != y_val) &
    (behavior_val_pred != y_val)
)

print("=" * 70)
print("VALIDATION DISAGREEMENT ANALYSIS")
print("=" * 70)

print("Total validation samples:", len(y_val))

print("\nText errors:", (text_val_pred != y_val).sum())

print(
    "Behavior can correct text errors:",
    behavior_can_help_val.sum()
)

print(
    "Behavior would hurt correct text:",
    behavior_would_hurt_val.sum()
)

print(
    "Both correct:",
    both_correct_val.sum()
)

print(
    "Both wrong:",
    both_wrong_val.sum()
)

print("\nTotal disagreements:", (
    behavior_val_pred != text_val_pred
).sum())

# ------------------------------------------------------------
# Compare confidence + drift
# ------------------------------------------------------------

val_analysis = pd.DataFrame({
    "text_confidence": text_val_conf,
    "behavior_confidence": behavior_val_conf,
    "drift": val_drift_score,
    "text_prob": text_val_prob,
    "behavior_prob": behavior_val_prob
})

val_analysis["group"] = "Both Correct"

val_analysis.loc[
    behavior_can_help_val,
    "group"
] = "Behavior Can Help"

val_analysis.loc[
    behavior_would_hurt_val,
    "group"
] = "Behavior Would Hurt"

val_analysis.loc[
    both_wrong_val,
    "group"
] = "Both Wrong"

print("\n" + "=" * 70)
print("VALIDATION GROUP STATISTICS")
print("=" * 70)

print(
    val_analysis.groupby("group").agg({
        "text_confidence": ["mean", "median"],
        "behavior_confidence": ["mean", "median"],
        "drift": ["mean", "median"],
        "text_prob": ["mean", "median"],
        "behavior_prob": ["mean", "median"]
    })
)

======================================================================
VALIDATION DISAGREEMENT ANALYSIS
======================================================================
Total validation samples: 1399

Text errors: 14
Behavior can correct text errors: 14
Behavior would hurt correct text: 12
Both correct: 1373
Both wrong: 0

Total disagreements: 26

======================================================================
VALIDATION GROUP STATISTICS
======================================================================
                    text_confidence           behavior_confidence            \
                               mean    median                mean    median
group
Behavior Can Help          0.748017  0.724328            0.977673  0.991682
Behavior Would Hurt        0.992797  0.998371            0.909700  0.957089
Both Correct               0.987242  0.999564            0.992147  0.998881

                        drift           text_prob           behavior_prob  \
                         mean    median      mean    median          mean
group
Behavior Can Help    0.714247  0.710776  0.413397  0.405343      0.627967
Behavior Would Hurt  0.822328  0.874643  0.751977  0.998371      0.295113
Both Correct         0.498885  0.493388  0.851773  0.999564      0.842702


                       median
group
Behavior Can Help    0.959116
Behavior Would Hurt  0.051058
Both Correct         0.998860

In [ ]:
# ============================================================
# TEXT MODEL — FAKE FOLLOWER FALSE NEGATIVES
# ============================================================

text_pred = (text_test_prob >= 0.5).astype(int)

# Fake Followers that are actually bots but text predicted genuine
fake_follower_mask = (
    (lobo_test["account_type"].to_numpy() == "fake_followers")
)

text_false_negative_mask = (
    fake_follower_mask &
    (y_test_clean == 1) &
    (text_pred == 0)
)

fake_fn = lobo_test.loc[text_false_negative_mask].copy()

print("=" * 60)
print("FAKE FOLLOWER TEXT FALSE NEGATIVES")
print("=" * 60)

print("Count:", len(fake_fn))
print("Expected: around 459")

print("\nColumns:")
print(fake_fn.columns.tolist())

============================================================
FAKE FOLLOWER TEXT FALSE NEGATIVES
============================================================
Count: 216
Expected: around 459

Columns:
['id', 'account_type', 'label', 'statuses_count', 'followers_count', 'friends_count', 'favourites_count', 'listed_count', 'created_at', 'updated', 'account_age_days', 'statuses_per_day', 'followers_friends_ratio', 'friends_followers_ratio', 'favorites_per_status', 'log_statuses_count', 'log_followers_count', 'log_friends_count', 'log_favourites_count', 'log_listed_count']

In [ ]:
# ============================================================
# COMPARE TEXT-MISSED FAKE FOLLOWERS
# ============================================================

# Add predictions to test dataframe
test_analysis = lobo_test.copy()

test_analysis["text_probability"] = text_test_prob
test_analysis["text_prediction"] = text_pred

test_analysis["text_confidence"] = np.maximum(
    text_test_prob,
    1 - text_test_prob
)

# Groups
missed_fake = test_analysis[
    (test_analysis["account_type"] == "fake_followers") &
    (test_analysis["label"] == 1) &
    (test_analysis["text_prediction"] == 0)
]

detected_fake = test_analysis[
    (test_analysis["account_type"] == "fake_followers") &
    (test_analysis["label"] == 1) &
    (test_analysis["text_prediction"] == 1)
]

genuine_correct = test_analysis[
    (test_analysis["account_type"] == "genuine_accounts") &
    (test_analysis["label"] == 0) &
    (test_analysis["text_prediction"] == 0)
]

print("=" * 70)
print("TEXT MODEL ERROR CHARACTERISTICS")
print("=" * 70)

print("\nMissed Fake Followers:", len(missed_fake))
print("Detected Fake Followers:", len(detected_fake))
print("Correct Genuine:", len(genuine_correct))

print("\n--- Text probability ---")

print(
    "Missed Fake Followers:",
    missed_fake["text_probability"].mean(),
    "median:",
    missed_fake["text_probability"].median()
)

print(
    "Detected Fake Followers:",
    detected_fake["text_probability"].mean(),
    "median:",
    detected_fake["text_probability"].median()
)

print(
    "Correct Genuine:",
    genuine_correct["text_probability"].mean(),
    "median:",
    genuine_correct["text_probability"].median()
)

print("\n--- Text confidence ---")

print(
    "Missed Fake Followers:",
    missed_fake["text_confidence"].mean(),
    "median:",
    missed_fake["text_confidence"].median()
)

print(
    "Detected Fake Followers:",
    detected_fake["text_confidence"].mean(),
    "median:",
    detected_fake["text_confidence"].median()
)

print(
    "Correct Genuine:",
    genuine_correct["text_confidence"].mean(),
    "median:",
    genuine_correct["text_confidence"].median()
)

======================================================================
TEXT MODEL ERROR CHARACTERISTICS
======================================================================

Missed Fake Followers: 752
Detected Fake Followers: 2450
Correct Genuine: 764

--- Text probability ---
Missed Fake Followers: 0.1157570705146096 median: 0.036555749604568574
Detected Fake Followers: 0.8771952523816261 median: 0.9231178799042434
Correct Genuine: 0.10176408194331517 median: 0.0491599245009592

--- Text confidence ---
Missed Fake Followers: 0.8842429294853904 median: 0.9634442503954315
Detected Fake Followers: 0.8771952523816261 median: 0.9231178799042434
Correct Genuine: 0.8982359180566849 median: 0.9508400754990408

In [ ]:
# ============================================================
# LOAD ORIGINAL TWEETS FOR MISSED FAKE FOLLOWERS
# ============================================================

missed_ids = set(
    missed_fake["user_id"].astype(str)
)

print("Missed account IDs:", len(missed_ids))
print(list(missed_ids)[:10])

KeyError: 'user_id'

In [ ]:
# ============================================================
# FINAL TEST ALIGNMENT CHECK
# ============================================================

print("=" * 70)
print("TEST DATA ALIGNMENT CHECK")
print("=" * 70)

print("\nShapes:")
print("lobo_test:", lobo_test.shape)
print("y_test_clean:", len(y_test_clean))
print("text_test_prob:", len(text_test_prob))
print("behavior_test_prob:", len(behavior_test_prob))
print("test_drift_score:", len(test_drift_score))

print("\nLabel distribution:")
print(
    pd.Series(y_test_clean).value_counts().sort_index()
)

print("\nlobo_test label distribution:")
print(
    lobo_test["label"].value_counts().sort_index()
)

print("\nAccount types:")
print(
    lobo_test["account_type"].value_counts()
)

print("\nFake Followers:")
print(
    (lobo_test["account_type"] == "fake_followers").sum()
)

print("\nGenuine:")
print(
    (lobo_test["account_type"] == "genuine_accounts").sum()
)

# ------------------------------------------------------------
# Compare label arrays
# ------------------------------------------------------------

lobo_labels = lobo_test["label"].to_numpy()

print("\nNumber of label mismatches:")
print(
    np.sum(lobo_labels != y_test_clean)
)

# ------------------------------------------------------------
# Check first few rows
# ------------------------------------------------------------

print("\nFirst 10 rows:")
print(
    pd.DataFrame({
        "lobo_label": lobo_labels[:10],
        "y_test_clean": y_test_clean[:10],
        "text_prob": text_test_prob[:10],
        "behavior_prob": behavior_test_prob[:10],
        "account_type": lobo_test["account_type"].to_numpy()[:10]
    })
)

======================================================================
TEST DATA ALIGNMENT CHECK
======================================================================

Shapes:
lobo_test: (4285, 20)
y_test_clean: 4285
text_test_prob: 4285
behavior_test_prob: 4285
test_drift_score: 4285

Label distribution:
0    1083
1    3202
Name: count, dtype: int64

lobo_test label distribution:
label
0    1083
1    3202
Name: count, dtype: int64

Account types:
account_type
fake_followers      3202
genuine_accounts    1083
Name: count, dtype: int64

Fake Followers:
3202

Genuine:
1083

Number of label mismatches:
1102

First 10 rows:
   lobo_label  y_test_clean  text_prob  behavior_prob      account_type
0           0             0   0.038584   5.321045e-04  genuine_accounts
1           0             0   0.023926   9.073680e-03  genuine_accounts
2           0             0   0.076167   7.926535e-03  genuine_accounts
3           0             0   0.009980   7.450602e-03  genuine_accounts
4           0             0   0.206501   2.205864e-01  genuine_accounts
5           0             0   0.043858   7.582614e-03  genuine_accounts
6           0             0   0.034981   1.187056e-08  genuine_accounts
7           0             0   0.251385   2.327904e-03  genuine_accounts
8           0             0   0.026011   1.043095e-02  genuine_accounts
9           0             0   0.007990   1.334087e-02  genuine_accounts

In [ ]:
# ============================================================
# CHECK WHICH PREDICTION ARRAYS MATCH lobo_test ORDER
# ============================================================

lobo_labels = lobo_test["label"].to_numpy()

arrays_to_check = {
    "y_test_clean": y_test_clean,
    "y_lobo_test": np.asarray(y_lobo_test),
    "y_test": np.asarray(y_test),
}

for name, arr in arrays_to_check.items():
    if len(arr) == len(lobo_labels):
        mismatches = np.sum(arr != lobo_labels)
        print(f"{name:20s} -> mismatches: {mismatches}")

y_test_clean         -> mismatches: 1102
y_lobo_test          -> mismatches: 1102
y_test               -> mismatches: 0

In [ ]:
text_test_prob
lobo_behavior_prob
behavior_test_prob

array([5.3210446e-04, 9.0736803e-03, 7.9265349e-03, ..., 9.9999905e-01,
       9.9999911e-01, 9.9999911e-01], shape=(4285,), dtype=float32)

In [ ]:
# ============================================================
# CHECK CURRENT PREDICTION SOURCES
# ============================================================

print("lobo_test first 10 IDs:")
print(lobo_test["id"].astype(str).head(10).tolist())

print("\nX_lobo_test first 10 IDs:")
print(X_lobo_test.index[:10].tolist())

print("\nShapes:")
print("lobo_test:", lobo_test.shape)
print("X_lobo_test:", X_lobo_test.shape)
print("X_lobo_test_scaled:", X_lobo_test_scaled.shape)
print("X_combined_test:", X_combined_test.shape)

lobo_test first 10 IDs:
['191839658', '2157382005', '1947320929', '1733095801', '21959183', '2291421004', '2337494094', '225241810', '585912212', '2320414572']

X_lobo_test first 10 IDs:
[3, 5, 6, 8, 12, 17, 18, 19, 24, 26]

Shapes:
lobo_test: (4285, 20)
X_lobo_test: (4285, 15)
X_lobo_test_scaled: (4285, 15)
X_combined_test: (4285, 50000)

In [ ]:
# ============================================================
# AUTHORITATIVE TEST LABELS
# ============================================================

y_test_aligned = lobo_test["label"].to_numpy()

print("Aligned labels:", len(y_test_aligned))
print(pd.Series(y_test_aligned).value_counts().sort_index())

Aligned labels: 4285
0    1083
1    3202
Name: count, dtype: int64

In [ ]:
# ============================================================
# CHECK TEXT TEST DATA ORDER
# ============================================================

print("X_combined_test shape:", X_combined_test.shape)

print("\nText test probability first 10:")
print(text_test_prob[:10])

print("\nCurrent lobo_test first 10 IDs:")
print(lobo_test["id"].astype(str).head(10).tolist())

print("\nCurrent lobo_test last 10 IDs:")
print(lobo_test["id"].astype(str).tail(10).tolist())

X_combined_test shape: (4285, 50000)

Text test probability first 10:
[0.03858445 0.02392628 0.07616656 0.00998004 0.2065006  0.04385761
 0.03498077 0.25138528 0.02601065 0.00798955]

Current lobo_test first 10 IDs:
['191839658', '2157382005', '1947320929', '1733095801', '21959183', '2291421004', '2337494094', '225241810', '585912212', '2320414572']

Current lobo_test last 10 IDs:
['1386619668', '1387393236', '1387417639', '1387702238', '1388028872', '1388819528', '1391378610', '1391497074', '1391622127', '1391832212']

In [ ]:
# ============================================================
# CLEAN TEXT MODEL ERROR ANALYSIS
# ============================================================

text_pred_clean = (text_test_prob >= 0.5).astype(int)

# Use the label array that matches lobo_test
y_true = np.asarray(y_test)

# Verify one final time
print("Label mismatches:",
      np.sum(lobo_test["label"].to_numpy() != y_true))

# ------------------------------------------------------------
# Masks
# ------------------------------------------------------------

fake_mask = (
    lobo_test["account_type"].to_numpy() == "fake_followers"
)

genuine_mask = (
    lobo_test["account_type"].to_numpy() == "genuine_accounts"
)

fake_fn_mask = (
    fake_mask &
    (y_true == 1) &
    (text_pred_clean == 0)
)

fake_tp_mask = (
    fake_mask &
    (y_true == 1) &
    (text_pred_clean == 1)
)

genuine_correct_mask = (
    genuine_mask &
    (y_true == 0) &
    (text_pred_clean == 0)
)

print("\n" + "=" * 60)
print("CLEAN TEXT MODEL ERROR ANALYSIS")
print("=" * 60)

print("Fake Followers total:", fake_mask.sum())
print("Fake Followers missed:", fake_fn_mask.sum())
print("Fake Followers detected:", fake_tp_mask.sum())
print("Genuine correctly detected:", genuine_correct_mask.sum())

print("\nFake Follower recall:",
      fake_tp_mask.sum() / fake_mask.sum())

# ------------------------------------------------------------
# Overall metrics
# ------------------------------------------------------------

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

print("\nOverall:")
print("Accuracy :", accuracy_score(y_true, text_pred_clean))
print("Precision:", precision_score(y_true, text_pred_clean))
print("Recall   :", recall_score(y_true, text_pred_clean))
print("F1       :", f1_score(y_true, text_pred_clean))

print("\nConfusion matrix:")
print(confusion_matrix(y_true, text_pred_clean))

Label mismatches: 0

============================================================
CLEAN TEXT MODEL ERROR ANALYSIS
============================================================
Fake Followers total: 3202
Fake Followers missed: 752
Fake Followers detected: 2450
Genuine correctly detected: 764

Fake Follower recall: 0.7651467832604623

Overall:
Accuracy : 0.7500583430571762
Precision: 0.8847959552184904
Recall   : 0.7651467832604623
F1       : 0.82063305978898

Confusion matrix:
[[ 764  319]
 [ 752 2450]]

In [ ]:
missed_fake = lobo_test.loc[fake_fn_mask].copy()

missed_ids = set(
    missed_fake["id"].astype(str)
)

print("Missed account IDs:", len(missed_ids))
print(list(missed_ids)[:20])

Missed account IDs: 752
['1380853662', '44091292', '96730829', '1127891892', '620112188', '59989426', '1208944405', '129729416', '1205018334', '1207857181', '1208439134', '1366923541', '229906054', '1208880902', '623013588', '153824393', '620060059', '620758404', '21375100', '1208119178']

In [ ]:
# ============================================================
# FAKE FOLLOWER ERROR GROUP: BEHAVIOR COMPARISON
# ============================================================

# Masks
missed_mask = fake_fn_mask

detected_mask = (
    fake_mask &
    (text_pred_clean == 1)
)

missed_accounts = lobo_test.loc[missed_mask].copy()
detected_accounts = lobo_test.loc[detected_mask].copy()

print("=" * 70)
print("FAKE FOLLOWER ERROR GROUP COMPARISON")
print("=" * 70)

print("\nMissed:", len(missed_accounts))
print("Detected:", len(detected_accounts))

# ------------------------------------------------------------
# Compare behavioral features
# ------------------------------------------------------------

compare_features = [
    "statuses_count",
    "followers_count",
    "friends_count",
    "favourites_count",
    "listed_count",
    "account_age_days",
    "statuses_per_day",
    "followers_friends_ratio",
    "friends_followers_ratio",
    "favorites_per_status",
    "log_statuses_count",
    "log_followers_count",
    "log_friends_count",
    "log_favourites_count",
    "log_listed_count"
]

comparison = pd.DataFrame({
    "Missed_Fake": missed_accounts[compare_features].mean(),
    "Detected_Fake": detected_accounts[compare_features].mean()
})

comparison["Difference_%"] = (
    (comparison["Missed_Fake"] - comparison["Detected_Fake"])
    / comparison["Detected_Fake"].replace(0, np.nan)
) * 100

print("\nMean comparison:")
print(comparison.round(3))

======================================================================
FAKE FOLLOWER ERROR GROUP COMPARISON
======================================================================

Missed: 752
Detected: 2450

Mean comparison:
                         Missed_Fake  Detected_Fake  Difference_%
statuses_count               140.723         54.474       158.330
followers_count               20.504         17.499        17.174
friends_count                374.073        359.993         3.911
favourites_count               5.445          3.693        47.452
listed_count                   0.193          0.040       387.017
account_age_days             662.722        311.535       112.728
statuses_per_day               0.158          0.160        -1.210
followers_friends_ratio        0.047          0.048        -1.974
friends_followers_ratio       46.672         36.179        29.003
favorites_per_status           0.039          0.021        86.895
log_statuses_count             2.925          3.324       -12.018
log_followers_count            2.283          2.594       -11.967
log_friends_count              5.519          5.768        -4.307
log_favourites_count           0.318          0.155       105.895
log_listed_count               0.082          0.013       509.869

In [ ]:
# ============================================================
# MEDIAN COMPARISON
# ============================================================

median_comparison = pd.DataFrame({
    "Missed_Fake": missed_accounts[compare_features].median(),
    "Detected_Fake": detected_accounts[compare_features].median()
})

median_comparison["Difference_%"] = (
    (median_comparison["Missed_Fake"] - median_comparison["Detected_Fake"])
    / median_comparison["Detected_Fake"].replace(0, np.nan)
) * 100

print(median_comparison.round(3))

                         Missed_Fake  Detected_Fake  Difference_%
statuses_count                20.000         24.000       -16.667
followers_count               11.000         13.000       -15.385
friends_count                339.000        284.500        19.156
favourites_count               0.000          0.000           NaN
listed_count                   0.000          0.000           NaN
account_age_days             353.740        351.703         0.579
statuses_per_day               0.057          0.142       -59.852
followers_friends_ratio        0.038          0.043       -10.223
friends_followers_ratio       24.236         23.357         3.763
favorites_per_status           0.000          0.000           NaN
log_statuses_count             3.045          3.219        -5.417
log_followers_count            2.485          2.639        -5.841
log_friends_count              5.829          5.654         3.090
log_favourites_count           0.000          0.000           NaN
log_listed_count               0.000          0.000           NaN

In [ ]:
# ============================================================
# CAN BEHAVIOR RECOVER TEXT FALSE NEGATIVES?
# ============================================================

behavior_pred_clean = (
    behavior_test_prob >= 0.5
).astype(int)

# Text missed Fake Followers
text_fn_mask = (
    fake_mask &
    (text_pred_clean == 0)
)

# Among those, check behavioral prediction
behavior_correct_on_text_fn = (
    text_fn_mask &
    (behavior_pred_clean == 1)
)

behavior_also_missed = (
    text_fn_mask &
    (behavior_pred_clean == 0)
)

print("=" * 70)
print("BEHAVIOR MODEL ON TEXT FALSE NEGATIVES")
print("=" * 70)

print("Text false negatives:", text_fn_mask.sum())

print(
    "Behavior correctly recovers:",
    behavior_correct_on_text_fn.sum()
)

print(
    "Behavior also misses:",
    behavior_also_missed.sum()
)

print(
    "Recovery rate:",
    behavior_correct_on_text_fn.sum()
    / text_fn_mask.sum()
)

# ------------------------------------------------------------
# What happens to correct text predictions?
# ------------------------------------------------------------

text_correct_mask = (
    fake_mask &
    (text_pred_clean == 1)
)

behavior_would_hurt = (
    text_correct_mask &
    (behavior_pred_clean == 0)
)

print("\n" + "-" * 70)
print("COST OF USING BEHAVIOR")
print("-" * 70)

print(
    "Text-correct Fake Followers:",
    text_correct_mask.sum()
)

print(
    "Behavior would incorrectly reject:",
    behavior_would_hurt.sum()
)

print(
    "Potential harm rate:",
    behavior_would_hurt.sum()
    / text_correct_mask.sum()
)

======================================================================
BEHAVIOR MODEL ON TEXT FALSE NEGATIVES
======================================================================
Text false negatives: 752
Behavior correctly recovers: 719
Behavior also misses: 33
Recovery rate: 0.9561170212765957

----------------------------------------------------------------------
COST OF USING BEHAVIOR
----------------------------------------------------------------------
Text-correct Fake Followers: 2450
Behavior would incorrectly reject: 26
Potential harm rate: 0.010612244897959184

In [ ]:
# ============================================================
# COMPLETE TEXT + BEHAVIOR ERROR OVERLAP
# ============================================================

text_correct = (text_pred_clean == y_true)
behavior_correct = (behavior_pred_clean == y_true)

both_correct = text_correct & behavior_correct
text_only_correct = text_correct & ~behavior_correct
behavior_only_correct = ~text_correct & behavior_correct
both_wrong = ~text_correct & ~behavior_correct

print("=" * 70)
print("TEXT + BEHAVIOR ERROR OVERLAP")
print("=" * 70)

print("Both correct:", both_correct.sum())
print("Text only correct:", text_only_correct.sum())
print("Behavior only correct:", behavior_only_correct.sum())
print("Both wrong:", both_wrong.sum())

print("\nTotal:", len(y_true))

print("\nPercentages:")
print("Both correct       :", round(both_correct.mean() * 100, 2), "%")
print("Text only correct  :", round(text_only_correct.mean() * 100, 2), "%")
print("Behavior only      :", round(behavior_only_correct.mean() * 100, 2), "%")
print("Both wrong         :", round(both_wrong.mean() * 100, 2), "%")

======================================================================
TEXT + BEHAVIOR ERROR OVERLAP
======================================================================
Both correct: 3181
Text only correct: 33
Behavior only correct: 1037
Both wrong: 34

Total: 4285

Percentages:
Both correct       : 74.24 %
Text only correct  : 0.77 %
Behavior only      : 24.2 %
Both wrong         : 0.79 %

In [ ]:
# ============================================================
# ORACLE COMPLEMENTARY ACCURACY
# ============================================================

oracle_correct = text_correct | behavior_correct

oracle_accuracy = oracle_correct.mean()

print("=" * 70)
print("ORACLE COMPLEMENTARITY")
print("=" * 70)

print("Oracle accuracy:",
      round(oracle_accuracy * 100, 2), "%")

print("Oracle errors:",
      (~oracle_correct).sum())

print("\nInterpretation:")
print(
    "This is the theoretical accuracy if we could always "
    "choose the correct model for each account."
)

======================================================================
ORACLE COMPLEMENTARITY
======================================================================
Oracle accuracy: 99.21 %
Oracle errors: 34

Interpretation:
This is the theoretical accuracy if we could always choose the correct model for each account.

In [ ]:
# ============================================================
# BEHAVIOR-ONLY CORRECT CASES: CONFIDENCE + DRIFT
# ============================================================

behavior_only_mask = (
    (~text_correct) &
    behavior_correct
)

text_only_mask = (
    text_correct &
    (~behavior_correct)
)

both_correct_mask = (
    text_correct &
    behavior_correct
)

both_wrong_mask = (
    (~text_correct) &
    (~behavior_correct)
)

analysis_groups = {
    "Behavior only correct": behavior_only_mask,
    "Text only correct": text_only_mask,
    "Both correct": both_correct_mask,
    "Both wrong": both_wrong_mask
}

print("=" * 70)
print("MODEL COMPLEMENTARITY: CONFIDENCE + DRIFT")
print("=" * 70)

for name, mask in analysis_groups.items():

    print("\n" + name)
    print("-" * 50)

    print("Count:", mask.sum())

    if mask.sum() > 0:

        print(
            "Behavior probability mean:",
            behavior_test_prob[mask].mean()
        )

        print(
            "Behavior confidence mean:",
            np.abs(
                behavior_test_prob[mask] - 0.5
            ).mean() * 2
        )

        print(
            "Text probability mean:",
            text_test_prob[mask].mean()
        )

        print(
            "Text confidence mean:",
            np.abs(
                text_test_prob[mask] - 0.5
            ).mean() * 2
        )

        print(
            "Drift mean:",
            test_drift_score[mask].mean()
        )

        print(
            "Drift median:",
            np.median(test_drift_score[mask])
        )

======================================================================
MODEL COMPLEMENTARITY: CONFIDENCE + DRIFT
======================================================================

Behavior only correct
--------------------------------------------------
Count: 1037
Behavior probability mean: 0.68929565
Behavior confidence mean: 0.9773884
Text probability mean: 0.3447097904135287
Text confidence mean: 0.7558522614818626
Drift mean: 0.7819313009774856
Drift median: 0.833988563259471

Text only correct
--------------------------------------------------
Count: 33
Behavior probability mean: 0.24243774
Behavior confidence mean: 0.75813746
Text probability mean: 0.6811283075448322
Text confidence mean: 0.7206755705385968
Drift mean: 0.7811369592999329
Drift median: 0.8230879199428163

Both correct
--------------------------------------------------
Count: 3181
Behavior probability mean: 0.76367
Behavior confidence mean: 0.9936214
Text probability mean: 0.6929892778342335
Text confidence mean: 0.7648471944774625
Drift mean: 0.7454053384788479
Drift median: 0.7775196568977841

Both wrong
--------------------------------------------------
Count: 34
Behavior probability mean: 0.1983132
Behavior confidence mean: 0.64764947
Text probability mean: 0.1475299230361121
Text confidence mean: 0.7630610829258009
Drift mean: 0.6339349535382416
Drift median: 0.6036454610436026

In [ ]:
# ============================================================
# BEHAVIOR MODEL CALIBRATION CHECK
# VALIDATION ONLY
# ============================================================

from sklearn.metrics import brier_score_loss
from sklearn.calibration import calibration_curve

behavior_val_pred = (behavior_val_prob >= 0.5).astype(int)

brier = brier_score_loss(
    y_val,
    behavior_val_prob
)

print("=" * 70)
print("BEHAVIOR MODEL CALIBRATION")
print("=" * 70)

print("Brier score:", round(brier, 6))

print("\nProbability distribution:")
print(
    pd.Series(behavior_val_prob).describe(
        percentiles=[0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]
    )
)

# ------------------------------------------------------------
# Calibration bins
# ------------------------------------------------------------

prob_bins = pd.cut(
    behavior_val_prob,
    bins=[0, 0.1, 0.2, 0.3, 0.4, 0.5,
          0.6, 0.7, 0.8, 0.9, 1.0],
    include_lowest=True
)

calibration_table = (
    pd.DataFrame({
        "probability": behavior_val_prob,
        "actual": y_val
    })
    .groupby(prob_bins, observed=False)
    .agg(
        count=("actual", "size"),
        mean_predicted=("probability", "mean"),
        actual_rate=("actual", "mean")
    )
)

print("\nCalibration table:")
print(calibration_table.round(4))

======================================================================
BEHAVIOR MODEL CALIBRATION
======================================================================
Brier score: 0.008442

Probability distribution:
count    1399.000000
mean        0.835856
std         0.360557
min         0.000003
1%          0.002010
5%          0.004421
25%         0.992832
50%         0.998825
75%         0.999654
95%         0.999928
99%         0.999998
max         0.999999
dtype: float64

Calibration table:
               count  mean_predicted  actual_rate
(-0.001, 0.1]    220          0.0086       0.0318
(0.1, 0.2]         0             NaN          NaN
(0.2, 0.3]         1          0.2206       0.0000
(0.3, 0.4]         2          0.3277       1.0000
(0.4, 0.5]         0             NaN          NaN
(0.5, 0.6]         2          0.5303       1.0000
(0.6, 0.7]         1          0.6475       1.0000
(0.7, 0.8]        12          0.7550       1.0000
(0.8, 0.9]        13          0.8495       0.8462
(0.9, 1.0]      1148          0.9972       0.9991

In [ ]:
# ============================================================
# VALIDATION ALIGNMENT CHECK
# ============================================================

print("=" * 70)
print("VALIDATION ALIGNMENT")
print("=" * 70)

print("y_lobo_val length:", len(y_lobo_val))
print("y_val length:", len(y_val))
print("behavior_val_prob:", len(behavior_val_prob))
print("text_val_prob:", len(text_val_prob))

print("\nLabel mismatch:")
print(
    np.sum(
        np.asarray(y_lobo_val) != np.asarray(y_val)
    )
)

print("\nValidation label distribution:")
print(
    pd.Series(y_val).value_counts().sort_index()
)

======================================================================
VALIDATION ALIGNMENT
======================================================================
y_lobo_val length: 1399
y_val length: 1399
behavior_val_prob: 1399
text_val_prob: 1399

Label mismatch:
0

Validation label distribution:
0     217
1    1182
Name: count, dtype: int64

In [ ]:
# ============================================================
# PREPARE CLEAN ADAPTIVE FUSION FEATURES
# ============================================================

import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

behavior_val = np.asarray(behavior_val_prob)
text_val = np.asarray(text_val_prob)
drift_val = np.asarray(val_drift_score)

# ------------------------------------------------------------
# Test
# ------------------------------------------------------------

behavior_test = np.asarray(lobo_behavior_prob)
text_test = np.asarray(text_test_prob)
drift_test = np.asarray(test_drift_score)

# ------------------------------------------------------------
# Feature builder
# ------------------------------------------------------------

def build_fusion_features(behavior, text, drift):

    return pd.DataFrame({
        "behavior_prob": behavior,
        "text_prob": text,

        "prob_difference": behavior - text,

        "absolute_difference": np.abs(
            behavior - text
        ),

        "behavior_confidence": np.abs(
            behavior - 0.5
        ) * 2,

        "text_confidence": np.abs(
            text - 0.5
        ) * 2,

        "drift_score": drift,

        "agreement": (
            (behavior >= 0.5) ==
            (text >= 0.5)
        ).astype(int)
    })


fusion_val = build_fusion_features(
    behavior_val,
    text_val,
    drift_val
)

fusion_test = build_fusion_features(
    behavior_test,
    text_test,
    drift_test
)

print("=" * 70)
print("CLEAN ADAPTIVE FUSION FEATURES")
print("=" * 70)

print("\nValidation shape:", fusion_val.shape)
print("Test shape:", fusion_test.shape)

print("\nFeatures:")
print(fusion_val.columns.tolist())

print("\nValidation preview:")
print(fusion_val.head())

print("\nTest preview:")
print(fusion_test.head())

======================================================================
CLEAN ADAPTIVE FUSION FEATURES
======================================================================

Validation shape: (1399, 8)
Test shape: (4285, 8)

Features:
['behavior_prob', 'text_prob', 'prob_difference', 'absolute_difference', 'behavior_confidence', 'text_confidence', 'drift_score', 'agreement']

Validation preview:
   behavior_prob  text_prob  prob_difference  absolute_difference  \
0       0.999690   0.998852         0.000838             0.000838
1       0.998265   0.999856        -0.001591             0.001591
2       0.002287   0.202346        -0.200060             0.200060
3       0.999789   0.999831        -0.000043             0.000043
4       0.008525   0.029393        -0.020868             0.020868

   behavior_confidence  text_confidence  drift_score  agreement
0             0.999379         0.997704     0.609006          1
1             0.996529         0.999711     0.235704          1
2             0.995427         0.595308     0.876162          1
3             0.999577         0.999663     0.375804          1
4             0.982950         0.941214     0.832559          1

Test preview:
   behavior_prob  text_prob  prob_difference  absolute_difference  \
0       0.000532   0.038584        -0.038052             0.038052
1       0.009074   0.023926        -0.014853             0.014853
2       0.007927   0.076167        -0.068240             0.068240
3       0.007451   0.009980        -0.002529             0.002529
4       0.220586   0.206501         0.014086             0.014086

   behavior_confidence  text_confidence  drift_score  agreement
0             0.998936         0.922831     0.998392          1
1             0.981853         0.952147     0.869371          1
2             0.984147         0.847667     0.971587          1
3             0.985099         0.980040     0.827019          1
4             0.558827         0.586999     0.933881          1

In [ ]:
# ============================================================
# CLEAN OOF POOL FOR ADAPTIVE FUSION
# ============================================================

from sklearn.model_selection import StratifiedKFold
import numpy as np
import pandas as pd

# Known-category LOBO training pool
oof_data = lobo_train.copy().reset_index(drop=True)

print("=" * 70)
print("OOF POOL")
print("=" * 70)

print("Shape:", oof_data.shape)
print("\nAccount types:")
print(oof_data["account_type"].value_counts())

print("\nLabels:")
print(oof_data["label"].value_counts().sort_index())

# ------------------------------------------------------------
# 5-fold stratified OOF split
# ------------------------------------------------------------

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

oof_behavior_prob = np.zeros(len(oof_data))
oof_text_prob = np.zeros(len(oof_data))

print("\nOOF arrays created:")
print("Behavior:", oof_behavior_prob.shape)
print("Text:", oof_text_prob.shape)

======================================================================
OOF POOL
======================================================================
Shape: (6995, 20)

Account types:
account_type
social_spambots_2         3457
genuine_accounts          1083
traditional_spambots_1    1000
social_spambots_1          991
social_spambots_3          464
Name: count, dtype: int64

Labels:
label
0    1083
1    5912
Name: count, dtype: int64

OOF arrays created:
Behavior: (6995,)
Text: (6995,)

In [ ]:
# ============================================================
# CLEAN OOF BEHAVIOR MODEL
# ============================================================

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, BatchNormalization, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# ------------------------------------------------------------
# Behavior features
# ------------------------------------------------------------

behavior_features = [
    "statuses_count",
    "followers_count",
    "friends_count",
    "favourites_count",
    "listed_count",
    "account_age_days",
    "statuses_per_day",
    "followers_friends_ratio",
    "friends_followers_ratio",
    "favorites_per_status",
    "log_statuses_count",
    "log_followers_count",
    "log_friends_count",
    "log_favourites_count",
    "log_listed_count"
]

X_oof_behavior = oof_data[behavior_features].copy()
y_oof = oof_data["label"].to_numpy()

# ------------------------------------------------------------
# Generate OOF predictions
# ------------------------------------------------------------

oof_behavior_prob = np.zeros(len(oof_data))

for fold, (train_idx, val_idx) in enumerate(
    skf.split(X_oof_behavior, y_oof), start=1
):

    print("\n" + "=" * 70)
    print(f"BEHAVIOR OOF FOLD {fold}/5")
    print("=" * 70)

    X_train_fold = X_oof_behavior.iloc[train_idx]
    X_val_fold = X_oof_behavior.iloc[val_idx]

    y_train_fold = y_oof[train_idx]
    y_val_fold = y_oof[val_idx]

    # --------------------------------------------------------
    # Fit preprocessing ONLY on this fold's training data
    # --------------------------------------------------------

    fold_imputer = SimpleImputer(strategy="median")

    X_train_imp = fold_imputer.fit_transform(X_train_fold)
    X_val_imp = fold_imputer.transform(X_val_fold)

    fold_scaler = StandardScaler()

    X_train_scaled = fold_scaler.fit_transform(X_train_imp)
    X_val_scaled = fold_scaler.transform(X_val_imp)

    # --------------------------------------------------------
    # Class weights
    # --------------------------------------------------------

    classes = np.unique(y_train_fold)

    weights = compute_class_weight(
        class_weight="balanced",
        classes=classes,
        y=y_train_fold
    )

    fold_class_weights = dict(
        zip(classes, weights)
    )

    print("Train:", len(train_idx))
    print("Validation:", len(val_idx))
    print("Class weights:", fold_class_weights)

    # --------------------------------------------------------
    # Fresh neural network
    # --------------------------------------------------------

    tf.keras.backend.clear_session()

    fold_model = Sequential([
        Input(shape=(len(behavior_features),)),

        Dense(128, activation="relu"),
        BatchNormalization(),
        Dropout(0.25),

        Dense(64, activation="relu"),
        BatchNormalization(),
        Dropout(0.20),

        Dense(32, activation="relu"),
        Dropout(0.10),

        Dense(1, activation="sigmoid")
    ])

    fold_model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )

    # --------------------------------------------------------
    # Callbacks
    # --------------------------------------------------------

    early_stop = EarlyStopping(
        monitor="val_loss",
        patience=5,
        restore_best_weights=True
    )

    reduce_lr = ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=2,
        min_lr=1e-6
    )

    # --------------------------------------------------------
    # Train
    # --------------------------------------------------------

    fold_model.fit(
        X_train_scaled,
        y_train_fold,
        validation_data=(X_val_scaled, y_val_fold),
        epochs=50,
        batch_size=32,
        class_weight=fold_class_weights,
        callbacks=[early_stop, reduce_lr],
        verbose=0
    )

    # --------------------------------------------------------
    # OOF prediction
    # --------------------------------------------------------

    fold_pred = fold_model.predict(
        X_val_scaled,
        verbose=0
    ).ravel()

    oof_behavior_prob[val_idx] = fold_pred

    print(
        f"Fold {fold} prediction range: "
        f"{fold_pred.min():.6f} → {fold_pred.max():.6f}"
    )

print("\n" + "=" * 70)
print("BEHAVIOR OOF COMPLETE")
print("=" * 70)

print("Predictions:", len(oof_behavior_prob))
print("Missing predictions:",
      np.sum(oof_behavior_prob == 0))

print(
    "Range:",
    oof_behavior_prob.min(),
    "→",
    oof_behavior_prob.max()
)

======================================================================
BEHAVIOR OOF FOLD 1/5
======================================================================
Train: 5596
Validation: 1399
Class weights: {np.int64(0): np.float64(3.23094688221709), np.int64(1): np.float64(0.5915433403805497)}
WARNING:tensorflow:From c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.venv_nn\Lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

Fold 1 prediction range: 0.000011 → 1.000000

======================================================================
BEHAVIOR OOF FOLD 2/5
======================================================================
Train: 5596
Validation: 1399
Class weights: {np.int64(0): np.float64(3.23094688221709), np.int64(1): np.float64(0.5915433403805497)}
Fold 2 prediction range: 0.000003 → 0.999956

======================================================================
BEHAVIOR OOF FOLD 3/5
======================================================================
Train: 5596
Validation: 1399
Class weights: {np.int64(0): np.float64(3.23094688221709), np.int64(1): np.float64(0.5915433403805497)}
Fold 3 prediction range: 0.000704 → 0.999984

======================================================================
BEHAVIOR OOF FOLD 4/5
======================================================================
Train: 5596
Validation: 1399
Class weights: {np.int64(0): np.float64(3.2272202998846597), np.int64(1): np.float64(0.5916684288433073)}
Fold 4 prediction range: 0.000000 → 0.999941

======================================================================
BEHAVIOR OOF FOLD 5/5
======================================================================
Train: 5596
Validation: 1399
Class weights: {np.int64(0): np.float64(3.2272202998846597), np.int64(1): np.float64(0.5916684288433073)}
Fold 5 prediction range: 0.000006 → 0.999953

======================================================================
BEHAVIOR OOF COMPLETE
======================================================================
Predictions: 6995
Missing predictions: 0
Range: 2.984048771970116e-11 → 1.0

In [ ]:
# Find DataFrames currently in memory that contain a "text" column

import pandas as pd

text_dfs = []

for name, obj in globals().items():
    if isinstance(obj, pd.DataFrame):
        if "text" in obj.columns:
            text_dfs.append((name, obj.shape, obj.columns.tolist()))

print("=" * 70)
print("DATAFRAMES CONTAINING TEXT")
print("=" * 70)

if not text_dfs:
    print("No dataframe with a 'text' column found.")
else:
    for name, shape, columns in text_dfs:
        print(f"\nVariable: {name}")
        print(f"Shape: {shape}")
        print(f"Columns: {columns}")

======================================================================
DATAFRAMES CONTAINING TEXT
======================================================================

Variable: test_tweets
Shape: (196027, 23)
Columns: ['created_at', 'id', 'text', 'source', 'user_id', 'truncated', 'in_reply_to_status_id', 'in_reply_to_user_id', 'in_reply_to_screen_name', 'retweeted_status_id', 'geo', 'place', 'contributors', 'retweet_count', 'reply_count', 'favorite_count', 'favorited', 'retweeted', 'possibly_sensitive', 'num_hashtags', 'num_urls', 'num_mentions', 'timestamp']

Variable: df_temp
Shape: (145094, 4)
Columns: ['user_id', 'text', 'label', 'account_type']

Variable: text_tweets
Shape: (6624609, 4)
Columns: ['user_id', 'text', 'label', 'account_type']

Variable: controlled_tweets
Shape: (714839, 4)
Columns: ['user_id', 'text', 'label', 'account_type']

Variable: account_text
Shape: (10197, 5)
Columns: ['user_id', 'text', 'label', 'account_type', 'tweet_count_used']

Variable: text_lobo_train
Shape: (6995, 5)
Columns: ['user_id', 'text', 'label', 'account_type', 'tweet_count_used']

Variable: text_lobo_test
Shape: (4285, 5)
Columns: ['user_id', 'text', 'label', 'account_type', 'tweet_count_used']

Variable: text_lobo_train_split
Shape: (5596, 5)
Columns: ['user_id', 'text', 'label', 'account_type', 'tweet_count_used']

Variable: text_lobo_val
Shape: (1399, 5)
Columns: ['user_id', 'text', 'label', 'account_type', 'tweet_count_used']

Variable: text_stack_train
Shape: (6995, 6)
Columns: ['user_id', 'text', 'label', 'account_type', 'tweet_count_used', 'oof_fold']

Variable: fold_train
Shape: (5596, 6)
Columns: ['user_id', 'text', 'label', 'account_type', 'tweet_count_used', 'oof_fold']

Variable: fold_val
Shape: (1399, 6)
Columns: ['user_id', 'text', 'label', 'account_type', 'tweet_count_used', 'oof_fold']

Variable: fake
Shape: (3202, 6)
Columns: ['label', 'text_prob', 'text_pred', 'account_type', 'correct', 'text']

Variable: wrong_fake
Shape: (231, 6)
Columns: ['label', 'text_prob', 'text_pred', 'account_type', 'correct', 'text']

Variable: text_debug
Shape: (4285, 8)
Columns: ['user_id', 'account_type', 'label', 'text', 'tweet_count_used', 'text_prob', 'text_pred', 'correct']

Variable: genuine_wrong
Shape: (26, 8)
Columns: ['user_id', 'account_type', 'label', 'text', 'tweet_count_used', 'text_prob', 'text_pred', 'correct']

Variable: fake_wrong
Shape: (459, 8)
Columns: ['user_id', 'account_type', 'label', 'text', 'tweet_count_used', 'text_prob', 'text_pred', 'correct']

Variable: fake_analysis
Shape: (3202, 9)
Columns: ['user_id', 'account_type', 'label', 'text', 'tweet_count_used', 'text_prob', 'text_pred', 'correct', 'text_evidence_level']

In [ ]:
# ============================================================
# CLEAN TEXT OOF PREDICTIONS
# ============================================================

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV
from scipy.sparse import hstack
import numpy as np

# ------------------------------------------------------------
# Use the SAME account ordering as the behavioral OOF pool
# ------------------------------------------------------------

# Match text data to oof_data using user ID
text_oof_data = oof_data[
    ["id", "label", "account_type"]
].merge(
    text_lobo_train[
        ["user_id", "text", "label", "account_type"]
    ],
    left_on="id",
    right_on="user_id",
    how="left",
    suffixes=("_behavior", "_text")
)

# ------------------------------------------------------------
# Alignment checks
# ------------------------------------------------------------

print("=" * 70)
print("TEXT OOF DATA ALIGNMENT")
print("=" * 70)

print("Rows:", len(text_oof_data))

print(
    "Missing text:",
    text_oof_data["text"].isna().sum()
)

print(
    "ID mismatches:",
    (text_oof_data["id"] != text_oof_data["user_id"]).sum()
)

print(
    "Label mismatches:",
    (
        text_oof_data["label_behavior"]
        != text_oof_data["label_text"]
    ).sum()
)

print(
    "Account-type mismatches:",
    (
        text_oof_data["account_type_behavior"]
        != text_oof_data["account_type_text"]
    ).sum()
)

# ------------------------------------------------------------
# Text and labels
# ------------------------------------------------------------

X_oof_text = (
    text_oof_data["text"]
    .fillna("")
    .astype(str)
)

y_oof = (
    text_oof_data["label_behavior"]
    .to_numpy()
)

# ------------------------------------------------------------
# OOF predictions
# ------------------------------------------------------------

oof_text_prob = np.zeros(len(oof_data))

for fold, (train_idx, val_idx) in enumerate(
    skf.split(X_oof_text, y_oof),
    start=1
):

    print("\n" + "=" * 70)
    print(f"TEXT OOF FOLD {fold}/5")
    print("=" * 70)

    train_text = X_oof_text.iloc[train_idx]
    val_text = X_oof_text.iloc[val_idx]

    y_train_fold = y_oof[train_idx]

    # --------------------------------------------------------
    # Word TF-IDF
    # --------------------------------------------------------

    word_vectorizer = TfidfVectorizer(
        max_features=20000,
        ngram_range=(1, 2),
        min_df=2,
        max_df=0.95,
        sublinear_tf=True
    )

    X_train_word = word_vectorizer.fit_transform(
        train_text
    )

    X_val_word = word_vectorizer.transform(
        val_text
    )

    # --------------------------------------------------------
    # Character TF-IDF
    # --------------------------------------------------------

    char_vectorizer = TfidfVectorizer(
        analyzer="char",
        ngram_range=(3, 5),
        min_df=3,
        max_features=30000,
        sublinear_tf=True
    )

    X_train_char = char_vectorizer.fit_transform(
        train_text
    )

    X_val_char = char_vectorizer.transform(
        val_text
    )

    # --------------------------------------------------------
    # Combine word + character features
    # --------------------------------------------------------

    X_train_combined = hstack([
        X_train_word,
        X_train_char
    ])

    X_val_combined = hstack([
        X_val_word,
        X_val_char
    ])

    print("Word:", X_train_word.shape)
    print("Char:", X_train_char.shape)
    print("Combined:", X_train_combined.shape)

    # --------------------------------------------------------
    # Linear SVM
    # --------------------------------------------------------

    text_svm = LinearSVC(
        C=0.002,
        class_weight={0: 1, 1: 0.5},
        random_state=42
    )

    # --------------------------------------------------------
    # Probability calibration
    # --------------------------------------------------------

    calibrated_text = CalibratedClassifierCV(
        estimator=text_svm,
        method="sigmoid",
        cv=5
    )

    calibrated_text.fit(
        X_train_combined,
        y_train_fold
    )

    # --------------------------------------------------------
    # Generate OOF probabilities
    # --------------------------------------------------------

    fold_pred = calibrated_text.predict_proba(
        X_val_combined
    )[:, 1]

    oof_text_prob[val_idx] = fold_pred

    print(
        f"Fold {fold} prediction range: "
        f"{fold_pred.min():.6f} → "
        f"{fold_pred.max():.6f}"
    )

# ------------------------------------------------------------
# Final checks
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TEXT OOF COMPLETE")
print("=" * 70)

print("Predictions:", len(oof_text_prob))

print(
    "Missing predictions:",
    np.sum(oof_text_prob == 0)
)

print(
    "Range:",
    oof_text_prob.min(),
    "→",
    oof_text_prob.max()
)

======================================================================
TEXT OOF DATA ALIGNMENT
======================================================================
Rows: 6995
Missing text: 0
ID mismatches: 0
Label mismatches: 0
Account-type mismatches: 0

======================================================================
TEXT OOF FOLD 1/5
======================================================================
Word: (5596, 20000)
Char: (5596, 30000)
Combined: (5596, 50000)
Fold 1 prediction range: 0.000920 → 0.999969

======================================================================
TEXT OOF FOLD 2/5
======================================================================
Word: (5596, 20000)
Char: (5596, 30000)
Combined: (5596, 50000)
Fold 2 prediction range: 0.001784 → 0.999831

======================================================================
TEXT OOF FOLD 3/5
======================================================================
Word: (5596, 20000)
Char: (5596, 30000)
Combined: (5596, 50000)
Fold 3 prediction range: 0.001189 → 0.999836

======================================================================
TEXT OOF FOLD 4/5
======================================================================
Word: (5596, 20000)
Char: (5596, 30000)
Combined: (5596, 50000)
Fold 4 prediction range: 0.001184 → 0.999929

======================================================================
TEXT OOF FOLD 5/5
======================================================================
Word: (5596, 20000)
Char: (5596, 30000)
Combined: (5596, 50000)
Fold 5 prediction range: 0.000995 → 0.999921

======================================================================
TEXT OOF COMPLETE
======================================================================
Predictions: 6995
Missing predictions: 0
Range: 0.0009198045841941098 → 0.9999691098949505

In [ ]:
# ============================================================
# CLEAN OOF DRIFT SCORES
# ============================================================

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.covariance import LedoitWolf
import numpy as np

oof_drift_score = np.zeros(len(oof_data))

X_oof_drift = oof_data[behavior_features].copy()

for fold, (train_idx, val_idx) in enumerate(
    skf.split(X_oof_drift, y_oof),
    start=1
):

    print("\n" + "=" * 70)
    print(f"DRIFT OOF FOLD {fold}/5")
    print("=" * 70)

    X_train_fold = X_oof_drift.iloc[train_idx]
    X_val_fold = X_oof_drift.iloc[val_idx]

    # --------------------------------------------------------
    # Fit preprocessing ONLY on fold training data
    # --------------------------------------------------------

    drift_imputer = SimpleImputer(strategy="median")

    X_train_imp = drift_imputer.fit_transform(
        X_train_fold
    )

    X_val_imp = drift_imputer.transform(
        X_val_fold
    )

    drift_scaler = StandardScaler()

    X_train_scaled = drift_scaler.fit_transform(
        X_train_imp
    )

    X_val_scaled = drift_scaler.transform(
        X_val_imp
    )

    # --------------------------------------------------------
    # Fit covariance only on training portion
    # --------------------------------------------------------

    covariance_model = LedoitWolf()

    covariance_model.fit(
        X_train_scaled
    )

    # --------------------------------------------------------
    # Mahalanobis distance
    # --------------------------------------------------------

    train_distance = covariance_model.mahalanobis(
        X_train_scaled
    )

    val_distance = covariance_model.mahalanobis(
        X_val_scaled
    )

    # --------------------------------------------------------
    # Convert distance into empirical percentile
    # based ONLY on fold training distribution
    # --------------------------------------------------------

    train_sorted = np.sort(train_distance)

    percentile_scores = np.searchsorted(
        train_sorted,
        val_distance,
        side="right"
    ) / len(train_sorted)

    oof_drift_score[val_idx] = percentile_scores

    print(
        f"Train distance: "
        f"{train_distance.min():.4f} → "
        f"{train_distance.max():.4f}"
    )

    print(
        f"OOF drift score: "
        f"{percentile_scores.min():.4f} → "
        f"{percentile_scores.max():.4f}"
    )

print("\n" + "=" * 70)
print("OOF DRIFT COMPLETE")
print("=" * 70)

print("Predictions:", len(oof_drift_score))

print(
    "Missing:",
    np.sum(oof_drift_score == 0)
)

print(
    "Range:",
    oof_drift_score.min(),
    "→",
    oof_drift_score.max()
)

======================================================================
DRIFT OOF FOLD 1/5
======================================================================
Train distance: 0.6431 → 5486.8641
OOF drift score: 0.0030 → 1.0000

======================================================================
DRIFT OOF FOLD 2/5
======================================================================
Train distance: 0.6639 → 5513.2282
OOF drift score: 0.0000 → 1.0000

======================================================================
DRIFT OOF FOLD 3/5
======================================================================
Train distance: 0.6383 → 4783.2615
OOF drift score: 0.0007 → 0.9987

======================================================================
DRIFT OOF FOLD 4/5
======================================================================
Train distance: 0.6405 → 4978.0831
OOF drift score: 0.0016 → 0.9996

======================================================================
DRIFT OOF FOLD 5/5
======================================================================
Train distance: 0.6385 → 4737.0807
OOF drift score: 0.0002 → 0.9980

======================================================================
OOF DRIFT COMPLETE
======================================================================
Predictions: 6995
Missing: 1
Range: 0.0 → 1.0

In [ ]:
# ============================================================
# CHECK THE SINGLE ZERO OOF DRIFT SCORE
# ============================================================

zero_idx = np.where(oof_drift_score == 0)[0]

print("=" * 70)
print("OOF DRIFT ZERO CHECK")
print("=" * 70)

print("Number of zeros:", len(zero_idx))

if len(zero_idx) > 0:

    print("\nZero index:", zero_idx)

    print("\nCorresponding account:")
    print(
        oof_data.iloc[zero_idx][
            ["id", "account_type", "label"]
        ]
    )

    print("\nBehavior OOF probability:")
    print(oof_behavior_prob[zero_idx])

    print("\nText OOF probability:")
    print(oof_text_prob[zero_idx])

    print("\nDrift score:")
    print(oof_drift_score[zero_idx])

======================================================================
OOF DRIFT ZERO CHECK
======================================================================
Number of zeros: 1

Zero index: [5884]

Corresponding account:
              id       account_type  label
5884  2348186930  social_spambots_2      1

Behavior OOF probability:
[0.99754447]

Text OOF probability:
[0.99961109]

Drift score:
[0.]

In [ ]:
# ============================================================
# BUILD CLEAN ADAPTIVE FUSION OOF FEATURES
# ============================================================

fusion_oof = pd.DataFrame({
    "behavior_prob": oof_behavior_prob,
    "text_prob": oof_text_prob,

    "prob_difference":
        oof_behavior_prob - oof_text_prob,

    "absolute_difference":
        np.abs(
            oof_behavior_prob - oof_text_prob
        ),

    "behavior_confidence":
        np.abs(
            oof_behavior_prob - 0.5
        ) * 2,

    "text_confidence":
        np.abs(
            oof_text_prob - 0.5
        ) * 2,

    "drift_score":
        oof_drift_score,

    "agreement": (
        (oof_behavior_prob >= 0.5) ==
        (oof_text_prob >= 0.5)
    ).astype(int)
})

y_fusion_oof = oof_data["label"].to_numpy()

print("=" * 70)
print("ADAPTIVE FUSION OOF DATA")
print("=" * 70)

print("Shape:", fusion_oof.shape)

print("\nColumns:")
print(fusion_oof.columns.tolist())

print("\nLabel distribution:")
print(
    pd.Series(y_fusion_oof)
    .value_counts()
    .sort_index()
)

print("\nMissing values:")
print(fusion_oof.isna().sum())

print("\nFeature summary:")
print(fusion_oof.describe().T)

print("\nFirst 5 rows:")
print(fusion_oof.head())

======================================================================
ADAPTIVE FUSION OOF DATA
======================================================================
Shape: (6995, 8)

Columns:
['behavior_prob', 'text_prob', 'prob_difference', 'absolute_difference', 'behavior_confidence', 'text_confidence', 'drift_score', 'agreement']

Label distribution:
0    1083
1    5912
Name: count, dtype: int64

Missing values:
behavior_prob          0
text_prob              0
prob_difference        0
absolute_difference    0
behavior_confidence    0
text_confidence        0
drift_score            0
agreement              0
dtype: int64

Feature summary:
                      count      mean       std           min       25%  \
behavior_prob        6995.0  0.833263  0.361033  2.984049e-11  0.989528
text_prob            6995.0  0.851405  0.331181  9.198046e-04  0.988133
prob_difference      6995.0 -0.018142  0.115976 -9.969337e-01 -0.005782
absolute_difference  6995.0  0.032749  0.112726  4.072248e-08  0.000756
behavior_confidence  6995.0  0.980245  0.068438  1.705623e-02  0.986337
text_confidence      6995.0  0.956693  0.131692  6.395339e-03  0.984210
drift_score          6995.0  0.500058  0.288826  0.000000e+00  0.250179
agreement            6995.0  0.980558  0.138084  0.000000e+00  1.000000

                          50%       75%       max
behavior_prob        0.997597  0.998864  1.000000
text_prob            0.998837  0.999369  0.999969
prob_difference     -0.001104  0.000304  0.987421
absolute_difference  0.002067  0.009101  0.996934
behavior_confidence  0.995421  0.997788  1.000000
text_confidence      0.997677  0.998739  0.999938
drift_score          0.501251  0.749375  1.000000
agreement            1.000000  1.000000  1.000000

First 5 rows:
   behavior_prob  text_prob  prob_difference  absolute_difference  \
0       0.000011   0.003431        -0.003420             0.003420
1       0.027634   0.012333         0.015301             0.015301
2       0.007810   0.001614         0.006197             0.006197
3       0.009595   0.081907        -0.072312             0.072312
4       0.232592   0.029711         0.202881             0.202881

   behavior_confidence  text_confidence  drift_score  agreement
0             0.999979         0.993138     0.997320          1
1             0.944733         0.975334     0.863653          1
2             0.984379         0.996772     0.956040          1
3             0.980810         0.836187     0.831308          1
4             0.534816         0.940577     0.936383          1

In [ ]:
# ============================================================
# ADAPTIVE FUSION MODEL
# ============================================================

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# ------------------------------------------------------------
# Fusion model
# ------------------------------------------------------------

fusion_model = Pipeline([
    (
        "scaler",
        StandardScaler()
    ),
    (
        "classifier",
        LogisticRegression(
            C=1.0,
            class_weight="balanced",
            max_iter=2000,
            random_state=42
        )
    )
])

# ------------------------------------------------------------
# Train ONLY on OOF predictions
# ------------------------------------------------------------

fusion_model.fit(
    fusion_oof,
    y_fusion_oof
)

print("=" * 70)
print("ADAPTIVE FUSION MODEL TRAINED")
print("=" * 70)

# ------------------------------------------------------------
# OOF performance
# ------------------------------------------------------------

oof_fusion_prob = fusion_model.predict_proba(
    fusion_oof
)[:, 1]

oof_fusion_pred = (
    oof_fusion_prob >= 0.5
).astype(int)

print("\nOOF PERFORMANCE")
print("-" * 70)

print(
    "Accuracy:",
    accuracy_score(
        y_fusion_oof,
        oof_fusion_pred
    )
)

print(
    "Precision:",
    precision_score(
        y_fusion_oof,
        oof_fusion_pred
    )
)

print(
    "Recall:",
    recall_score(
        y_fusion_oof,
        oof_fusion_pred
    )
)

print(
    "F1:",
    f1_score(
        y_fusion_oof,
        oof_fusion_pred
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_fusion_oof,
        oof_fusion_pred
    )
)

print("\nClassification Report:")
print(
    classification_report(
        y_fusion_oof,
        oof_fusion_pred,
        target_names=["Genuine", "Bot"]
    )
)

# ------------------------------------------------------------
# Feature importance
# ------------------------------------------------------------

classifier = fusion_model.named_steps["classifier"]

feature_importance = pd.DataFrame({
    "feature": fusion_oof.columns,
    "coefficient": classifier.coef_[0]
})

feature_importance["abs_coefficient"] = (
    feature_importance["coefficient"].abs()
)

feature_importance = (
    feature_importance
    .sort_values(
        "abs_coefficient",
        ascending=False
    )
)

print("\n" + "=" * 70)
print("FUSION FEATURE IMPORTANCE")
print("=" * 70)

print(
    feature_importance[
        ["feature", "coefficient"]
    ].to_string(index=False)
)

======================================================================
ADAPTIVE FUSION MODEL TRAINED
======================================================================

OOF PERFORMANCE
----------------------------------------------------------------------
Accuracy: 0.9901358112937813
Precision: 0.9991457372287715
Recall: 0.9891745602165088
F1: 0.9941351466213345

Confusion Matrix:
[[1078    5]
 [  64 5848]]

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.94      1.00      0.97      1083
         Bot       1.00      0.99      0.99      5912

    accuracy                           0.99      6995
   macro avg       0.97      0.99      0.98      6995
weighted avg       0.99      0.99      0.99      6995


======================================================================
FUSION FEATURE IMPORTANCE
======================================================================
            feature  coefficient
          text_prob     2.037101
      behavior_prob     1.852524
        drift_score    -0.488306
    text_confidence     0.276386
behavior_confidence    -0.074228
    prob_difference    -0.050227
absolute_difference    -0.023645
          agreement    -0.007231

In [ ]:
# ============================================================
# ADAPTIVE FUSION — CLEAN VALIDATION EVALUATION
# ============================================================

fusion_val_prob = fusion_model.predict_proba(
    fusion_val
)[:, 1]

fusion_val_pred = (
    fusion_val_prob >= 0.5
).astype(int)

print("=" * 70)
print("ADAPTIVE FUSION — VALIDATION")
print("=" * 70)

print(
    "Accuracy:",
    accuracy_score(
        y_val,
        fusion_val_pred
    )
)

print(
    "Precision:",
    precision_score(
        y_val,
        fusion_val_pred
    )
)

print(
    "Recall:",
    recall_score(
        y_val,
        fusion_val_pred
    )
)

print(
    "F1:",
    f1_score(
        y_val,
        fusion_val_pred
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_val,
        fusion_val_pred
    )
)

print("\nClassification Report:")
print(
    classification_report(
        y_val,
        fusion_val_pred,
        target_names=["Genuine", "Bot"]
    )
)

print("\nPrediction probability range:")
print(
    fusion_val_prob.min(),
    "→",
    fusion_val_prob.max()
)

======================================================================
ADAPTIVE FUSION — VALIDATION
======================================================================
Accuracy: 0.9942816297355254
Precision: 1.0
Recall: 0.9932318104906938
F1: 0.9966044142614601

Confusion Matrix:
[[ 217    0]
 [   8 1174]]

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.96      1.00      0.98       217
         Bot       1.00      0.99      1.00      1182

    accuracy                           0.99      1399
   macro avg       0.98      1.00      0.99      1399
weighted avg       0.99      0.99      0.99      1399


Prediction probability range:
0.002096789607342352 → 0.9988469397604599

In [ ]:
# ============================================================
# FINAL ADAPTIVE FUSION — UNSEEN FAKE FOLLOWERS
# ============================================================

fusion_test_prob = fusion_model.predict_proba(
    fusion_test
)[:, 1]

fusion_test_pred = (
    fusion_test_prob >= 0.5
).astype(int)

print("=" * 70)
print("FINAL ADAPTIVE FUSION — UNSEEN FAKE FOLLOWERS")
print("=" * 70)

print(
    "Accuracy:",
    accuracy_score(
        y_test,
        fusion_test_pred
    )
)

print(
    "Precision:",
    precision_score(
        y_test,
        fusion_test_pred
    )
)

print(
    "Recall:",
    recall_score(
        y_test,
        fusion_test_pred
    )
)

print(
    "F1:",
    f1_score(
        y_test,
        fusion_test_pred
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test,
        fusion_test_pred
    )
)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        fusion_test_pred,
        target_names=["Genuine", "Bot"]
    )
)

print("\nProbability range:")
print(
    fusion_test_prob.min(),
    "→",
    fusion_test_prob.max()
)

print("\nPrediction distribution:")
print(
    pd.Series(
        fusion_test_pred
    ).value_counts().sort_index()
)

======================================================================
FINAL ADAPTIVE FUSION — UNSEEN FAKE FOLLOWERS
======================================================================
Accuracy: 0.7957992998833139
Precision: 0.9476721816083109
Recall: 0.769206745783885
F1: 0.8491639372521979

Confusion Matrix:
[[ 947  136]
 [ 739 2463]]

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.56      0.87      0.68      1083
         Bot       0.95      0.77      0.85      3202

    accuracy                           0.80      4285
   macro avg       0.75      0.82      0.77      4285
weighted avg       0.85      0.80      0.81      4285


Probability range:
0.0020701999333357095 → 0.9973317483022942

Prediction distribution:
0    1686
1    2599
Name: count, dtype: int64

In [ ]:
# ============================================================
# STEP 1 — RECOMPUTE FINAL TEST DRIFT
# ============================================================

# Use the SAME training-fitted drift objects
# created from the LOBO training data.

X_drift_test_raw = lobo_test[behavior_features].copy()

# Transform test data using TRAINING-fitted preprocessing
X_drift_test_imputed = drift_imputer_final.transform(
    X_drift_test_raw
)

X_drift_test_scaled = drift_scaler_final.transform(
    X_drift_test_imputed
)

# Mahalanobis distance using TRAINING-fitted covariance
test_mahal = drift_cov_model_final.mahalanobis(
    X_drift_test_scaled
)

# Convert to empirical percentile relative to training distribution
def empirical_percentile_score(value, reference_sorted):
    return np.searchsorted(
        reference_sorted,
        value,
        side="right"
    ) / len(reference_sorted)

drift_test_score = np.array([
    empirical_percentile_score(
        value,
        train_mahal_sorted
    )
    for value in test_mahal
])

print("=" * 70)
print("FINAL TEST DRIFT")
print("=" * 70)

print("Number of test accounts:", len(drift_test_score))
print("Drift range:",
      drift_test_score.min(),
      "→",
      drift_test_score.max())

print("Mean drift:", drift_test_score.mean())
print("Median drift:", np.median(drift_test_score))

print("95th percentile:",
      np.percentile(drift_test_score, 95))

print("99th percentile:",
      np.percentile(drift_test_score, 99))

======================================================================
FINAL TEST DRIFT
======================================================================
Number of test accounts: 4285
Drift range: 0.226590421729807 → 1.0
Mean drift: 0.7536355773377049
Median drift: 0.7875268048606148
95th percentile: 0.9966047176554682
99th percentile: 0.9992852037169406

In [ ]:
# ============================================================
# STEP 2 — BUILD FINAL RELIABILITY DATASET
# ============================================================

final_prob = fusion_test_prob
final_pred = fusion_test_pred

final_confidence = np.abs(final_prob - 0.5) * 2

final_correct = (
    final_pred == y_test
).astype(int)

reliability_test = pd.DataFrame({
    "id": lobo_test["id"].values,
    "account_type": lobo_test["account_type"].values,
    "true_label": y_test,
    "prediction": final_pred,
    "fusion_probability": final_prob,
    "confidence": final_confidence,
    "drift_score": drift_test_score,
    "correct": final_correct
})

print("=" * 70)
print("FINAL RELIABILITY DATASET")
print("=" * 70)

print("Shape:", reliability_test.shape)

print("\nMissing values:")
print(reliability_test.isna().sum())

print("\nOverall accuracy:",
      reliability_test["correct"].mean())

print("\nConfidence:")
print(
    reliability_test["confidence"].min(),
    "→",
    reliability_test["confidence"].max()
)

print("\nDrift:")
print(
    reliability_test["drift_score"].min(),
    "→",
    reliability_test["drift_score"].max()
)

======================================================================
FINAL RELIABILITY DATASET
======================================================================
Shape: (4285, 8)

Missing values:
id                    0
account_type          0
true_label            0
prediction            0
fusion_probability    0
confidence            0
drift_score           0
correct               0
dtype: int64

Overall accuracy: 0.7957992998833139

Confidence:
0.0002368050515515474 → 0.9958596001333285

Drift:
0.226590421729807 → 1.0

In [ ]:
# ============================================================
# STEP 3 — DRIFT-BASED RELIABILITY ANALYSIS
# ============================================================

reliability_test["reliability_group"] = pd.cut(
    reliability_test["drift_score"],
    bins=[-np.inf, 0.80, 0.95, np.inf],
    labels=[
        "Reliable",
        "Review",
        "High Drift / Low Reliability"
    ],
    right=False
)

reliability_summary = (
    reliability_test
    .groupby("reliability_group", observed=True)
    .agg(
        accounts=("correct", "size"),
        correct=("correct", "sum"),
        accuracy=("correct", "mean"),
        mean_confidence=("confidence", "mean"),
        mean_drift=("drift_score", "mean")
    )
    .reset_index()
)

print("=" * 70)
print("DRIFT-BASED RELIABILITY — UNSEEN FAKE FOLLOWERS")
print("=" * 70)

print(reliability_summary.to_string(index=False))

print("\nCounts:")
print(
    reliability_test["reliability_group"]
    .value_counts()
    .sort_index()
)

======================================================================
DRIFT-BASED RELIABILITY — UNSEEN FAKE FOLLOWERS
======================================================================
           reliability_group  accounts  correct  accuracy  mean_confidence  mean_drift
                    Reliable      2185     1755  0.803204         0.818982    0.595047
                      Review      1257     1060  0.843278         0.833693    0.874880
High Drift / Low Reliability       843      595  0.705813         0.758101    0.983898

Counts:
reliability_group
Reliable                        2185
Review                          1257
High Drift / Low Reliability     843
Name: count, dtype: int64

In [ ]:
# ============================================================
# STEP 4 — CONFIDENCE VS CORRECTNESS
# ============================================================

confidence_bins = pd.cut(
    reliability_test["confidence"],
    bins=[0, 0.25, 0.50, 0.75, 0.90, 1.0],
    labels=[
        "Very Low",
        "Low",
        "Moderate",
        "High",
        "Very High"
    ],
    include_lowest=True
)

confidence_summary = (
    reliability_test
    .assign(confidence_group=confidence_bins)
    .groupby("confidence_group", observed=True)
    .agg(
        accounts=("correct", "size"),
        correct=("correct", "sum"),
        accuracy=("correct", "mean"),
        mean_drift=("drift_score", "mean")
    )
    .reset_index()
)

print("=" * 70)
print("CONFIDENCE-BASED RELIABILITY")
print("=" * 70)

print(confidence_summary.to_string(index=False))

======================================================================
CONFIDENCE-BASED RELIABILITY
======================================================================
confidence_group  accounts  correct  accuracy  mean_drift
        Very Low       327      125  0.382263    0.795268
             Low       419       82  0.195704    0.672929
        Moderate       466      169  0.362661    0.862496
            High       223      216  0.968610    0.781882
       Very High      2850     2818  0.988772    0.740714

In [ ]:
# ============================================================
# STEP 5 — FIND RELIABILITY THRESHOLD USING VALIDATION ONLY
# ============================================================

val_confidence = np.abs(
    fusion_val_prob - 0.5
) * 2

val_correct = (
    fusion_val_pred == y_val
).astype(int)

thresholds = [
    0.50,
    0.60,
    0.70,
    0.75,
    0.80,
    0.85,
    0.90,
    0.95,
    0.98,
    0.99
]

threshold_results = []

for threshold in thresholds:

    reliable_mask = val_confidence >= threshold

    coverage = reliable_mask.mean()

    if reliable_mask.sum() > 0:
        accuracy = val_correct[reliable_mask].mean()
    else:
        accuracy = np.nan

    threshold_results.append({
        "confidence_threshold": threshold,
        "reliable_accounts": reliable_mask.sum(),
        "coverage": coverage,
        "accuracy_when_reliable": accuracy
    })

threshold_df = pd.DataFrame(threshold_results)

print("=" * 70)
print("VALIDATION-BASED CONFIDENCE RELIABILITY")
print("=" * 70)

print(
    threshold_df.to_string(index=False)
)

======================================================================
VALIDATION-BASED CONFIDENCE RELIABILITY
======================================================================
 confidence_threshold  reliable_accounts  coverage  accuracy_when_reliable
                 0.50               1383  0.988563                0.998554
                 0.60               1381  0.987134                0.999276
                 0.70               1377  0.984274                1.000000
                 0.75               1376  0.983560                1.000000
                 0.80               1375  0.982845                1.000000
                 0.85               1373  0.981415                1.000000
                 0.90               1370  0.979271                1.000000
                 0.95               1366  0.976412                1.000000
                 0.98               1353  0.967119                1.000000
                 0.99               1257  0.898499                1.000000

In [ ]:
# ============================================================
# STEP 6 — FROZEN CONFIDENCE-BASED RELIABILITY
#            ON UNSEEN FAKE FOLLOWERS
# ============================================================

CONFIDENCE_THRESHOLD = 0.70

reliability_test["decision"] = np.where(
    reliability_test["confidence"] >= CONFIDENCE_THRESHOLD,
    "Automatic",
    "Review"
)

automatic_mask = (
    reliability_test["confidence"] >= CONFIDENCE_THRESHOLD
)

review_mask = ~automatic_mask

# Accuracy among automatic decisions
automatic_accuracy = (
    reliability_test.loc[
        automatic_mask,
        "correct"
    ].mean()
)

# Accuracy among review cases
review_accuracy = (
    reliability_test.loc[
        review_mask,
        "correct"
    ].mean()
)

automatic_count = automatic_mask.sum()
review_count = review_mask.sum()

automatic_coverage = (
    automatic_count /
    len(reliability_test)
)

review_coverage = (
    review_count /
    len(reliability_test)
)

print("=" * 70)
print("FROZEN CONFIDENCE RELIABILITY — UNSEEN FAKE FOLLOWERS")
print("=" * 70)

print(f"\nConfidence threshold: {CONFIDENCE_THRESHOLD}")

print("\nAUTOMATIC DECISIONS")
print("-------------------")
print("Accounts:", automatic_count)
print("Coverage:", automatic_coverage)
print("Accuracy:", automatic_accuracy)

print("\nREVIEW CASES")
print("------------")
print("Accounts:", review_count)
print("Coverage:", review_coverage)
print("Accuracy:", review_accuracy)

print("\nOverall:")
print("Total accounts:", len(reliability_test))

======================================================================
FROZEN CONFIDENCE RELIABILITY — UNSEEN FAKE FOLLOWERS
======================================================================

Confidence threshold: 0.7

AUTOMATIC DECISIONS
-------------------
Accounts: 3113
Coverage: 0.726487747957993
Accuracy: 0.9858657243816255

REVIEW CASES
------------
Accounts: 1172
Coverage: 0.273512252042007
Accuracy: 0.2909556313993174

Overall:
Total accounts: 4285

In [ ]:
# ============================================================
# STEP 7 — CONFIDENCE + DRIFT CROSS ANALYSIS
# ============================================================

reliability_test["drift_group"] = np.where(
    reliability_test["drift_score"] < 0.95,
    "Lower Drift",
    "High Drift"
)

cross_reliability = (
    reliability_test
    .groupby(
        ["decision", "drift_group"],
        observed=True
    )
    .agg(
        accounts=("correct", "size"),
        correct=("correct", "sum"),
        accuracy=("correct", "mean"),
        mean_confidence=("confidence", "mean"),
        mean_drift=("drift_score", "mean")
    )
    .reset_index()
)

print("=" * 70)
print("CONFIDENCE + DRIFT CROSS ANALYSIS")
print("=" * 70)

print(
    cross_reliability.to_string(index=False)
)

======================================================================
CONFIDENCE + DRIFT CROSS ANALYSIS
======================================================================
 decision drift_group  accounts  correct  accuracy  mean_confidence  mean_drift
Automatic  High Drift       503      499  0.992048         0.951756    0.982275
Automatic Lower Drift      2610     2570  0.984674         0.971245    0.698528
   Review  High Drift       340       96  0.282353         0.471606    0.986299
   Review Lower Drift       832      245  0.294471         0.363557    0.693201

In [ ]:
# ============================================================
# STEP 8 — FINAL MODEL COMPARISON TABLE
# ============================================================

final_results = pd.DataFrame([
    {
        "Model": "Behavior-only",
        "Accuracy": 0.7384,
        "Precision": 0.8235,   # approximate from current clean result
        "Recall": np.nan,
        "F1": 0.8235
    },
    {
        "Model": "Text-only",
        "Accuracy": 0.750058,
        "Precision": 0.884796,
        "Recall": 0.765147,
        "F1": 0.820633
    },
    {
        "Model": "50:50 Fusion",
        "Accuracy": 0.7522,
        "Precision": 0.8419,
        "Recall": 0.8229,
        "F1": 0.8323
    },
    {
        "Model": "Adaptive Fusion",
        "Accuracy": 0.795799,
        "Precision": 0.947672,
        "Recall": 0.769207,
        "F1": 0.849164
    }
])

print("=" * 90)
print("FINAL UNSEEN-CATEGORY MODEL COMPARISON")
print("=" * 90)

print(
    final_results.to_string(
        index=False,
        formatters={
            "Accuracy": "{:.2%}".format,
            "Precision": lambda x: "N/A" if pd.isna(x) else f"{x:.2%}",
            "Recall": lambda x: "N/A" if pd.isna(x) else f"{x:.2%}",
            "F1": "{:.2%}".format
        }
    )
)

==========================================================================================
FINAL UNSEEN-CATEGORY MODEL COMPARISON
==========================================================================================
          Model Accuracy Precision Recall     F1
  Behavior-only   73.84%    82.35%    NaN 82.35%
      Text-only   75.01%    88.48% 76.51% 82.06%
   50:50 Fusion   75.22%    84.19% 82.29% 83.23%
Adaptive Fusion   79.58%    94.77% 76.92% 84.92%

In [ ]:
# ============================================================
# STEP 8A — EXACT CLEAN BEHAVIOR BASELINE
# ============================================================

behavior_test_pred = (
    lobo_behavior_nn_v2
    .predict(X_lobo_test_scaled, verbose=0)
    .ravel() >= 0.5
).astype(int)

print("=" * 70)
print("EXACT CLEAN BEHAVIOR-ONLY — UNSEEN FAKE FOLLOWERS")
print("=" * 70)

print(
    "Accuracy:",
    accuracy_score(y_test, behavior_test_pred)
)

print(
    "Precision:",
    precision_score(y_test, behavior_test_pred)
)

print(
    "Recall:",
    recall_score(y_test, behavior_test_pred)
)

print(
    "F1:",
    f1_score(y_test, behavior_test_pred)
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(y_test, behavior_test_pred)
)

======================================================================
EXACT CLEAN BEHAVIOR-ONLY — UNSEEN FAKE FOLLOWERS
======================================================================
Accuracy: 0.9843640606767795
Precision: 0.9974611234528721
Recall: 0.9815740162398501
F1: 0.9894538013536912

Confusion Matrix:
[[1075    8]
 [  59 3143]]

In [ ]:
# ============================================================
# BEHAVIOR MODEL CONSISTENCY CHECK
# ============================================================

print("=" * 70)
print("BEHAVIOR MODEL CONSISTENCY CHECK")
print("=" * 70)

print("\nModel:")
print(lobo_behavior_nn_v2)

print("\nTest data:")
print("X_lobo_test_scaled:", X_lobo_test_scaled.shape)
print("y_test:", y_test.shape)

# Current predictions
behavior_prob_check = (
    lobo_behavior_nn_v2
    .predict(X_lobo_test_scaled, verbose=0)
    .ravel()
)

behavior_pred_check = (
    behavior_prob_check >= 0.5
).astype(int)

print("\nProbability range:")
print(
    behavior_prob_check.min(),
    "→",
    behavior_prob_check.max()
)

print("\nMetrics:")
print("Accuracy :", accuracy_score(y_test, behavior_pred_check))
print("Precision:", precision_score(y_test, behavior_pred_check))
print("Recall   :", recall_score(y_test, behavior_pred_check))
print("F1       :", f1_score(y_test, behavior_pred_check))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, behavior_pred_check))

======================================================================
BEHAVIOR MODEL CONSISTENCY CHECK
======================================================================

Model:
<Sequential name=sequential_9, built=True>

Test data:
X_lobo_test_scaled: (4285, 15)
y_test: (4285,)

Probability range:
1.1475534e-08 → 1.0

Metrics:
Accuracy : 0.9843640606767795
Precision: 0.9974611234528721
Recall   : 0.9815740162398501
F1       : 0.9894538013536912

Confusion Matrix:
[[1075    8]
 [  59 3143]]

In [ ]:
# ============================================================
# STEP 9 — BEHAVIOR-ONLY RELIABILITY DATASET
# ============================================================

behavior_final_prob = behavior_prob_check
behavior_final_pred = behavior_pred_check

behavior_final_confidence = (
    np.abs(behavior_final_prob - 0.5) * 2
)

behavior_final_correct = (
    behavior_final_pred == y_test
).astype(int)

behavior_reliability_test = pd.DataFrame({
    "id": lobo_test["id"].values,
    "account_type": lobo_test["account_type"].values,
    "true_label": y_test,
    "prediction": behavior_final_pred,
    "behavior_probability": behavior_final_prob,
    "confidence": behavior_final_confidence,
    "drift_score": drift_test_score,
    "correct": behavior_final_correct
})

print("=" * 70)
print("BEHAVIOR-ONLY RELIABILITY — UNSEEN FAKE FOLLOWERS")
print("=" * 70)

print("Shape:", behavior_reliability_test.shape)

print("\nMissing values:")
print(behavior_reliability_test.isna().sum())

print("\nOverall accuracy:")
print(
    behavior_reliability_test["correct"].mean()
)

print("\nConfidence range:")
print(
    behavior_reliability_test["confidence"].min(),
    "→",
    behavior_reliability_test["confidence"].max()
)

print("\nDrift range:")
print(
    behavior_reliability_test["drift_score"].min(),
    "→",
    behavior_reliability_test["drift_score"].max()
)

======================================================================
BEHAVIOR-ONLY RELIABILITY — UNSEEN FAKE FOLLOWERS
======================================================================
Shape: (4285, 8)

Missing values:
id                      0
account_type            0
true_label              0
prediction              0
behavior_probability    0
confidence              0
drift_score             0
correct                 0
dtype: int64

Overall accuracy:
0.9843640606767795

Confidence range:
0.0054336786 → 1.0

Drift range:
0.226590421729807 → 1.0

In [ ]:
# ============================================================
# STEP 10 — BEHAVIOR MODEL CONFIDENCE RELIABILITY
#             VALIDATION ONLY
# ============================================================

behavior_val_confidence = (
    np.abs(behavior_val_prob - 0.5) * 2
)

behavior_val_correct = (
    behavior_val_pred == y_val
).astype(int)

thresholds = [
    0.50,
    0.60,
    0.70,
    0.75,
    0.80,
    0.85,
    0.90,
    0.95,
    0.98,
    0.99
]

behavior_threshold_results = []

for threshold in thresholds:

    reliable_mask = (
        behavior_val_confidence >= threshold
    )

    coverage = reliable_mask.mean()

    if reliable_mask.sum() > 0:
        accuracy = behavior_val_correct[
            reliable_mask
        ].mean()
    else:
        accuracy = np.nan

    behavior_threshold_results.append({
        "confidence_threshold": threshold,
        "reliable_accounts": reliable_mask.sum(),
        "coverage": coverage,
        "accuracy_when_reliable": accuracy
    })

behavior_threshold_df = pd.DataFrame(
    behavior_threshold_results
)

print("=" * 70)
print("BEHAVIOR MODEL — VALIDATION CONFIDENCE RELIABILITY")
print("=" * 70)

print(
    behavior_threshold_df.to_string(index=False)
)

======================================================================
BEHAVIOR MODEL — VALIDATION CONFIDENCE RELIABILITY
======================================================================
 confidence_threshold  reliable_accounts  coverage  accuracy_when_reliable
                 0.50               1390  0.993567                0.992806
                 0.60               1381  0.987134                0.992759
                 0.70               1376  0.983560                0.992733
                 0.75               1371  0.979986                0.992706
                 0.80               1368  0.977841                0.994152
                 0.85               1363  0.974267                0.994131
                 0.90               1356  0.969264                0.994838
                 0.95               1335  0.954253                0.997004
                 0.98               1256  0.897784                0.997611
                 0.99               1105  0.789850                0.999095

In [ ]:
# ============================================================
# STEP 11 — FROZEN BEHAVIOR CONFIDENCE RELIABILITY
#            UNSEEN FAKE FOLLOWERS
# ============================================================

BEHAVIOR_CONFIDENCE_THRESHOLD = 0.95

behavior_reliability_test["decision"] = np.where(
    behavior_reliability_test["confidence"]
    >= BEHAVIOR_CONFIDENCE_THRESHOLD,
    "Automatic",
    "Review"
)

automatic_mask = (
    behavior_reliability_test["confidence"]
    >= BEHAVIOR_CONFIDENCE_THRESHOLD
)

review_mask = ~automatic_mask

automatic_count = automatic_mask.sum()
review_count = review_mask.sum()

automatic_coverage = (
    automatic_count /
    len(behavior_reliability_test)
)

review_coverage = (
    review_count /
    len(behavior_reliability_test)
)

automatic_accuracy = (
    behavior_reliability_test.loc[
        automatic_mask,
        "correct"
    ].mean()
)

review_accuracy = (
    behavior_reliability_test.loc[
        review_mask,
        "correct"
    ].mean()
)

print("=" * 70)
print("FINAL BEHAVIOR-ONLY RELIABILITY")
print("UNSEEN FAKE FOLLOWERS")
print("=" * 70)

print(
    f"\nConfidence threshold: "
    f"{BEHAVIOR_CONFIDENCE_THRESHOLD}"
)

print("\nAUTOMATIC DECISIONS")
print("-------------------")
print("Accounts:", automatic_count)
print("Coverage:", automatic_coverage)
print("Accuracy:", automatic_accuracy)

print("\nREVIEW CASES")
print("------------")
print("Accounts:", review_count)
print("Coverage:", review_coverage)
print("Accuracy:", review_accuracy)

print("\nOverall:")
print("Total accounts:",
      len(behavior_reliability_test))

======================================================================
FINAL BEHAVIOR-ONLY RELIABILITY
UNSEEN FAKE FOLLOWERS
======================================================================

Confidence threshold: 0.95

AUTOMATIC DECISIONS
-------------------
Accounts: 4088
Coverage: 0.9540256709451576
Accuracy: 0.9963307240704501

REVIEW CASES
------------
Accounts: 197
Coverage: 0.04597432905484247
Accuracy: 0.7360406091370558

Overall:
Total accounts: 4285

In [ ]:
# ============================================================
# STEP 12 — ERROR CONCENTRATION IN REVIEW CASES
# ============================================================

automatic_errors = (
    (~behavior_reliability_test.loc[
        automatic_mask, "correct"
    ].astype(bool))
    .sum()
)

review_errors = (
    (~behavior_reliability_test.loc[
        review_mask, "correct"
    ].astype(bool))
    .sum()
)

automatic_error_rate = (
    1 - automatic_accuracy
)

review_error_rate = (
    1 - review_accuracy
)

print("=" * 70)
print("ERROR CONCENTRATION ANALYSIS")
print("=" * 70)

print("\nAUTOMATIC")
print("---------")
print("Accounts:", automatic_count)
print("Errors:", automatic_errors)
print("Error rate:", automatic_error_rate)

print("\nREVIEW")
print("------")
print("Accounts:", review_count)
print("Errors:", review_errors)
print("Error rate:", review_error_rate)

print("\nError concentration:")
print(
    "Review cases contain",
    review_errors,
    "of",
    automatic_errors + review_errors,
    "total errors."
)

print(
    "Percentage of all errors in review:",
    review_errors /
    (automatic_errors + review_errors)
)

======================================================================
ERROR CONCENTRATION ANALYSIS
======================================================================

AUTOMATIC
---------
Accounts: 4088
Errors: 15
Error rate: 0.003669275929549909

REVIEW
------
Accounts: 197
Errors: 52
Error rate: 0.2639593908629442

Error concentration:
Review cases contain 52 of 67 total errors.
Percentage of all errors in review: 0.7761194029850746

In [ ]:
# ============================================================
# STEP 13 — DRIFT DISTRIBUTION IN AUTOMATIC vs REVIEW
# ============================================================

drift_reliability_summary = (
    behavior_reliability_test
    .groupby("decision", observed=True)
    .agg(
        accounts=("correct", "size"),
        mean_drift=("drift_score", "mean"),
        median_drift=("drift_score", "median"),
        high_drift_accounts=(
            "drift_score",
            lambda x: (x >= 0.95).sum()
        ),
        high_drift_rate=(
            "drift_score",
            lambda x: (x >= 0.95).mean()
        ),
        mean_confidence=("confidence", "mean"),
        accuracy=("correct", "mean")
    )
    .reset_index()
)

print("=" * 70)
print("DRIFT DISTRIBUTION — AUTOMATIC vs REVIEW")
print("=" * 70)

print(
    drift_reliability_summary.to_string(index=False)
)

======================================================================
DRIFT DISTRIBUTION — AUTOMATIC vs REVIEW
======================================================================
 decision  accounts  mean_drift  median_drift  high_drift_accounts  high_drift_rate  mean_confidence  accuracy
Automatic      4088    0.756458      0.795747                  819         0.200342         0.996359  0.996331
   Review       197    0.695061      0.676197                   24         0.121827         0.752213  0.736041

In [ ]:
# ============================================================
# STEP 14 — FINE-GRAINED FUSION WEIGHT OPTIMIZATION
# VALIDATION ONLY
# ============================================================

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

behavior_val_prob = behavior_prob_val
text_val_prob = text_prob_val

results = []

# Behavior weight from 0% to 100%
for alpha in np.arange(0.00, 1.01, 0.01):

    # alpha = behavior weight
    # (1-alpha) = text weight
    fusion_prob = (
        alpha * behavior_val_prob
        + (1 - alpha) * text_val_prob
    )

    fusion_pred = (fusion_prob >= 0.5).astype(int)

    results.append({
        "behavior_weight": round(alpha, 2),
        "text_weight": round(1 - alpha, 2),
        "accuracy": accuracy_score(y_val, fusion_pred),
        "precision": precision_score(y_val, fusion_pred),
        "recall": recall_score(y_val, fusion_pred),
        "f1": f1_score(y_val, fusion_pred)
    })

fusion_weight_results = pd.DataFrame(results)

# Sort by validation F1
best_f1 = fusion_weight_results.sort_values(
    "f1", ascending=False
).iloc[0]

# Sort by validation accuracy
best_accuracy = fusion_weight_results.sort_values(
    "accuracy", ascending=False
).iloc[0]

print("=" * 70)
print("FINE-GRAINED FUSION WEIGHT OPTIMIZATION")
print("=" * 70)

print("\nBEST BY VALIDATION F1")
print(best_f1)

print("\nBEST BY VALIDATION ACCURACY")
print(best_accuracy)

print("\nTOP 10 WEIGHTS BY F1")
print(
    fusion_weight_results
    .sort_values("f1", ascending=False)
    .head(10)
    .to_string(index=False)
)

NameError: name 'behavior_prob_val' is not defined

In [ ]:
print(fusion_val.columns.tolist())
print(fusion_val.shape)

['behavior_prob', 'text_prob', 'prob_difference', 'absolute_difference', 'behavior_confidence', 'text_confidence', 'drift_score', 'agreement']
(1399, 8)

In [ ]:
# ============================================================
# STEP 14 — FINE-GRAINED FUSION WEIGHT OPTIMIZATION
# VALIDATION ONLY
# ============================================================

import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# Get aligned validation probabilities
behavior_val_prob = fusion_val["behavior_prob"].values
text_val_prob = fusion_val["text_prob"].values

results = []

# Test behavior weights from 0% to 100%
for alpha in np.arange(0.00, 1.01, 0.01):

    fusion_prob = (
        alpha * behavior_val_prob
        + (1 - alpha) * text_val_prob
    )

    fusion_pred = (fusion_prob >= 0.5).astype(int)

    results.append({
        "behavior_weight": round(alpha, 2),
        "text_weight": round(1 - alpha, 2),
        "accuracy": accuracy_score(y_val, fusion_pred),
        "precision": precision_score(y_val, fusion_pred, zero_division=0),
        "recall": recall_score(y_val, fusion_pred, zero_division=0),
        "f1": f1_score(y_val, fusion_pred, zero_division=0)
    })

fusion_weight_results = pd.DataFrame(results)

best_f1 = fusion_weight_results.loc[
    fusion_weight_results["f1"].idxmax()
]

best_accuracy = fusion_weight_results.loc[
    fusion_weight_results["accuracy"].idxmax()
]

print("=" * 70)
print("FINE-GRAINED FUSION WEIGHT OPTIMIZATION")
print("=" * 70)

print("\nBEST BY VALIDATION F1")
print(best_f1.to_string())

print("\nBEST BY VALIDATION ACCURACY")
print(best_accuracy.to_string())

print("\nTOP 10 WEIGHTS BY VALIDATION F1")
print(
    fusion_weight_results
    .sort_values("f1", ascending=False)
    .head(10)
    .to_string(index=False)
)

======================================================================
FINE-GRAINED FUSION WEIGHT OPTIMIZATION
======================================================================

BEST BY VALIDATION F1
behavior_weight    0.48
text_weight        0.52
accuracy           1.00
precision          1.00
recall             1.00
f1                 1.00

BEST BY VALIDATION ACCURACY
behavior_weight    0.48
text_weight        0.52
accuracy           1.00
precision          1.00
recall             1.00
f1                 1.00

TOP 10 WEIGHTS BY VALIDATION F1
 behavior_weight  text_weight  accuracy  precision   recall       f1
            0.49         0.51  1.000000   1.000000 1.000000 1.000000
            0.48         0.52  1.000000   1.000000 1.000000 1.000000
            0.50         0.50  0.999285   1.000000 0.999154 0.999577
            0.44         0.56  0.997856   1.000000 0.997462 0.998729
            0.45         0.55  0.997856   1.000000 0.997462 0.998729
            0.47         0.53  0.997856   1.000000 0.997462 0.998729
            0.46         0.54  0.997856   1.000000 0.997462 0.998729
            0.51         0.49  0.996426   0.999152 0.996616 0.997882
            0.40         0.60  0.995711   0.998305 0.996616 0.997460
            0.42         0.58  0.995711   0.998305 0.996616 0.997460

In [ ]:
# ============================================================
# STEP 15 — FROZEN WEIGHTED FUSION
# UNSEEN FAKE FOLLOWERS TEST
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# Freeze weights selected ONLY from validation
behavior_weight = 0.48
text_weight = 0.52

# Aligned unseen-test probabilities
behavior_test_prob = behavior_prob_check
text_test_prob = text_test_prob

# Weighted fusion
frozen_fusion_prob = (
    behavior_weight * behavior_test_prob
    + text_weight * text_test_prob
)

# Classification threshold remains 0.5
frozen_fusion_pred = (
    frozen_fusion_prob >= 0.5
).astype(int)

# Metrics
frozen_accuracy = accuracy_score(
    y_test,
    frozen_fusion_pred
)

frozen_precision = precision_score(
    y_test,
    frozen_fusion_pred,
    zero_division=0
)

frozen_recall = recall_score(
    y_test,
    frozen_fusion_pred,
    zero_division=0
)

frozen_f1 = f1_score(
    y_test,
    frozen_fusion_pred,
    zero_division=0
)

frozen_cm = confusion_matrix(
    y_test,
    frozen_fusion_pred
)

print("=" * 70)
print("FROZEN WEIGHTED FUSION — UNSEEN FAKE FOLLOWERS")
print("=" * 70)

print(f"\nBehavior weight : {behavior_weight:.2f}")
print(f"Text weight     : {text_weight:.2f}")

print(f"\nAccuracy  : {frozen_accuracy:.4f} ({frozen_accuracy*100:.2f}%)")
print(f"Precision : {frozen_precision:.4f} ({frozen_precision*100:.2f}%)")
print(f"Recall    : {frozen_recall:.4f} ({frozen_recall*100:.2f}%)")
print(f"F1-score  : {frozen_f1:.4f} ({frozen_f1*100:.2f}%)")

print("\nConfusion Matrix:")
print(frozen_cm)

print("\nProbability range:")
print(
    f"{frozen_fusion_prob.min():.6f}"
    f" → "
    f"{frozen_fusion_prob.max():.6f}"
)

======================================================================
FROZEN WEIGHTED FUSION — UNSEEN FAKE FOLLOWERS
======================================================================

Behavior weight : 0.48
Text weight     : 0.52

Accuracy  : 0.8653 (86.53%)
Precision : 0.9521 (95.21%)
Recall    : 0.8632 (86.32%)
F1-score  : 0.9055 (90.55%)

Confusion Matrix:
[[ 944  139]
 [ 438 2764]]

Probability range:
0.002083 → 0.998902

In [ ]:
# ============================================================
# STEP 16 — ERROR ANALYSIS: BEHAVIOR vs TEXT vs FUSION
# ============================================================

behavior_pred = (behavior_test_prob >= 0.5).astype(int)
text_pred = (text_test_prob >= 0.5).astype(int)
fusion_pred = frozen_fusion_pred

comparison = pd.DataFrame({
    "true": y_test,
    "behavior_pred": behavior_pred,
    "text_pred": text_pred,
    "fusion_pred": fusion_pred
})

comparison["behavior_correct"] = (
    comparison["behavior_pred"] == comparison["true"]
)

comparison["text_correct"] = (
    comparison["text_pred"] == comparison["true"]
)

comparison["fusion_correct"] = (
    comparison["fusion_pred"] == comparison["true"]
)

print("=" * 70)
print("ERROR ANALYSIS")
print("=" * 70)

print("\nBEHAVIOR ONLY")
print(
    "Correct:",
    comparison["behavior_correct"].sum()
)
print(
    "Errors:",
    (~comparison["behavior_correct"]).sum()
)

print("\nTEXT ONLY")
print(
    "Correct:",
    comparison["text_correct"].sum()
)
print(
    "Errors:",
    (~comparison["text_correct"]).sum()
)

print("\nFUSION")
print(
    "Correct:",
    comparison["fusion_correct"].sum()
)
print(
    "Errors:",
    (~comparison["fusion_correct"]).sum()
)

# Important cases
behavior_wrong_text_right = (
    (~comparison["behavior_correct"]) &
    (comparison["text_correct"])
).sum()

behavior_right_text_wrong = (
    (comparison["behavior_correct"]) &
    (~comparison["text_correct"])
).sum()

both_wrong = (
    (~comparison["behavior_correct"]) &
    (~comparison["text_correct"])
).sum()

print("\n" + "-" * 70)
print("COMPLEMENTARITY")
print("-" * 70)

print(
    "Behavior wrong + Text correct:",
    behavior_wrong_text_right
)

print(
    "Behavior correct + Text wrong:",
    behavior_right_text_wrong
)

print(
    "Both wrong:",
    both_wrong
)

======================================================================
ERROR ANALYSIS
======================================================================

BEHAVIOR ONLY
Correct: 4218
Errors: 67

TEXT ONLY
Correct: 3214
Errors: 1071

FUSION
Correct: 3708
Errors: 577

----------------------------------------------------------------------
COMPLEMENTARITY
----------------------------------------------------------------------
Behavior wrong + Text correct: 33
Behavior correct + Text wrong: 1037
Both wrong: 34

In [ ]:
# ============================================================
# STEP 17 — BEHAVIOR CONFIDENCE ANALYSIS
# VALIDATION ONLY
# ============================================================

behavior_val_prob = fusion_val["behavior_prob"].values
text_val_prob = fusion_val["text_prob"].values

behavior_val_pred = (
    behavior_val_prob >= 0.5
).astype(int)

behavior_val_confidence = (
    np.abs(behavior_val_prob - 0.5) * 2
)

val_confidence_analysis = pd.DataFrame({
    "behavior_prob": behavior_val_prob,
    "text_prob": text_val_prob,
    "true": y_val,
    "behavior_pred": behavior_val_pred,
    "confidence": behavior_val_confidence
})

val_confidence_analysis["behavior_correct"] = (
    val_confidence_analysis["behavior_pred"]
    == val_confidence_analysis["true"]
)

# Confidence ranges
bins = [0, 0.50, 0.70, 0.80, 0.90, 0.95, 0.98, 1.01]
labels = [
    "<0.50",
    "0.50–0.70",
    "0.70–0.80",
    "0.80–0.90",
    "0.90–0.95",
    "0.95–0.98",
    "≥0.98"
]

val_confidence_analysis["confidence_group"] = pd.cut(
    val_confidence_analysis["confidence"],
    bins=bins,
    labels=labels,
    right=False
)

summary = (
    val_confidence_analysis
    .groupby("confidence_group", observed=False)
    .agg(
        accounts=("true", "size"),
        errors=("behavior_correct", lambda x: (~x).sum()),
        accuracy=("behavior_correct", "mean")
    )
    .reset_index()
)

print("=" * 70)
print("BEHAVIOR CONFIDENCE vs ERROR RATE")
print("=" * 70)

print(summary.to_string(index=False))

======================================================================
BEHAVIOR CONFIDENCE vs ERROR RATE
======================================================================
confidence_group  accounts  errors  accuracy
           <0.50         9       2  0.777778
       0.50–0.70        14       0  1.000000
       0.70–0.80         8       2  0.750000
       0.80–0.90        12       1  0.916667
       0.90–0.95        21       3  0.857143
       0.95–0.98        79       1  0.987342
           ≥0.98      1256       3  0.997611

In [ ]:
# ============================================================
# STEP 18 — GATED FUSION
# VALIDATION ONLY
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# Validation probabilities
behavior_val_prob = fusion_val["behavior_prob"].values
text_val_prob = fusion_val["text_prob"].values

behavior_val_pred = (
    behavior_val_prob >= 0.5
).astype(int)

behavior_val_confidence = (
    np.abs(behavior_val_prob - 0.5) * 2
)

results = []

# Candidate gate thresholds
gate_thresholds = [
    0.50, 0.60, 0.70, 0.75,
    0.80, 0.85, 0.90, 0.95,
    0.98, 0.99
]

for gate in gate_thresholds:

    # Weighted fusion used only for uncertain cases
    weighted_prob = (
        0.48 * behavior_val_prob
        + 0.52 * text_val_prob
    )

    # Start with behavioral prediction
    gated_pred = behavior_val_pred.copy()

    # Identify uncertain behavioral predictions
    uncertain_mask = (
        behavior_val_confidence < gate
    )

    # Let fusion handle uncertain cases
    gated_pred[uncertain_mask] = (
        weighted_prob[uncertain_mask] >= 0.5
    ).astype(int)

    results.append({
        "gate": gate,
        "fusion_cases": uncertain_mask.sum(),
        "fusion_percentage": uncertain_mask.mean() * 100,
        "accuracy": accuracy_score(y_val, gated_pred),
        "precision": precision_score(
            y_val, gated_pred, zero_division=0
        ),
        "recall": recall_score(
            y_val, gated_pred, zero_division=0
        ),
        "f1": f1_score(
            y_val, gated_pred, zero_division=0
        )
    })

gated_results = pd.DataFrame(results)

print("=" * 70)
print("GATED FUSION — VALIDATION ONLY")
print("=" * 70)

print(
    gated_results.to_string(index=False)
)

print("\n" + "=" * 70)
print("BEST BY VALIDATION F1")
print("=" * 70)

best_gate = gated_results.loc[
    gated_results["f1"].idxmax()
]

print(best_gate.to_string())

======================================================================
GATED FUSION — VALIDATION ONLY
======================================================================
 gate  fusion_cases  fusion_percentage  accuracy  precision   recall       f1
 0.50             9           0.643317  0.992852   0.997453 0.994078 0.995763
 0.60            18           1.286633  0.992852   0.997453 0.994078 0.995763
 0.70            23           1.644031  0.992852   0.997453 0.994078 0.995763
 0.75            28           2.001430  0.992852   0.997453 0.994078 0.995763
 0.80            31           2.215868  0.994282   0.999150 0.994078 0.996607
 0.85            36           2.573267  0.994282   0.999150 0.994078 0.996607
 0.90            43           3.073624  0.994996   0.999150 0.994924 0.997033
 0.95            64           4.574696  0.997141   1.000000 0.996616 0.998305
 0.98           143          10.221587  0.997856   1.000000 0.997462 0.998729
 0.99           294          21.015011  0.999285   1.000000 0.999154 0.999577

======================================================================
BEST BY VALIDATION F1
======================================================================
gate                   0.990000
fusion_cases         294.000000
fusion_percentage     21.015011
accuracy               0.999285
precision              1.000000
recall                 0.999154
f1                     0.999577

In [ ]:
# ============================================================
# STEP 19 — FROZEN GATED FUSION
# UNSEEN FAKE FOLLOWERS TEST
# ============================================================

# Frozen settings selected ONLY from validation
behavior_weight = 0.48
text_weight = 0.52
gate = 0.99

# Unseen-test probabilities
behavior_test_prob = behavior_prob_check
text_test_prob = text_test_prob

# Behavioral prediction
behavior_test_pred = (
    behavior_test_prob >= 0.5
).astype(int)

# Behavioral confidence
behavior_test_confidence = (
    np.abs(behavior_test_prob - 0.5) * 2
)

# Weighted fusion probability
weighted_fusion_test_prob = (
    behavior_weight * behavior_test_prob
    + text_weight * text_test_prob
)

weighted_fusion_test_pred = (
    weighted_fusion_test_prob >= 0.5
).astype(int)

# ------------------------------------------------------------
# GATED DECISION
# ------------------------------------------------------------

# Start with behavioral prediction
gated_test_pred = behavior_test_pred.copy()

# Cases where behavior is not sufficiently confident
uncertain_test_mask = (
    behavior_test_confidence < gate
)

# Use fusion only for uncertain cases
gated_test_pred[uncertain_test_mask] = (
    weighted_fusion_test_prob[uncertain_test_mask] >= 0.5
).astype(int)

# ------------------------------------------------------------
# METRICS
# ------------------------------------------------------------

gated_accuracy = accuracy_score(
    y_test,
    gated_test_pred
)

gated_precision = precision_score(
    y_test,
    gated_test_pred,
    zero_division=0
)

gated_recall = recall_score(
    y_test,
    gated_test_pred,
    zero_division=0
)

gated_f1 = f1_score(
    y_test,
    gated_test_pred,
    zero_division=0
)

gated_cm = confusion_matrix(
    y_test,
    gated_test_pred
)

# ------------------------------------------------------------
# OUTPUT
# ------------------------------------------------------------

print("=" * 70)
print("FROZEN GATED FUSION — UNSEEN FAKE FOLLOWERS")
print("=" * 70)

print(f"\nBehavior weight : {behavior_weight:.2f}")
print(f"Text weight     : {text_weight:.2f}")
print(f"Confidence gate : {gate:.2f}")

print("\nGated cases:")
print(
    f"{uncertain_test_mask.sum()} "
    f"/ {len(y_test)} "
    f"({uncertain_test_mask.mean()*100:.2f}%)"
)

print("\nPerformance:")
print(
    f"Accuracy  : {gated_accuracy:.4f} "
    f"({gated_accuracy*100:.2f}%)"
)

print(
    f"Precision : {gated_precision:.4f} "
    f"({gated_precision*100:.2f}%)"
)

print(
    f"Recall    : {gated_recall:.4f} "
    f"({gated_recall*100:.2f}%)"
)

print(
    f"F1-score  : {gated_f1:.4f} "
    f"({gated_f1*100:.2f}%)"
)

print("\nConfusion Matrix:")
print(gated_cm)

======================================================================
FROZEN GATED FUSION — UNSEEN FAKE FOLLOWERS
======================================================================

Behavior weight : 0.48
Text weight     : 0.52
Confidence gate : 0.99

Gated cases:
783 / 4285 (18.27%)

Performance:
Accuracy  : 0.9561 (95.61%)
Precision : 0.9760 (97.60%)
Recall    : 0.9650 (96.50%)
F1-score  : 0.9705 (97.05%)

Confusion Matrix:
[[1007   76]
 [ 112 3090]]

In [ ]:
# ============================================================
# STEP 20 — ANALYZE THE 783 GATED CASES
# ============================================================

gated_mask = uncertain_test_mask

gated_analysis = pd.DataFrame({
    "true": y_test[gated_mask],
    "behavior_prob": behavior_test_prob[gated_mask],
    "text_prob": text_test_prob[gated_mask],
    "behavior_pred": behavior_test_pred[gated_mask],
    "fusion_pred": weighted_fusion_test_pred[gated_mask]
})

gated_analysis["behavior_correct"] = (
    gated_analysis["behavior_pred"] == gated_analysis["true"]
)

gated_analysis["fusion_correct"] = (
    gated_analysis["fusion_pred"] == gated_analysis["true"]
)

print("=" * 70)
print("GATED CASE ANALYSIS")
print("=" * 70)

print(f"\nTotal gated cases: {len(gated_analysis)}")

print("\nBehavior:")
print(
    "Correct:",
    gated_analysis["behavior_correct"].sum()
)
print(
    "Errors:",
    (~gated_analysis["behavior_correct"]).sum()
)

print("\nFusion:")
print(
    "Correct:",
    gated_analysis["fusion_correct"].sum()
)
print(
    "Errors:",
    (~gated_analysis["fusion_correct"]).sum()
)

# ------------------------------------------------------------
# Cases where fusion helps
# ------------------------------------------------------------

behavior_wrong_fusion_right = (
    (~gated_analysis["behavior_correct"]) &
    (gated_analysis["fusion_correct"])
).sum()

# Cases where fusion hurts
behavior_right_fusion_wrong = (
    (gated_analysis["behavior_correct"]) &
    (~gated_analysis["fusion_correct"])
).sum()

# Both wrong
both_wrong = (
    (~gated_analysis["behavior_correct"]) &
    (~gated_analysis["fusion_correct"])
).sum()

# Both correct
both_correct = (
    (gated_analysis["behavior_correct"]) &
    (gated_analysis["fusion_correct"])
).sum()

print("\n" + "-" * 70)
print("WHAT DID FUSION DO?")
print("-" * 70)

print(
    "Behavior wrong → Fusion correct:",
    behavior_wrong_fusion_right
)

print(
    "Behavior correct → Fusion wrong:",
    behavior_right_fusion_wrong
)

print(
    "Both correct:",
    both_correct
)

print(
    "Both wrong:",
    both_wrong
)

======================================================================
GATED CASE ANALYSIS
======================================================================

Total gated cases: 783

Behavior:
Correct: 720
Errors: 63

Fusion:
Correct: 599
Errors: 184

----------------------------------------------------------------------
WHAT DID FUSION DO?
----------------------------------------------------------------------
Behavior wrong → Fusion correct: 16
Behavior correct → Fusion wrong: 137
Both correct: 583
Both wrong: 47

In [ ]:
# ============================================================
# STEP 21 — BEHAVIOR PRIMARY + TEXT SECONDARY
# THREE-WAY DECISION
# ============================================================

# Predictions
behavior_pred = (behavior_test_prob >= 0.5).astype(int)
text_pred = (text_test_prob >= 0.5).astype(int)

# Agreement
agreement_mask = behavior_pred == text_pred
disagreement_mask = ~agreement_mask

# ------------------------------------------------------------
# Automatic predictions:
# Only accept when both models agree.
# ------------------------------------------------------------

automatic_pred = behavior_pred[agreement_mask]
automatic_true = y_test[agreement_mask]

automatic_accuracy = accuracy_score(
    automatic_true,
    automatic_pred
)

automatic_coverage = agreement_mask.mean()

# ------------------------------------------------------------
# Review cases
# ------------------------------------------------------------

review_true = y_test[disagreement_mask]

# Errors among automatic cases
automatic_errors = (
    automatic_pred != automatic_true
).sum()

# Errors among review cases
# We don't automatically classify these.
# We calculate how many would have been errors
# if behavior had been forced to decide.
review_behavior_pred = behavior_pred[disagreement_mask]

review_errors = (
    review_behavior_pred != review_true
).sum()

total_errors = (
    behavior_pred != y_test
).sum()

print("=" * 70)
print("BEHAVIOR PRIMARY + TEXT SECONDARY")
print("=" * 70)

print("\nTOTAL")
print(f"Accounts: {len(y_test)}")
print(f"Behavior errors: {total_errors}")

print("\nAUTOMATIC")
print(f"Accounts: {agreement_mask.sum()}")
print(f"Coverage: {automatic_coverage*100:.2f}%")
print(f"Errors: {automatic_errors}")
print(f"Accuracy: {automatic_accuracy*100:.2f}%")

print("\nREVIEW")
print(f"Accounts: {disagreement_mask.sum()}")
print(f"Coverage: {disagreement_mask.mean()*100:.2f}%")
print(f"Behavior errors inside review: {review_errors}")

print("\nERROR CONCENTRATION")

if total_errors > 0:
    print(
        f"Behavior errors sent to review: "
        f"{review_errors}/{total_errors} "
        f"({review_errors/total_errors*100:.2f}%)"
    )

======================================================================
BEHAVIOR PRIMARY + TEXT SECONDARY
======================================================================

TOTAL
Accounts: 4285
Behavior errors: 67

AUTOMATIC
Accounts: 3215
Coverage: 75.03%
Errors: 34
Accuracy: 98.94%

REVIEW
Accounts: 1070
Coverage: 24.97%
Behavior errors inside review: 33

ERROR CONCENTRATION
Behavior errors sent to review: 33/67 (49.25%)

In [ ]:
# ============================================================
# STEP 22 — CONFIDENCE-AWARE FUSION
# VALIDATION ONLY
# ============================================================

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score

behavior_val_prob = fusion_val["behavior_prob"].values
text_val_prob = fusion_val["text_prob"].values

behavior_val_pred = (
    behavior_val_prob >= 0.5
).astype(int)

text_val_pred = (
    text_val_prob >= 0.5
).astype(int)

behavior_val_conf = (
    np.abs(behavior_val_prob - 0.5) * 2
)

text_val_conf = (
    np.abs(text_val_prob - 0.5) * 2
)

results = []

# Behavior confidence above this = trust behavior
behavior_gates = [
    0.90, 0.92, 0.94, 0.95,
    0.96, 0.97, 0.98, 0.99
]

# Text must be this much more confident
# before it is allowed to influence behavior
confidence_advantages = [
    0.00, 0.02, 0.05, 0.10,
    0.15, 0.20, 0.25, 0.30
]

for gate in behavior_gates:

    for advantage in confidence_advantages:

        final_pred = behavior_val_pred.copy()

        # Cases where behavior is below the confidence gate
        uncertain = behavior_val_conf < gate

        # Text must have a confidence advantage
        text_dominant = (
            text_val_conf >
            behavior_val_conf + advantage
        )

        # Only allow text to influence these cases
        use_text = uncertain & text_dominant

        final_pred[use_text] = text_val_pred[use_text]

        acc = accuracy_score(y_val, final_pred)
        f1 = f1_score(y_val, final_pred, zero_division=0)

        results.append({
            "behavior_gate": gate,
            "text_advantage": advantage,
            "text_used_cases": use_text.sum(),
            "text_used_percent": use_text.mean() * 100,
            "accuracy": acc,
            "f1": f1
        })

confidence_fusion_results = pd.DataFrame(results)

print("=" * 70)
print("CONFIDENCE-AWARE FUSION — VALIDATION ONLY")
print("=" * 70)

print("\nTOP 15 BY VALIDATION F1")

print(
    confidence_fusion_results
    .sort_values(
        ["f1", "accuracy"],
        ascending=False
    )
    .head(15)
    .to_string(index=False)
)

print("\nTOP 15 BY VALIDATION ACCURACY")

print(
    confidence_fusion_results
    .sort_values(
        ["accuracy", "f1"],
        ascending=False
    )
    .head(15)
    .to_string(index=False)
)

======================================================================
CONFIDENCE-AWARE FUSION — VALIDATION ONLY
======================================================================

TOP 15 BY VALIDATION F1
 behavior_gate  text_advantage  text_used_cases  text_used_percent  accuracy       f1
          0.99            0.00              176          12.580415  0.998570 0.999153
          0.95            0.00               58           4.145818  0.997141 0.998305
          0.96            0.00               66           4.717655  0.997141 0.998305
          0.97            0.00               74           5.289492  0.997141 0.998305
          0.98            0.00              102           7.290922  0.997141 0.998305
          0.95            0.02               55           3.931380  0.996426 0.997882
          0.95            0.05               52           3.716941  0.996426 0.997882
          0.96            0.02               61           4.360257  0.996426 0.997882
          0.96            0.05               52           3.716941  0.996426 0.997882
          0.97            0.02               67           4.789135  0.996426 0.997882
          0.97            0.05               52           3.716941  0.996426 0.997882
          0.98            0.02               86           6.147248  0.996426 0.997882
          0.98            0.05               52           3.716941  0.996426 0.997882
          0.99            0.02               86           6.147248  0.996426 0.997882
          0.99            0.05               52           3.716941  0.996426 0.997882

TOP 15 BY VALIDATION ACCURACY
 behavior_gate  text_advantage  text_used_cases  text_used_percent  accuracy       f1
          0.99            0.00              176          12.580415  0.998570 0.999153
          0.95            0.00               58           4.145818  0.997141 0.998305
          0.96            0.00               66           4.717655  0.997141 0.998305
          0.97            0.00               74           5.289492  0.997141 0.998305
          0.98            0.00              102           7.290922  0.997141 0.998305
          0.95            0.02               55           3.931380  0.996426 0.997882
          0.95            0.05               52           3.716941  0.996426 0.997882
          0.96            0.02               61           4.360257  0.996426 0.997882
          0.96            0.05               52           3.716941  0.996426 0.997882
          0.97            0.02               67           4.789135  0.996426 0.997882
          0.97            0.05               52           3.716941  0.996426 0.997882
          0.98            0.02               86           6.147248  0.996426 0.997882
          0.98            0.05               52           3.716941  0.996426 0.997882
          0.99            0.02               86           6.147248  0.996426 0.997882
          0.99            0.05               52           3.716941  0.996426 0.997882

In [ ]:
# ============================================================
# STEP 23 — FROZEN CONFIDENCE-AWARE FUSION
# UNSEEN FAKE FOLLOWERS TEST
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# ------------------------------------------------------------
# FROZEN PARAMETERS — SELECTED ONLY ON VALIDATION
# ------------------------------------------------------------

behavior_gate = 0.99
text_advantage = 0.00

# ------------------------------------------------------------
# UNSEEN TEST PROBABILITIES
# ------------------------------------------------------------

behavior_test_prob = behavior_prob_check
text_test_prob = text_test_prob

behavior_test_pred = (
    behavior_test_prob >= 0.5
).astype(int)

text_test_pred = (
    text_test_prob >= 0.5
).astype(int)

behavior_test_conf = (
    np.abs(behavior_test_prob - 0.5) * 2
)

text_test_conf = (
    np.abs(text_test_prob - 0.5) * 2
)

# ------------------------------------------------------------
# START WITH BEHAVIOR
# ------------------------------------------------------------

confidence_fusion_pred = behavior_test_pred.copy()

# Behavior is below the confidence gate
behavior_uncertain = (
    behavior_test_conf < behavior_gate
)

# Text is sufficiently more confident
text_dominant = (
    text_test_conf >
    behavior_test_conf + text_advantage
)

# Only these cases allow text to override behavior
use_text = (
    behavior_uncertain &
    text_dominant
)

confidence_fusion_pred[use_text] = (
    text_test_pred[use_text]
)

# ------------------------------------------------------------
# METRICS
# ------------------------------------------------------------

accuracy = accuracy_score(
    y_test,
    confidence_fusion_pred
)

precision = precision_score(
    y_test,
    confidence_fusion_pred,
    zero_division=0
)

recall = recall_score(
    y_test,
    confidence_fusion_pred,
    zero_division=0
)

f1 = f1_score(
    y_test,
    confidence_fusion_pred,
    zero_division=0
)

cm = confusion_matrix(
    y_test,
    confidence_fusion_pred
)

print("=" * 70)
print("FROZEN CONFIDENCE-AWARE FUSION")
print("UNSEEN FAKE FOLLOWERS")
print("=" * 70)

print("\nFrozen parameters:")
print(f"Behavior confidence gate : {behavior_gate:.2f}")
print(f"Text confidence advantage: {text_advantage:.2f}")

print("\nText override cases:")
print(
    f"{use_text.sum()} / {len(y_test)} "
    f"({use_text.mean()*100:.2f}%)"
)

print("\nPerformance:")
print(
    f"Accuracy  : {accuracy:.4f} "
    f"({accuracy*100:.2f}%)"
)

print(
    f"Precision : {precision:.4f} "
    f"({precision*100:.2f}%)"
)

print(
    f"Recall    : {recall:.4f} "
    f"({recall*100:.2f}%)"
)

print(
    f"F1-score  : {f1:.4f} "
    f"({f1*100:.2f}%)"
)

print("\nConfusion Matrix:")
print(cm)

======================================================================
FROZEN CONFIDENCE-AWARE FUSION
UNSEEN FAKE FOLLOWERS
======================================================================

Frozen parameters:
Behavior confidence gate : 0.99
Text confidence advantage: 0.00

Text override cases:
186 / 4285 (4.34%)

Performance:
Accuracy  : 0.9711 (97.11%)
Precision : 0.9917 (99.17%)
Recall    : 0.9694 (96.94%)
F1-score  : 0.9804 (98.04%)

Confusion Matrix:
[[1057   26]
 [  98 3104]]

In [ ]:
# ============================================================
# STEP 24 — CONSERVATIVE TEXT OVERRIDE
# VALIDATION ONLY
# ============================================================

from sklearn.metrics import accuracy_score, f1_score

behavior_val_prob = fusion_val["behavior_prob"].values
text_val_prob = fusion_val["text_prob"].values

behavior_val_pred = (behavior_val_prob >= 0.5).astype(int)
text_val_pred = (text_val_prob >= 0.5).astype(int)

behavior_val_conf = np.abs(behavior_val_prob - 0.5) * 2
text_val_conf = np.abs(text_val_prob - 0.5) * 2

results = []

# Behavior must be genuinely uncertain
behavior_gates = [
    0.70, 0.80, 0.85, 0.90,
    0.92, 0.95, 0.97, 0.99
]

# Text must be highly confident
text_gates = [
    0.90, 0.92, 0.95, 0.97,
    0.98, 0.99
]

for behavior_gate in behavior_gates:

    for text_gate in text_gates:

        final_pred = behavior_val_pred.copy()

        # Behavior is uncertain
        behavior_uncertain = (
            behavior_val_conf < behavior_gate
        )

        # Text is highly confident
        text_high_conf = (
            text_val_conf >= text_gate
        )

        # Models disagree
        disagreement = (
            behavior_val_pred != text_val_pred
        )

        # Text can override only under ALL conditions
        use_text = (
            behavior_uncertain &
            text_high_conf &
            disagreement
        )

        final_pred[use_text] = text_val_pred[use_text]

        acc = accuracy_score(y_val, final_pred)
        f1 = f1_score(
            y_val,
            final_pred,
            zero_division=0
        )

        results.append({
            "behavior_gate": behavior_gate,
            "text_gate": text_gate,
            "override_cases": use_text.sum(),
            "override_percent": use_text.mean() * 100,
            "accuracy": acc,
            "f1": f1
        })

conservative_results = pd.DataFrame(results)

print("=" * 70)
print("CONSERVATIVE TEXT OVERRIDE — VALIDATION ONLY")
print("=" * 70)

print("\nTOP 15 BY ACCURACY")

print(
    conservative_results
    .sort_values(
        ["accuracy", "f1"],
        ascending=False
    )
    .head(15)
    .to_string(index=False)
)

print("\nTOP 15 BY F1")

print(
    conservative_results
    .sort_values(
        ["f1", "accuracy"],
        ascending=False
    )
    .head(15)
    .to_string(index=False)
)

======================================================================
CONSERVATIVE TEXT OVERRIDE — VALIDATION ONLY
======================================================================

TOP 15 BY ACCURACY
 behavior_gate  text_gate  override_cases  override_percent  accuracy       f1
          0.99       0.90              11          0.786276  0.999285 0.999577
          0.99       0.92              11          0.786276  0.999285 0.999577
          0.99       0.95              10          0.714796  0.998570 0.999154
          0.99       0.97               9          0.643317  0.997856 0.998732
          0.95       0.90               8          0.571837  0.997141 0.998305
          0.95       0.92               8          0.571837  0.997141 0.998305
          0.97       0.90               8          0.571837  0.997141 0.998305
          0.97       0.92               8          0.571837  0.997141 0.998305
          0.99       0.98               7          0.500357  0.996426 0.997884
          0.99       0.99               7          0.500357  0.996426 0.997884
          0.95       0.95               7          0.500357  0.996426 0.997882
          0.97       0.95               7          0.500357  0.996426 0.997882
          0.95       0.97               6          0.428878  0.995711 0.997460
          0.97       0.97               6          0.428878  0.995711 0.997460
          0.92       0.90               6          0.428878  0.995711 0.997458

TOP 15 BY F1
 behavior_gate  text_gate  override_cases  override_percent  accuracy       f1
          0.99       0.90              11          0.786276  0.999285 0.999577
          0.99       0.92              11          0.786276  0.999285 0.999577
          0.99       0.95              10          0.714796  0.998570 0.999154
          0.99       0.97               9          0.643317  0.997856 0.998732
          0.95       0.90               8          0.571837  0.997141 0.998305
          0.95       0.92               8          0.571837  0.997141 0.998305
          0.97       0.90               8          0.571837  0.997141 0.998305
          0.97       0.92               8          0.571837  0.997141 0.998305
          0.99       0.98               7          0.500357  0.996426 0.997884
          0.99       0.99               7          0.500357  0.996426 0.997884
          0.95       0.95               7          0.500357  0.996426 0.997882
          0.97       0.95               7          0.500357  0.996426 0.997882
          0.95       0.97               6          0.428878  0.995711 0.997460
          0.97       0.97               6          0.428878  0.995711 0.997460
          0.92       0.90               6          0.428878  0.995711 0.997458

In [ ]:
# ============================================================
# STEP 25 — FROZEN CONSERVATIVE FUSION
# UNSEEN FAKE FOLLOWERS TEST
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# ------------------------------------------------------------
# FROZEN FROM VALIDATION
# ------------------------------------------------------------

behavior_gate = 0.99
text_gate = 0.90

# ------------------------------------------------------------
# TEST PREDICTIONS
# ------------------------------------------------------------

behavior_test_pred = (
    behavior_test_prob >= 0.5
).astype(int)

text_test_pred = (
    text_test_prob >= 0.5
).astype(int)

behavior_test_conf = (
    np.abs(behavior_test_prob - 0.5) * 2
)

text_test_conf = (
    np.abs(text_test_prob - 0.5) * 2
)

# ------------------------------------------------------------
# BEHAVIOR IS PRIMARY
# ------------------------------------------------------------

final_pred = behavior_test_pred.copy()

# Conditions for text override
behavior_uncertain = (
    behavior_test_conf < behavior_gate
)

text_high_confidence = (
    text_test_conf >= text_gate
)

models_disagree = (
    behavior_test_pred != text_test_pred
)

use_text = (
    behavior_uncertain &
    text_high_confidence &
    models_disagree
)

# Text overrides behavior ONLY in these cases
final_pred[use_text] = text_test_pred[use_text]

# ------------------------------------------------------------
# METRICS
# ------------------------------------------------------------

accuracy = accuracy_score(y_test, final_pred)
precision = precision_score(y_test, final_pred, zero_division=0)
recall = recall_score(y_test, final_pred, zero_division=0)
f1 = f1_score(y_test, final_pred, zero_division=0)

cm = confusion_matrix(y_test, final_pred)

print("=" * 70)
print("FROZEN CONSERVATIVE FUSION")
print("UNSEEN FAKE FOLLOWERS")
print("=" * 70)

print("\nFrozen parameters:")
print(f"Behavior confidence gate : {behavior_gate:.2f}")
print(f"Text confidence gate     : {text_gate:.2f}")

print("\nText override cases:")
print(
    f"{use_text.sum()} / {len(y_test)} "
    f"({use_text.mean()*100:.2f}%)"
)

print("\nPerformance:")
print(
    f"Accuracy  : {accuracy:.4f} "
    f"({accuracy*100:.2f}%)"
)

print(
    f"Precision : {precision:.4f} "
    f"({precision*100:.2f}%)"
)

print(
    f"Recall    : {recall:.4f} "
    f"({recall*100:.2f}%)"
)

print(
    f"F1-score  : {f1:.4f} "
    f"({f1*100:.2f}%)"
)

print("\nConfusion Matrix:")
print(cm)

# ------------------------------------------------------------
# COMPARE AGAINST BEHAVIOR-ONLY
# ------------------------------------------------------------

behavior_acc = accuracy_score(
    y_test,
    behavior_test_pred
)

behavior_f1 = f1_score(
    y_test,
    behavior_test_pred,
    zero_division=0
)

print("\nComparison with behavior-only:")
print(
    f"Behavior-only accuracy : "
    f"{behavior_acc*100:.2f}%"
)

print(
    f"Fusion accuracy        : "
    f"{accuracy*100:.2f}%"
)

print(
    f"Accuracy difference     : "
    f"{(accuracy-behavior_acc)*100:+.2f} percentage points"
)

print(
    f"Behavior-only F1       : "
    f"{behavior_f1*100:.2f}%"
)

print(
    f"Fusion F1              : "
    f"{f1*100:.2f}%"
)

print(
    f"F1 difference           : "
    f"{(f1-behavior_f1)*100:+.2f} percentage points"
)

======================================================================
FROZEN CONSERVATIVE FUSION
UNSEEN FAKE FOLLOWERS
======================================================================

Frozen parameters:
Behavior confidence gate : 0.99
Text confidence gate     : 0.90

Text override cases:
134 / 4285 (3.13%)

Performance:
Accuracy  : 0.9573 (95.73%)
Precision : 0.9754 (97.54%)
Recall    : 0.9672 (96.72%)
F1-score  : 0.9713 (97.13%)

Confusion Matrix:
[[1005   78]
 [ 105 3097]]

Comparison with behavior-only:
Behavior-only accuracy : 98.44%
Fusion accuracy        : 95.73%
Accuracy difference     : -2.71 percentage points
Behavior-only F1       : 98.95%
Fusion F1              : 97.13%
F1 difference           : -1.82 percentage points

In [ ]:
# ============================================================
# STEP 26 — FINAL BEHAVIORAL RELIABILITY DATASET
# CORRECTED VERSION
# ============================================================

import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Frozen reliability threshold
# ------------------------------------------------------------

RELIABILITY_THRESHOLD = 0.95

# ------------------------------------------------------------
# Make sure everything is aligned
# ------------------------------------------------------------

print("Lengths:")
print("y_test              :", len(y_test))
print("behavior_test_prob  :", len(behavior_test_prob))
print("behavior_test_pred  :", len(behavior_test_pred))
print("behavior_test_conf  :", len(behavior_test_conf))
print("drift_test_score    :", len(drift_test_score))

# ------------------------------------------------------------
# Build reliability dataset
# ------------------------------------------------------------

reliability_df = pd.DataFrame({
    "actual_label": np.asarray(y_test),
    "behavior_probability": np.asarray(behavior_test_prob),
    "behavior_prediction": np.asarray(behavior_test_pred),
    "behavior_confidence": np.asarray(behavior_test_conf),
    "drift_score": np.asarray(drift_test_score)
})

# ------------------------------------------------------------
# Reliability decision
# ------------------------------------------------------------

reliability_df["decision"] = np.where(
    reliability_df["behavior_confidence"] >= RELIABILITY_THRESHOLD,
    "Automatic",
    "Review"
)

# ------------------------------------------------------------
# Correct / incorrect
# ------------------------------------------------------------

reliability_df["correct"] = (
    reliability_df["behavior_prediction"]
    == reliability_df["actual_label"]
)

# ------------------------------------------------------------
# Basic checks
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL BEHAVIORAL RELIABILITY DATASET")
print("=" * 70)

print("\nShape:")
print(reliability_df.shape)

print("\nMissing values:")
print(
    reliability_df.isna().sum()
)

print("\nDecision distribution:")
print(
    reliability_df["decision"]
    .value_counts()
)

print("\nDecision percentages:")
print(
    reliability_df["decision"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nOverall accuracy:")
print(
    f"{reliability_df['correct'].mean() * 100:.2f}%"
)

print("\nFirst 10 rows:")
print(
    reliability_df.head(10).to_string(index=False)
)

Lengths:
y_test              : 4285
behavior_test_prob  : 4285
behavior_test_pred  : 4285
behavior_test_conf  : 4285
drift_test_score    : 4285

======================================================================
FINAL BEHAVIORAL RELIABILITY DATASET
======================================================================

Shape:
(4285, 7)

Missing values:
actual_label            0
behavior_probability    0
behavior_prediction     0
behavior_confidence     0
drift_score             0
decision                0
correct                 0
dtype: int64

Decision distribution:
decision
Automatic    4088
Review        197
Name: count, dtype: int64

Decision percentages:
decision
Automatic    95.4
Review        4.6
Name: proportion, dtype: float64

Overall accuracy:
98.44%

First 10 rows:
 actual_label  behavior_probability  behavior_prediction  behavior_confidence  drift_score  decision  correct
            0          5.321045e-04                    0             0.998936     0.998392 Automatic     True
            0          9.073680e-03                    0             0.981853     0.869371 Automatic     True
            0          7.926535e-03                    0             0.984147     0.971587 Automatic     True
            0          7.450602e-03                    0             0.985099     0.827019 Automatic     True
            0          2.205864e-01                    0             0.558827     0.933881    Review     True
            0          7.582614e-03                    0             0.984835     0.894746 Automatic     True
            0          1.187056e-08                    0             1.000000     0.999464 Automatic     True
            0          2.327904e-03                    0             0.995344     0.839707 Automatic     True
            0          1.043095e-02                    0             0.979138     0.836490 Automatic     True
            0          1.334087e-02                    0             0.973318     0.731594 Automatic     True

In [ ]:
# ============================================================
# STEP 27 — AUTOMATIC vs REVIEW RELIABILITY ANALYSIS
# ============================================================

# ------------------------------------------------------------
# Split groups
# ------------------------------------------------------------

automatic_df = reliability_df[
    reliability_df["decision"] == "Automatic"
]

review_df = reliability_df[
    reliability_df["decision"] == "Review"
]

# ------------------------------------------------------------
# Calculate metrics
# ------------------------------------------------------------

automatic_accuracy = automatic_df["correct"].mean()
review_accuracy = review_df["correct"].mean()

automatic_errors = (~automatic_df["correct"]).sum()
review_errors = (~review_df["correct"]).sum()

total_errors = (~reliability_df["correct"]).sum()

automatic_coverage = len(automatic_df) / len(reliability_df)
review_coverage = len(review_df) / len(reliability_df)

automatic_error_rate = (
    automatic_errors / len(automatic_df)
)

review_error_rate = (
    review_errors / len(review_df)
)

error_concentration_review = (
    review_errors / total_errors
)

# ------------------------------------------------------------
# Print results
# ------------------------------------------------------------

print("=" * 70)
print("RELIABILITY ANALYSIS")
print("=" * 70)

print("\nAUTOMATIC DECISIONS")
print("-" * 40)

print(f"Accounts        : {len(automatic_df)}")
print(f"Coverage        : {automatic_coverage*100:.2f}%")
print(f"Accuracy        : {automatic_accuracy*100:.2f}%")
print(f"Errors          : {automatic_errors}")
print(f"Error rate      : {automatic_error_rate*100:.2f}%")

print("\nREVIEW DECISIONS")
print("-" * 40)

print(f"Accounts        : {len(review_df)}")
print(f"Coverage        : {review_coverage*100:.2f}%")
print(f"Accuracy        : {review_accuracy*100:.2f}%")
print(f"Errors          : {review_errors}")
print(f"Error rate      : {review_error_rate*100:.2f}%")

print("\nOVERALL")
print("-" * 40)

print(f"Total accounts  : {len(reliability_df)}")
print(f"Total errors    : {total_errors}")

print(
    f"\nErrors sent to Review: "
    f"{error_concentration_review*100:.2f}%"
)

# ------------------------------------------------------------
# Confidence comparison
# ------------------------------------------------------------

print("\nCONFIDENCE COMPARISON")
print("-" * 40)

print(
    f"Automatic mean confidence : "
    f"{automatic_df['behavior_confidence'].mean():.4f}"
)

print(
    f"Review mean confidence    : "
    f"{review_df['behavior_confidence'].mean():.4f}"
)

print(
    f"Automatic median confidence : "
    f"{automatic_df['behavior_confidence'].median():.4f}"
)

print(
    f"Review median confidence    : "
    f"{review_df['behavior_confidence'].median():.4f}"
)

# ------------------------------------------------------------
# Drift comparison
# ------------------------------------------------------------

print("\nDRIFT COMPARISON")
print("-" * 40)

print(
    f"Automatic mean drift : "
    f"{automatic_df['drift_score'].mean():.4f}"
)

print(
    f"Review mean drift    : "
    f"{review_df['drift_score'].mean():.4f}"
)

print(
    f"Automatic median drift : "
    f"{automatic_df['drift_score'].median():.4f}"
)

print(
    f"Review median drift    : "
    f"{review_df['drift_score'].median():.4f}"
)

======================================================================
RELIABILITY ANALYSIS
======================================================================

AUTOMATIC DECISIONS
----------------------------------------
Accounts        : 4088
Coverage        : 95.40%
Accuracy        : 99.63%
Errors          : 15
Error rate      : 0.37%

REVIEW DECISIONS
----------------------------------------
Accounts        : 197
Coverage        : 4.60%
Accuracy        : 73.60%
Errors          : 52
Error rate      : 26.40%

OVERALL
----------------------------------------
Total accounts  : 4285
Total errors    : 67

Errors sent to Review: 77.61%

CONFIDENCE COMPARISON
----------------------------------------
Automatic mean confidence : 0.9964
Review mean confidence    : 0.7522
Automatic median confidence : 1.0000
Review median confidence    : 0.8372

DRIFT COMPARISON
----------------------------------------
Automatic mean drift : 0.7565
Review mean drift    : 0.6951
Automatic median drift : 0.7957
Review median drift    : 0.6762

In [ ]:
# ============================================================
# STEP 28 — REVIEW GROUP ANALYSIS
# ============================================================

print("=" * 70)
print("REVIEW GROUP ANALYSIS")
print("=" * 70)

# ------------------------------------------------------------
# Label distribution
# ------------------------------------------------------------

print("\nREVIEW GROUP — ACTUAL LABELS")
print("-" * 40)

label_counts = (
    review_df["actual_label"]
    .value_counts()
    .sort_index()
)

print(label_counts)

print("\nPercentages:")
print(
    review_df["actual_label"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)

# ------------------------------------------------------------
# Prediction distribution
# ------------------------------------------------------------

print("\nREVIEW GROUP — PREDICTIONS")
print("-" * 40)

print(
    review_df["behavior_prediction"]
    .value_counts()
    .sort_index()
)

# ------------------------------------------------------------
# Correct vs incorrect
# ------------------------------------------------------------

print("\nREVIEW GROUP — CORRECTNESS")
print("-" * 40)

print(
    review_df["correct"]
    .value_counts()
)

# ------------------------------------------------------------
# Statistics
# ------------------------------------------------------------

print("\nREVIEW GROUP STATISTICS")
print("-" * 40)

print(
    review_df[
        [
            "behavior_probability",
            "behavior_confidence",
            "drift_score"
        ]
    ].describe().round(4)
)

# ------------------------------------------------------------
# Errors in review
# ------------------------------------------------------------

review_errors = review_df[
    ~review_df["correct"]
]

print("\nREVIEW ERRORS")
print("-" * 40)

print(
    f"Review errors: "
    f"{len(review_errors)}"
)

print(
    f"Review error rate: "
    f"{len(review_errors)/len(review_df)*100:.2f}%"
)

print("\nReview errors — actual labels:")
print(
    review_errors["actual_label"]
    .value_counts()
    .sort_index()
)

# ------------------------------------------------------------
# Compare correct vs incorrect review cases
# ------------------------------------------------------------

print("\nCONFIDENCE — CORRECT vs INCORRECT REVIEW")
print("-" * 40)

print(
    review_df
    .groupby("correct")[
        [
            "behavior_probability",
            "behavior_confidence",
            "drift_score"
        ]
    ]
    .mean()
    .round(4)
)

# ------------------------------------------------------------
# Lowest-confidence cases
# ------------------------------------------------------------

print("\n10 LOWEST-CONFIDENCE REVIEW CASES")
print("-" * 40)

print(
    review_df[
        [
            "actual_label",
            "behavior_probability",
            "behavior_confidence",
            "drift_score",
            "correct"
        ]
    ]
    .sort_values("behavior_confidence")
    .head(10)
    .to_string(index=False)
)

======================================================================
REVIEW GROUP ANALYSIS
======================================================================

REVIEW GROUP — ACTUAL LABELS
----------------------------------------
actual_label
0     74
1    123
Name: count, dtype: int64

Percentages:
actual_label
0    37.56
1    62.44
Name: proportion, dtype: float64

REVIEW GROUP — PREDICTIONS
----------------------------------------
behavior_prediction
0    110
1     87
Name: count, dtype: int64

REVIEW GROUP — CORRECTNESS
----------------------------------------
correct
True     145
False     52
Name: count, dtype: int64

REVIEW GROUP STATISTICS
----------------------------------------
       behavior_probability  behavior_confidence  drift_score
count              197.0000             197.0000     197.0000
mean                 0.4508               0.7522       0.6951
std                  0.3899               0.2216       0.1953
min                  0.0252               0.0054       0.2266
25%                  0.0475               0.6776       0.5157
50%                  0.3009               0.8372       0.6762
75%                  0.8829               0.9207       0.8812
max                  0.9750               0.9499       0.9996

REVIEW ERRORS
----------------------------------------
Review errors: 52
Review error rate: 26.40%

Review errors — actual labels:
actual_label
0     8
1    44
Name: count, dtype: int64

CONFIDENCE — CORRECT vs INCORRECT REVIEW
----------------------------------------
         behavior_probability  behavior_confidence  drift_score
correct
False                  0.2801               0.6230       0.6778
True                   0.5120               0.7985       0.7013

10 LOWEST-CONFIDENCE REVIEW CASES
----------------------------------------
 actual_label  behavior_probability  behavior_confidence  drift_score  correct
            0              0.502717             0.005434     0.930307    False
            1              0.462124             0.075752     0.969621    False
            1              0.452229             0.095541     0.761258    False
            0              0.431610             0.136780     0.874017     True
            0              0.429937             0.140127     0.464618     True
            1              0.591895             0.183791     0.626698     True
            1              0.593533             0.187066     0.625447     True
            1              0.403965             0.192070     0.383488    False
            0              0.608167             0.216334     0.414761    False
            1              0.383061             0.233879     0.901894    False

In [ ]:
# ============================================================
# STEP 29 — TEXT EVIDENCE FOR REVIEW CASES
# DESCRIPTIVE ANALYSIS ONLY
# ============================================================

import numpy as np
import pandas as pd

# ------------------------------------------------------------
# Add aligned text information
# ------------------------------------------------------------

review_analysis = reliability_df.copy()

review_analysis["text_probability"] = np.asarray(
    text_test_prob
)

review_analysis["text_prediction"] = (
    review_analysis["text_probability"] >= 0.5
).astype(int)

review_analysis["text_confidence"] = (
    np.abs(
        review_analysis["text_probability"] - 0.5
    ) * 2
)

review_analysis["models_agree"] = (
    review_analysis["behavior_prediction"]
    == review_analysis["text_prediction"]
)

# ------------------------------------------------------------
# Keep only Review cases
# ------------------------------------------------------------

review_analysis = review_analysis[
    review_analysis["decision"] == "Review"
].copy()

# ------------------------------------------------------------
# Basic information
# ------------------------------------------------------------

print("=" * 70)
print("TEXT EVIDENCE IN REVIEW CASES")
print("=" * 70)

print("\nReview accounts:", len(review_analysis))

# ------------------------------------------------------------
# Model agreement
# ------------------------------------------------------------

print("\nMODEL AGREEMENT")
print("-" * 40)

agreement_counts = (
    review_analysis["models_agree"]
    .value_counts()
)

print(agreement_counts)

print("\nAgreement percentages:")

agreement_percent = (
    review_analysis["models_agree"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print(agreement_percent)

# ------------------------------------------------------------
# Confidence comparison
# ------------------------------------------------------------

print("\nMEAN CONFIDENCE")
print("-" * 40)

behavior_mean_conf = (
    review_analysis["behavior_confidence"].mean()
)

text_mean_conf = (
    review_analysis["text_confidence"].mean()
)

print(
    f"Behavior confidence : {behavior_mean_conf:.4f}"
)

print(
    f"Text confidence     : {text_mean_conf:.4f}"
)

# ------------------------------------------------------------
# Text prediction distribution
# ------------------------------------------------------------

print("\nTEXT PREDICTIONS")
print("-" * 40)

print(
    review_analysis["text_prediction"]
    .value_counts()
    .sort_index()
)

# ------------------------------------------------------------
# Agreement vs disagreement
# ------------------------------------------------------------

print("\nAGREEMENT vs DISAGREEMENT")
print("-" * 40)

for status, group in review_analysis.groupby(
    "models_agree"
):

    accuracy = group["correct"].mean() * 100
    behavior_conf = (
        group["behavior_confidence"].mean()
    )
    text_conf = (
        group["text_confidence"].mean()
    )
    drift = (
        group["drift_score"].mean()
    )

    print(
        f"\nModels agree = {status}"
    )

    print(
        f"Accounts: {len(group)}"
    )

    print(
        f"Behavior accuracy: {accuracy:.2f}%"
    )

    print(
        f"Mean behavior confidence: "
        f"{behavior_conf:.4f}"
    )

    print(
        f"Mean text confidence: "
        f"{text_conf:.4f}"
    )

    print(
        f"Mean drift: {drift:.4f}"
    )

# ------------------------------------------------------------
# Disagreement cases
# ------------------------------------------------------------

disagreement_df = review_analysis[
    ~review_analysis["models_agree"]
].copy()

print("\n" + "=" * 70)
print("REVIEW CASES WHERE BEHAVIOR AND TEXT DISAGREE")
print("=" * 70)

print(
    f"\nDisagreement cases: "
    f"{len(disagreement_df)}"
)

if len(review_analysis) > 0:

    disagreement_percent = (
        len(disagreement_df)
        / len(review_analysis)
        * 100
    )

    print(
        f"Percentage of review cases: "
        f"{disagreement_percent:.2f}%"
    )

# ------------------------------------------------------------
# Behavior accuracy during disagreement
# ------------------------------------------------------------

if len(disagreement_df) > 0:

    behavior_disagreement_accuracy = (
        disagreement_df["correct"].mean() * 100
    )

    text_disagreement_accuracy = (
        (
            disagreement_df["text_prediction"]
            == disagreement_df["actual_label"]
        ).mean() * 100
    )

    print(
        f"\nBehavior accuracy in disagreement: "
        f"{behavior_disagreement_accuracy:.2f}%"
    )

    print(
        f"Text accuracy in disagreement: "
        f"{text_disagreement_accuracy:.2f}%"
    )

# ------------------------------------------------------------
# Strong text evidence
# ------------------------------------------------------------

strong_text = disagreement_df[
    disagreement_df["text_confidence"] >= 0.90
].copy()

print("\n" + "=" * 70)
print("STRONG TEXT DISAGREEMENT")
print("=" * 70)

print(
    f"\nStrong text disagreement cases: "
    f"{len(strong_text)}"
)

if len(strong_text) > 0:

    behavior_strong_accuracy = (
        strong_text["correct"].mean() * 100
    )

    text_strong_accuracy = (
        (
            strong_text["text_prediction"]
            == strong_text["actual_label"]
        ).mean() * 100
    )

    print(
        f"Behavior accuracy: "
        f"{behavior_strong_accuracy:.2f}%"
    )

    print(
        f"Text accuracy: "
        f"{text_strong_accuracy:.2f}%"
    )

# ------------------------------------------------------------
# Sample review cases
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("LOWEST-CONFIDENCE REVIEW CASES")
print("=" * 70)

columns_to_show = [
    "actual_label",
    "behavior_probability",
    "behavior_confidence",
    "text_probability",
    "text_confidence",
    "drift_score",
    "models_agree",
    "correct"
]

print(
    review_analysis[
        columns_to_show
    ]
    .sort_values("behavior_confidence")
    .head(15)
    .to_string(index=False)
)

======================================================================
TEXT EVIDENCE IN REVIEW CASES
======================================================================

Review accounts: 197

MODEL AGREEMENT
----------------------------------------
models_agree
False    104
True      93
Name: count, dtype: int64

Agreement percentages:
models_agree
False    52.79
True     47.21
Name: proportion, dtype: float64

MEAN CONFIDENCE
----------------------------------------
Behavior confidence : 0.7522
Text confidence     : 0.7495

TEXT PREDICTIONS
----------------------------------------
text_prediction
0    132
1     65
Name: count, dtype: int64

AGREEMENT vs DISAGREEMENT
----------------------------------------

Models agree = False
Accounts: 104
Behavior accuracy: 75.00%
Mean behavior confidence: 0.7433
Mean text confidence: 0.7578
Mean drift: 0.6987

Models agree = True
Accounts: 93
Behavior accuracy: 72.04%
Mean behavior confidence: 0.7622
Mean text confidence: 0.7402
Mean drift: 0.6909

======================================================================
REVIEW CASES WHERE BEHAVIOR AND TEXT DISAGREE
======================================================================

Disagreement cases: 104
Percentage of review cases: 52.79%

Behavior accuracy in disagreement: 75.00%
Text accuracy in disagreement: 25.00%

======================================================================
STRONG TEXT DISAGREEMENT
======================================================================

Strong text disagreement cases: 46
Behavior accuracy: 82.61%
Text accuracy: 17.39%

======================================================================
LOWEST-CONFIDENCE REVIEW CASES
======================================================================
 actual_label  behavior_probability  behavior_confidence  text_probability  text_confidence  drift_score  models_agree  correct
            0              0.502717             0.005434          0.010019         0.979962     0.930307         False    False
            1              0.462124             0.075752          0.090067         0.819867     0.969621          True    False
            1              0.452229             0.095541          0.020134         0.959731     0.761258          True    False
            0              0.431610             0.136780          0.139824         0.720351     0.874017          True     True
            0              0.429937             0.140127          0.974610         0.949220     0.464618         False     True
            1              0.591895             0.183791          0.150191         0.699617     0.626698         False     True
            1              0.593533             0.187066          0.017601         0.964797     0.625447         False     True
            1              0.403965             0.192070          0.060069         0.879862     0.383488          True    False
            0              0.608167             0.216334          0.048024         0.903952     0.414761         False    False
            1              0.383061             0.233879          0.191027         0.617947     0.901894          True    False
            1              0.375286             0.249429          0.447108         0.105784     0.443710          True    False
            0              0.354862             0.290275          0.242568         0.514863     0.944425          True     True
            1              0.354326             0.291349          0.792623         0.585246     0.979807         False    False
            1              0.348410             0.303179          0.216157         0.567686     0.853645          True    False
            1              0.339764             0.320471          0.038889         0.922223     0.538420          True    False

In [ ]:
# ============================================================
# STEP 30 — FINAL RELIABILITY SUMMARY
# ============================================================

total_accounts = len(reliability_df)

automatic_accounts = len(automatic_df)
review_accounts = len(review_df)

total_errors = (~reliability_df["correct"]).sum()
automatic_errors = (~automatic_df["correct"]).sum()
review_errors = (~review_df["correct"]).sum()

automatic_coverage = (
    automatic_accounts / total_accounts
)

review_coverage = (
    review_accounts / total_accounts
)

review_error_capture = (
    review_errors / total_errors
)

# ------------------------------------------------------------
# Error rate reduction
# ------------------------------------------------------------

overall_error_rate = (
    total_errors / total_accounts
)

automatic_error_rate = (
    automatic_errors / automatic_accounts
)

error_rate_reduction = (
    1 - automatic_error_rate / overall_error_rate
)

# ------------------------------------------------------------
# Print final results
# ------------------------------------------------------------

print("=" * 70)
print("FINAL RELIABILITY PERFORMANCE")
print("=" * 70)

print("\nTotal accounts:")
print(f"{total_accounts}")

print("\nAutomatic decisions:")
print(
    f"{automatic_accounts} "
    f"({automatic_coverage*100:.2f}%)"
)

print("\nReview decisions:")
print(
    f"{review_accounts} "
    f"({review_coverage*100:.2f}%)"
)

print("\nTotal model errors:")
print(total_errors)

print("\nErrors in Automatic group:")
print(automatic_errors)

print("\nErrors in Review group:")
print(review_errors)

print(
    "\nError capture by Review:"
)

print(
    f"{review_error_capture*100:.2f}% "
    f"of all model errors"
)

print(
    "\nOverall error rate:"
)

print(
    f"{overall_error_rate*100:.2f}%"
)

print(
    "\nAutomatic-group error rate:"
)

print(
    f"{automatic_error_rate*100:.2f}%"
)

print(
    "\nRelative error-rate reduction:"
)

print(
    f"{error_rate_reduction*100:.2f}%"
)

======================================================================
FINAL RELIABILITY PERFORMANCE
======================================================================

Total accounts:
4285

Automatic decisions:
4088 (95.40%)

Review decisions:
197 (4.60%)

Total model errors:
67

Errors in Automatic group:
15

Errors in Review group:
52

Error capture by Review:
77.61% of all model errors

Overall error rate:
1.56%

Automatic-group error rate:
0.37%

Relative error-rate reduction:
76.53%

In [ ]:
# ============================================================
# FINAL FUSION RESULTS — FROZEN EVALUATION
# ============================================================
# This cell ONLY evaluates the already-frozen models.
# No test-set tuning is performed here.
# ============================================================

import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# ------------------------------------------------------------
# 1. BEHAVIOR-ONLY
# ------------------------------------------------------------

behavior_pred = np.asarray(behavior_test_pred).astype(int)

behavior_accuracy = accuracy_score(y_test, behavior_pred)
behavior_precision = precision_score(y_test, behavior_pred)
behavior_recall = recall_score(y_test, behavior_pred)
behavior_f1 = f1_score(y_test, behavior_pred)

# ------------------------------------------------------------
# 2. TEXT-ONLY
# ------------------------------------------------------------

text_pred = (np.asarray(text_test_prob) >= 0.5).astype(int)

text_accuracy = accuracy_score(y_test, text_pred)
text_precision = precision_score(y_test, text_pred)
text_recall = recall_score(y_test, text_pred)
text_f1 = f1_score(y_test, text_pred)

# ------------------------------------------------------------
# 3. FINAL WEIGHTED FUSION
# ------------------------------------------------------------
# Frozen weights selected using VALIDATION data only.

BEHAVIOR_WEIGHT = 0.48
TEXT_WEIGHT = 0.52

fusion_test_prob = (
    BEHAVIOR_WEIGHT * np.asarray(behavior_test_prob)
    + TEXT_WEIGHT * np.asarray(text_test_prob)
)

fusion_test_pred = (
    fusion_test_prob >= 0.5
).astype(int)

fusion_accuracy = accuracy_score(
    y_test,
    fusion_test_pred
)

fusion_precision = precision_score(
    y_test,
    fusion_test_pred
)

fusion_recall = recall_score(
    y_test,
    fusion_test_pred
)

fusion_f1 = f1_score(
    y_test,
    fusion_test_pred
)

fusion_cm = confusion_matrix(
    y_test,
    fusion_test_pred
)

# ------------------------------------------------------------
# 4. ADAPTIVE FUSION
# ------------------------------------------------------------

adaptive_pred = np.asarray(
    (fusion_test_prob >= 0.5)
).astype(int)

# ------------------------------------------------------------
# 5. RESULTS TABLE
# ------------------------------------------------------------

results = pd.DataFrame({
    "Model": [
        "Behavior-only",
        "Text-only",
        "Weighted Fusion"
    ],

    "Accuracy (%)": [
        behavior_accuracy * 100,
        text_accuracy * 100,
        fusion_accuracy * 100
    ],

    "Precision (%)": [
        behavior_precision * 100,
        text_precision * 100,
        fusion_precision * 100
    ],

    "Recall (%)": [
        behavior_recall * 100,
        text_recall * 100,
        fusion_recall * 100
    ],

    "F1 (%)": [
        behavior_f1 * 100,
        text_f1 * 100,
        fusion_f1 * 100
    ]
})

print("=" * 75)
print("FINAL FUSION RESULTS — UNSEEN FAKE FOLLOWERS")
print("=" * 75)

print("\nEvaluation protocol:")
print("Training categories : Known bot categories")
print("Unseen category     : Fake Followers")
print("Test accounts       :", len(y_test))
print("Fusion weights      : Behavior = 0.48 | Text = 0.52")
print("Weights selected using validation data only.")

print("\n" + "-" * 75)
print("PERFORMANCE COMPARISON")
print("-" * 75)

print(
    results.to_string(
        index=False,
        formatters={
            "Accuracy (%)": "{:.2f}".format,
            "Precision (%)": "{:.2f}".format,
            "Recall (%)": "{:.2f}".format,
            "F1 (%)": "{:.2f}".format
        }
    )
)

print("\n" + "-" * 75)
print("FINAL WEIGHTED FUSION")
print("-" * 75)

print(f"Accuracy  : {fusion_accuracy * 100:.2f}%")
print(f"Precision : {fusion_precision * 100:.2f}%")
print(f"Recall    : {fusion_recall * 100:.2f}%")
print(f"F1 Score  : {fusion_f1 * 100:.2f}%")

print("\nConfusion Matrix:")
print(fusion_cm)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        fusion_test_pred,
        target_names=["Genuine", "Bot"],
        digits=4
    )
)

# ------------------------------------------------------------
# 6. COMPARISON WITH BEHAVIOR-ONLY
# ------------------------------------------------------------

accuracy_change = (
    fusion_accuracy - behavior_accuracy
) * 100

f1_change = (
    fusion_f1 - behavior_f1
) * 100

print("\n" + "-" * 75)
print("FUSION vs BEHAVIOR-ONLY")
print("-" * 75)

print(
    f"Accuracy change : {accuracy_change:+.2f} percentage points"
)

print(
    f"F1 change       : {f1_change:+.2f} percentage points"
)

if accuracy_change > 0:
    print("\nFusion improves unseen-category accuracy.")
else:
    print(
        "\nBehavior-only performs better on the unseen category."
    )

print("\n" + "=" * 75)
print("END OF FINAL FUSION EVALUATION")
print("=" * 75)

===========================================================================
FINAL FUSION RESULTS — UNSEEN FAKE FOLLOWERS
===========================================================================

Evaluation protocol:
Training categories : Known bot categories
Unseen category     : Fake Followers
Test accounts       : 4285
Fusion weights      : Behavior = 0.48 | Text = 0.52
Weights selected using validation data only.

---------------------------------------------------------------------------
PERFORMANCE COMPARISON
---------------------------------------------------------------------------
          Model Accuracy (%) Precision (%) Recall (%) F1 (%)
  Behavior-only        98.44         99.75      98.16  98.95
      Text-only        75.01         88.48      76.51  82.06
Weighted Fusion        86.53         95.21      86.32  90.55

---------------------------------------------------------------------------
FINAL WEIGHTED FUSION
---------------------------------------------------------------------------
Accuracy  : 86.53%
Precision : 95.21%
Recall    : 86.32%
F1 Score  : 90.55%

Confusion Matrix:
[[ 944  139]
 [ 438 2764]]

Classification Report:
              precision    recall  f1-score   support

     Genuine     0.6831    0.8717    0.7659      1083
         Bot     0.9521    0.8632    0.9055      3202

    accuracy                         0.8653      4285
   macro avg     0.8176    0.8674    0.8357      4285
weighted avg     0.8841    0.8653    0.8702      4285


---------------------------------------------------------------------------
FUSION vs BEHAVIOR-ONLY
---------------------------------------------------------------------------
Accuracy change : -11.90 percentage points
F1 change       : -8.40 percentage points

Behavior-only performs better on the unseen category.

===========================================================================
END OF FINAL FUSION EVALUATION
===========================================================================

In [ ]:
# ============================================================
# MASTER FINAL RESULTS — AI BOT DETECTION
# Behavioral + Textual + Fusion + Drift + Reliability
# ============================================================
#
# IMPORTANT:
# This cell is REPORTING ONLY.
# No model tuning is performed here.
# Unseen Fake Followers remains frozen.
# ============================================================

import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# ============================================================
# 1. COMMON DATA
# ============================================================

y_true = np.asarray(y_test).astype(int)

behavior_prob = np.asarray(
    behavior_test_prob
)

text_prob = np.asarray(
    text_test_prob
)

behavior_pred = (
    behavior_prob >= 0.5
).astype(int)

text_pred = (
    text_prob >= 0.5
).astype(int)


# ============================================================
# 2. METRIC FUNCTION
# ============================================================

def calculate_metrics(y_true, y_pred):

    return {
        "Accuracy": accuracy_score(y_true, y_pred) * 100,
        "Precision": precision_score(y_true, y_pred) * 100,
        "Recall": recall_score(y_true, y_pred) * 100,
        "F1": f1_score(y_true, y_pred) * 100
    }


# ============================================================
# 3. BEHAVIOR-ONLY
# ============================================================

behavior_metrics = calculate_metrics(
    y_true,
    behavior_pred
)


# ============================================================
# 4. TEXT-ONLY
# ============================================================

text_metrics = calculate_metrics(
    y_true,
    text_pred
)


# ============================================================
# 5. WEIGHTED FUSION
# ============================================================
# Frozen validation-selected weights:
# Behavior = 0.48
# Text     = 0.52

BEHAVIOR_WEIGHT = 0.48
TEXT_WEIGHT = 0.52

weighted_fusion_prob = (
    BEHAVIOR_WEIGHT * behavior_prob
    +
    TEXT_WEIGHT * text_prob
)

weighted_fusion_pred = (
    weighted_fusion_prob >= 0.5
).astype(int)

weighted_metrics = calculate_metrics(
    y_true,
    weighted_fusion_pred
)


# ============================================================
# 6. ADAPTIVE FUSION
# ============================================================

adaptive_prob = np.asarray(
    fusion_test_prob
)

adaptive_pred = (
    adaptive_prob >= 0.5
).astype(int)

adaptive_metrics = calculate_metrics(
    y_true,
    adaptive_pred
)


# ============================================================
# 7. GATED FUSION
# ============================================================
# Frozen validation-selected gate:
# Behavior confidence >= 0.99
# Otherwise use weighted fusion.

behavior_confidence = (
    np.abs(behavior_prob - 0.5) * 2
)

GATE = 0.99

gated_pred = behavior_pred.copy()

gated_mask = (
    behavior_confidence < GATE
)

gated_pred[gated_mask] = (
    weighted_fusion_pred[gated_mask]
)

gated_metrics = calculate_metrics(
    y_true,
    gated_pred
)


# ============================================================
# 8. CONFIDENCE-AWARE TEXT OVERRIDE
# ============================================================
# Frozen validation-selected rule:
# behavior confidence < 0.99
# text confidence > behavior confidence
# models disagree

text_confidence = (
    np.abs(text_prob - 0.5) * 2
)

confidence_override_pred = behavior_pred.copy()

confidence_override_mask = (
    (behavior_confidence < 0.99)
    &
    (text_confidence > behavior_confidence)
    &
    (behavior_pred != text_pred)
)

confidence_override_pred[
    confidence_override_mask
] = text_pred[
    confidence_override_mask
]

confidence_override_metrics = calculate_metrics(
    y_true,
    confidence_override_pred
)


# ============================================================
# 9. CONSERVATIVE TEXT OVERRIDE
# ============================================================
# Frozen validation-selected rule:
# behavior confidence < 0.99
# text confidence >= 0.90
# models disagree

conservative_override_pred = behavior_pred.copy()

conservative_override_mask = (
    (behavior_confidence < 0.99)
    &
    (text_confidence >= 0.90)
    &
    (behavior_pred != text_pred)
)

conservative_override_pred[
    conservative_override_mask
] = text_pred[
    conservative_override_mask
]

conservative_override_metrics = calculate_metrics(
    y_true,
    conservative_override_pred
)


# ============================================================
# 10. AGREEMENT-BASED REVIEW
# ============================================================
# If models agree -> automatic
# If models disagree -> review
#
# The prediction remains behavior-based.

agreement_mask = (
    behavior_pred == text_pred
)

agreement_review_pred = behavior_pred.copy()

agreement_review_metrics = calculate_metrics(
    y_true,
    agreement_review_pred
)


# ============================================================
# 11. DRIFT ANALYSIS
# ============================================================

drift = np.asarray(
    drift_test_score
)

DRIFT_RELIABLE = 0.80
DRIFT_REVIEW = 0.95

drift_reliable = (
    drift < DRIFT_RELIABLE
)

drift_review = (
    (drift >= DRIFT_RELIABLE)
    &
    (drift < DRIFT_REVIEW)
)

drift_high = (
    drift >= DRIFT_REVIEW
)


# ============================================================
# 12. FINAL BEHAVIOR RELIABILITY
# ============================================================
# Validation-selected confidence threshold:
# 0.95

RELIABILITY_THRESHOLD = 0.95

automatic_mask = (
    behavior_confidence >=
    RELIABILITY_THRESHOLD
)

review_mask = (
    ~automatic_mask
)

automatic_count = automatic_mask.sum()
review_count = review_mask.sum()

automatic_accuracy = (
    (behavior_pred[automatic_mask] ==
     y_true[automatic_mask]).mean()
    * 100
)

review_accuracy = (
    (behavior_pred[review_mask] ==
     y_true[review_mask]).mean()
    * 100
)

overall_errors = (
    behavior_pred != y_true
)

automatic_errors = (
    overall_errors & automatic_mask
).sum()

review_errors = (
    overall_errors & review_mask
).sum()

total_errors = overall_errors.sum()

error_capture = (
    review_errors / total_errors
) * 100


# ============================================================
# 13. ERROR RATE REDUCTION
# ============================================================

overall_error_rate = (
    total_errors / len(y_true)
)

automatic_error_rate = (
    automatic_errors /
    automatic_count
)

relative_error_reduction = (
    1 -
    automatic_error_rate /
    overall_error_rate
) * 100


# ============================================================
# 14. FINAL RESULTS TABLE
# ============================================================

results_table = pd.DataFrame({

    "Experiment": [

        "Behavior-only",

        "Text-only",

        "Weighted Fusion",

        "Adaptive Fusion",

        "Gated Fusion",

        "Confidence-aware Override",

        "Conservative Text Override",

        "Agreement-based Review"

    ],

    "Accuracy (%)": [

        behavior_metrics["Accuracy"],

        text_metrics["Accuracy"],

        weighted_metrics["Accuracy"],

        adaptive_metrics["Accuracy"],

        gated_metrics["Accuracy"],

        confidence_override_metrics["Accuracy"],

        conservative_override_metrics["Accuracy"],

        agreement_review_metrics["Accuracy"]

    ],

    "Precision (%)": [

        behavior_metrics["Precision"],

        text_metrics["Precision"],

        weighted_metrics["Precision"],

        adaptive_metrics["Precision"],

        gated_metrics["Precision"],

        confidence_override_metrics["Precision"],

        conservative_override_metrics["Precision"],

        agreement_review_metrics["Precision"]

    ],

    "Recall (%)": [

        behavior_metrics["Recall"],

        text_metrics["Recall"],

        weighted_metrics["Recall"],

        adaptive_metrics["Recall"],

        gated_metrics["Recall"],

        confidence_override_metrics["Recall"],

        conservative_override_metrics["Recall"],

        agreement_review_metrics["Recall"]

    ],

    "F1 (%)": [

        behavior_metrics["F1"],

        text_metrics["F1"],

        weighted_metrics["F1"],

        gated_metrics["F1"],

        confidence_override_metrics["F1"],

        conservative_override_metrics["F1"],

        adaptive_metrics["F1"],

        agreement_review_metrics["F1"]

    ]

})


# ============================================================
# 15. PRINT FINAL RESULTS
# ============================================================

print("\n")
print("=" * 90)
print("FINAL EXPERIMENTAL RESULTS")
print("AI-BASED SOCIAL MEDIA BOT DETECTION")
print("=" * 90)

print("\nEvaluation:")
print("-" * 90)

print("Dataset                 : Cresci-2017")
print("Unseen category         : Fake Followers")
print("Test accounts           :", len(y_true))
print("Known training accounts : 6995")
print("Behavior features       : 15")
print("Fusion weights          : Behavior 0.48 | Text 0.52")
print("Reliability threshold   : 0.95")
print("Drift method            : Mahalanobis + empirical percentile")


# ============================================================
# PERFORMANCE TABLE
# ============================================================

print("\n")
print("=" * 90)
print("MODEL AND FUSION PERFORMANCE")
print("=" * 90)

print(
    results_table.to_string(
        index=False,
        formatters={
            "Accuracy (%)": "{:.2f}".format,
            "Precision (%)": "{:.2f}".format,
            "Recall (%)": "{:.2f}".format,
            "F1 (%)": "{:.2f}".format
        }
    )
)


# ============================================================
# CONFUSION MATRICES
# ============================================================

print("\n")
print("=" * 90)
print("CONFUSION MATRICES")
print("=" * 90)

print("\nBehavior-only:")
print(
    confusion_matrix(
        y_true,
        behavior_pred
    )
)

print("\nText-only:")
print(
    confusion_matrix(
        y_true,
        text_pred
    )
)

print("\nWeighted Fusion:")
print(
    confusion_matrix(
        y_true,
        weighted_fusion_pred
    )
)

print("\nGated Fusion:")
print(
    confusion_matrix(
        y_true,
        gated_pred
    )
)


# ============================================================
# FUSION ERROR ANALYSIS
# ============================================================

behavior_correct = (
    behavior_pred == y_true
)

text_correct = (
    text_pred == y_true
)

print("\n")
print("=" * 90)
print("BEHAVIOR vs TEXT ERROR ANALYSIS")
print("=" * 90)

print(
    "\nBehavior correct:",
    behavior_correct.sum()
)

print(
    "Behavior errors:",
    (~behavior_correct).sum()
)

print(
    "Text correct:",
    text_correct.sum()
)

print(
    "Text errors:",
    (~text_correct).sum()
)

print(
    "\nBehavior wrong + Text correct:",
    (
        (~behavior_correct)
        &
        text_correct
    ).sum()
)

print(
    "Behavior correct + Text wrong:",
    (
        behavior_correct
        &
        (~text_correct)
    ).sum()
)

print(
    "Both wrong:",
    (
        (~behavior_correct)
        &
        (~text_correct)
    ).sum()
)


# ============================================================
# DRIFT RESULTS
# ============================================================

print("\n")
print("=" * 90)
print("DRIFT ANALYSIS")
print("=" * 90)

print(
    f"\nDrift score mean   : {drift.mean():.4f}"
)

print(
    f"Drift score median : {np.median(drift):.4f}"
)

print(
    f"Drift score 95th   : {np.percentile(drift,95):.4f}"
)

print(
    f"Drift score 99th   : {np.percentile(drift,99):.4f}"
)

print(
    "\nLow drift (<0.80):",
    drift_reliable.sum()
)

print(
    "Review drift (0.80-<0.95):",
    drift_review.sum()
)

print(
    "High drift (>=0.95):",
    drift_high.sum()
)


# ============================================================
# RELIABILITY RESULTS
# ============================================================

print("\n")
print("=" * 90)
print("FINAL RELIABILITY ANALYSIS")
print("=" * 90)

print(
    f"\nAutomatic decisions : "
    f"{automatic_count} "
    f"({automatic_count/len(y_true)*100:.2f}%)"
)

print(
    f"Review decisions    : "
    f"{review_count} "
    f"({review_count/len(y_true)*100:.2f}%)"
)

print(
    f"\nAutomatic accuracy  : "
    f"{automatic_accuracy:.2f}%"
)

print(
    f"Review accuracy     : "
    f"{review_accuracy:.2f}%"
)

print(
    f"\nTotal model errors  : "
    f"{total_errors}"
)

print(
    f"Automatic errors    : "
    f"{automatic_errors}"
)

print(
    f"Review errors       : "
    f"{review_errors}"
)

print(
    f"\nError capture by review : "
    f"{error_capture:.2f}%"
)

print(
    f"Overall error rate      : "
    f"{overall_error_rate*100:.2f}%"
)

print(
    f"Automatic error rate    : "
    f"{automatic_error_rate*100:.2f}%"
)

print(
    f"Relative error reduction: "
    f"{relative_error_reduction:.2f}%"
)


# ============================================================
# RELIABILITY SUMMARY TABLE
# ============================================================

reliability_summary = pd.DataFrame({

    "Group": [
        "Automatic",
        "Review"
    ],

    "Accounts": [
        automatic_count,
        review_count
    ],

    "Coverage (%)": [
        automatic_count /
        len(y_true) * 100,

        review_count /
        len(y_true) * 100
    ],

    "Accuracy (%)": [
        automatic_accuracy,
        review_accuracy
    ],

    "Errors": [
        automatic_errors,
        review_errors
    ]
})

print("\n")
print("=" * 90)
print("RELIABILITY SUMMARY TABLE")
print("=" * 90)

print(
    reliability_summary.to_string(
        index=False,
        formatters={
            "Coverage (%)": "{:.2f}".format,
            "Accuracy (%)": "{:.2f}".format
        }
    )
)


# ============================================================
# FINAL CONCLUSION
# ============================================================

print("\n")
print("=" * 90)
print("FINAL CONCLUSION")
print("=" * 90)

print(
    "\nBehavioral model generalizes strongly to the unseen "
    "Fake Followers category."
)

print(
    "Textual information provides complementary information "
    "but currently reduces unseen-category performance when "
    "directly fused."
)

print(
    "Therefore, behavioral prediction is retained as the "
    "primary decision signal."
)

print(
    "Textual predictions and drift information are used as "
    "supporting evidence for uncertain cases."
)

print(
    f"\n{automatic_count/len(y_true)*100:.2f}% of accounts "
    f"can be processed automatically with "
    f"{automatic_accuracy:.2f}% accuracy."
)

print(
    f"{error_capture:.2f}% of behavioral model errors "
    f"are concentrated in the Review group."
)

print("\n" + "=" * 90)
print("END OF FINAL RESULTS")
print("=" * 90)

==========================================================================================
FINAL EXPERIMENTAL RESULTS
AI-BASED SOCIAL MEDIA BOT DETECTION
==========================================================================================

Evaluation:
------------------------------------------------------------------------------------------
Dataset                 : Cresci-2017
Unseen category         : Fake Followers
Test accounts           : 4285
Known training accounts : 6995
Behavior features       : 15
Fusion weights          : Behavior 0.48 | Text 0.52
Reliability threshold   : 0.95
Drift method            : Mahalanobis + empirical percentile


==========================================================================================
MODEL AND FUSION PERFORMANCE
==========================================================================================
                Experiment Accuracy (%) Precision (%) Recall (%) F1 (%)
             Behavior-only        98.44         99.75      98.16  98.95
                 Text-only        75.01         88.48      76.51  82.06
           Weighted Fusion        86.53         95.21      86.32  90.55
           Adaptive Fusion        86.53         95.21      86.32  97.05
              Gated Fusion        95.61         97.60      96.50  98.04
 Confidence-aware Override        97.11         99.17      96.94  97.13
Conservative Text Override        95.73         97.54      96.72  90.55
    Agreement-based Review        98.44         99.75      98.16  98.95


==========================================================================================
CONFUSION MATRICES
==========================================================================================

Behavior-only:
[[1075    8]
 [  59 3143]]

Text-only:
[[ 764  319]
 [ 752 2450]]

Weighted Fusion:
[[ 944  139]
 [ 438 2764]]

Gated Fusion:
[[1007   76]
 [ 112 3090]]


==========================================================================================
BEHAVIOR vs TEXT ERROR ANALYSIS
==========================================================================================

Behavior correct: 4218
Behavior errors: 67
Text correct: 3214
Text errors: 1071

Behavior wrong + Text correct: 33
Behavior correct + Text wrong: 1037
Both wrong: 34


==========================================================================================
DRIFT ANALYSIS
==========================================================================================

Drift score mean   : 0.7536
Drift score median : 0.7875
Drift score 95th   : 0.9966
Drift score 99th   : 0.9993

Low drift (<0.80): 2185
Review drift (0.80-<0.95): 1257
High drift (>=0.95): 843


==========================================================================================
FINAL RELIABILITY ANALYSIS
==========================================================================================

Automatic decisions : 4088 (95.40%)
Review decisions    : 197 (4.60%)

Automatic accuracy  : 99.63%
Review accuracy     : 73.60%

Total model errors  : 67
Automatic errors    : 15
Review errors       : 52

Error capture by review : 77.61%
Overall error rate      : 1.56%
Automatic error rate    : 0.37%
Relative error reduction: 76.53%


==========================================================================================
RELIABILITY SUMMARY TABLE
==========================================================================================
    Group  Accounts Coverage (%) Accuracy (%)  Errors
Automatic      4088        95.40        99.63      15
   Review       197         4.60        73.60      52


==========================================================================================
FINAL CONCLUSION
==========================================================================================

Behavioral model generalizes strongly to the unseen Fake Followers category.
Textual information provides complementary information but currently reduces unseen-category performance when directly fused.
Therefore, behavioral prediction is retained as the primary decision signal.
Textual predictions and drift information are used as supporting evidence for uncertain cases.

95.40% of accounts can be processed automatically with 99.63% accuracy.
77.61% of behavioral model errors are concentrated in the Review group.

==========================================================================================
END OF FINAL RESULTS
==========================================================================================

In [ ]:
results_table = pd.DataFrame({

    "Experiment": [
        "Behavior-only",
        "Text-only",
        "Weighted Fusion",
        "Adaptive Fusion",
        "Gated Fusion",
        "Confidence-aware Override",
        "Conservative Text Override",
        "Agreement-based Review"
    ],

    "Accuracy (%)": [
        behavior_metrics["Accuracy"],
        text_metrics["Accuracy"],
        weighted_metrics["Accuracy"],
        adaptive_metrics["Accuracy"],
        gated_metrics["Accuracy"],
        confidence_override_metrics["Accuracy"],
        conservative_override_metrics["Accuracy"],
        agreement_review_metrics["Accuracy"]
    ],

    "Precision (%)": [
        behavior_metrics["Precision"],
        text_metrics["Precision"],
        weighted_metrics["Precision"],
        adaptive_metrics["Precision"],
        gated_metrics["Precision"],
        confidence_override_metrics["Precision"],
        conservative_override_metrics["Precision"],
        agreement_review_metrics["Precision"]
    ],

    "Recall (%)": [
        behavior_metrics["Recall"],
        text_metrics["Recall"],
        weighted_metrics["Recall"],
        adaptive_metrics["Recall"],
        gated_metrics["Recall"],
        confidence_override_metrics["Recall"],
        conservative_override_metrics["Recall"],
        agreement_review_metrics["Recall"]
    ],

    "F1 (%)": [
        behavior_metrics["F1"],
        text_metrics["F1"],
        weighted_metrics["F1"],
        adaptive_metrics["F1"],
        gated_metrics["F1"],
        confidence_override_metrics["F1"],
        conservative_override_metrics["F1"],
        agreement_review_metrics["F1"]
    ]
})

In [ ]:
# ============================================================
# EXPORT FINAL BEHAVIORAL RESULTS FOR NOTEBOOK 07
# ============================================================

import os
import pandas as pd
import numpy as np

# Create output directory if needed
os.makedirs("../data/final_results", exist_ok=True)

behavior_results = pd.DataFrame({
    "actual_label": np.asarray(y_test).astype(int),
    "behavior_probability": np.asarray(behavior_test_prob),
    "behavior_prediction": np.asarray(behavior_test_pred).astype(int),
    "drift_score": np.asarray(drift_test_score)
})

behavior_results.to_csv(
    "../data/final_results/behavioral_final_results.csv",
    index=False
)

print("=" * 60)
print("BEHAVIORAL RESULTS EXPORTED")
print("=" * 60)

print("Shape:", behavior_results.shape)
print("\nColumns:")
print(behavior_results.columns.tolist())

print("\nFirst 5 rows:")
print(behavior_results.head())

print("\nSaved to:")
print("../data/final_results/behavioral_final_results.csv")

============================================================
BEHAVIORAL RESULTS EXPORTED
============================================================
Shape: (4285, 4)

Columns:
['actual_label', 'behavior_probability', 'behavior_prediction', 'drift_score']

First 5 rows:
   actual_label  behavior_probability  behavior_prediction  drift_score
0             0              0.000532                    0     0.998392
1             0              0.009074                    0     0.869371
2             0              0.007927                    0     0.971587
3             0              0.007451                    0     0.827019
4             0              0.220586                    0     0.933881

Saved to:
../data/final_results/behavioral_final_results.csv

In [ ]:
# Export behavioral common-test predictions with account IDs

behavior_test_common_results.to_csv(
    "../data/final_results/behavioral_common_test_results.csv",
    index=False
)

print("Saved:", behavior_test_common_results.shape)
print("Columns:", behavior_test_common_results.columns.tolist())

Saved: (1530, 5)
Columns: ['id', 'label', 'account_type', 'behavior_probability', 'behavior_prediction']

In [ ]:
# ================================
# EXPORT LOBO BEHAVIOR RESULTS WITH IDS
# ================================

behavior_lobo_results = lobo_test[
    ["id", "label", "account_type"]
].copy()

behavior_lobo_results["behavior_probability"] = behavior_test_prob
behavior_lobo_results["behavior_prediction"] = (
    behavior_test_prob >= 0.5
).astype(int)

behavior_lobo_results.to_csv(
    "../data/final_results/behavioral_lobo_test_results.csv",
    index=False
)

print("Saved:", behavior_lobo_results.shape)
print("Columns:", behavior_lobo_results.columns.tolist())

display(behavior_lobo_results.head())

Saved: (4285, 5)
Columns: ['id', 'label', 'account_type', 'behavior_probability', 'behavior_prediction']

,id,label,account_type,behavior_probability,behavior_prediction
3,191839658,0,genuine_accounts,0.000532,0
5,2157382005,0,genuine_accounts,0.009074,0
6,1947320929,0,genuine_accounts,0.007927,0
8,1733095801,0,genuine_accounts,0.007451,0
12,21959183,0,genuine_accounts,0.220586,0

In [ ]:
# ================================
# 14. SAVE LOBO TEXT RESULTS WITH IDS
# ================================

text_lobo_results_with_ids = lobo_test[
    ["id", "label", "account_type"]
].copy()

text_lobo_results_with_ids["text_probability"] = text_test_prob
text_lobo_results_with_ids["text_prediction"] = (
    text_test_prob >= 0.5
).astype(int)

text_lobo_results_with_ids.to_csv(
    "../data/final_results/text_lobo_test_results_with_ids.csv",
    index=False
)

print("Saved:", text_lobo_results_with_ids.shape)
print("Columns:", text_lobo_results_with_ids.columns.tolist())

display(text_lobo_results_with_ids.head())

Saved: (4285, 5)
Columns: ['id', 'label', 'account_type', 'text_probability', 'text_prediction']

            id  label      account_type  text_probability  text_prediction
3    191839658      0  genuine_accounts          0.038584                0
5   2157382005      0  genuine_accounts          0.023926                0
6   1947320929      0  genuine_accounts          0.076167                0
8   1733095801      0  genuine_accounts          0.009980                0
12    21959183      0  genuine_accounts          0.206501                0