In [1]:
import os

print("Current directory:")
print(os.getcwd())

print("\nFiles/folders:")
for item in os.listdir():
    print(item)

Current directory:
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\notebooks

Files/folders:
01_dataset_cleaning.ipynb
02_feature_engineering.ipynb
03_baseline_model.ipynb
04_behavioral_neural_network.ipynb
05_textual_model.ipynb

In [2]:
import os

project_root = os.path.dirname(os.getcwd())

print("Project root:")
print(project_root)

print("\nProject files/folders:")
for root, dirs, files in os.walk(project_root):
    # Skip virtual environments and git folder
    dirs[:] = [d for d in dirs if d not in [".git", ".venv_nn", "__pycache__"]]
    
    for file in files:
        print(os.path.join(root, file))

Project root:
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection

Project files/folders:
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\.gitignore
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\bot output.png
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\bot output2.png
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\output3.png
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\output4.png
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\README.md
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\requirements.txt
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\processed\behavior_features.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\READ.ME
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\crowdflower_results.csv\crowdflower_results_aggregated.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\crowdflower_results.csv\crowdflower_results_contributors.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\crowdflower_results.csv\crowdflower_results_detailed.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\fake_followers.csv\fake_followers.csv\tweets.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\fake_followers.csv\fake_followers.csv\users.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\fake_followers.csv\__MACOSX\._fake_followers.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\fake_followers.csv\__MACOSX\fake_followers.csv\._tweets.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\fake_followers.csv\__MACOSX\fake_followers.csv\._users.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\genuine_accounts.csv\tweets.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\genuine_accounts.csv\users.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\social_spambots_1.csv\social_spambots_1.csv\tweets.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\social_spambots_1.csv\social_spambots_1.csv\users.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\social_spambots_2.csv\social_spambots_2.csv\tweets.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\social_spambots_2.csv\social_spambots_2.csv\users.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\social_spambots_3.csv\social_spambots_3.csv\tweets.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\social_spambots_3.csv\social_spambots_3.csv\users.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\traditional_spambots_1.csv\traditional_spambots_1.csv\tweets.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\traditional_spambots_1.csv\traditional_spambots_1.csv\users.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\traditional_spambots_2.csv\traditional_spambots_2.csv\users.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\traditional_spambots_3.csv\traditional_spambots_3.csv\users.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\traditional_spambots_4.csv\traditional_spambots_4.csv\users.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\notebooks\01_dataset_cleaning.ipynb
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\notebooks\02_feature_engineering.ipynb
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\notebooks\03_baseline_model.ipynb
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\notebooks\04_behavioral_neural_network.ipynb
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\notebooks\05_textual_model.ipynb

In [4]:
import pandas as pd
import os

raw_path = os.path.join(
    project_root,
    "data", "raw", "datasets_full.csv"
)

tweet_files = [
    "fake_followers.csv/fake_followers.csv/tweets.csv",
    "genuine_accounts.csv/tweets.csv",
    "social_spambots_1.csv/social_spambots_1.csv/tweets.csv",
    "social_spambots_2.csv/social_spambots_2.csv/tweets.csv",
    "social_spambots_3.csv/social_spambots_3.csv/tweets.csv",
    "traditional_spambots_1.csv/traditional_spambots_1.csv/tweets.csv",
    "traditional_spambots_2.csv/traditional_spambots_2.csv/tweets.csv",
    "traditional_spambots_3.csv/traditional_spambots_3.csv/tweets.csv",
    "traditional_spambots_4.csv/traditional_spambots_4.csv/tweets.csv",
]

for relative_path in tweet_files:
    path = os.path.join(raw_path, relative_path)

    print("\n" + "="*70)
    print(relative_path)

    if not os.path.exists(path):
        print("FILE NOT FOUND")
        continue

    try:
        df_temp = pd.read_csv(
            path,
            encoding="latin1"
        )

        print("Shape:", df_temp.shape)
        print("Columns:", df_temp.columns.tolist())
        display(df_temp.head(2))

    except Exception as e:
        print("ERROR:", type(e).__name__)
        print(e)

======================================================================
fake_followers.csv/fake_followers.csv/tweets.csv
Shape: (196027, 23)
Columns: ['created_at', 'id', 'text', 'source', 'user_id', 'truncated', 'in_reply_to_status_id', 'in_reply_to_user_id', 'in_reply_to_screen_name', 'retweeted_status_id', 'geo', 'place', 'contributors', 'retweet_count', 'reply_count', 'favorite_count', 'favorited', 'retweeted', 'possibly_sensitive', 'num_hashtags', 'num_urls', 'num_mentions', 'timestamp']

C:\Users\namit\AppData\Local\Temp\ipykernel_8248\3725853827.py:32: DtypeWarning: Columns (0: in_reply_to_screen_name, 1: place) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(

,created_at,id,text,source,user_id,truncated,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,retweeted_status_id,...,retweet_count,reply_count,favorite_count,favorited,retweeted,possibly_sensitive,num_hashtags,num_urls,num_mentions,timestamp
0,Sat Apr 20 13:19:19 +0000 2013,325599560959393793,https://t.co/iocNIgHxXH. @LovesOfaLDNgirl her...,"<a href=""http://twitter.com/download/iphone"" r...",10935572,NaN,0,0,NaN,NaN,...,0,0,0,NaN,NaN,NaN,0,1,1,2013-04-20 15:19:19
1,Tue Apr 16 19:31:39 +0000 2013,324243711443730434,Well done hubby @Allan_76 http://t.co/AaeTwLucUG,"<a href=""http://instagram.com"" rel=""nofollow"">...",10935572,NaN,0,0,NaN,NaN,...,0,0,0,NaN,NaN,NaN,0,1,1,2013-04-16 21:31:39

======================================================================
genuine_accounts.csv/tweets.csv

C:\Users\namit\AppData\Local\Temp\ipykernel_8248\3725853827.py:32: DtypeWarning: Columns (0: id) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(

Shape: (2839362, 25)
Columns: ['id', 'text', 'source', 'user_id', 'truncated', 'in_reply_to_status_id', 'in_reply_to_user_id', 'in_reply_to_screen_name', 'retweeted_status_id', 'geo', 'place', 'contributors', 'retweet_count', 'reply_count', 'favorite_count', 'favorited', 'retweeted', 'possibly_sensitive', 'num_hashtags', 'num_urls', 'num_mentions', 'created_at', 'timestamp', 'crawled_at', 'updated']

,id,text,source,user_id,truncated,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,retweeted_status_id,geo,...,favorited,retweeted,possibly_sensitive,num_hashtags,num_urls,num_mentions,created_at,timestamp,crawled_at,updated
0,593932392663912449,RT @morningJewshow: Speaking about Jews and co...,"<a href=""http://tapbots.com/tweetbot"" rel=""nof...",678033.0,NaN,0.0,0.0,NaN,5.939322e+17,NaN,...,NaN,NaN,NaN,0.0,0.0,1.0,Fri May 01 00:18:11 +0000 2015,2015-05-01 02:18:11,2015-05-01 12:57:19,2015-05-01 12:57:19
1,593895316719423488,This age/face recognition thing..no reason pla...,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",678033.0,NaN,0.0,0.0,NaN,0.000000e+00,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,Thu Apr 30 21:50:52 +0000 2015,2015-04-30 23:50:52,2015-05-01 12:57:19,2015-05-01 12:57:19

======================================================================
social_spambots_1.csv/social_spambots_1.csv/tweets.csv

C:\Users\namit\AppData\Local\Temp\ipykernel_8248\3725853827.py:32: DtypeWarning: Columns (0: place) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(

Shape: (1610034, 25)
Columns: ['id', 'text', 'source', 'user_id', 'truncated', 'in_reply_to_status_id', 'in_reply_to_user_id', 'in_reply_to_screen_name', 'retweeted_status_id', 'geo', 'place', 'contributors', 'retweet_count', 'reply_count', 'favorite_count', 'favorited', 'retweeted', 'possibly_sensitive', 'num_hashtags', 'num_urls', 'num_mentions', 'created_at', 'timestamp', 'crawled_at', 'updated']

,id,text,source,user_id,truncated,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,retweeted_status_id,geo,...,favorited,retweeted,possibly_sensitive,num_hashtags,num_urls,num_mentions,created_at,timestamp,crawled_at,updated
0,532627591686275072,I Pooh - In silenzio 1968 http://t.co/ahvQxUqTws,"<a href=""http://www.facebook.com/twitter"" rel=...",24858289,NaN,0,0,NaN,0,NaN,...,NaN,NaN,NaN,0,1,0,Wed Nov 12 20:14:48 +0000 2014,2014-11-12 21:14:48,2014-11-12 21:44:09,2014-11-12 21:44:09
1,532624255058706432,http://t.co/HyI5EQKz6Q,"<a href=""http://www.facebook.com/twitter"" rel=...",24858289,NaN,0,0,NaN,0,NaN,...,NaN,NaN,NaN,0,1,0,Wed Nov 12 20:01:32 +0000 2014,2014-11-12 21:01:32,2014-11-12 21:44:09,2014-11-12 21:44:09

======================================================================
social_spambots_2.csv/social_spambots_2.csv/tweets.csv

C:\Users\namit\AppData\Local\Temp\ipykernel_8248\3725853827.py:32: DtypeWarning: Columns (0: place) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(

Shape: (428542, 25)
Columns: ['id', 'text', 'source', 'user_id', 'truncated', 'in_reply_to_status_id', 'in_reply_to_user_id', 'in_reply_to_screen_name', 'retweeted_status_id', 'geo', 'place', 'contributors', 'retweet_count', 'reply_count', 'favorite_count', 'favorited', 'retweeted', 'possibly_sensitive', 'num_hashtags', 'num_urls', 'num_mentions', 'created_at', 'timestamp', 'crawled_at', 'updated']

,id,text,source,user_id,truncated,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,retweeted_status_id,geo,...,favorited,retweeted,possibly_sensitive,num_hashtags,num_urls,num_mentions,created_at,timestamp,crawled_at,updated
0,532613365307547649,Mother daughter java time http://t.co/iPNFLGY2dA,"<a href=""http://instagram.com"" rel=""nofollow"">...",16195340,NaN,0,0,NaN,0,NaN,...,NaN,NaN,1.0,0,1,0,Wed Nov 12 19:18:16 +0000 2014,2014-11-12 20:18:16,2014-11-12 21:33:09,2014-11-12 21:33:09
1,532596235296071682,#NSFW XXX pics and preview vids from the Den o...,"<a href=""http://gremln.com"" rel=""nofollow"">Gre...",16195340,NaN,0,0,NaN,0,NaN,...,NaN,NaN,1.0,3,1,0,Wed Nov 12 18:10:12 +0000 2014,2014-11-12 19:10:12,2014-11-12 21:33:09,2014-11-12 21:33:09

======================================================================
social_spambots_3.csv/social_spambots_3.csv/tweets.csv

C:\Users\namit\AppData\Local\Temp\ipykernel_8248\3725853827.py:32: DtypeWarning: Columns (0: in_reply_to_screen_name, 1: place) have mixed types. Specify dtype option on import or set low_memory=False.
  df_temp = pd.read_csv(

Shape: (1418557, 25)
Columns: ['id', 'text', 'source', 'user_id', 'truncated', 'in_reply_to_status_id', 'in_reply_to_user_id', 'in_reply_to_screen_name', 'retweeted_status_id', 'geo', 'place', 'contributors', 'retweet_count', 'reply_count', 'favorite_count', 'favorited', 'retweeted', 'possibly_sensitive', 'num_hashtags', 'num_urls', 'num_mentions', 'created_at', 'timestamp', 'crawled_at', 'updated']

,id,text,source,user_id,truncated,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,retweeted_status_id,geo,...,favorited,retweeted,possibly_sensitive,num_hashtags,num_urls,num_mentions,created_at,timestamp,crawled_at,updated
0,532626057124651008,Am postat o fotografie nouÄ pe Facebook http:...,"<a href=""http://www.facebook.com/twitter"" rel=...",16282004,NaN,0,0,NaN,0,NaN,...,NaN,NaN,NaN,0,1,0,Wed Nov 12 20:08:42 +0000 2014,2014-11-12 21:08:42,2014-11-12 21:33:55,2014-11-12 21:33:55
1,532625740693766144,Am postat o fotografie nouÄ pe Facebook http:...,"<a href=""http://www.facebook.com/twitter"" rel=...",16282004,NaN,0,0,NaN,0,NaN,...,NaN,NaN,NaN,0,1,0,Wed Nov 12 20:07:26 +0000 2014,2014-11-12 21:07:26,2014-11-12 21:33:55,2014-11-12 21:33:55

======================================================================
traditional_spambots_1.csv/traditional_spambots_1.csv/tweets.csv
Shape: (145094, 25)
Columns: ['id', 'text', 'source', 'user_id', 'truncated', 'in_reply_to_status_id', 'in_reply_to_user_id', 'in_reply_to_screen_name', 'retweeted_status_id', 'geo', 'place', 'contributors', 'retweet_count', 'reply_count', 'favorite_count', 'favorited', 'retweeted', 'possibly_sensitive', 'num_hashtags', 'num_urls', 'num_mentions', 'created_at', 'timestamp', 'crawled_at', 'updated']

,id,text,source,user_id,truncated,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,retweeted_status_id,geo,...,favorited,retweeted,possibly_sensitive,num_hashtags,num_urls,num_mentions,created_at,timestamp,crawled_at,updated
0,22642586115,CPPRI Recruitment 2010 at http://ping.fm/yp8zH,"<a href=""http://www.ping.fm/"" rel=""nofollow"">P...",7248952,NaN,0,0,NaN,0,NaN,...,NaN,NaN,NaN,0,1,0,1283282654000L,2010-08-31 21:24:14,0000-00-00 00:00:00,2014-04-16 23:57:17
1,22642583483,National Games Secretariat Recruitment 2010 :...,"<a href=""http://www.ping.fm/"" rel=""nofollow"">P...",7248952,NaN,0,0,NaN,0,NaN,...,NaN,NaN,NaN,0,1,0,1283282651000L,2010-08-31 21:24:11,0000-00-00 00:00:00,2014-04-16 23:57:17

======================================================================
traditional_spambots_2.csv/traditional_spambots_2.csv/tweets.csv
FILE NOT FOUND

======================================================================
traditional_spambots_3.csv/traditional_spambots_3.csv/tweets.csv
FILE NOT FOUND

======================================================================
traditional_spambots_4.csv/traditional_spambots_4.csv/tweets.csv
FILE NOT FOUND

In [5]:
import pandas as pd
import os

# Store loaded tweet data
tweet_data = []

for relative_path in tweet_files:
    path = os.path.join(raw_path, relative_path)

    if not os.path.exists(path):
        continue

    print(f"\nLoading: {relative_path}")

    try:
        # Read only columns useful for textual analysis
        df_temp = pd.read_csv(
            path,
            encoding="latin1",
            low_memory=False,
            usecols=lambda col: col in [
                "text",
                "user_id",
                "created_at",
                "timestamp"
            ]
        )

        # Remove rows without text
        df_temp = df_temp.dropna(subset=["text"])

        # Identify account type from file path
        account_type = relative_path.split("/")[0].replace(".csv", "")

        df_temp["account_type"] = account_type

        tweet_data.append(df_temp)

        print("Tweets loaded:", len(df_temp))

    except Exception as e:
        print("ERROR:", type(e).__name__)
        print(e)

print("\n" + "="*70)
print("Files successfully loaded:", len(tweet_data))

Loading: fake_followers.csv/fake_followers.csv/tweets.csv
Tweets loaded: 196007

Loading: genuine_accounts.csv/tweets.csv
Tweets loaded: 2826790

Loading: social_spambots_1.csv/social_spambots_1.csv/tweets.csv
Tweets loaded: 1609944

Loading: social_spambots_2.csv/social_spambots_2.csv/tweets.csv
Tweets loaded: 428221

Loading: social_spambots_3.csv/social_spambots_3.csv/tweets.csv
Tweets loaded: 1418553

Loading: traditional_spambots_1.csv/traditional_spambots_1.csv/tweets.csv
Tweets loaded: 145094

======================================================================
Files successfully loaded: 6

In [6]:
print("Tweet datasets loaded:")
for i, df_temp in enumerate(tweet_data):
    print(i, df_temp.shape, df_temp["account_type"].iloc[0])

Tweet datasets loaded:
0 (196007, 5) fake_followers
1 (2826790, 5) genuine_accounts
2 (1609944, 5) social_spambots_1
3 (428221, 5) social_spambots_2
4 (1418553, 5) social_spambots_3
5 (145094, 5) traditional_spambots_1

In [7]:
print("=" * 70)
print("SEARCHING FOR ALL TWEET FILES")
print("=" * 70)

for root, dirs, files in os.walk(raw_path):
    for file in files:
        if file.lower() == "tweets.csv":
            full_path = os.path.join(root, file)
            print(full_path)

======================================================================
SEARCHING FOR ALL TWEET FILES
======================================================================
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\fake_followers.csv\fake_followers.csv\tweets.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\genuine_accounts.csv\tweets.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\social_spambots_1.csv\social_spambots_1.csv\tweets.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\social_spambots_2.csv\social_spambots_2.csv\tweets.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\social_spambots_3.csv\social_spambots_3.csv\tweets.csv
c:\Users\namit\OneDrive\Desktop\AI_Bot_Detection\data\raw\datasets_full.csv\traditional_spambots_1.csv\traditional_spambots_1.csv\tweets.csv

In [8]:
dataset_info = {
    "fake_followers": 1,
    "genuine_accounts": 0,
    "social_spambots_1": 1,
    "social_spambots_2": 1,
    "social_spambots_3": 1,
    "traditional_spambots_1": 1
}

print("Available textual datasets:")
for name, label in dataset_info.items():
    print(f"{name:25} → label {label}")

Available textual datasets:
fake_followers            → label 1
genuine_accounts          → label 0
social_spambots_1         → label 1
social_spambots_2         → label 1
social_spambots_3         → label 1
traditional_spambots_1    → label 1

In [9]:
# Combine tweets from the available datasets
# while keeping only the information needed for the textual model.

text_dfs = []

for df_temp in tweet_data:
    account_type = df_temp["account_type"].iloc[0]
    label = dataset_info[account_type]

    temp = df_temp[["user_id", "text"]].copy()
    temp["label"] = label
    temp["account_type"] = account_type

    # Remove missing/empty tweets
    temp["text"] = temp["text"].astype(str).str.strip()
    temp = temp[temp["text"].str.len() > 0]

    text_dfs.append(temp)

text_tweets = pd.concat(text_dfs, ignore_index=True)

print("Combined tweet dataset shape:", text_tweets.shape)
print("\nLabel distribution:")
print(text_tweets["label"].value_counts())

print("\nAccount type distribution:")
print(text_tweets["account_type"].value_counts())

print("\nUnique accounts:", text_tweets["user_id"].nunique())

display(text_tweets.head())

Combined tweet dataset shape: (6624609, 4)

Label distribution:
label
1    3797819
0    2826790
Name: count, dtype: int64

Account type distribution:
account_type
genuine_accounts          2826790
social_spambots_1         1609944
social_spambots_3         1418553
social_spambots_2          428221
fake_followers             196007
traditional_spambots_1     145094
Name: count, dtype: int64

Unique accounts: 10197

,user_id,text,label,account_type
0,10935572.0,https://t.co/iocNIgHxXH. @LovesOfaLDNgirl her...,1,fake_followers
1,10935572.0,Well done hubby @Allan_76 http://t.co/AaeTwLucUG,1,fake_followers
2,10935572.0,Two years with my lovely husband - thank you f...,1,fake_followers
3,10935572.0,Sorry bunny about your ears but I was hungry.....,1,fake_followers
4,10935572.0,"Small man, big drink @Allan_76 http://t.co/4NU...",1,fake_followers

In [10]:
account_labels = (
    text_tweets
    .groupby("user_id")
    .agg(
        label=("label", "first"),
        account_type=("account_type", "first"),
        tweet_count=("text", "count")
    )
    .reset_index()
)

print("Account-level dataset shape:", account_labels.shape)

print("\nAccount labels:")
print(account_labels["label"].value_counts())

print("\nAccount types:")
print(account_labels["account_type"].value_counts())

print("\nTweets per account:")
print(account_labels["tweet_count"].describe())

Account-level dataset shape: (10197, 4)

Account labels:
label
1    9114
0    1083
Name: count, dtype: int64

Account types:
account_type
social_spambots_2         3457
fake_followers            3202
genuine_accounts          1083
traditional_spambots_1    1000
social_spambots_1          991
social_spambots_3          464
Name: count, dtype: int64

Tweets per account:
count    10197.000000
mean       649.662548
std       1096.342282
min          1.000000
25%         28.000000
50%         97.000000
75%        605.000000
max       3383.000000
Name: tweet_count, dtype: float64

In [12]:
import pandas as pd
import os

behavior_path = os.path.join(
    project_root,
    "data",
    "processed",
    "behavior_features.csv"
)

behavior_df = pd.read_csv(behavior_path)

print("Behavioral dataset shape:", behavior_df.shape)
print("Columns:")
print(behavior_df.columns.tolist())

display(behavior_df.head())

Behavioral dataset shape: (14368, 20)
Columns:
['id', 'account_type', 'label', 'statuses_count', 'followers_count', 'friends_count', 'favourites_count', 'listed_count', 'created_at', 'updated', 'account_age_days', 'statuses_per_day', 'followers_friends_ratio', 'friends_followers_ratio', 'favorites_per_status', 'log_statuses_count', 'log_followers_count', 'log_friends_count', 'log_favourites_count', 'log_listed_count']

,id,account_type,label,statuses_count,followers_count,friends_count,favourites_count,listed_count,created_at,updated,account_age_days,statuses_per_day,followers_friends_ratio,friends_followers_ratio,favorites_per_status,log_statuses_count,log_followers_count,log_friends_count,log_favourites_count,log_listed_count
0,1502026416,genuine_accounts,0,2177,208,332,265,1,Tue Jun 11 11:20:35 +0000 2013,2016-03-15 15:53:47,1008.189722,2.159316,0.626506,1.596154,0.121727,7.686162,5.342334,5.808142,5.583496,0.693147
1,2492782375,genuine_accounts,0,2660,330,485,3972,5,Tue May 13 10:37:57 +0000 2014,2016-03-15 15:53:48,672.219340,3.957042,0.680412,1.469697,1.493233,7.886457,5.802118,6.186209,8.287277,1.791759
2,293212315,genuine_accounts,0,1254,166,177,1185,0,Wed May 04 23:30:37 +0000 2011,2016-03-15 15:53:48,1776.682766,0.705810,0.937853,1.066265,0.944976,7.134891,5.117994,5.181784,7.078342,0.000000
3,191839658,genuine_accounts,0,202968,2248,981,60304,101,Fri Sep 17 14:02:10 +0000 2010,2016-03-15 15:53:48,2006.077523,101.176549,2.291539,0.436388,0.297111,12.220809,7.718241,6.889591,11.007170,4.624973
4,3020965143,genuine_accounts,0,82,21,79,5,0,Fri Feb 06 04:10:49 +0000 2015,2016-03-15 15:53:48,403.488183,0.203228,0.265823,3.761905,0.060976,4.418841,3.091042,4.382027,1.791759,0.000000

In [13]:
print("Behavioral accounts:", behavior_df["id"].nunique())
print("Textual accounts:", text_tweets["user_id"].nunique())

print("\nBehavior ID type:")
print(behavior_df["id"].dtype)

print("\nText user_id type:")
print(text_tweets["user_id"].dtype)

Behavioral accounts: 14368
Textual accounts: 10197

Behavior ID type:
int64

Text user_id type:
float64

In [14]:
# Normalize account IDs before matching

behavior_ids = set(
    behavior_df["id"]
    .astype("int64")
    .astype(str)
)

text_tweets["user_id"] = pd.to_numeric(
    text_tweets["user_id"],
    errors="coerce"
)

text_tweets = text_tweets.dropna(subset=["user_id"])

text_tweets["user_id"] = (
    text_tweets["user_id"]
    .astype("int64")
    .astype(str)
)

print("Behavioral accounts:", len(behavior_ids))
print("Textual accounts:", text_tweets["user_id"].nunique())

matched_ids = set(text_tweets["user_id"]) & behavior_ids

print("Matched accounts:", len(matched_ids))
print(
    "Match percentage:",
    round(len(matched_ids) / len(behavior_ids) * 100, 2),
    "%"
)

Behavioral accounts: 14368
Textual accounts: 10197
Matched accounts: 10197
Match percentage: 70.97 %

In [15]:
# Create account-level textual dataset
# using behavioral labels as the ground truth

account_labels = (
    behavior_df[["id", "label", "account_type"]]
    .copy()
)

account_labels["id"] = (
    account_labels["id"]
    .astype("int64")
    .astype(str)
)

text_account_data = (
    text_tweets
    .groupby("user_id")
    .agg(
        tweet_count=("text", "count"),
        text=("text", lambda x: " ".join(x))
    )
    .reset_index()
)

# Match textual accounts with behavioral labels
text_account_data = text_account_data.merge(
    account_labels,
    left_on="user_id",
    right_on="id",
    how="inner"
)

print("Final account-level textual dataset:")
print(text_account_data.shape)

print("\nLabels:")
print(text_account_data["label"].value_counts())

print("\nAccount types:")
print(text_account_data["account_type"].value_counts())

print("\nTweets per account:")
print(text_account_data["tweet_count"].describe())

Final account-level textual dataset:
(10197, 6)

Labels:
label
1    9114
0    1083
Name: count, dtype: int64

Account types:
account_type
social_spambots_2         3457
fake_followers            3202
genuine_accounts          1083
traditional_spambots_1    1000
social_spambots_1          991
social_spambots_3          464
Name: count, dtype: int64

Tweets per account:
count    10197.000000
mean       649.662548
std       1096.342282
min          1.000000
25%         28.000000
50%         97.000000
75%        605.000000
max       3383.000000
Name: tweet_count, dtype: float64

In [16]:
# ============================================================
# CONTROLLED TWEET SAMPLING
# Maximum 100 tweets per account
# ============================================================

MAX_TWEETS_PER_ACCOUNT = 100

# Keep only the columns we need
controlled_tweets = text_tweets[
    ["user_id", "text", "label", "account_type"]
].copy()

# Shuffle tweets so accounts with many tweets don't always
# contribute only their earliest tweets
controlled_tweets = controlled_tweets.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

# Take at most 100 tweets per account
controlled_tweets = (
    controlled_tweets
    .groupby("user_id", group_keys=False)
    .head(MAX_TWEETS_PER_ACCOUNT)
    .reset_index(drop=True)
)

print("=" * 70)
print("CONTROLLED TEXTUAL DATASET")
print("=" * 70)

print("\nShape:", controlled_tweets.shape)

print("\nTweets per account:")
print(
    controlled_tweets
    .groupby("user_id")
    .size()
    .describe()
)

print("\nMaximum tweets per account:",
      controlled_tweets.groupby("user_id").size().max())

print("\nUnique accounts:",
      controlled_tweets["user_id"].nunique())

print("\nLabels:")
print(controlled_tweets["label"].value_counts())

print("\nAccount types:")
print(controlled_tweets["account_type"].value_counts())

======================================================================
CONTROLLED TEXTUAL DATASET
======================================================================

Shape: (714839, 4)

Tweets per account:
count    10197.000000
mean        70.102873
std         37.267681
min          1.000000
25%         28.000000
50%         97.000000
75%        100.000000
max        100.000000
dtype: float64

Maximum tweets per account: 100

Unique accounts: 10197

Labels:
label
1    607687
0    107152
Name: count, dtype: int64

Account types:
account_type
social_spambots_2         328706
genuine_accounts          107152
fake_followers             99850
social_spambots_1          99100
social_spambots_3          46400
traditional_spambots_1     33631
Name: count, dtype: int64

In [17]:
# ============================================================
# CREATE ACCOUNT-LEVEL TEXT REPRESENTATION
# ============================================================

account_text = (
    controlled_tweets
    .groupby("user_id")
    .agg(
        text=("text", lambda x: " ".join(x)),
        label=("label", "first"),
        account_type=("account_type", "first"),
        tweet_count_used=("text", "count")
    )
    .reset_index()
)

print("=" * 70)
print("FINAL CONTROLLED ACCOUNT-LEVEL TEXT DATASET")
print("=" * 70)

print("\nShape:", account_text.shape)

print("\nLabels:")
print(account_text["label"].value_counts())

print("\nAccount types:")
print(account_text["account_type"].value_counts())

print("\nTweets used per account:")
print(account_text["tweet_count_used"].describe())

display(account_text.head())

======================================================================
FINAL CONTROLLED ACCOUNT-LEVEL TEXT DATASET
======================================================================

Shape: (10197, 5)

Labels:
label
1    9114
0    1083
Name: count, dtype: int64

Account types:
account_type
social_spambots_2         3457
fake_followers            3202
genuine_accounts          1083
traditional_spambots_1    1000
social_spambots_1          991
social_spambots_3          464
Name: count, dtype: int64

Tweets used per account:
count    10197.000000
mean        70.102873
std         37.267681
min          1.000000
25%         28.000000
50%         97.000000
75%        100.000000
max        100.000000
Name: tweet_count_used, dtype: float64

,user_id,text,label,account_type,tweet_count_used
0,100024367,"Prepare-se para o apocalipse: vem ai, Blog Cro...",1,traditional_spambots_1,35
1,100065024,BOMBA AGORA SEU TWITTER com milhares de novos ...,1,traditional_spambots_1,15
2,100219528,http://t.co/Fd4XyQFK Hey everyone! I just made...,1,fake_followers,6
3,1002202471,"You call the driver of a car a motorist, until...",1,social_spambots_3,100
4,100257788,#pmtamsc boa noite pro @_mend3 O// RT @webdica...,1,traditional_spambots_1,58

In [18]:
from sklearn.model_selection import train_test_split

# ============================================================
# ACCOUNT-LEVEL TRAIN / VALIDATION / TEST SPLIT
# ============================================================

# First: 70% train, 30% temporary
train_text, temp_text = train_test_split(
    account_text,
    test_size=0.30,
    stratify=account_text["label"],
    random_state=42
)

# Second: split the temporary 30% into
# 15% validation and 15% test
val_text, test_text = train_test_split(
    temp_text,
    test_size=0.50,
    stratify=temp_text["label"],
    random_state=42
)

print("=" * 70)
print("ACCOUNT-LEVEL TEXT SPLIT")
print("=" * 70)

print("\nTrain shape:", train_text.shape)
print("Validation shape:", val_text.shape)
print("Test shape:", test_text.shape)

print("\nTrain labels:")
print(train_text["label"].value_counts())

print("\nValidation labels:")
print(val_text["label"].value_counts())

print("\nTest labels:")
print(test_text["label"].value_counts())

print("\nTotal accounts:",
      len(train_text) + len(val_text) + len(test_text))

# Verify that no account appears in multiple splits
train_ids = set(train_text["user_id"])
val_ids = set(val_text["user_id"])
test_ids = set(test_text["user_id"])

print("\nAccount overlap checks:")
print("Train ∩ Validation:", len(train_ids & val_ids))
print("Train ∩ Test:", len(train_ids & test_ids))
print("Validation ∩ Test:", len(val_ids & test_ids))

======================================================================
ACCOUNT-LEVEL TEXT SPLIT
======================================================================

Train shape: (7137, 5)
Validation shape: (1530, 5)
Test shape: (1530, 5)

Train labels:
label
1    6379
0     758
Name: count, dtype: int64

Validation labels:
label
1    1368
0     162
Name: count, dtype: int64

Test labels:
label
1    1367
0     163
Name: count, dtype: int64

Total accounts: 10197

Account overlap checks:
Train ∩ Validation: 0
Train ∩ Test: 0
Validation ∩ Test: 0

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

# ============================================================
# TF-IDF TEXT REPRESENTATION
# ============================================================

tfidf = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

# Fit ONLY on training accounts
X_train_tfidf = tfidf.fit_transform(train_text["text"])

# Transform validation and test using the SAME vectorizer
X_val_tfidf = tfidf.transform(val_text["text"])
X_test_tfidf = tfidf.transform(test_text["text"])

y_train_text = train_text["label"]
y_val_text = val_text["label"]
y_test_text = test_text["label"]

print("=" * 70)
print("TF-IDF REPRESENTATION")
print("=" * 70)

print("\nVocabulary size:", len(tfidf.vocabulary_))

print("\nTrain TF-IDF shape:", X_train_tfidf.shape)
print("Validation TF-IDF shape:", X_val_tfidf.shape)
print("Test TF-IDF shape:", X_test_tfidf.shape)

print("\nSparse matrix:")
print("Train:", type(X_train_tfidf))
print("Validation:", type(X_val_tfidf))
print("Test:", type(X_test_tfidf))

======================================================================
TF-IDF REPRESENTATION
======================================================================

Vocabulary size: 20000

Train TF-IDF shape: (7137, 20000)
Validation TF-IDF shape: (1530, 20000)
Test TF-IDF shape: (1530, 20000)

Sparse matrix:
Train: <class 'scipy.sparse._csr.csr_matrix'>
Validation: <class 'scipy.sparse._csr.csr_matrix'>
Test: <class 'scipy.sparse._csr.csr_matrix'>

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# ============================================================
# TF-IDF + LOGISTIC REGRESSION
# ============================================================

text_lr = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

text_lr.fit(X_train_tfidf, y_train_text)

# Validation predictions
val_pred = text_lr.predict(X_val_tfidf)

print("=" * 70)
print("TEXTUAL BASELINE — TF-IDF + LOGISTIC REGRESSION")
print("=" * 70)

print("\nValidation Performance")
print("-" * 50)

print(f"Accuracy : {accuracy_score(y_val_text, val_pred):.4f}")
print(f"Precision: {precision_score(y_val_text, val_pred):.4f}")
print(f"Recall   : {recall_score(y_val_text, val_pred):.4f}")
print(f"F1-Score : {f1_score(y_val_text, val_pred):.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_val_text,
        val_pred,
        target_names=["Genuine", "Bot"]
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_val_text, val_pred))

======================================================================
TEXTUAL BASELINE — TF-IDF + LOGISTIC REGRESSION
======================================================================

Validation Performance
--------------------------------------------------
Accuracy : 0.9784
Precision: 1.0000
Recall   : 0.9759
F1-Score : 0.9878

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.83      1.00      0.91       162
         Bot       1.00      0.98      0.99      1368

    accuracy                           0.98      1530
   macro avg       0.92      0.99      0.95      1530
weighted avg       0.98      0.98      0.98      1530


Confusion Matrix:
[[ 162    0]
 [  33 1335]]

In [21]:
from sklearn.svm import LinearSVC

# ============================================================
# TF-IDF + LINEAR SVM
# ============================================================

text_svm = LinearSVC(
    class_weight="balanced",
    random_state=42
)

text_svm.fit(X_train_tfidf, y_train_text)

# Validation predictions
svm_val_pred = text_svm.predict(X_val_tfidf)

print("=" * 70)
print("TEXTUAL BASELINE — TF-IDF + LINEAR SVM")
print("=" * 70)

print("\nValidation Performance")
print("-" * 50)

print(f"Accuracy : {accuracy_score(y_val_text, svm_val_pred):.4f}")
print(f"Precision: {precision_score(y_val_text, svm_val_pred):.4f}")
print(f"Recall   : {recall_score(y_val_text, svm_val_pred):.4f}")
print(f"F1-Score : {f1_score(y_val_text, svm_val_pred):.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_val_text,
        svm_val_pred,
        target_names=["Genuine", "Bot"]
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_val_text, svm_val_pred))

======================================================================
TEXTUAL BASELINE — TF-IDF + LINEAR SVM
======================================================================

Validation Performance
--------------------------------------------------
Accuracy : 0.9810
Precision: 0.9963
Recall   : 0.9825
F1-Score : 0.9893

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.87      0.97      0.92       162
         Bot       1.00      0.98      0.99      1368

    accuracy                           0.98      1530
   macro avg       0.93      0.98      0.95      1530
weighted avg       0.98      0.98      0.98      1530


Confusion Matrix:
[[ 157    5]
 [  24 1344]]

In [22]:
# ============================================================
# NEURAL TEXT MODEL — PREPARE ACCOUNT TEXT
# ============================================================

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

print("=" * 70)
print("PREPARING TEXT FOR NEURAL MODEL")
print("=" * 70)

# Maximum vocabulary
MAX_WORDS = 30000

# Maximum sequence length
MAX_LEN = 300

# Tokenizer
tokenizer = Tokenizer(
    num_words=MAX_WORDS,
    oov_token="<OOV>"
)

# IMPORTANT:
# Fit tokenizer ONLY on training accounts
tokenizer.fit_on_texts(train_text["text"])

# Convert text → integer sequences
X_train_seq = tokenizer.texts_to_sequences(train_text["text"])
X_val_seq = tokenizer.texts_to_sequences(val_text["text"])
X_test_seq = tokenizer.texts_to_sequences(test_text["text"])

# Pad sequences
X_train_pad = pad_sequences(
    X_train_seq,
    maxlen=MAX_LEN,
    padding="post",
    truncating="post"
)

X_val_pad = pad_sequences(
    X_val_seq,
    maxlen=MAX_LEN,
    padding="post",
    truncating="post"
)

X_test_pad = pad_sequences(
    X_test_seq,
    maxlen=MAX_LEN,
    padding="post",
    truncating="post"
)

print("\nVocabulary size:", len(tokenizer.word_index))

print("\nTraining shape:", X_train_pad.shape)
print("Validation shape:", X_val_pad.shape)
print("Test shape:", X_test_pad.shape)

print("\nData type:", X_train_pad.dtype)

======================================================================
PREPARING TEXT FOR NEURAL MODEL
======================================================================

Vocabulary size: 365386

Training shape: (7137, 300)
Validation shape: (1530, 300)
Test shape: (1530, 300)

Data type: int32

In [23]:
# ============================================================
# NEURAL TEXT MODEL — BIDIRECTIONAL LSTM
# ============================================================

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Embedding,
    SpatialDropout1D,
    Bidirectional,
    LSTM,
    Dense,
    Dropout
)
from tensorflow.keras.callbacks import (
    EarlyStopping,
    ReduceLROnPlateau
)
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

print("=" * 70)
print("BUILDING BIDIRECTIONAL LSTM TEXT MODEL")
print("=" * 70)

# ------------------------------------------------------------
# Model parameters
# ------------------------------------------------------------

MAX_WORDS = 30000
EMBED_DIM = 128
LSTM_UNITS = 64

# ------------------------------------------------------------
# Build model
# ------------------------------------------------------------

text_nn = Sequential([
    
    Embedding(
        input_dim=MAX_WORDS,
        output_dim=EMBED_DIM,
        mask_zero=True
    ),

    SpatialDropout1D(0.25),

    Bidirectional(
        LSTM(
            LSTM_UNITS,
            dropout=0.20,
            recurrent_dropout=0.10
        )
    ),

    Dense(64, activation="relu"),

    Dropout(0.40),

    Dense(1, activation="sigmoid")
])

# ------------------------------------------------------------
# Compile
# ------------------------------------------------------------

text_nn.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=0.001
    ),
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

# ------------------------------------------------------------
# Display architecture
# ------------------------------------------------------------

text_nn.summary()

# ------------------------------------------------------------
# Class weights
# ------------------------------------------------------------

classes = np.unique(y_train_text)

weights = compute_class_weight(
    class_weight="balanced",
    classes=classes,
    y=y_train_text
)

class_weights = dict(
    zip(classes, weights)
)

print("\nClass weights:")
print(class_weights)

# ------------------------------------------------------------
# Callbacks
# ------------------------------------------------------------

early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True,
    verbose=1
)

reduce_lr = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=2,
    min_lr=1e-6,
    verbose=1
)

print("\nModel ready.")

======================================================================
BUILDING BIDIRECTIONAL LSTM TEXT MODEL
======================================================================
WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ spatial_dropout1d               │ ?                      │             0 │
│ (SpatialDropout1D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Class weights:
{np.int64(0): np.float64(4.70778364116095), np.int64(1): np.float64(0.5594137012070858)}

Model ready.

In [ ]:
# ============================================================
# TRAIN BIDIRECTIONAL LSTM
# ============================================================

print("=" * 70)
print("TRAINING BIDIRECTIONAL LSTM TEXT MODEL")
print("=" * 70)

history_text_nn = text_nn.fit(
    X_train_pad,
    y_train_text,
    
    validation_data=(
        X_val_pad,
        y_val_text
    ),
    
    epochs=20,
    batch_size=64,
    
    class_weight=class_weights,
    
    callbacks=[
        early_stopping,
        reduce_lr
    ],
    
    verbose=1
)

print("\n" + "=" * 70)
print("TEXTUAL NEURAL NETWORK TRAINING COMPLETED")
print("=" * 70)

print(
    "Epochs actually completed:",
    len(history_text_nn.history["loss"])
)

======================================================================
TRAINING BIDIRECTIONAL LSTM TEXT MODEL
======================================================================
Epoch 1/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 117s 919ms/step - accuracy: 0.7786 - loss: 0.5156 - precision: 0.9606 - recall: 0.7844 - val_accuracy: 0.8719 - val_loss: 0.3969 - val_precision: 0.9991 - val_recall: 0.8575 - learning_rate: 0.0010
Epoch 2/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 99s 887ms/step - accuracy: 0.9339 - loss: 0.1677 - precision: 0.9960 - recall: 0.9298 - val_accuracy: 0.9431 - val_loss: 0.1497 - val_precision: 0.9946 - val_recall: 0.9415 - learning_rate: 0.0010
Epoch 3/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 102s 913ms/step - accuracy: 0.9249 - loss: 0.1605 - precision: 0.9978 - recall: 0.9180 - val_accuracy: 0.9464 - val_loss: 0.1330 - val_precision: 0.9961 - val_recall: 0.9437 - learning_rate: 0.0010
Epoch 4/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 102s 909ms/step - accuracy: 0.9665 - loss: 0.0828 - precision: 0.9981 - recall: 0.9644 - val_accuracy: 0.9569 - val_loss: 0.1136 - val_precision: 0.9917 - val_recall: 0.9598 - learning_rate: 0.0010
Epoch 5/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 100s 896ms/step - accuracy: 0.9651 - loss: 0.0732 - precision: 0.9989 - recall: 0.9621 - val_accuracy: 0.9477 - val_loss: 0.1641 - val_precision: 0.9939 - val_recall: 0.9474 - learning_rate: 0.0010
Epoch 6/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 893ms/step - accuracy: 0.9627 - loss: 0.0820 - precision: 0.9984 - recall: 0.9599
Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
112/112 ━━━━━━━━━━━━━━━━━━━━ 103s 918ms/step - accuracy: 0.9627 - loss: 0.0820 - precision: 0.9984 - recall: 0.9599 - val_accuracy: 0.9379 - val_loss: 0.2015 - val_precision: 0.9915 - val_recall: 0.9386 - learning_rate: 0.0010
Epoch 7/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 103s 917ms/step - accuracy: 0.9745 - loss: 0.0565 - precision: 0.9990 - recall: 0.9724 - val_accuracy: 0.9497 - val_loss: 0.1434 - val_precision: 0.9901 - val_recall: 0.9532 - learning_rate: 5.0000e-04
Epoch 8/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 895ms/step - accuracy: 0.9846 - loss: 0.0302 - precision: 0.9997 - recall: 0.9831
Epoch 8: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
112/112 ━━━━━━━━━━━━━━━━━━━━ 103s 921ms/step - accuracy: 0.9846 - loss: 0.0302 - precision: 0.9997 - recall: 0.9831 - val_accuracy: 0.9569 - val_loss: 0.1321 - val_precision: 0.9924 - val_recall: 0.9591 - learning_rate: 5.0000e-04
Epoch 9/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 144s 938ms/step - accuracy: 0.9901 - loss: 0.0191 - precision: 0.9998 - recall: 0.9890 - val_accuracy: 0.9621 - val_loss: 0.1256 - val_precision: 0.9895 - val_recall: 0.9678 - learning_rate: 2.5000e-04
Epoch 9: early stopping
Restoring model weights from the end of the best epoch: 4.

======================================================================
TEXTUAL NEURAL NETWORK TRAINING COMPLETED
======================================================================
Epochs actually completed: 9

In [25]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)
import numpy as np

# ============================================================
# BIDIRECTIONAL LSTM — FINAL VALIDATION + TEST EVALUATION
# ============================================================

print("=" * 70)
print("BIDIRECTIONAL LSTM — FINAL EVALUATION")
print("=" * 70)

# ------------------------------------------------------------
# Validation predictions
# ------------------------------------------------------------

val_prob = text_lstm.predict(
    X_val_seq,
    batch_size=64,
    verbose=1
).ravel()

val_pred = (val_prob >= 0.5).astype(int)

print("\nValidation Performance")
print("-" * 50)

print(f"Accuracy : {accuracy_score(y_val_text, val_pred):.4f}")
print(f"Precision: {precision_score(y_val_text, val_pred, zero_division=0):.4f}")
print(f"Recall   : {recall_score(y_val_text, val_pred, zero_division=0):.4f}")
print(f"F1-Score : {f1_score(y_val_text, val_pred, zero_division=0):.4f}")

print("\nValidation Classification Report:")
print(
    classification_report(
        y_val_text,
        val_pred,
        target_names=["Genuine", "Bot"],
        zero_division=0
    )
)

print("\nValidation Confusion Matrix:")
print(confusion_matrix(y_val_text, val_pred))


# ------------------------------------------------------------
# Test predictions
# ------------------------------------------------------------

test_prob = text_lstm.predict(
    X_test_seq,
    batch_size=64,
    verbose=1
).ravel()

test_pred = (test_prob >= 0.5).astype(int)

print("\n" + "=" * 70)
print("TEST PERFORMANCE")
print("=" * 70)

test_accuracy = accuracy_score(y_test_text, test_pred)
test_precision = precision_score(
    y_test_text, test_pred, zero_division=0
)
test_recall = recall_score(
    y_test_text, test_pred, zero_division=0
)
test_f1 = f1_score(
    y_test_text, test_pred, zero_division=0
)

print(f"\nAccuracy : {test_accuracy:.4f}")
print(f"Precision: {test_precision:.4f}")
print(f"Recall   : {test_recall:.4f}")
print(f"F1-Score : {test_f1:.4f}")

print("\nTest Classification Report:")
print(
    classification_report(
        y_test_text,
        test_pred,
        target_names=["Genuine", "Bot"],
        zero_division=0
    )
)

print("\nTest Confusion Matrix:")
print(confusion_matrix(y_test_text, test_pred))


# ------------------------------------------------------------
# Store results for later comparison
# ------------------------------------------------------------

lstm_results = {
    "accuracy": test_accuracy,
    "precision": test_precision,
    "recall": test_recall,
    "f1": test_f1
}

print("\n" + "=" * 70)
print("LSTM TEST EVALUATION COMPLETED")
print("=" * 70)

======================================================================
BIDIRECTIONAL LSTM — FINAL EVALUATION
======================================================================

NameError: name 'text_lstm' is not defined

In [26]:
print("Variables containing 'model':")
print([name for name in globals() if "model" in name.lower()])

print("\nVariables containing 'lstm':")
print([name for name in globals() if "lstm" in name.lower()])

Variables containing 'model':
[]

Variables containing 'lstm':
['LSTM', 'LSTM_UNITS']

In [27]:
print("Sequence variables:")
print([name for name in globals() if "seq" in name.lower()])

Sequence variables:
['pad_sequences', 'X_train_seq', 'X_val_seq', 'X_test_seq', 'Sequential']

In [29]:
# ============================================================
# EVALUATE BIDIRECTIONAL LSTM — VALIDATION SET
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)
import numpy as np

print("=" * 70)
print("TEXTUAL NEURAL NETWORK — VALIDATION PERFORMANCE")
print("=" * 70)

# Get prediction probabilities
val_prob = text_nn.predict(
    X_val_pad,
    batch_size=64,
    verbose=1
).ravel()

# Convert probabilities to class predictions
val_pred = (val_prob >= 0.5).astype(int)

print("\nValidation Performance")
print("-" * 50)

print(f"Accuracy : {accuracy_score(y_val_text, val_pred):.4f}")
print(f"Precision: {precision_score(y_val_text, val_pred):.4f}")
print(f"Recall   : {recall_score(y_val_text, val_pred):.4f}")
print(f"F1-Score : {f1_score(y_val_text, val_pred):.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_val_text,
        val_pred,
        target_names=["Genuine", "Bot"]
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_val_text, val_pred))

======================================================================
TEXTUAL NEURAL NETWORK — VALIDATION PERFORMANCE
======================================================================
24/24 ━━━━━━━━━━━━━━━━━━━━ 3s 125ms/step

Validation Performance
--------------------------------------------------
Accuracy : 0.9569
Precision: 0.9917
Recall   : 0.9598
F1-Score : 0.9755

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.73      0.93      0.82       162
         Bot       0.99      0.96      0.98      1368

    accuracy                           0.96      1530
   macro avg       0.86      0.95      0.90      1530
weighted avg       0.96      0.96      0.96      1530


Confusion Matrix:
[[ 151   11]
 [  55 1313]]

In [30]:
# ============================================================
# TEST SET PERFORMANCE
# ============================================================

print("=" * 70)
print("TEXTUAL NEURAL NETWORK — TEST PERFORMANCE")
print("=" * 70)

test_prob = text_nn.predict(
    X_test_pad,
    batch_size=64,
    verbose=1
).ravel()

test_pred = (test_prob >= 0.5).astype(int)

print("\nTest Performance")
print("-" * 50)

print(f"Accuracy : {accuracy_score(y_test_text, test_pred):.4f}")
print(f"Precision: {precision_score(y_test_text, test_pred):.4f}")
print(f"Recall   : {recall_score(y_test_text, test_pred):.4f}")
print(f"F1-Score : {f1_score(y_test_text, test_pred):.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_test_text,
        test_pred,
        target_names=["Genuine", "Bot"]
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test_text, test_pred))

======================================================================
TEXTUAL NEURAL NETWORK — TEST PERFORMANCE
======================================================================
24/24 ━━━━━━━━━━━━━━━━━━━━ 3s 123ms/step

Test Performance
--------------------------------------------------
Accuracy : 0.9588
Precision: 0.9880
Recall   : 0.9656
F1-Score : 0.9767

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.76      0.90      0.82       163
         Bot       0.99      0.97      0.98      1367

    accuracy                           0.96      1530
   macro avg       0.87      0.93      0.90      1530
weighted avg       0.96      0.96      0.96      1530


Confusion Matrix:
[[ 147   16]
 [  47 1320]]

In [31]:
# ============================================================
# NEURAL TEXT MODEL V2 — IMPROVED BIDIRECTIONAL LSTM
# ============================================================

print("=" * 70)
print("BUILDING IMPROVED BIDIRECTIONAL LSTM — V2")
print("=" * 70)

# ------------------------------------------------------------
# V2 parameters
# ------------------------------------------------------------

MAX_WORDS_V2 = 50000
EMBED_DIM_V2 = 160
LSTM_UNITS_V2 = 96

# ------------------------------------------------------------
# Build improved model
# ------------------------------------------------------------

text_nn_v2 = Sequential([

    Embedding(
        input_dim=MAX_WORDS_V2,
        output_dim=EMBED_DIM_V2,
        mask_zero=True
    ),

    SpatialDropout1D(0.20),

    Bidirectional(
        LSTM(
            LSTM_UNITS_V2,
            dropout=0.15,
            recurrent_dropout=0.05
        )
    ),

    Dense(
        96,
        activation="relu"
    ),

    Dropout(0.30),

    Dense(
        32,
        activation="relu"
    ),

    Dropout(0.20),

    Dense(
        1,
        activation="sigmoid"
    )
])

# ------------------------------------------------------------
# Compile
# ------------------------------------------------------------

text_nn_v2.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=0.0005
    ),
    loss="binary_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

# ------------------------------------------------------------
# Display architecture
# ------------------------------------------------------------

text_nn_v2.summary()

print("\nImproved BiLSTM V2 ready.")

======================================================================
BUILDING IMPROVED BIDIRECTIONAL LSTM — V2
======================================================================

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ spatial_dropout1d_1             │ ?                      │             0 │
│ (SpatialDropout1D)              │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Improved BiLSTM V2 ready.

In [32]:
# ============================================================
# CHECK TOKEN ID RANGE
# ============================================================

print("=" * 70)
print("CHECKING TOKEN IDS FOR BILSTM V2")
print("=" * 70)

print("Maximum token ID in training:",
      X_train_pad.max())

print("Maximum token ID in validation:",
      X_val_pad.max())

print("Maximum token ID in test:",
      X_test_pad.max())

print("V2 embedding input dimension:",
      MAX_WORDS_V2)

print("\nMinimum token ID in training:",
      X_train_pad.min())

print("\nSequence shape:")
print("Train:", X_train_pad.shape)
print("Validation:", X_val_pad.shape)
print("Test:", X_test_pad.shape)

======================================================================
CHECKING TOKEN IDS FOR BILSTM V2
======================================================================
Maximum token ID in training: 29999
Maximum token ID in validation: 29997
Maximum token ID in test: 29999
V2 embedding input dimension: 50000

Minimum token ID in training: 0

Sequence shape:
Train: (7137, 300)
Validation: (1530, 300)
Test: (1530, 300)

In [33]:
# ============================================================
# TRAIN IMPROVED BIDIRECTIONAL LSTM — V2
# ============================================================

print("=" * 70)
print("TRAINING IMPROVED BIDIRECTIONAL LSTM — V2")
print("=" * 70)

# Fresh callbacks for V2
early_stopping_v2 = EarlyStopping(
    monitor="val_loss",
    patience=4,
    restore_best_weights=True,
    verbose=1
)

reduce_lr_v2 = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=2,
    min_lr=1e-6,
    verbose=1
)

# ------------------------------------------------------------
# Train
# ------------------------------------------------------------

history_text_nn_v2 = text_nn_v2.fit(
    X_train_pad,
    y_train_text,

    validation_data=(
        X_val_pad,
        y_val_text
    ),

    epochs=20,
    batch_size=64,

    class_weight=class_weights,

    callbacks=[
        early_stopping_v2,
        reduce_lr_v2
    ],

    verbose=1
)

print("\n" + "=" * 70)
print("TEXTUAL NEURAL NETWORK V2 TRAINING COMPLETED")
print("=" * 70)

print(
    "Epochs actually completed:",
    len(history_text_nn_v2.history["loss"])
)

======================================================================
TRAINING IMPROVED BIDIRECTIONAL LSTM — V2
======================================================================
Epoch 1/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 183s 2s/step - accuracy: 0.6557 - loss: 0.4819 - precision: 0.9790 - recall: 0.6283 - val_accuracy: 0.9327 - val_loss: 0.1644 - val_precision: 0.9938 - val_recall: 0.9306 - learning_rate: 5.0000e-04
Epoch 2/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 155s 1s/step - accuracy: 0.9344 - loss: 0.1663 - precision: 0.9963 - recall: 0.9301 - val_accuracy: 0.9190 - val_loss: 0.2164 - val_precision: 0.9992 - val_recall: 0.9101 - learning_rate: 5.0000e-04
Epoch 3/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - accuracy: 0.9311 - loss: 0.1439 - precision: 0.9978 - recall: 0.9249
Epoch 3: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.
112/112 ━━━━━━━━━━━━━━━━━━━━ 152s 1s/step - accuracy: 0.9311 - loss: 0.1439 - precision: 0.9978 - recall: 0.9249 - val_accuracy: 0.9314 - val_loss: 0.2336 - val_precision: 0.9984 - val_recall: 0.9247 - learning_rate: 5.0000e-04
Epoch 4/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 157s 1s/step - accuracy: 0.9696 - loss: 0.0654 - precision: 0.9995 - recall: 0.9665 - val_accuracy: 0.9582 - val_loss: 0.1283 - val_precision: 0.9962 - val_recall: 0.9569 - learning_rate: 2.5000e-04
Epoch 5/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 161s 1s/step - accuracy: 0.9790 - loss: 0.0473 - precision: 0.9995 - recall: 0.9770 - val_accuracy: 0.9647 - val_loss: 0.0986 - val_precision: 0.9925 - val_recall: 0.9678 - learning_rate: 2.5000e-04
Epoch 6/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 161s 1s/step - accuracy: 0.9738 - loss: 0.0510 - precision: 0.9997 - recall: 0.9710 - val_accuracy: 0.9595 - val_loss: 0.1015 - val_precision: 0.9962 - val_recall: 0.9583 - learning_rate: 2.5000e-04
Epoch 7/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - accuracy: 0.9818 - loss: 0.0378 - precision: 0.9992 - recall: 0.9804
Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
112/112 ━━━━━━━━━━━━━━━━━━━━ 201s 1s/step - accuracy: 0.9818 - loss: 0.0378 - precision: 0.9992 - recall: 0.9804 - val_accuracy: 0.9569 - val_loss: 0.1343 - val_precision: 0.9947 - val_recall: 0.9569 - learning_rate: 2.5000e-04
Epoch 8/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 162s 1s/step - accuracy: 0.9887 - loss: 0.0246 - precision: 0.9998 - recall: 0.9875 - val_accuracy: 0.9680 - val_loss: 0.1190 - val_precision: 0.9940 - val_recall: 0.9700 - learning_rate: 1.2500e-04
Epoch 9/20
112/112 ━━━━━━━━━━━━━━━━━━━━ 0s 1s/step - accuracy: 0.9894 - loss: 0.0226 - precision: 0.9997 - recall: 0.9884
Epoch 9: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
112/112 ━━━━━━━━━━━━━━━━━━━━ 164s 1s/step - accuracy: 0.9894 - loss: 0.0226 - precision: 0.9997 - recall: 0.9884 - val_accuracy: 0.9667 - val_loss: 0.1150 - val_precision: 0.9933 - val_recall: 0.9693 - learning_rate: 1.2500e-04
Epoch 9: early stopping
Restoring model weights from the end of the best epoch: 5.

======================================================================
TEXTUAL NEURAL NETWORK V2 TRAINING COMPLETED
======================================================================
Epochs actually completed: 9

In [34]:
# ============================================================
# BILSTM V2 — TEST PERFORMANCE
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

print("=" * 70)
print("TEXTUAL NEURAL NETWORK V2 — TEST PERFORMANCE")
print("=" * 70)

# Test probabilities
test_prob_v2 = text_nn_v2.predict(
    X_test_pad,
    batch_size=64,
    verbose=1
).ravel()

# Convert probabilities to class predictions
test_pred_v2 = (test_prob_v2 >= 0.5).astype(int)

print("\nTest Performance")
print("-" * 50)

print(f"Accuracy : {accuracy_score(y_test_text, test_pred_v2):.4f}")
print(f"Precision: {precision_score(y_test_text, test_pred_v2):.4f}")
print(f"Recall   : {recall_score(y_test_text, test_pred_v2):.4f}")
print(f"F1-Score : {f1_score(y_test_text, test_pred_v2):.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_test_text,
        test_pred_v2,
        target_names=["Genuine", "Bot"]
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test_text, test_pred_v2))

======================================================================
TEXTUAL NEURAL NETWORK V2 — TEST PERFORMANCE
======================================================================
24/24 ━━━━━━━━━━━━━━━━━━━━ 7s 238ms/step

Test Performance
--------------------------------------------------
Accuracy : 0.9706
Precision: 0.9911
Recall   : 0.9759
F1-Score : 0.9834

Classification Report:
              precision    recall  f1-score   support

     Genuine       0.82      0.93      0.87       163
         Bot       0.99      0.98      0.98      1367

    accuracy                           0.97      1530
   macro avg       0.91      0.95      0.93      1530
weighted avg       0.97      0.97      0.97      1530


Confusion Matrix:
[[ 151   12]
 [  33 1334]]

In [35]:
# ============================================================
# TEXTUAL CROSS-TYPE ROBUSTNESS — SETUP
# ============================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("TEXTUAL CROSS-TYPE ROBUSTNESS")
print("=" * 70)

print("\nAvailable account types:")
print(text_account_df["account_type"].value_counts())

======================================================================
TEXTUAL CROSS-TYPE ROBUSTNESS
======================================================================

Available account types:

NameError: name 'text_account_df' is not defined

In [37]:
# ============================================================
# FIND ACCOUNT-LEVEL DATAFRAME
# ============================================================

print("=" * 70)
print("SEARCHING FOR ACCOUNT-LEVEL TEXT DATAFRAME")
print("=" * 70)

all_vars = list(globals().items())

for name, obj in all_vars:
    if isinstance(obj, pd.DataFrame):
        print(f"\n{name}")
        print("Shape:", obj.shape)
        print("Columns:", list(obj.columns))

======================================================================
SEARCHING FOR ACCOUNT-LEVEL TEXT DATAFRAME
======================================================================

df_temp
Shape: (145094, 5)
Columns: ['text', 'user_id', 'created_at', 'timestamp', 'account_type']

temp
Shape: (145094, 4)
Columns: ['user_id', 'text', 'label', 'account_type']

text_tweets
Shape: (6624609, 4)
Columns: ['user_id', 'text', 'label', 'account_type']

account_labels
Shape: (14368, 3)
Columns: ['id', 'label', 'account_type']

behavior_df
Shape: (14368, 20)
Columns: ['id', 'account_type', 'label', 'statuses_count', 'followers_count', 'friends_count', 'favourites_count', 'listed_count', 'created_at', 'updated', 'account_age_days', 'statuses_per_day', 'followers_friends_ratio', 'friends_followers_ratio', 'favorites_per_status', 'log_statuses_count', 'log_followers_count', 'log_friends_count', 'log_favourites_count', 'log_listed_count']

text_account_data
Shape: (10197, 6)
Columns: ['user_id', 'tweet_count', 'text', 'id', 'label', 'account_type']

controlled_tweets
Shape: (714839, 4)
Columns: ['user_id', 'text', 'label', 'account_type']

account_text
Shape: (10197, 5)
Columns: ['user_id', 'text', 'label', 'account_type', 'tweet_count_used']

train_text
Shape: (7137, 5)
Columns: ['user_id', 'text', 'label', 'account_type', 'tweet_count_used']

temp_text
Shape: (3060, 5)
Columns: ['user_id', 'text', 'label', 'account_type', 'tweet_count_used']

val_text
Shape: (1530, 5)
Columns: ['user_id', 'text', 'label', 'account_type', 'tweet_count_used']

test_text
Shape: (1530, 5)
Columns: ['user_id', 'text', 'label', 'account_type', 'tweet_count_used']

In [38]:
# ============================================================
# CHECK ACCOUNT TYPES IN EXISTING TEXT SPLITS
# ============================================================

print("=" * 70)
print("ACCOUNT TYPES IN TEXT SPLITS")
print("=" * 70)

for name, df in [
    ("TRAIN", train_text),
    ("VALIDATION", val_text),
    ("TEST", test_text)
]:
    
    print(f"\n{name}")
    print("-" * 50)
    print(df["account_type"].value_counts())

======================================================================
ACCOUNT TYPES IN TEXT SPLITS
======================================================================

TRAIN
--------------------------------------------------
account_type
social_spambots_2         2433
fake_followers            2257
genuine_accounts           758
traditional_spambots_1     692
social_spambots_1          680
social_spambots_3          317
Name: count, dtype: int64

VALIDATION
--------------------------------------------------
account_type
social_spambots_2         512
fake_followers            468
genuine_accounts          162
social_spambots_1         158
traditional_spambots_1    150
social_spambots_3          80
Name: count, dtype: int64

TEST
--------------------------------------------------
account_type
social_spambots_2         512
fake_followers            477
genuine_accounts          163
traditional_spambots_1    158
social_spambots_1         153
social_spambots_3          67
Name: count, dtype: int64

In [39]:
# ============================================================
# TEXTUAL ROBUSTNESS — LEAVE-ONE-BOT-TYPE-OUT
# TF-IDF + LINEAR SVM
# ============================================================

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("=" * 70)
print("TEXTUAL ROBUSTNESS — LEAVE-ONE-BOT-TYPE-OUT")
print("=" * 70)

# Bot types that can be held out
bot_types = [
    "fake_followers",
    "social_spambots_1",
    "social_spambots_2",
    "social_spambots_3",
    "traditional_spambots_1"
]

robustness_results = []

for held_out in bot_types:

    print("\n" + "=" * 70)
    print("HELD-OUT BOT TYPE:", held_out)
    print("=" * 70)

    # --------------------------------------------------------
    # TRAINING DATA
    # Genuine accounts + all bot types EXCEPT held-out type
    # --------------------------------------------------------

    train_robust = account_text[
        (account_text["account_type"] == "genuine_accounts") |
        (
            (account_text["label"] == 1) &
            (account_text["account_type"] != held_out)
        )
    ].copy()

    # --------------------------------------------------------
    # TEST DATA
    # Genuine accounts + ONLY held-out bot type
    # --------------------------------------------------------

    test_robust = account_text[
        (account_text["account_type"] == "genuine_accounts") |
        (account_text["account_type"] == held_out)
    ].copy()

    print("Training accounts:", len(train_robust))
    print("Testing accounts :", len(test_robust))

    print("\nTraining distribution:")
    print(train_robust["account_type"].value_counts())

    print("\nTesting distribution:")
    print(test_robust["account_type"].value_counts())

    # --------------------------------------------------------
    # TF-IDF
    # Fit ONLY on training data
    # --------------------------------------------------------

    vectorizer = TfidfVectorizer(
        max_features=20000,
        ngram_range=(1, 2),
        min_df=2,
        max_df=0.95,
        sublinear_tf=True
    )

    X_train_robust = vectorizer.fit_transform(
        train_robust["text"]
    )

    X_test_robust = vectorizer.transform(
        test_robust["text"]
    )

    y_train_robust = train_robust["label"].values
    y_test_robust = test_robust["label"].values

    # --------------------------------------------------------
    # Linear SVM
    # --------------------------------------------------------

    svm_robust = LinearSVC(
        class_weight="balanced",
        random_state=42
    )

    svm_robust.fit(
        X_train_robust,
        y_train_robust
    )

    # --------------------------------------------------------
    # Predictions
    # --------------------------------------------------------

    test_pred = svm_robust.predict(
        X_test_robust
    )

    # --------------------------------------------------------
    # Metrics
    # --------------------------------------------------------

    accuracy = accuracy_score(
        y_test_robust,
        test_pred
    )

    precision = precision_score(
        y_test_robust,
        test_pred,
        zero_division=0
    )

    recall = recall_score(
        y_test_robust,
        test_pred,
        zero_division=0
    )

    f1 = f1_score(
        y_test_robust,
        test_pred,
        zero_division=0
    )

    print("\nPerformance on UNSEEN bot type:")
    print("-" * 50)

    print(f"Accuracy : {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall   : {recall:.4f}")
    print(f"F1-Score : {f1:.4f}")

    # --------------------------------------------------------
    # Save result
    # --------------------------------------------------------

    robustness_results.append({
        "held_out_type": held_out,
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    })


# ============================================================
# FINAL RESULTS TABLE
# ============================================================

robustness_df = pd.DataFrame(
    robustness_results
)

print("\n" + "=" * 70)
print("FINAL TEXTUAL ROBUSTNESS RESULTS")
print("=" * 70)

display(
    robustness_df.style.format({
        "accuracy": "{:.4f}",
        "precision": "{:.4f}",
        "recall": "{:.4f}",
        "f1": "{:.4f}"
    })
)

print("\nMean Accuracy:",
      robustness_df["accuracy"].mean())

print("Mean F1:",
      robustness_df["f1"].mean())

======================================================================
TEXTUAL ROBUSTNESS — LEAVE-ONE-BOT-TYPE-OUT
======================================================================

======================================================================
HELD-OUT BOT TYPE: fake_followers
======================================================================
Training accounts: 6995
Testing accounts : 4285

Training distribution:
account_type
social_spambots_2         3457
genuine_accounts          1083
traditional_spambots_1    1000
social_spambots_1          991
social_spambots_3          464
Name: count, dtype: int64

Testing distribution:
account_type
fake_followers      3202
genuine_accounts    1083
Name: count, dtype: int64

Performance on UNSEEN bot type:
--------------------------------------------------
Accuracy : 0.5480
Precision: 1.0000
Recall   : 0.3951
F1-Score : 0.5664

======================================================================
HELD-OUT BOT TYPE: social_spambots_1
======================================================================
Training accounts: 9206
Testing accounts : 2074

Training distribution:
account_type
social_spambots_2         3457
fake_followers            3202
genuine_accounts          1083
traditional_spambots_1    1000
social_spambots_3          464
Name: count, dtype: int64

Testing distribution:
account_type
genuine_accounts     1083
social_spambots_1     991
Name: count, dtype: int64

Performance on UNSEEN bot type:
--------------------------------------------------
Accuracy : 0.9966
Precision: 1.0000
Recall   : 0.9929
F1-Score : 0.9965

======================================================================
HELD-OUT BOT TYPE: social_spambots_2
======================================================================
Training accounts: 6740
Testing accounts : 4540

Training distribution:
account_type
fake_followers            3202
genuine_accounts          1083
traditional_spambots_1    1000
social_spambots_1          991
social_spambots_3          464
Name: count, dtype: int64

Testing distribution:
account_type
social_spambots_2    3457
genuine_accounts     1083
Name: count, dtype: int64

Performance on UNSEEN bot type:
--------------------------------------------------
Accuracy : 0.9566
Precision: 1.0000
Recall   : 0.9430
F1-Score : 0.9707

======================================================================
HELD-OUT BOT TYPE: social_spambots_3
======================================================================
Training accounts: 9733
Testing accounts : 1547

Training distribution:
account_type
social_spambots_2         3457
fake_followers            3202
genuine_accounts          1083
traditional_spambots_1    1000
social_spambots_1          991
Name: count, dtype: int64

Testing distribution:
account_type
genuine_accounts     1083
social_spambots_3     464
Name: count, dtype: int64

Performance on UNSEEN bot type:
--------------------------------------------------
Accuracy : 0.9838
Precision: 1.0000
Recall   : 0.9461
F1-Score : 0.9723

======================================================================
HELD-OUT BOT TYPE: traditional_spambots_1
======================================================================
Training accounts: 9197
Testing accounts : 2083

Training distribution:
account_type
social_spambots_2    3457
fake_followers       3202
genuine_accounts     1083
social_spambots_1     991
social_spambots_3     464
Name: count, dtype: int64

Testing distribution:
account_type
genuine_accounts          1083
traditional_spambots_1    1000
Name: count, dtype: int64

Performance on UNSEEN bot type:
--------------------------------------------------
Accuracy : 0.9894
Precision: 1.0000
Recall   : 0.9780
F1-Score : 0.9889

======================================================================
FINAL TEXTUAL ROBUSTNESS RESULTS
======================================================================

AttributeError: The '.style' accessor requires jinja2

In [40]:
# ============================================================
# DISPLAY TEXTUAL ROBUSTNESS RESULTS
# ============================================================

print("=" * 70)
print("FINAL TEXTUAL ROBUSTNESS RESULTS")
print("=" * 70)

display(
    robustness_df.round(4)
)

print("\nMean Accuracy:",
      round(robustness_df["accuracy"].mean(), 4))

print("Mean F1:",
      round(robustness_df["f1"].mean(), 4))

======================================================================
FINAL TEXTUAL ROBUSTNESS RESULTS
======================================================================

            held_out_type  accuracy  precision  recall      f1
0          fake_followers    0.5480        1.0  0.3951  0.5664
1       social_spambots_1    0.9966        1.0  0.9929  0.9965
2       social_spambots_2    0.9566        1.0  0.9430  0.9707
3       social_spambots_3    0.9838        1.0  0.9461  0.9723
4  traditional_spambots_1    0.9894        1.0  0.9780  0.9889

Mean Accuracy: 0.8949
Mean F1: 0.8989